### ISSUE TITLE
Test image

### ISSUE THREAD

**Issue by it33** [mattermost/docs#10]
![image](https://cloud.githubusercontent.com/assets/177788/12605075/199e32ee-c476-11e5-9097-ae36e9958226.png)

**Comment by esethna** [comment]
![image](https://cloud.githubusercontent.com/assets/14333569/12622088/faad5624-c4e0-11e5-9548-a095b6a60878.png)

**Comment by esethna** [comment]
![image](https://cloud.githubusercontent.com/assets/14333569/12622114/13854986-c4e1-11e5-968f-7b70e951d0fa.png)

**Comment by esethna** [comment]
![image](https://cloud.githubusercontent.com/assets/14333569/12622129/2bcb04d6-c4e1-11e5-9701-3176e837c471.png)

**Comment by esethna** [comment]
![image](https://cloud.githubusercontent.com/assets/14333569/12622142/3d1cce5e-c4e1-11e5-9508-1d8ab4eb6e91.png)

**Comment by esethna** [comment]
![image](https://cloud.githubusercontent.com/assets/14333569/12622152/4ad357ac-c4e1-11e5-904e-9c9520747a9b.png)

**Comment by esethna** [comment]
![image](https://cloud.githubusercontent.com/assets/14333569/12622168/5b091df0-c4e1-11e5-92ac-0cbf0feb7421.png)

**Comment by esethna** [comment]
![image](https://cloud.githubusercontent.com/assets/14333569/12757627/a47dbb0c-c98d-11e5-9331-4da5e57b5c95.png)

**Comment by it33** [comment]
![image](https://cloud.githubusercontent.com/assets/177788/13022120/160d2c68-d194-11e5-927a-10d0f3c1ec8d.png)

**Comment by esethna** [comment]
![image](https://cloud.githubusercontent.com/assets/14333569/13122278/283c738c-d584-11e5-9fac-6519e5c333f8.png)

**Comment by asaadmahmoodspin** [comment]
![arrangement1](https://cloud.githubusercontent.com/assets/11034289/13149477/76a1ae20-d683-11e5-9e8b-4377fd76f8bb.jpg)
![arrangement2](https://cloud.githubusercontent.com/assets/11034289/13149478/76d6be1c-d683-11e5-8546-fdd52ae03f6b.png)
![arrangement3](https://cloud.githubusercontent.com/assets/11034289/13149480/76f639a4-d683-11e5-9e18-0ebdae366932.jpg)
![arrangement4](https://cloud.githubusercontent.com/assets/11034289/13149481/76fb0da8-d683-11e5-922e-91fe5cb9ab9a.png)
![choice1](https://cloud.githubusercontent.com/assets/11034289/13149483/76fd30ba-d683-11e5-801e-a524edd1863e.png)
![choice2](https://cloud.githubusercontent.com/assets/11034289/13149482/76fd07f2-d683-11e5-9721-a652ce54b4f0.png)
![confirmation](https://cloud.githubusercontent.com/assets/11034289/13149493/7849e10c-d683-11e5-9e83-f18da9811a47.jpg)
![header1](https://cloud.githubusercontent.com/assets/11034289/13149484/77046e02-d683-11e5-9e6b-f5e079cb5e0c.png)
![header2](https://cloud.githubusercontent.com/assets/11034289/13149485/77275246-d683-11e5-92c0-2a576ca3ca5e.png)
![input1](https://cloud.githubusercontent.com/assets/11034289/13149486/77281d70-d683-11e5-9895-fe373344739a.png)
![input2](https://cloud.githubusercontent.com/assets/11034289/13149487/77326af0-d683-11e5-9254-e74e35f9c314.png)
![placement1](https://cloud.githubusercontent.com/assets/11034289/13149488/773331c4-d683-11e5-906d-db86850c39ac.png)
![placement2](https://cloud.githubusercontent.com/assets/11034289/13149489/773aaa6c-d683-11e5-9000-dbee4c352fd2.png)
![placement3](https://cloud.githubusercontent.com/assets/11034289/13149490/77522bce-d683-11e5-961e-d97b6f29dfff.png)
![saveprompt](https://cloud.githubusercontent.com/assets/11034289/13149491/775525e0-d683-11e5-8f16-2434702d9d78.png)

**Comment by asaadmahmoodspin** [comment]
![arrangement5](https://cloud.githubusercontent.com/assets/11034289/13149714/5ce9bac6-d684-11e5-9bc9-76b23c06afa4.jpg)

**Comment by asaadmahmoodspin** [comment]
![screen shot 2016-02-18 at 9 31 52 pm](https://cloud.githubusercontent.com/assets/11034289/13150330/206a1e4e-d687-11e5-9a24-49b8e2cb06f7.png)
![screen shot 2016-02-18 at 9 32 20 pm](https://cloud.githubusercontent.com/assets/11034289/13150327/20324aaa-d687-11e5-8a6c-b3854f403030.png)
![screen shot 2016-02-18 at 9 32 41 pm](https://cloud.githubusercontent.com/assets/11034289/13150329/205d1b7c-d687-11e5-93f6-17aa65fae41b.png)
