### ISSUE TITLE
Doc whitelabeling options

### ISSUE THREAD

**Issue by it33** [mattermost/docs#1006]
In the last year, there's been a lot of questions on white-labeling, below is a draft doc update to share our thoughts and options available. 

#### Customizing Mattermost branding 

Mattermost is designed for self-hosted communication and there's a number of technical options to customize the branding and identity to meet your organizational needs. In addition, Enterprise Edition offers advanced custom branding tools for non-technical users to meet corporate policies. 

Note: 

- Please avoid branding that could be confused with the Mattermost brand. For example, it's okay to brand as "Healthcare Central", because it's a complete different brand, but not "Mattermost Healthcare Central", because it's potentially confused with the Mattermost brand. Please see the [Mattermost trademark guidelines](https://www.mattermost.org/trademark-standards-of-use/) for details. 
- While you're welcome to add your own copyright notice in the user interface if you feel it warranted by your changes or your content, we ask that you do not remove the Mattermost, Inc. copyright notice from the login footer or from the About dialog. 

MATTERMOST SERVER 

Mattermost Team Edition and Mattermost Enterprise Edition: 

- You can change any string in the Mattermost interface by editing the `en.json` file. 
- You can replace the Mattermost logo in emails by changing the file located in the `/images` directory. 
- You can add custom emoji based on your organization's requirements. 
- You can [customize the options in the main menu using System Console options](https://docs.mattermost.com/administration/config-settings.html#legal-and-support) 

Mattermost Enterprise Edition: 

Mattermost Enterprise Edition E10 and higher offer [advanced tools for custom branding in the System Console](https://docs.mattermost.com/administration/config-settings.html#customization), including: 
- Customizing Site Name and Site Description without changing `en.json`
- Providing a custom image and custom text to the login screen 
- (in future) Change name and image references without updating `en.json` and `/images` directory 
- (in future) Select default theme colors 

MATTERMOST MOBILE APPS IN REACT NATIVE 

For Mattermost mobile apps in React Native you can replace the name, images and key strings with custom branding using the open source repository and compile your own versions. 

- https://github.com/mattermost/mattermost-mobile

While most organizations deploy to internal AppStores, so long as branding is not confused with official Mattermost products, you are more than welcome to publish to iTunes and Google Play. 

MATTERMOST MOBILE APPS USING WEBVIEWS 

In addition to the branding options for React Native apps, for the Mattermost mobile apps supporting webviews you can also use the source code to embed the mobile experiences into your own mobile apps. 

- https://github.com/mattermost/ios
- https://github.com/mattermost/android

MATTERMOST DESKTOP APPS 

For Mattermost desktop apps you can replace the name, images and key strings with custom branding using the open source repository and compile your own versions. 

- https://github.com/mattermost/desktop

**Comment by machineghost** [comment]
>You can change any string in the Mattermost interface by editing the en.json file.

This does not appear to be true.  When you click the icon in the lower-left, a bunch of options appear, starting with "Welcome to Mattermost".  However, that string doesn't appear in `en.json`.

**Comment by cwarnermm** [comment]
Hello @machineghost! Given the outdated nature of this closed PR, can you point me to where you found the content you believe to be incorrect/outdated, please?

**Comment by machineghost** [comment]
Well, I commented on a piece of documentation (the URL is literally "docs/issues"), not a PR, but I guess GitHub added it as a comment on  the PR?

In any case, the way I found this page was through Google.  I was trying to understand how to "white label" Mattermost, and first I found https://developers.mattermost.com/contribute/mobile/build-your-own/white-label/ (which was completely unhelpful, as it only addressed the mobile app), but then I found this documentation page.

**Comment by cwarnermm** [comment]
Thank you for the context, @machineghost. Both Mattermost Cloud and self-hosted deployments include support for custom branding. You can find more information on our [custom branding tools](https://docs.mattermost.com/configure/custom-branding-tools.html) in our product documentation.

You can also find additional details about product white labeling here: https://docs.mattermost.com/about/faq-business.html#rebranding

**Comment by machineghost** [comment]
Thanks so much @cwarnermm, those links were very helpful.
