### ISSUE TITLE
Drafting community guidelines

### ISSUE THREAD

**Issue by it33** [mattermost/docs#1007]
Opening a ticket to add community guidelines, draft: 

Community Guidelines  
--------------------------

The Mattermost community is intended to be welcoming, pleasant, informative, and constructive. We use a few simple rules to support this: 

1. **House rule.** We have a simple "house rule": Interact as if you're a guest in someone's house. If you wouldn't feel comfortable saying something to someone in person, in that person's home, then don't say it in our community. 

2. **Right place.** Please keep conversations in the right system, see `Getting Help with Mattermost <https://about.mattermost.com/help/>`_  for links. 

When discussions move outside the guidelines, it's the responsibility of moderators to guide things back. 
 
----

I'm wondering if we can keep things short and memorable, or will this eventually just balloon... 

Also, we probably want to say something discouraging the use of fake accounts, e.g.: 

![image](https://cloud.githubusercontent.com/assets/177788/24077454/f73f7fae-0c0a-11e7-9686-eb2b219478e3.png)

![image](https://cloud.githubusercontent.com/assets/177788/24077451/d0960986-0c0a-11e7-86b2-77d3e47aea66.png)

**Comment by justinegeffen** [comment]
This article in the handbook addresses this issue: https://handbook.mattermost.com/contributors/contributors/contribution-guidelines.
