### ISSUE TITLE
Document current way of adding/removing nodes from the cluster

### ISSUE THREAD

**Issue by lfbrock** [mattermost/docs#1009]
Document current way of adding/removing nodes from the cluster using load config from file.

**Comment by jasonblais** [comment]
After chatting with Corey, this is actually not currently supported. Recommendation is to add/remove a node and restart the server afterwards (this shouldn't happen very often).

Kubernetes will be more useful for auto-scaling Mattermost based on usage, where adding/removing nodes is handled better.
