### ISSUE TITLE
Make Enterprise policy features more discoverable

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#1014]
From https://pre-release.mattermost.com/core/pl/sc6s9b7p7t839kzrctkyafkiur

> Just a heads-up that the discoverability of the policy features for enterprise could be better on docs.mattermost.com
I had trouble finding https://docs.mattermost.com/administration/config-settings.html#policy and I knew it existed
Not sure who owns this but something to think about

Options:
 1) Create a doc page for Advanced Policy/Permissions
 2) Expand the Deployment section and walk through what a real enterprise deployment needs

**Comment by justinegeffen** [comment]
1. [Advanced permissions](https://docs.mattermost.com/deployment/advanced-permissions.html) page has been created. 
2. [Deployment section](https://docs.mattermost.com/guides/administrator.html#deployment) is quite extensive, and we also have the [Enterprise Rollout Checklist](https://docs.mattermost.com/getting-started/enterprise-roll-out-checklist.html).

Closing.
