### ISSUE TITLE
Doc RDP communication process with security researchers

### ISSUE THREAD

**Issue by it33** [mattermost/docs#1015]
We should document communication protocol with security researchers providing issue reports according to our responsible disclosure policy: 

Communicating with Security Researchers: 

1. After a report is received immediately acknowledge it was received and will be under review (this can be an auto-reply just confirming the report was received, or a manual email macro) 
2. Within X days review the report, and if it doesn't meet criteria respond with a reason why. Open a ticket in docs repo to document the reason so if people report a duplicate issue the explanation is public, e.g. we have people "discovering" account enumeration by telling people their password is incorrect, which we purposely offer as a usability benefit, which we don't see as a security issue if people are properly deployed behind a firewall, and which can be optionally switched off (We should at least open a ticket to document this, and eventually get it into some sort of FAQ). 
3. If the report does meet criteria, and we plan to ship a patch, we should reply back and let them know work is in progress and to thank them for their report and ask if a) they would like to be publicly credited and what name to use (no links, sorry), b) optionally if they would be open to us sending them a modest thank you gift through the mail, and if so, to let us know their mailing address. 
4. If someone offers a name, we should add it to the end of the "Security Research Hall of Fame" list at https://www.mattermost.org/responsible-disclosure-policy/. If someone has multiple contributions, note that in their name and move them to the top of the list. 
5. If they've given their address, mail the gift. 
6. Ship the security fix per the standard policy.

**Comment by justinegeffen** [comment]
@DSchalla, is this something you'd be open to helping with? Or, if we already have this let me know and I'll make sure it's in the correct place in the handbook. :)

**Comment by DSchalla** [comment]
Hey @justinegeffen,

we have a public documentation for this here: https://mattermost.com/security-vulnerability-report/ and a internal security team document we have in our Shared Google Drive that covers the entire internal workflow, which would cover the second side. We could move this to the public handbook, but may need to give it another pass before doing so.
