### ISSUE TITLE
Make configuration settings more discoverable

### ISSUE THREAD

**Issue by it33** [mattermost/docs#1018]
Most of what people want is in Configuration Settings and they're not show at TOC level and they should be: https://docs.mattermost.com/guides/administrator.html#administration

People need this: 

![image](https://cloud.githubusercontent.com/assets/177788/24335881/36f0ecde-123a-11e7-91b5-f7f7105da92e.png)

But people get this: 

![image](https://cloud.githubusercontent.com/assets/177788/24335879/28fccaa8-123a-11e7-8951-5aac968a39e1.png)

**Comment by JeffSchering** [comment]
Fixed in [Increased ToC maxdepth to 3 in admin section #1097](https://github.com/mattermost/docs/issues/1097)
