### ISSUE TITLE
Define "small improvement" in Contributor's Guide

### ISSUE THREAD

**Issue by it33** [mattermost/docs#1028]
We need to update https://docs.mattermost.com/developer/contribution-guide.html with definition and examples of "small improvement". 

Criteria: 
- Consensus improvement is small--i.e. 100% of core committers reviewing PR agree
- Does not require an update to docs.mattermost.com 
- Not more than a few lines of changes

Examples (need to link to PR examples, we can probably fine better examples than these): 
- Adjustments to better align with UX guidelines 
- Tidying up small bits of code 
- Small improvements to make help text more clear

**Comment by prixone** [comment]
Examples
some one just update a file and forgot to update the same method within a function of that file:
https://github.com/mattermost/platform/pull/5878

**Comment by JeffSchering** [comment]
Would the term "incremental improvement" in place of "small improvement" be more or less self-explanatory here?

**Comment by gluelue** [comment]
I agree with @JeffSchering on using the term "incremental improvement".

**Comment by jasonblais** [comment]
See #1083 for proposed changes

**Comment by prixone** [comment]
@JeffSchering when I read "incremental" the first thing that comes to mind is something that will be on-going whereas "small" comes in as something of minor, in a fixed size. I do think that incremental would fit more in the "technical writing" jargon but as a person that often misunderstand technical writing, I would say "small" is much more friendly, or perhaps "minor improvement". Then again that is just my personal opinion, and perhaps I am the minority that sees it that way, or rather read it that way.

**Comment by jasonblais** [comment]
Thanks @prixone for the feedback, really appreciate your input here.

I added a comment in my PR, which had a related note, feel free to add any feedback? https://github.com/mattermost/docs/pull/1083#discussion_r111788163
