### ISSUE TITLE
Q&A on mobile security storage

### ISSUE THREAD

**Issue by it33** [mattermost/docs#1044]
Add to: https://docs.mattermost.com/overview/faq.html

Not urgent, need @coreyhulen for final review, asking @JeffSchering to help add to FAQ

How is data stored on mobile? 

Data Storage on Mobile Web Experience 
- Security for mobile web experience is similar to the security for a desktop web experience. 
- Similar to a desktop web browser, data may be stored in the mobile web browser cache which resides on the storage system of the device operating system which is protected by security measures in the physical device and its operating system. 
- If you log out or your account is disabled, the data in the browser cache may reside until the cache expires or the temporary file system store on the operating system is cleared, depending on your operating system. 

Data Storage on First Generation Native Mobile Apps 
- First Generation Native Mobile Apps are used pre-dominantly to deliver mobile push notifications for iOS and Android, and then to provide the mobile web experience within a mobile application. 
- These apps are currently available via iTunes and Google Play and full source code is available at https://github.com/mattermost/ios and https://github.com/mattermost/android
- Because the user experience is delivered through an embedded web view, the data storage properties are the same as with the Mobile Web Experience (see above)

**Comment by JeffSchering** [comment]
Closing. Resolved by https://github.com/mattermost/docs/pull/1179, which adds the info to this doc: https://docs.mattermost.com/deployment/client-side-data.html
