### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by it33** [mattermost/docs#1119]
Proposing we write-up some personas so the user experience team is on the same page in terms of target audience for design. 

NOTES: 

1. Personas represent the "target intersection" of needs from target user segment. They are a tool for the user experience team to design broad, relevant solutions, they are not a definition of our target audience. 

Example: If we were designing a new desert for an American restaurant, the persona we use might be a 45-year-old vacationer from Austria with nut and dairy allergies celebrating an anniversary with their significant other. The persona allows us to think through the needs of a broad set of users (people celebrating an event, people with allergies, couples, non-native English-speakers, etc.), but the persona is not what we'd consider a target audience. 

PROPOSED USER PERSONAS: 

# Neve the non-technical team member 
- Neve is joining a new organization that runs on a private network. She misses the SaaS messenger she used to use at another company, that can't meet the needs of her new organization. She finds Mattermost Team Edition and should be able to set it up in less than 5 minutes on her private network. She potentially [deploys Mattermost through an AppStore such as Bitnami](https://www.youtube.com/watch?v=AKqHWqrAgpk?)  
- Every month Neve decides whether she should update the the latest version of Mattermost after reading about the new features from the Mattermost blog. She's more inclined to update when there's a security fix, but she's also really busy and doesn't always have time, unless there is a cool new end user feature she feels her team could really use.

# Ingrid the IT Manager  
- Ingrid has worked in IT for many years and provides tools for end users to meet their needs while keeping infrastructure secure, compliant and meeting all the IT policies of the organization. 
- When Nancy's Mattermost Team Edition deployment gets popular beyond Nancy's team, people start asking Ingrid's help to have Mattermost managed centrally by Ingrid's IT team, rather than every team organizing their own
- Ingrid might develop orchestration or automation for deploying and maintaining Mattermost, and possibly open source it. 

# Enid the Enterprise IT Developer 
- Helps build tools and integrations for teams in the enterprise 
- Nancy asks Enid's help to create some integrations into different systems for her Mattermost deployment 
- Enid might decide to open source some of her work, depending on the policy of her organization 

# Alexus the Amazing Developer 
- Alexus may or may not be a Mattermost user at work, but she comes across the Mattermost open source project and is interested in completing some tickets out of personal interest--to contribute, to learn, or for some fun on the weekend creating something used by thousands of people.

**Comment by lfbrock** [comment]
Any design personas should be based off of user research as the starting point, I think some of these fit but there are some other points that feel like they're more based on a target audience/who we think the audience should be than user research. 

Target audience is for marketing personas, but we shouldn't use marketing personas for design.

**Comment by it33** [comment]
Completely agree on user research, that said, I'm proposing we design the product for the persona, rather than the persona for the product. We shouldn't be limited by the people using our product today, we should focus on the audience we want. 

Most people aren't lactose intolerant and allergic to nuts, but if our persona is the intersection of those properties--if we begin with the most challenging design constraints and properly prioritize--I believe we make better decisions. 

My thoughts on specifics: 

1. Neve is our aspirational user. She is someone who works day-to-day at an organization using a private network and needs a tool for messaging. She has access to a Linux or Window Server and is able to follow step-by-step instructions with screenshots to install Mattermost in 5 minutes. She is able to install SharePoint and Project Server through the same process. 

2. I think you're right that there's an eval process. I think we want to focus on the case where we win a non-technical end user first and IT is meeting demand. More likely the case is a developer installs Mattermost to scratch their own itch, and IT takes it over after an eval of other options. That said, we have encountered many "theoretically technical people" who aren't familiar with Linux and web servers (e.g. maybe they are Windows admins) who want to install Mattermost, and there are essentially "non-technical" when it comes to the first install experience of Mattermost.

**Comment by lfbrock** [comment]
I'm fine with having aspirational personas, but we should make it clear which ones they are and that they're "proto-personas" (where the idea is they will be validated later on), since typically when people say personas they are based on research/real users.

**Comment by justinegeffen** [comment]
This is a great suggestion. I believe Marketing have put together personas. @ekl1773, is this something you could verify? Thank you! :)
