### ISSUE TITLE
How to incorporate docs earlier into the PR review process

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#1135]
Notes from an earlier discussion with @JeffSchering 

----

See this excerpt from http://contentstrategy101.com/contents/creating-useful-information/

Content is an afterthought. Technical content is seen as a necessary evil and not a strategic asset. 

Documentation is created at the last minute, content creators are not full members of the product teams, and the “just get something out there” mentality prevails. 

When a writer is involved early on, he can advise you on how to create a design that requires no recourse to documentation. 

The last thing you want is a user looking at the modal and wondering what to do, and maybe thinking of looking in the docs. Every minute spent using the docs is a minute spent not using the product. 

Help text and other clues in the UI can prevent a lot of frustration for end users.

----

Creating an issue to discuss openly with anyone interested.

**Comment by it33** [comment]
1. Our design principle is "fast, obvious, forgiving" and great documentation is vital to a great product. 
2. We need to bring in great people to the team that care more about documentation than about other priorities. If people care, and they are great, they will influence the team to create great docs. 

[Here is what it looks like when a developer is working with someone who cares about documentation.](https://github.com/EionRobb/purple-mattermost/commits/master?after=208502a25b310c72d4f8148412349995903b0fbc+34)

Here is the result in 5 days of working together after hours: 

- [Install Guide](https://github.com/EionRobb/purple-mattermost/blob/master/INSTALL.md#server-install)
- [Verification Guide](https://github.com/EionRobb/purple-mattermost/blob/master/VERIFICATION.md)
- [README](https://github.com/EionRobb/purple-mattermost/blob/master/README.md)

**Comment by justinegeffen** [comment]
I'm happy to confirm that this issue has been solved by the addition of two technical writers. :)
