### ISSUE TITLE
UX Design Challenge - Mockup of theme settings refinement 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#1151]
This ticket is a "Mattermost Open Source UX Design Challenge" that may be used to assess the abilities of a UX designer as a candidate for a staff role at Mattermost, Inc., working on the Mattermost open source project. 

- We estimate a design should take around 1-4 hours to complete depending on skill level. 
- Should you accept this challenge and produce a better design than all other candidates, your work may be used by the Mattermost open source project, in which case you will be credited for the design in its release announcement, and in the history of the open source project through the tickets created to implement the feature. 

Should you decide not to accept this challenge, please let your recruiter know and an alternative evaluation project will be provided. 

# Mockup of theme settings refinement 

The design challenge is to examine Mattermost's existing theme settings menu and propose a refinement of the design using heuristic evaluation and a wire-frame mock-up. 

![image](https://cloud.githubusercontent.com/assets/177788/25602306/94ae99f0-2ea7-11e7-99e5-5e0b0a1f7efc.png)

Note: 

- The goal of this design challenge is not a complete design, but to create a sketch of minor improvements to the design of an interface as a starting point for a conversation with your next interviewer. 
- Normally a designer would have access to product managers, user researchers, personas, use cases and other supporting materials when working, and this is not the case with this exercise. 
- Please assume you are the user for which the interface is targeting, and the context is using Mattermost for day-to-day communication at work. 

To start: 

1. Sign-up for the [Mattermost Community Server](https://pre-release.mattermost.com)
2. Go to Account Settings > Display > Theme and explore the existing theme settings menu. 
3. Understand the functionality for 
   1. Selecting a pre-configured theme
   2. Changing theme settings
   3. Exporting a theme by copying its theme code
   4. I mporting a theme using its theme code
   5. Importing a Slack theme. 
4. Conduct a heuristic evaluation to critique the usability and design of the current implementation. 
5. Mockup a wireframe of key screens for a new design that addresses the heuristic evaluation issues identified in Step 4. 
6. Conduct a heuristic evaluation of your mockup and iterate on the design until you feel your design is a clear improvement from the original design 
7. On the Mattermost server, go to the [Feature Proposals channel](https://pre-release.mattermost.com/core/channels/feature-ideas) and make a posting with: 
   1. A link to this ticket 
   2. Your heuristic evaluation of the original design from Step 4
   3. The wireframe mockups of your newly proposed design 
8. Optional: Answer any feedback from the community on your design ideas 

Once complete, please contact your recruiter to have your design reviewed by the next interviewer.

**Comment by justinegeffen** [comment]
@matthewbirtch, is this something the UX team still uses? If so, perhaps we can move it to the Handbook as part of the interview process/onboarding for the UX team? Thank you!

**Comment by andrewbrown00** [comment]
@justinegeffen we can remove this as Matt's correct, this is VERY out of date 🙂

**Comment by it33** [comment]
👍
