### ISSUE TITLE
Replace embedded images in docs with RST tables where possible

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#1161]
There are examples of embedded images in our docs, which could simply be RST tables. The embedded images makes it hard to
 - update information when something has changed
 - copy the text

Some examples include:
 - embedded image for Markdown Basics (if a user sees the help table, there's a good chance they try to copy-paste the Markdown formatting into a channel): https://docs.mattermost.com/help/getting-started/messaging-basics.html#messaging-basics
 - embedded image for list of commands (makes it hard to update if anything is changed): https://docs.mattermost.com/help/messaging/executing-commands.html

Note: Some of these help docs are in our platform repo too as they're translated across different languages: https://github.com/mattermost/platform

**Comment by JeffSchering** [comment]
Closing. Resolved by https://github.com/mattermost/docs/pull/1356
