### ISSUE TITLE
broken link or missing information

### ISSUE THREAD

**Issue by cpanato** [mattermost/docs#1268]
In line `37` of `/source/process/developer.rst` there is a link that looks like is missing his page or something

the `paid simulation` when you click it redirect to the same page and goes to the top.

```
- You've either made substantial contributions to the Mattermost open source project or are open to completing a `paid simulation <https://docs.mattermost.com/process/developer.html#paid-simulation>`_ to assess your comfort in working in open source.
```

**Comment by JeffSchering** [comment]
Thanks @cpanato!  Resolved by https://github.com/mattermost/docs/pull/1339.
