### ISSUE TITLE
[Help Wanted] Documentation for installing on Debian Jessie

### ISSUE THREAD

**Issue by JeffSchering** [mattermost/docs#1275]
Help is needed to incorporate the feedback from https://github.com/mattermost/platform/issues/1185 into the Debian Jessie docs at https://docs.mattermost.com/install/prod-debian.html.

If you're willing to take this on, reply here and join the Documentation channel on the Mattermost public server at https://pre-release.mattermost.com/core/channels/documentation, where you can ask questions and coordinate efforts with anyone else who happens to be working on this too.

Thanks!

**Comment by acgustafson** [comment]
I would love to take this on. Let me know if there is anything specific you are looking for. in the document.

**Comment by JeffSchering** [comment]
Thanks @acgustafson! Basically the end goal is to have the Debian install look like the other installs (https://docs.mattermost.com/install/install-rhel-71.html and https://docs.mattermost.com/install/install-ubuntu-1604.html for eg.)

Ideally, someone should be able to, for the most part, copy/paste the commands from the instructions into their terminal and successfully install Mattermost.

**Comment by JeffSchering** [comment]
Thanks for [Modified Install Guide for Debian Jessie #1301](https://github.com/mattermost/docs/pull/1301) @acgustafson!
