### ISSUE TITLE
Erroneous Config File /etc/nginx/sites-available/mattermost

### ISSUE THREAD

**Issue by IanMaquignaz** [mattermost/docs#1277]
**Issues With NGINX SSL Config**
- "..." Results in Nginx crash. Replace with {domain-name}
- "}" in incorrect location.
- Strongly suggest providing entire Nginx config file (as shown below)
- Instructions are unclear as to how to configure Mattermost before attempting NGINX SSL. Errors result in Mattermost failure and require reinstall + clearing of MySql.  

**Provided Code:**
server {
   listen 80 default_server;
   server_name   {domain-name} ;
   return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl http2;
  server_name    **. . .** ;
  ssl on;
  ssl_certificate /etc/letsencrypt/live/{domain-name}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/{domain-name}/privkey.pem;
  ssl_session_timeout 5m;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
**}**

**Actual Working Code:**
upstream backend {
   server 127.0.0.1:8065;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=mattermost_cache:10m max_size=3g inactive=120m use_temp_path=off;

server {
   listen 80 default_server;
   server_name   {domain-name} ;
   return 301 https://$server_name$request_uri;
}
server {
  listen 8067 ssl http2;
  server_name    {domain-name} ;

  ssl on;
  ssl_certificate /etc/letsencrypt/live/{domain-name}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/{domain-name}/privkey.pem;
  ssl_session_timeout 5m;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;

   location ~ /api/v[0-9]+/(users/)?websocket$ {
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       client_max_body_size 50M;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       proxy_read_timeout 600s;
       proxy_pass http://backend;
   }

   location / {
       client_max_body_size 50M;
       proxy_set_header Connection "";
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       proxy_read_timeout 600s;
       proxy_cache mattermost_cache;
       proxy_cache_revalidate on;
       proxy_cache_min_uses 2;
       proxy_cache_use_stale timeout;
       proxy_cache_lock on;
       proxy_pass http://backend;
   }
}

**Comment by JeffSchering** [comment]
Hi @IanMaquignaz 

Step 8 says to incorporate the highlighted lines into your existing file. It doesn't say to replace the file. The reason that it's done this way is because we don't always know the existing contents of the config file. The sample that you posted might work in your installation, but other admins have different preferences and settings.

We're always looking to improve the docs. If there's something not clear about the instructions in Step 8 (or elsewhere) please let us know.

![image](https://user-images.githubusercontent.com/20325173/28221183-2e77d494-6877-11e7-8ab7-b3223796a0d0.png)

**Comment by IanMaquignaz** [comment]
Forgive my ignorance, but in order to make mattermost work with nginx, I had to place the content of "location /api/v3/users/websocket{ ... }" within the body of server { } and "server_name ...;" has to be written as "server_name {domain-name};" (replacing {domain-name} with your domain name). 

Is that not correct?

**Comment by JeffSchering** [comment]
Ah, ok. I think I understand the source of the confusion. It looks like the docs don't make it clear that you first configure NGINX as a proxy (https://docs.mattermost.com/install/install-ubuntu-1404.html#configuring-nginx-as-a-proxy-for-mattermost-server), then if you want to set up SSL, follow the additional instructions at https://docs.mattermost.com/install/install-ubuntu-1404.html#configuring-nginx-with-ssl-and-http-2.

So the instructions might not be clear enough about having to set up as a proxy first, and then later modifying the existing file to set up SSL. Is that correct?

**Comment by IanMaquignaz** [comment]
More or less. I did follow the steps to set up as a proxy first, then tried to setup the existing file for SSL. As you noted, step 8 says to incorporate the highlighted lines into your existing file, but those lines produced a configuration non-functional with NGINX.

To resolve the issue, I had to move the original proxy information to within the body of the ssl server configuration and provide a valid server name. Else the new SSL NGINX configuration does not properly redirect to the mattermost backend, and instead you get a systemctl error, or, redirected to the NGINX 'hello world' page.

**Comment by JeffSchering** [comment]
I see in your actual working code sample you have this:
>server {
>listen 8067 ssl http2;
>server_name {domain-name} ;

The standard SSL port is 443, which is what's in the doc. Is that the source of the problems? The code sample in the docs has 443, but your actual port is 8067.

**Comment by IanMaquignaz** [comment]
Correct, this is custom for our domain. It works with the current configuration of mattermost and the configuration of our other servers which run NGINX. Our mattermost server can be accessed at https://{domain-name}:8067.

To clarify, our mattermost server works great and we are very happy with it. The believed error in the instructions is that the highlighted lines for SSL NGINX modification suggest two changes which prevented NGINX from configuring (with port 443 or 8067).  I've used all-caps below to markup the changes I had to make to make it functional. This takes into account that we don't always know the existing contents of the config file, and moves the config forwards from basic proxy configuration to working SSL configuration.

**server {
   listen 80 default_server;
   server_name   {domain-name} ;
   return 301 https://$server_name$request_uri;
}**

server {
  **listen 443 ssl http2;**
  server_name    . . . ;

  **ssl on;
  ssl_certificate /etc/letsencrypt/live/{domain-name}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/{domain-name}/privkey.pem;
  ssl_session_timeout 5m;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;**
} _<-- THIS BRACKET HERE, WHICH IS SHOWN IN SSL INSTRUCTIONS_


**_ --> Should actually be as follows: <--_**

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=mattermost_cache:10m max_size=3g inactive=120m use_temp_path=off;

**server {
listen 80 default_server;
server_name {domain-name} ; 
return 301 https://$server_name$request_uri;
}**
server {
**listen 443 ssl http2;
server_name {domain-name} ;** <-- SAME AS PROXY INSTRUCTIONS

**ssl on;
ssl_certificate /etc/letsencrypt/live/{domain-name}/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/{domain-name}/privkey.pem;
ssl_session_timeout 5m;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
ssl_prefer_server_ciphers on;
ssl_session_cache shared:SSL:10m;**
**_<-- NO BRACKET HERE_**

location ~ /api/v[0-9]+/(users/)?websocket$ {
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
client_max_body_size 50M;
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Frame-Options SAMEORIGIN;
proxy_buffers 256 16k;
proxy_buffer_size 16k;
proxy_read_timeout 600s;
proxy_pass http://backend;
}

location / {
client_max_body_size 50M;
proxy_set_header Connection "";
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Frame-Options SAMEORIGIN;
proxy_buffers 256 16k;
proxy_buffer_size 16k;
proxy_read_timeout 600s;
proxy_cache mattermost_cache;
proxy_cache_revalidate on;
proxy_cache_min_uses 2;
proxy_cache_use_stale timeout;
proxy_cache_lock on;
proxy_pass http://backend;
}
} _**<-- USE OLD BRACKET HERE FROM PROXY**_

**Comment by JeffSchering** [comment]
It looks like the lines that caused you problems were lines that are not highlighted, and should not be copied. If there's something about the instructions that can be improved to make sure that it's clear that only the highlighted lines are relevant, then let us know. Otherwise, I'd like to close this issue.

**Comment by IanMaquignaz** [comment]
Please remove the bracket that should not be there and write server_name {domain-name} as shown in the proxy instructions. 

This will make changes between the proxy instructions and SSL instructions more explicit. Current instructions say to modify only highlight lines... of a file that shows modifications beyond what should be present after the proxy instructions.

**Comment by JeffSchering** [comment]
Thanks @IanMaquignaz! I apologize for misunderstanding; thanks for the effort you put into explaining the situation. I created this PR: https://github.com/mattermost/docs/pull/1376

**Comment by IanMaquignaz** [comment]
Thanks @JeffSchering!
