### ISSUE TITLE
JSON payloads for example web hooks in the documentation are not visible

### ISSUE THREAD

**Issue by Miles-Davies-HORIBA** [mattermost/docs#1430]
The JSON payloads are not visible in the documentation for web hooks making it difficult to understand what is required to web hook.

**Comment by jasonblais** [comment]
@Miles-Davies-HORIBA Looks like the latest update caused a bunch of issues. For some reason images are sized incorrectly and the payloads are missing as you said --- sorry about that, we'll look at fixing.

**Comment by jasonblais** [comment]
@Miles-Davies-HORIBA Should be fixed now. Thanks for reporting it!
