### ISSUE TITLE
Update mobile developer documentation to reflect release of mobile apps

### ISSUE THREAD

**Issue by aditya-konarde** [mattermost/docs#1461]
The [mobile developer machine setup documentation](https://docs.mattermost.com/developer/mobile-developer-setup.html) currently states that the Mattermost mobile apps are not yet released and will be released in March 2017. 

Since the apps have now been released and are available on the Android and iOS stores, it makes sense to update the first line which says that the mobile apps are unreleased.

**Comment by lindy65** [comment]
Thanks for the report @aditya-konarde :)  I've created a pull request to update the doc.

**Comment by aditya-konarde** [comment]
You're welcome @lindy65 :)
:+1: for the quick fix.
