### ISSUE TITLE
Write documentation in Markdown instead of reStructuredText

### ISSUE THREAD

**Issue by bbenoist** [mattermost/docs#1474]
Since Mattermorst uses Markdown (very important feature 👍 ), I wanted to copy-paste some doc in a channel to help our user with useful tips.

I was quite disappointed to see that your documentation is written with reStructuredText instead 😕 

Do you have any plan to switch at some point?

**Comment by lindy65** [comment]
Hi @bbenoist,

Thank you for your question,

We used to use markdown for our documentation but switched to reStructuredText a while ago.

Perhaps you could copy/paste the `raw` version of the doc and edit it a little to render properly in the channel?
