### ISSUE TITLE
Where necessary, expand the descriptions of the CLI commands

### ISSUE THREAD

**Issue by peterdamian** [mattermost/docs#1499]
The description for some CLI commands is too brief. For example documentation of the ``create user`` command simply says: 

"Create a user."

More would be beneficial. Explain how this differs from inviting a user. If there is a way of doing the same thing through the sytem console describe it. Also explain any related server configuration options. 

See also #1498 and #1497.

**Comment by justinegeffen** [comment]
I believe the CLI commands, especially for mmctl, are more detailed and provide the required information. For example, we have a description, a usage example, and a section explaining config. options. 

@cwarnermm, I'm closing this as completed but wanted to add you in case there's anything that may be helpful for the future config docs work.
