### ISSUE TITLE
The 'platform channel move' command example is incorrect. It shows only one argument but there should be two.

### ISSUE THREAD

**Issue by peterdamian** [mattermost/docs#1500]
Revise this example to show the team argument. Also revise the format section to include the required arguments, i.e. ``platform channel move {channel} {team}``

**Comment by justinegeffen** [comment]
This command no longer exists and the channel move command has been replaced with mmctl channel move: https://docs.mattermost.com/manage/mmctl-command-line-tool.html#mmctl-channel-move. Closing. :)
