### ISSUE TITLE
Document installing Mattermost using Docker

### ISSUE THREAD

**Issue by peterdamian** [mattermost/docs#1505]
Installing Mattermost using Docker is the quickest way to get up and running with Mattermost. The URL https://docs.mattermost.com/install/docker-local-machine.html briefly describes how to do this and the instructions are probably adequate for anyone familiar with Docker. However these instructions should be expanded for users who don't know Docker. 

Since this is aimed at an audience unfamiliar with Docker, emphasize how easy it is to install Docker and how easy it is to then install the Mattermost server. 

Once Mattermost is up and running users need to configure the server by changing settings, adding users etc. Configuration changes require a restart. Explain how this is done using the *docker* command. 

Where possible perform the tasks described in #1504.

Explain the limitations of running Mattermost from within Docker. Some functionality may not be available on some platforms.

**Comment by acgustafson** [comment]
Personally I see this as a non issue. Mattermost docs shouldn't be teaching someone how to use Docker, that is what Docker's wiki is for. Maybe it is worth adding a link to docker's wiki with a docker quick start guide like [this one](https://docs.docker.com/get-started/)?

I do think it would be worth noting some of the limitations of running Mattermost on docker. Thoughts?

**Comment by justinegeffen** [comment]
I've reviewed the current Docker and Kubernetes documentation and from what I can see they are more comprehensive than they likely were in 2017. For example, links to additional configurations (such as adding users) are now included as are links to Docker documentation. 

The only information that is not included is limitations. @acgustafson, would you be open to sharing some of those and letting me know whether they're still an issue so they can be addressed? :)

**Comment by justinegeffen** [comment]
Following up on this; @acgustafson, are you open to taking a look at this and letting me know whether they address your comments? It would be much appreciated. :)

**Comment by justinegeffen** [comment]
The Docker documentation has been moved to: https://github.com/mattermost/docker. Closing this issue. :)
