### ISSUE TITLE
Provide a troubleshooting section specific to MySQL installation errors

### ISSUE THREAD

**Issue by peterdamian** [mattermost/docs#1513]
In a bare-bones installation (see #1504) the only possible point of failure apart from the Mattermost server, is the database. MySQL database error messages are not always helpful. Give examples of error messages and show how they relate to following types of errors:

- incorrect settings in the database driver file
- incorrect owner of mattermost database
- incorrect database user

This could be a new "Installation Troubleshooting" section.

**Comment by lindy65** [comment]
Hi @peterdamian 

Thanks for your feedback!  Appreciated...

Is this something you'd be interested in doing a pull request for?

**Comment by peterdamian** [comment]
Hi @lindy65,

I'll start working on this.

**Comment by lindy65** [comment]
Thanks @peterdamian :)

**Comment by justinegeffen** [comment]
Hi @peterdamian. I wanted to follow up on this and find out whether you'd be open to submitting a pull request for your changes? They look very useful and it would be great to have the team look them over. Thank you!

**Comment by justinegeffen** [comment]
This work has been completed and can be found here: https://docs.mattermost.com/install/trouble_mysql.html. Closing. :)
