### ISSUE TITLE
Wrong directory path in "Compiling Mattermost"

### ISSUE THREAD

**Issue by WyattPorter** [mattermost/docs#1528]
Hi,

in the file `docs/source/developer/dev-setup-compiling.rst` (current `master`; commit  d31f09de5cc53c21d338f26bc5e45608284bf89f) one is asked to:

> ... change to the source directory with the following command:
>   ``cd ~/go/src/github.com/mattermost/platform``

which will not work (since the folder does not exist).
Substituting `platform` with `mattermost-server` helps (hence suggested change).

Probably related to #1477.

Regards,
wp

**Comment by lindy65** [comment]
Thanks @WyattPorter !

I've created a [pull request](https://github.com/mattermost/docs/pull/1540) to fix the issue.
