### ISSUE TITLE
Changelog misaligned in TOC

### ISSUE THREAD

**Issue by shieldsjared** [mattermost/docs#1550]
Noticed that the changelog is appearing in the top-level of the table of contents (screenshot below).
If this wasn't intended, it's due to the type of underline being used the Changelog header.  The only reason this seem's off is because everything in the top of the TOC is a reference to a guide, or something similar; however, the changelog is currently a section within the administrator's guide (yet appears as a sibling in the TOC).

FIX: `.\source\guides\administrator.rst`

**OLD:**
``` rst
Changelog
=========
```
![image](https://user-images.githubusercontent.com/600643/31308067-e18e2066-ab3d-11e7-8b50-64fd683750d1.png)

**NEW:**
``` rst
Changelog
---------
```
![image](https://user-images.githubusercontent.com/600643/31308105-797b408e-ab3e-11e7-972a-3b297b382156.png)

I'm happy to submit a quick PR.

**Comment by lindy65** [comment]
Hey @shieldsjared,

Thanks for your feedback,

To be honest, I'm not sure whether the change was intentional so will defer to @jasonblais or @esethna to chime in.

**Comment by jasonblais** [comment]
That was a mistake, thanks @shieldsjared! Have fixed it with https://github.com/mattermost/docs/commit/b47f2b52362770ba92beb31b3f3f6194d15576bc#diff-4446e82190a7cf09548325ccc982363e
