### ISSUE TITLE
Consistent TOCs

### ISSUE THREAD

**Issue by seenthattinker** [mattermost/docs#1579]
In the Docs » Mattermost Overview » Security Overview section we get an example of a redundancy:

**Security Overview**
Security in Mattermost software is continually reviewed by developers, IT administrators and security researchers accountable for deploying the software in their organizations.

Multiple rounds of penetration testing and security analysis, in addition to internal reviews, have produced a long list of safeguards, processes, policies, and compliance features, please see:

Contents

**Security Overview**
Security Features
Private Cloud Deployment with Secure Mobile Apps
Centralized Security and Administration
Transmission Security
Integrity & Audit Controls
Authentication Safeguards
Access Control Policy
Security Updates
Security Policies
HIPAA compliance

Security Overview is the top tier heading. It comes from the left sidebar TOC. It does not need to be repeated in the hyperlinked micro TOC. The micro TOC is for navigating the content in that page. It does not need to restate the top heading. This is flawed information architecture. The problem as delimited in this post repeats itself throughout the documentation. An information architecture edit needs to be undertaken to apply consistent navigation.

**Comment by bvineyar** [comment]
I can work on this one.

**Comment by justinegeffen** [comment]
Hi @bvineyar! Thanks for offering to take this on. Are you still open to taking a look at it? If so, please let me know whether you have any questions - I am more than happy to help and look forward to working with you on this. :)

**Comment by justinegeffen** [comment]
To add to this, we are working on a larger IA/organization project and community feedback/insight would be really helpful. Let me know if you want more information or come join the [Documentation channel](https://community.mattermost.com/core/channels/documentation) and we can discuss further.

**Comment by justinegeffen** [comment]
This has been addressed by docs 2.0. :) Closing.
