### ISSUE TITLE
Overview Section Requires Edit

### ISSUE THREAD

**Issue by seenthattinker** [mattermost/docs#1580]
The Overview section needs to be strictly edited for consistency and clarity. There are too many parenthetical phrases (ideas dropped between quotation marks in an otherwise clean declarative sentence) which make the reading cumbersome.

**Comment by justinegeffen** [comment]
Hi @seenthattinker. This is great feedback. I've taken a look at the [Overview](https://docs.mattermost.com/overview/index.html) section and as there are multiple sections I was wondering if you had any specific section in mind for which you'd be open to editing and submitting a pull request?

**Comment by seenthattinker** [comment]
All of them, next week.

**Comment by justinegeffen** [comment]
This has been addressed by docs 2.0. Closing. :)
