### ISSUE TITLE
Administrator’s Guide TOC is Redundant and too Long

### ISSUE THREAD

**Issue by seenthattinker** [mattermost/docs#1583]
The Administrator's Guide TOC should be redone to limit white space on the page and avert the redundancy of the left sidebar TOC and the main page TOC.

**Comment by justinegeffen** [comment]
Hi @seenthattinker. Thanks for raising this. Would you be open to providing an example of limiting the white space and averting the LHS navigation? We're actively working on documentation improvements, so your insight and suggestions are extremely helpful. Thank you!

**Comment by seenthattinker** [comment]
You need to do what u have done on the first splash page the documentation presents. You have a number of boxes which lead the reader to books. Similarily, the TOCs of some of the books should be presented with a little more style to make top level selecion possible by glancing at one page. At present your information is lacking all architecture and design.

**Comment by justinegeffen** [comment]
Hi @seenthattinker. I've taken a look at the docs and I'd like to confirm that splash page refers to [these docs](https://docs.mattermost.com/)? Additionally, what I understand of your feedback is that each doc set should be an individual block so that it only contains its own TOC rather than navigating to the entire doc set?

**Comment by seenthattinker** [comment]
That is correct. Apologies, I have not been able to get to your work as I
am occupied.
*_____________________________________________*
*Bruce MacDonald*
*seenthattinker@gmail.com <seenthattinker@gmail.com>*
*TextMe: 647 491 7106*
*Skype Phone Number: 864 810 1039*

*Skype: seenthattinker1*

**Comment by justinegeffen** [comment]
No problem at all, @seenthattinker - we appreciate you raising these issues and working with us thus far. I can confirm that your suggestion is under consideration as part of a larger improvement plan (you'll see the overarching project link in this ticket). 

Would you be open to working with us on this once we've moved into the next phase and providing some feedback?

**Comment by seenthattinker** [comment]
It is entirely possible I might be getting a technical writing teaching job
here in Costa Rica. If I do, I would like to take on Mattermost as a class
project. Reorganize and publish epubs, sphinx site, and pdf.
*_____________________________________________*
*Bruce MacDonald*
*seenthattinker@gmail.com <seenthattinker@gmail.com>*
*TextMe: 647 491 7106*
*Skype Phone Number: 864 810 1039*

*Skype: seenthattinker1*

**Comment by justinegeffen** [comment]
Congratulations on the potential job - that sounds very exciting! I'm adding @jasonblais and @wiersgallak to this thread as they're also involved in the current publishing project and can provide insight into how to potentially fold this into the overall architecture part of the GSoD project goals.

**Comment by justinegeffen** [comment]
This has been addressed by docs 2.0. Closing. :)
