### ISSUE TITLE
Bullets

### ISSUE THREAD

**Issue by seenthattinker** [mattermost/docs#1589]
A style protocol has to be initiated to use bullets the same way consistently. For example:

Mattermost empowers organizations to achieve their highest priorities through modern, enterprise-grade communication. Enjoy all the productivity benefits of workplace messaging across web, mobile and PC, with unlimited archiving, search and integrations in a single-tenant, private cloud solution under IT control.

Thousands of organizations use Mattermost around the world in 14 languages for its unmatched benefits:

Sec

- urity - Keep vital communications, including access to mobile and desktop apps, behind your firewall. Deploy using dozens of security features vetted by top security researchers. Data stays on servers you control, encrypted using keys you control.
- Configurability - Adapt your deployment to your needs, preferences, and existing systems. The open source Mattermost server enables advanced white labelling and customization with complete access to RESTful server APIs, drivers, webhooks and hundreds of 3rd party extensions.
- Scalability - Grow from dozens of users to tens of thousands on the same server. Built on a high performance, single-tenant infrastructure, Mattermost E20 offers cluster-based high availability deployments with horizontal scaling and advanced performance monitoring.

These should just be paragraphs. 

This problem persists throughout the documentation.

**Comment by justinegeffen** [comment]
Hi @seenthattinker! Thanks for raising this issue. Could you provide a little more detail around the guidelines you're suggesting? 

In the example you've given, I do see the benefit in using bullets as it's a list but there is definitely a case for not using them and having paragraphs instead because the information is still effectively conveyed. 

We have a style guide but it doesn't dictate specifically when bullets should be used rather than paragraphs. If you have a style guide in mind for this please let me know as this type of feedback is extremely helpful! 

Thank you!

**Comment by seenthattinker** [comment]
I would use bullets when the description item is a term or a definition which does not need a complete sentenece but is a long phrase. Cocatenating them makes them creates clumsy complex-compound sentences which read like a Romanian encyclppdia entry. Long lists of single word items can be put in a sentence with commas. Using bullets for them creates too much white space on the page.

**Comment by justinegeffen** [comment]
Thanks, @seenthattinker I understand your perspective and experience with our documentation.

We have not received any supporting comments or suggestions for this change and I was wondering if you'd be open to sharing the style guide recommendations for this suggestion?  

There are stylistic recommendations around bullet lists and how to punctuate and capitalize them in guides such as The Chicago Manual of Style, but no set guidelines on what can/should be a bullet list. 

We are very open to feedback on our documentation - the challenge is the amount of work involved in assessing the lists and bullet points throughout the documentation, their suitability and potential need to be rewritten. In addition, we're working on paring down our larger sections of content and introducing more bullet lists for better readability.

That said, the readability and structure of our documentation is important to us and so we would be happy to review a detailed proposal of these changes, with some examples based on our documentation. This will provide us with a framework within which to compare the suggestions against our plans, as well as assess the potential work involved. 

We could also then share this with the wider community and obtain their feedback.

**Comment by seenthattinker** [comment]
Sure, I can do that. I need a few days. I am working on a book right now.
point me to your style guide please.
*_____________________________________________*
*Bruce MacDonald*
*seenthattinker@gmail.com <seenthattinker@gmail.com>*
*TextMe: 647 491 7106*
*Skype Phone Number: 864 810 1039*

*Skype: seenthattinker1*

**Comment by justinegeffen** [comment]
That's no problem at all! :) 

Our style guide is located [here](https://docs.mattermost.com/process/documentation-guidelines.html) and you can also read about our [technical writing handbook](https://handbook.mattermost.com/operations/research-and-development/product/product-technical-writing-team-handbook) for more details about processes.

**Comment by justinegeffen** [comment]
This has been addressed by docs 2.0. Closing. :)
