### ISSUE TITLE
Private Cloud Deployment with Secure Mobile Apps

### ISSUE THREAD

**Issue by seenthattinker** [mattermost/docs#1591]
Correct all parts of the documentation where a bulleted list commences after a heading.

**Comment by justinegeffen** [comment]
Thanks for picking this up, @seenthattinker. I've taken a look at the [Deployment section](https://docs.mattermost.com/deployment/deployment.html) of our documentation and it looks like this has been revised and resolved. Are you open to looking it over and letting me know whether that's the case?

**Comment by seenthattinker** [comment]
Yes.

**Comment by justinegeffen** [comment]
Great! :)

**Comment by justinegeffen** [comment]
Hi @seenthattinker. I wanted to follow up on this, and find out whether you'd be open to confirming this has been addressed. :)

**Comment by justinegeffen** [comment]
This has been addressed by docs 2.0. Closing. :)
