### ISSUE TITLE
cross references

### ISSUE THREAD

**Issue by seenthattinker** [mattermost/docs#1593]
Cross-references do not need descriptors. See example:

Security Updates
Security updates address newly discovered attacks reported to Mattermost, Inc. by the security research community. Disclosures are made confidentially, under the Mattermost responsible disclosure policy, allowing for Mattermost, Inc. to provide security updates to the community prior to public disclosure.

For more information, please see:

Mattermost Security Updates Disclosures
A summary of security updates made based on past and on-going security analysis and penetration testing.
Mattermost Responsible Disclosure Policy
An overview of how security issues are confidentially reported to and address by Mattermost, Inc.

**Comment by justinegeffen** [comment]
Hi @seenthattinker. Thanks for raising this issue. Would you be open to updating the page in question and submitting a pull request? That will allow us to review the changes and confirm the next steps. Thank you!

**Comment by seenthattinker** [comment]
Yes, next week.

**Comment by justinegeffen** [comment]
This has been resolved as part of docs 2.0. Closing. :)
