### ISSUE TITLE
fixed width fonts

### ISSUE THREAD

**Issue by seenthattinker** [mattermost/docs#1594]
fixed width fonts, used for code snippets, and typically grayed in a box, are using a font too small for compatibility with the defacto colophon/fonts/style.

**Comment by justinegeffen** [comment]
Thanks for letting us know about this, @seenthattinker. I wanted to find out whether this issue has been resolved or it's something that requires investigation. Here is [one example of a code block](https://docs.mattermost.com/install/install-mmte-helm-gitlab-helm.html) - if you'd be open to taking a look and letting me know your thoughts that would be great. :)

**Comment by seenthattinker** [comment]
I'll do it.

**Comment by justinegeffen** [comment]
This has been addressed by our new style template which was introduced in v6.0. Closing. :)
