### ISSUE TITLE
web-mobiled-based 

### ISSUE THREAD

**Issue by seenthattinker** [mattermost/docs#1595]
No such nomenclature exists even in the most vernacular of computer jargons.

**Comment by justinegeffen** [comment]
Thanks for raising this, @seenthattinker. Would you be open to editing the section in question and submitting a pull request?

**Comment by seenthattinker** [comment]
Yes, next week.

**Comment by justinegeffen** [comment]
I've reviewed the documentation and the incorrect version is located in [a fork](https://jeffschering.github.io/mmdocs/upgrade/deployment/deployment.html). The Mattermost content [here](https://docs.mattermost.com/deployment/deployment.html) does not have this typo. Closing as resolved.
