### ISSUE TITLE
General edit of Deployment Overview

### ISSUE THREAD

**Issue by seenthattinker** [mattermost/docs#1596]
There are too many inconsistencies to list, but a best writing practice or style has to be created and adhered to for a more comprehensible body of documentation. One example is as follows:

Receive emails on desktop and mobile from the Mattermost server.

This is a sentence under a heading, but it isn't a sentence. It might be a suitable uncapitalized bullet, but it is not that either. The pattern for the page follows a sentence (subject, object, verb) and phrase (two of the aforementioned three: subject, object, verb, but not all three) that makes for a bad read.

**Comment by justinegeffen** [comment]
This has been completed by the PMs as part of v6.0 work. Closing. :)
