### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by seenthattinker** [mattermost/docs#1597]
In the Overview section, in particular, there are many instances of micro-headings that should really be tables.

**Comment by mattzamudio** [comment]
I can take care of this, but a little more detail as to what you have in mind would be helpful. I have a pretty clear idea of what we are looking for, but I'd like to hear it from you. 

I'm a first time contributor, so this seems like a great starting point. Can you assign the project to me?

**Comment by mattzamudio** [comment]
Hi @seenthattinker or, if he's not around anymore, maybe @amyblais. I never heard back about this. We are talking about the Security Overview page, correct? 

Just wanted to get your input before getting started.

**Comment by justinegeffen** [comment]
Hi @seenthattinker. I wanted to follow up on this and get some more details about your suggestion. Readability and clarity are important to us, so improvements in that respect are always welcome. 

It would be great to have an idea of how this would look so you're welcome to edit the docs to include your suggestion and submit a pull request for review and feedback. Let me know if you have any questions.

**Comment by seenthattinker** [comment]
I will do this starting Monday. The PDF is awful. You need to go through Latex on the Sphinx system, customize the output, then generate the same way web is generated, or go straight to epub, which Sphinx does exceptionally well. I will start editing next week. Be prepared. I am going to be ruthless and unsparing with the language.

**Comment by justinegeffen** [comment]
Thanks, @seenthattinker. I look forward to your contribution and working with you on it. :)

**Comment by justinegeffen** [comment]
This has been addressed as part of docs 2.0 and the 6.0 release. Closing. :)
