### ISSUE TITLE
Restore link to API Docs

### ISSUE THREAD

**Issue by pixelbrackets** [mattermost/docs#1663]
Expectation: I expect a link to API Docs in the Integration Guide.

Actual result: The Integration Guide is missing a link to [api.md](https://github.com/mattermost/docs/blob/master/source/developer/api.md). Instead it shows a link on how to add endpoints to the API ([api4.rst](https://github.com/mattermost/docs/blob/master/source/developer/api4.rst)).

![bildschirmfoto vom 2017-11-30 18-31-06](https://user-images.githubusercontent.com/1592995/33446056-24df82c4-d5ff-11e7-936a-152331351292.png)

Possible solution: 

1. Convert [api.md](https://github.com/mattermost/docs/blob/master/source/developer/api.md) to api.rst
1. Change the link in [integration.rst](https://github.com/mattermost/docs/blob/master/source/guides/integration.rst) from ```/developer/api*``` to ```/developer/api.rst```
1. Rename [api4.rst](https://github.com/mattermost/docs/blob/master/source/developer/api4.rst) to api-development-version4.rst
1. Change the link in [developer.rst](https://github.com/mattermost/docs/blob/master/source/guides/developer.rst) from ```/developer/api.*``` to ```/developer/api-development*```

If you agree I may prepare a pull request.

**Comment by jasonblais** [comment]
@pixelbrackets Agree, sounds great. Nice catch!

We'd welcome a pull request for this change.

**Comment by lindy65** [comment]
Thanks for the pull request @pixelbrackets! I'll close this issue off now :)
