### ISSUE TITLE
Cropped thumbnail of sent pictures?

### ISSUE THREAD

**Issue by Narmel** [mattermost/docs#1692]
Why do the thumb nails of the sent images need to be cropped?

**Comment by esethna** [comment]
Hi @Narmel, agree. We are working on an update to image thumbnails hopefully coming in the January release. In this update, single image thumbnails appear uncropped and larger in the center pane. Propose closing this ticket to track the progress on the PR here: https://github.com/mattermost/mattermost-webapp/pull/357
