### ISSUE TITLE
Reduce redundant config in config-proxy-nginx.rst

### ISSUE THREAD

**Issue by J0WI** [mattermost/docs#1780]
It's not necessary to have the same configuration in all `location` blocks. They can be moved to the `http` block instead.
A working patch can be found [here](https://patch-diff.githubusercontent.com/raw/mattermost/docs/pull/1772.patch). Feel free to use it or continue from there.

**Comment by lindy65** [comment]
Hi @J0WI,

Thanks for the feedback,

Appreciate your PR and hoping someone will continue where you left off :)

**Comment by J0WI** [comment]
@lindy65 for what reason has this been closed?

**Comment by lindy65** [comment]
Hi @J0WI,

I closed the issue off as it hasn't had any activity since Feb 12th and the associated PR is also closed.  Are you interested in continuing with the PR?

**Comment by J0WI** [comment]
@lindy65 the linked patch can still be used, I think the patch is still working. But I can't open the PR myself because of your restrictive CLA.

Feel free to use [the patch](https://patch-diff.githubusercontent.com/raw/mattermost/docs/pull/1772.patch) to fix this issue.

**Comment by lindy65** [comment]
Thanks @J0WI, appreciated :)  I will pass this on to the development team...
