### ISSUE TITLE
Staff Product Manager page

### ISSUE THREAD

**Issue by it33** [mattermost/docs#1818]
@lfbrock, Dan Williams and @coreyhulen published the start of a staff PM page: https://github.com/mattermost/docs/blob/master/source/process/product-manager.rst

1. Can you help fill in "Levels" and "Take Home Exercises"?
2. Dan, could you work with Lindsay for responsibility and requirements?
3. I'm going to ask Rich to update the company description, working with Morgan, based on our meeting last week.

**Comment by justinegeffen** [comment]
This has been addressed in the [Product Team Handbook](https://handbook.mattermost.com/operations/research-and-development/product/product-management-team-handbook).
