### ISSUE TITLE
Document how to set up Kubernetes 

### ISSUE THREAD

**Issue by mirhonda** [mattermost/docs#1828]
Document how to set up Kubernetes on AWS, Azure and Google Cloud. Although we have issue #1505 related to Docker, we don't instructions about Kubernetes.  

Going forward, I recommend creating an issue template to collect a baseline of initial information about doc-related issues.

**Comment by mirhonda** [comment]
I'm self-assigning this issue 👍 We can consider it a work in progress. 🛤

**Comment by jasonblais** [comment]
Thanks @mirhonda! 

> Going forward, I recommend creating an issue template to collect a baseline of initial information about doc-related issues.

That's a great suggestion. What information do you think would be useful?

**Comment by mirhonda** [comment]
My pleasure @jasonblais  - the template could include details about the affected:

- audience: _Who are we writing the topic for?_
- version(s): _Does the situation apply to previous releases, for the current release and going forward, or a future release?_
- platforms: _Does this situation apply to every platform or only specific one(s)?_
- related topics: _Are there other existing topics that the reader should consider? Do parallel or other topics need to be written?_

Interested in your ideas...

**Comment by jasonblais** [comment]
Yeah, I think that's a good template to start with, and we can always expand or adjust as we work through doc issues.

Let's test it out for Kubernetes:

1. Audience : We're writing this document for IT administrators who want to deploy a standard Mattermost cluster for thousands of users. This administrator could be using any platform of their choice.
2. Version(s): This applies to all versions v4.0 and later, which was the last release when major changes to high availability (HA) configuration and clustering were made.
3. Platforms: Theoretically any, but we'll focus on AWS, Azure and Google Cloud as these are the most popular among our customers.
4. Related topics: None, apart from [existing documentation for Kubernetes](https://github.com/mattermost/mattermost-kubernetes) and [HA configuration](https://docs.mattermost.com/deployment/cluster.html)

**Comment by mirhonda** [comment]
@jasonblais and @crspeller: I have a few questions about my content draft. Please share your thoughts and any other considerations about this content strategy. This subject is new to me. I want to be sure I'm writing to the appropriate level:
### Summary 
New procedures about installing Kubernetes in popular cloud services: AWS, Azure, and GoogleCloud.
### New content
Parent topic: "Cloud Services Setup"
Child topics: "Installing Kubernetes on AWS", "Installing Kubernetes on Azure" and "Installing Kubernetes on GoogleCloud"
_logic:_ This structure allows for future expansion to other cloud services.

### Outstanding questions
(for parent topic) should we:
- Link to the general Kubernetes page? (https://kubernetes.io/) or related cloud services comparison (https://codefresh.io/kubernetes-tutorial/kubernetes-cloud-aws-vs-gcp-vs-azure/)
- Mention that users need admin credentials to their respective cloud services or is that a given?
- Invite users to join related Mattermost channels, such as Developers?

(for child topics) should we: 
- Include a statement about the best use case for a particular cloud service?
- Mention kops as a best practice for AWS?

**Comment by jasonblais** [comment]
Thanks @mirhonda! 

Summary and content look good. For Kubernetes docs, are you thinking of a layout like https://docs.mattermost.com/deployment/sso-saml.html or one where they're all in one page?

For your questions:

> Link to the general Kubernetes page? (https://kubernetes.io/) or related cloud services comparison (https://codefresh.io/kubernetes-tutorial/kubernetes-cloud-aws-vs-gcp-vs-azure/)

I think that would be helpful for an admin, so yes

>  Mention that users need admin credentials to their respective cloud services or is that a given?

Yes, it doesn't hurt to mention it, as not all admins may know.

> Invite users to join related Mattermost channels, such as Developers?

Would the purpose be for troubleshooting questions? 

> Include a statement about the best use case for a particular cloud service?

Yea, that would be awesome!

> Mention kops as a best practice for AWS?

This I'll defer to @crspeller

**Comment by mirhonda** [comment]
Thanks @jasonblais! 
>For Kubernetes docs, are you thinking of a layout like https://docs.mattermost.com/deployment/sso-saml.html or one where they're all in one page?

Yes, the layout will be similar to https://docs.mattermost.com/deployment/sso-saml.html and https://docs.mattermost.com/developer/dev-setup.html with one general page linking out to more specific pages with one cloud service platform per page.

>Would the purpose be for troubleshooting questions?

Yes, troubleshooting as well as best practices.

Thanks for your help,
Mirhonda

**Comment by jasonblais** [comment]
For troubleshooting, we link to our troubleshooting forums: https://www.mattermost.org/troubleshoot/

This is just so it's easier for others searching in Google to find the information.

**Comment by mirhonda** [comment]
Hi @crspeller and @jasonblais - I'm trying to identify what's common across all platforms for installing kubernetes versus what is specific to AWS, Azure or GoogleCloud. Does this overall process see correct for all platforms:
1. Package your app into a Docker image
2. Upload the image to a registry
3. Create a container cluster
4. Deploy your app to the cluster
5. Scale up your deployment
6. Deploy a new version of your app

**Comment by mirhonda** [comment]
Thanks for the confirmation @crspeller.

**Comment by mirhonda** [comment]
Closing this issue based on discussion with @jasonblais and @lfbrock.

**Comment by mirhonda** [comment]
Closing this issue based on a conversation with @jasonblais and @lfbrock.
