### ISSUE TITLE
Why mattermost logged me out ?

### ISSUE THREAD

**Issue by maskalek** [mattermost/docs#1865]
From time to time mattermost logs me out and I have to type my credentials again and again. Issues exists in windows and android versions.
It is very annoying, but the main problem is I don't see if I logged in or not as long as I restore app because by default it starts minimized. 
Could you improve this behavior or at least save credentials not to write them always?

**Comment by svelle** [comment]
This is the repository for the documentation not the client or the server. 
The login timeout is set by the server-administrator and has to be set for each server individually, so you either want to contact that person or if you set up Mattermost by yourself change the corresponding setting.

**Comment by lindy65** [comment]
I'll close this issue off here for now.  Please feel free to open a new issue in the mattermost-server repository if you still experience a problem.
