### ISSUE TITLE
Interactive Message Buttons examples are confusing

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#1883]
On [this page](https://docs.mattermost.com/developer/interactive-message-buttons.html) there's this example:

```
{
  "update": {
    "message": "Updated!"
  },
  "ephemeral_text": "You updated the post!"
}
```

However, it doesn't describe where to place this to update the original post. This should be clarified.

**Comment by cwarnermm** [comment]
@mickmister - Would you be open to reviewing the existing developer documentation on [interactive messages and buttons](https://developers.mattermost.com/integrate/admin-guide/admin-interactive-messages/) to see if changes made would improve the clarity of that content?
