### ISSUE TITLE
Troubles with logg in 

### ISSUE THREAD

**Issue by FVaCh** [mattermost/docs#1903]
I have an SSO account and can´t reset my password

**Comment by amyblais** [comment]
Hey @FVaCh,

Apologies for late response, are you still having trouble accessing your account?

If yes, what error message are you seeing? What browser / app / server version do you use?

**Comment by FVaCh** [comment]
No worries,

I can´t still log in, and i´m not able to change my password.


Frida Vazquez  | Supervisor, Business Processing
Eje 5 Norte 990, Col. Santa Barbara, C.P 02230 | Azcapotzalco, Mexico
p +52 55 4164 2924 | fvazquez@tesla.com<mailto:fvazquez@tesla.com>

[cid:image002.png@01D3CBEF.F8EB9F90]<http://www.tesla.com/>         [cid:image004.png@01D3CBEF.F8EB9F90] <https://twitter.com/tesla>     [cid:image006.png@01D3CBEF.F8EB9F90] <https://www.youtube.com/channel/UC5WjFrtBdufl6CZojX3D8dQ>     [cid:image008.png@01D3CBEF.F8EB9F90] <https://www.instagram.com/teslamotors/>     [cid:image010.png@01D3CBEF.F8EB9F90] <https://www.linkedin.com/company/tesla-motors/>

**Comment by amyblais** [comment]
Thank you for letting me know! Would you like to post this issue in our Peer-to-peer Forum here: https://forum.mattermost.org/ - it is more active and somebody will definitely be available to provide technical assistance.

In your post you can also include any relevant info including what error message you are seeing, and what browser / app / server version you are using.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via your issue in the forum linked above.
