### ISSUE TITLE
HOW DO YOU MUTE THE NOTIFICATION SOUND?!

### ISSUE THREAD

**Issue by cgibson08201989** [mattermost/docs#1920]
I've tried everywhere to find the mute option for the notification sound. where is it? The super loud sound hurts my ears when ever it goes off and I have my headphones on. 

Thanks!

**Comment by lindalumitchell** [comment]
Hi @cgibson08201989, you can turn off the notification sound here:

Main (hamburger) menu > Account Settings > Notifications > Desktop Notifications > Edit

You should be able to select `Off` under the Notification Sound setting there.

Hope that helps!

**Comment by lindy65** [comment]
I'll close this issue off here for now as there hasn't been any feedback.  Please feel free to open a new issue if you still experience a problem

**Comment by hico11** [comment]
could show image as to where to turn off the notification sounds?
