### ISSUE TITLE
Apache Conf do not work for Apache 2.4.18

### ISSUE THREAD

**Issue by indikatordesign** [mattermost/docs#2122]
Hello,

I followed the configuration instructions for Apache and HTTPS. Unfortunately the websockets cannot be connected. Anybody have any idea what might be causing this?

Apache v. 2.4.18

## Settings
```
ProxyPreserveHost On
ProxyRequests Off
LogLevel debug

<Proxy *>
	Require all granted
</Proxy>

RewriteEngine On
RewriteCond %{REQUEST_URI} /api/v[0-9]+/(users/)?websocket [NC,OR]
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC,OR]
RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
RewriteRule .* wss://127.0.0.1:8065%{REQUEST_URI} [P,QSA,L]
RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
RewriteRule .* http://127.0.0.1:8065%{REQUEST_URI} [P,QSA,L]

<LocationMatch "^/api/v(?<apiversion>[0-9]+)/(?<apiusers>users/)?websocket">
	Require all granted
	ProxyPass wss://127.0.0.1:8065/api/v%{env:MATCH_APIVERSION}/%{env:MATCH_APIUSERS}websocket
	ProxyPassReverse wss://127.0.0.1:8065/api/v%{env:MATCH_APIVERSION}/%{env:MATCH_APIUSERS}websocket
	ProxyPassReverseCookieDomain 127.0.0.1 my-domain.com
</LocationMatch>

<Location />
	Require all granted
	ProxyPass http://127.0.0.1:8065/
	ProxyPassReverse http://127.0.0.1:8065/
	ProxyPassReverseCookieDomain 127.0.0.1 my-domain.com
</Location>
```

## Loaded Apache Modules
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 aclr_module (shared)
 actions_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 auth_digest_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cgi_module (shared)
 data_module (shared)
 dav_module (shared)
 dav_fs_module (shared)
 dav_lock_module (shared)
 dbd_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 filter_module (shared)
 headers_module (shared)
 heartmonitor_module (shared)
 include_module (shared)
 ldap_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 passenger_module (shared)
 perl_module (shared)
 proxy_module (shared)
 proxy_express_module (shared)
 proxy_fcgi_module (shared)
 proxy_http_module (shared)
 proxy_wstunnel_module (shared)
 python_module (shared)
 remoteip_module (shared)
 rewrite_module (shared)
 security2_module (shared)
 session_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 suexec_module (shared)
 unique_id_module (shared)
 userdir_module (shared)

## Error Messages
GET /api/v4/websocket HTTP/1.0	- SSL/TLS-Access for Apache

[ssl:debug] ssl_engine_kernel.c(354): AH02034: Initial (No.1) HTTPS request received for child 87 (server my-domain.com:443) - Apache-Error

[authz_core:debug] mod_authz_core.c(809): AH01626: authorization result of Require all granted: granted - Apache-Error

[authz_core:debug] mod_authz_core.c(809): AH01626: authorization result of <RequireAny>: granted - Apache-Error

[proxy:debug] mod_proxy.c(1160): AH01143: Running scheme wss handler (attempt 0) - Apache-Error

[proxy_fcgi:debug] mod_proxy_fcgi.c(879): AH01076: url: wss://127.0.0.1:8065/api/v4/websocket proxyname: (null) proxyport: 0 - Apache-Error

[proxy_fcgi:debug] mod_proxy_fcgi.c(882): AH01077: declining URL wss://127.0.0.1:8065/api/v4/websocket - Apache-Error

[proxy_http:debug] mod_proxy_http.c(1943): AH01113: HTTP: declining URL wss://127.0.0.1:8065/api/v4/websocket - Apache-Error

[proxy_wstunnel:debug] mod_proxy_wstunnel.c(341): AH02900: declining URL wss://127.0.0.1:8065/api/v4/websocket (not WebSocket) - Apache-Error

AH01144: No protocol handler was valid for the URL /api/v4/websocket. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule. - Apache-Error

[authz_core:debug] mod_authz_core.c(809): AH01626: authorization result of Require all granted: granted - Apache-Error

[authz_core:debug] mod_authz_core.c(809): AH01626: authorization result of <RequireAny>: granted - Apache-Error

[proxy:debug] mod_proxy.c(1160): AH01143: Running scheme http handler (attempt 0) - Apache-Error

[proxy_fcgi:debug] mod_proxy_fcgi.c(879): AH01076: url: http://127.0.0.1:8065/error_docs/internal_server_error.html proxyname: (null) proxyport: 0 - Apache-Error

[proxy_fcgi:debug] mod_proxy_fcgi.c(882): AH01077: declining URL http://127.0.0.1:8065/error_docs/internal_server_error.html - Apache-Error

[proxy:debug] proxy_util.c(2160): AH00942: HTTP: has acquired connection for (127.0.0.1) - Apache-Error

[proxy:debug] proxy_util.c(2213): AH00944: connecting http://127.0.0.1:8065/error_docs/internal_server_error.html to 127.0.0.1:8065 - Apache-Error

[proxy:debug] proxy_util.c(2422): AH00947: connected /error_docs/internal_server_error.html to 127.0.0.1:8065 - Apache-Error

[proxy:debug] proxy_util.c(2175): AH00943: : has released connection for (127.0.0.1) - Apache-Error

[deflate:debug] mod_deflate.c(853): AH01384: Zlib: Compressed 3169 to 1366 : URL /error_docs/internal_server_error.html - Apache-Error

**Comment by amyblais** [comment]
Hi @indikatordesign! Apologies for late reply. This is the Docs repo, so we don't follow the Issues here as regularly for troubleshooting issues - would you like to reopen this in the [Server repo](https://github.com/mattermost/mattermost-server/issues) or the [Forums](https://forum.mattermost.org/) so that we can help troubleshoot this? Thank you!
