### ISSUE TITLE
Zoom plugin screenshot is out-of-date

### ISSUE THREAD

**Issue by it33** [mattermost/docs#2129]
Docs are missing "Zoom URL": https://github.com/mattermost/docs/blob/master/source/integrations/zoom.rst#zoom-setup-guide

Updated image: 
![image](https://user-images.githubusercontent.com/177788/42194342-4c8d82b8-7e28-11e8-9dad-2daca7a96063.png)

**Comment by amyblais** [comment]
Closing via https://github.com/mattermost/docs/pull/2159
