### ISSUE TITLE
Zoom documentation not following doc guidelines for text formatting 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#2130]
# Mattermost Doc Guidelines for Text Formatting 

Here: https://docs.mattermost.com/process/documentation-guidelines.html#text-formatting

Specifically field names (e.g. **API Secret**) and clickable controls (e.g. **API** tab) should be **bold**. 
![image](https://user-images.githubusercontent.com/177788/42194696-1189229c-7e2a-11e8-8b5f-205739988f22.png)

Zoom docs aren't following this: 
https://docs.mattermost.com/integrations/zoom.html

![image](https://user-images.githubusercontent.com/177788/42194687-02e571c8-7e2a-11e8-934d-34a1fdc4f214.png)

There's probably other areas we're not following the guidelines as well. Can someone create a process so whoever is approving doc PRs is checking them via the doc guidelines?

**Comment by amyblais** [comment]
Closing via https://github.com/mattermost/docs/pull/2159
