### ISSUE TITLE
last iOS update is not working

### ISSUE THREAD

**Issue by Franck0d** [mattermost/docs#2135]
Hello, since the last update on iOS 10.3.3 (iPhone 5) the app quits when I try to open it.
The number of non read message is still appearing.
I have tried to remove the app en reloaded it but no change.
Can anybody help?

**Comment by amyblais** [comment]
Hi @Franck0d! Sorry for the late reply - would you like to reopen this Issue in the mobile repo so we can help troubleshoot this: https://github.com/mattermost/mattermost-mobile/issues?

There is also an ongoing Issue regarding app crashes that you might want to take a look at for further information: https://github.com/mattermost/mattermost-mobile/issues/1799.
