### ISSUE TITLE
missing docs: How to release a binary package ?

### ISSUE THREAD

**Issue by jk2K** [mattermost/docs#2153]
new developer docs site lacks guide on how to make binary package, the old site once had the tutorial

for example: 

1. how to build server, linux, mac, windows
2. how to build client
3. how to package

**Comment by amyblais** [comment]
Thanks @jk2K! A ticket for this was created and you can track its progress here: https://mattermost.atlassian.net/browse/MM-11446.

Let us know if you're interested in contributing!

**Comment by jk2K** [comment]
I'm interested, I will learn how to contribute

**Comment by amyblais** [comment]
Great to hear that, this page has instructions on how to get started: https://github.com/mattermost/mattermost-developer-documentation#mattermost-developer-documentation-
