### ISSUE TITLE
[Help Wanted] UX Design Challenge - Mockup of right hand sidebar refinement

### ISSUE THREAD

**Issue by michaelgamble** [mattermost/docs#2158]
This ticket is a "Mattermost Open Source UX Design Challenge" we encourage you to participate in this challenge and share your expertise and ideas on how to improve Mattermost. Throughout this process you will be engaging with our community of experts in the UX Design channel on our pre-release server [here](https://pre-release.mattermost.com/core/channels/ux-design), exchanging ideas in order to build something everyone is excited to use!

- We estimate a design should take around 4-8 hours to complete depending on your skill level. 
- Should you produce a better design than all other contributors in this challenge, your work may be used by the Mattermost open source project, in which case you will be credited for the design in its release announcement, and in the history of the open source project through the tickets created to implement the feature. 
- Please fill out the Mattermost contributor level agreement here.

### Mockup of the right hand sidebar refinement 
The design challenge is to examine Mattermost's existing right hand sidebar and propose a refinement of the design using heuristic evaluation and competitive analysis to mock up a wire-frame. Consider your time and feel free to selectively choose which states below are included in the proposal.

Some areas of improvement to consider:

- The general style and design of the right hand side bar including
  - Header
  - Icons
  - Content
- Go through each of the instances of right hand side bar below and provide your ideas and recommendations on how we could improve or approach them differently both aesthetically and or functionally.

Currently it exists in five states, below the screenshots are instructions on how to find and try each state:

| WebRTC: | Pinned Posts: |
| :------------- | :------------- |
| <img width="300" alt="webrtc 2x" src="https://user-images.githubusercontent.com/31866506/42770574-edf24dd0-88f2-11e8-8042-70d1b89cb045.png"> | <img width="300" alt="pinned-posts 2x" src="https://user-images.githubusercontent.com/31866506/42770712-1d8f1136-88f3-11e8-9aa7-f7276ca47499.png"> |

| Search: | Mentions: |
| :------------- | :------------- |
| <img width="300" alt="search-results 2x" src="https://user-images.githubusercontent.com/31866506/42771112-1efc6478-88f4-11e8-9323-83d1a9049a58.png"> | <img width="300" alt="mentions 2x" src="https://user-images.githubusercontent.com/31866506/42771151-40eecdaa-88f4-11e8-9f4a-d5ca1722b0dc.png"> |

| Flagged Posts: |
| :------------- |
| <img width="300" alt="flagged-posts 2x" src="https://user-images.githubusercontent.com/31866506/43086898-7cea4eec-8e6c-11e8-8d9a-107f253fe2b0.png"> |

Note: 

- The goal of this design challenge is not a complete design, but to create a sketch of minor improvements to the design of an interface as a starting point for a conversation with one of Mattermosts UX Design core contributors. 
- Normally a designer would have access to product managers, user researchers, personas, use cases and other supporting materials when working, and this is not the case with this exercise. 
- Please assume you are the user for which the interface is targeting, and the context is using Mattermost for day-to-day communication at work. 

To start: 

1. Sign-up for the [Mattermost Community Server](https://pre-release.mattermost.com)
2. Find and enter the “public test channel” by clicking the “+” button beside the public channels header in the left hand sidebar, you should see the channel header bar with all of the buttons that trigger the right hand sidebar. 
3. In order to see the WebRTC functionality, create a direct message to “@mike_gamble” and you will see the WebRTC button in the direct message header.
4. Understand the functionality in the right hand sidebar for 
  a. WebRTC
  b. Pinned Posts (create a post in a new channel and pin it)
  c. Search (search for a word in an existing post in a channel)
  d. Mentions (create a test post mentioning yourself by putting and at symbol in front of your username like “@username”)
  e. Flag posts (hover over a post and click the flag icon that shows up beside the date and time stamp)
5. Conduct a heuristic evaluation to critique the usability and design of the current implementation.
6. Conduct a competitive analysis to explore commonly used practices and patterns.
7. Mockup a wireframe of key screens for a new design that addresses the heuristic evaluation issues identified in Step 5 and 6.
8. Conduct a heuristic evaluation of your mockup and iterate on the design until you feel your design is a clear improvement from the original design
9. On the Mattermost server, go to the [Design Challenge channel](https://pre-release.mattermost.com/core/channels/design-challeng) and make a posting with:
  a. A link to this ticket
  b. Your heuristic evaluation of the original design from Step 5
  c. Your competitive analysis from Step 6
  d. The wireframe mockups of your newly proposed design 
10. Optional: Answer any feedback from the community on your design ideas 

Once complete, please contact reach out to a UX Design core contributor in the UX Design Channel on our pre-release server [here](https://pre-release.mattermost.com/core/channels/ux-design) and submit your design for review.

**Comment by justinegeffen** [comment]
Confirmed with @michaelgamble as completed and to be closed.
