### ISSUE TITLE
Webhook example screenshot is confusing

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#2211]
[On this page](https://docs.mattermost.com/developer/webhooks-incoming.html#simple-incoming-webhook) the screenshot shows "webhook [BOT]" which makes it seem that the username is changed to "webhook [BOT]" instead of it being "username [BOT]". We should update it clear that the [BOT] is appended to a username and the username isn't overridden.

**Comment by lfbrock** [comment]
I think the username actually does get overridden to be "webhook" if a) the system is set to allow overriding usernames, and b) no username is specified in the webhook payload

**Comment by icelander** [comment]
Confirmed, closing.
