### ISSUE TITLE
English [UK] Dictionary needed

### ISSUE THREAD

**Issue by GaryNoble** [mattermost/docs#2247]
Currently the 'English' dictionary is English [US] not actual English.

Please, at the very least, add a '[US]' to the word 'English' in the dictionary list even if adding English English is not a top priority, as it is currently a misrepresentation.

**Comment by amyblais** [comment]
Hi @GaryNoble!

Can you help clarify what page in the documentation you are referring to and I can take a look?

**Comment by GaryNoble** [comment]
Hi Amy,

I'm not sure what documentation you mean - I was referring to the in-app dictionaries - perhaps my request went to the wrong subforum?

Just in case, I was referring to this:
![image](https://user-images.githubusercontent.com/42768231/44796828-b9cd6780-aba5-11e8-914a-0a152428b064.png)

**Comment by amyblais** [comment]
Hi @GaryNoble!

Thanks for the details, I opened a ticket here to add '[US]' beside 'English' in the dictionary: https://mattermost.atlassian.net/browse/MM-11910.

Also, we have a Feature Request open here to add UK English to the dictionary which you can upvote: https://mattermost.uservoice.com/forums/306457-general/suggestions/34600312-support-for-australian-british-english!

**Comment by amyblais** [comment]
Hi @GaryNoble, the Jira ticket I referenced above has now been resolved and tested internally. I believe the improvement will be available in the next desktop app release.

Also, thanks for voting the Feature Request to add UK English to the dictionary, we can continue to track this in Uservoice,
