### ISSUE TITLE
Provide more explicit instructions for AD/LDAP configuration

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#2278]
[The instructions for setting up AD/LDAP](https://docs.mattermost.com/deployment/sso-ldap.html) only include this line for configuration AD/LDAP, but if you choose a non-static field for the `IdAttribute` you will end up deactivating users because this is both unique and case-sensitive.

This document should be modified to warn users of this problem..

**Comment by justinegeffen** [comment]
hi @icelander - I wanted to find out whether you are open to providing the updated content so we can add it to the documentation. Thank you!
