### ISSUE TITLE
[Help Wanted] UX Design Challenge - Navigating between multiple servers

### ISSUE THREAD

**Issue by michaelgamble** [mattermost/docs#2326]
# Navigating between multiple servers
This ticket is a "Mattermost Open Source UX Design Challenge" we encourage you to participate in this challenge and share your expertise and ideas on how to improve Mattermost. Throughout this process you will be engaging with our community of experts in the UX Design channel on our pre-release server [here](https://pre-release.mattermost.com/core/channels/ux-design), exchanging ideas in order to build something everyone is excited to use!
### Desired Impact 
We have customers with tens of thousands of users on two separate servers. The impact of this design is to provide an updated UI for navigating between those servers with a simple, elegant and aesthetically polished experience for those users.
### Goal
To examine Mattermost's existing user experience and design patterns around navigating multiple servers and propose a refinement of the design using heuristic evaluation and competitive analysis to mockup a wire-frame. 

(We do not expect complete designs, wireframes and supporting material to serve as a starting point for assessing the possible solution)
### Background Details
This came out of multiple discussions within the design team at Mattermost as one of the most obvious areas for improvement from an aesthetic / polish perspective.
The feature is intended for users that connect and navigate multiple servers instances, typically seen in large enterprise deployments.
### Use Cases
Normally a designer would have access to product managers, user researchers, personas, use cases and other supporting materials when working, and this is not the case with this exercise. 

Please assume you are the user for which the interface is targeting, and the context is using Mattermost for day-to-day communication at work.

**Navigating multiple servers**
Currently only visible in the desktop application when more then one server is configured.
- The user will navigate between multiple configured servers through the tabs across the top of the application.
![multiple-server-tabs](https://user-images.githubusercontent.com/31866506/46565992-35c57880-c8e5-11e8-9042-5b81981114d2.png)
- The system can generate notification jewels in the server tab for any mentions made to your user, or if the session expires in the tab that’s not in focus.
## Exercise Instructions
- We estimate a design should take around 4-8 hours to complete depending on your skill level.
- Should you produce a better design than all other contributors in this challenge, your work may be used by the Mattermost open source project, in which case you will be credited for the design in its release announcement, and in the history of the open source project through the tickets created to implement the feature.

1. Fill out the Mattermost contributor level agreement [here](https://www.mattermost.org/mattermost-contributor-agreement/).
2. Sign-up for the [Mattermost Community Server](https://pre-release.mattermost.com).
3. Sign-up for the [Mattermost Test Server](https://rctesting.reddogsofwar.com).
4. Download the appropriate desktop application for your operating system [here](https://about.mattermost.com/download/).
5. Find the preferences for the desktop application and add both servers to the desktop application.
6. Understand the functionality for navigating between multiple servers
7. Conduct a heuristic evaluation to critique the usability and design of the current implementation.
8. Conduct a competitive analysis of other products to explore commonly used practices and patterns.
9. Mockup a wireframe of key screens for a new design that addresses the heuristic evaluation issues identified in Step 6 and 7.
10. Conduct a heuristic evaluation of your mockup and iterate on the design until you feel your design is a clear improvement from the original design
11. On the Mattermost server, go to the [Design Challenge](https://pre-release.mattermost.com/core/channels/design-challenge) channel and make a posting with:
  a. A link to this ticket
  b. Your heuristic evaluation of the original design from Step 6
  c. Your competitive analysis from Step 7
  d. The wireframe mockups of your newly proposed design 
12. Optional: Answer any feedback from the community on your design ideas

Once complete, please contact reach out to a UX Design core contributor in the UX Design Channel on our pre-release server [here](https://pre-release.mattermost.com/core/channels/ux-design) and submit your design for review.

**Comment by justinegeffen** [comment]
Confirmed with @michaelgamble as completed and to be closed.
