### ISSUE TITLE
--all-teams flag for bulk export needs to come at the end of the command

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#2352]
Currently in the docs the `--all-teams` flag comes after `bulk` in the command:

```bash
$ sudo ./mattermost export bulk --all-teams file.json
```
It should read this:

```bash
$ sudo ./mattermost export bulk file.json --all-teams
```

**Comment by hanzei** [comment]
Closing this one as https://github.com/mattermost/docs/pull/2353 got merged.
