### ISSUE TITLE
Add client/plugins to Upgrade documentation

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#2416]
The current [upgrade documentation](
https://docs.mattermost.com/administration/upgrade.html) does not include a reference to the `client/plugins` directory. These should be updated to include ensuring this directory, just like `plugins` is replaced in steps 7, 8, and 14.

**Comment by jasonblais** [comment]
@hanzei If this is a required step when plugins are installed/enabled, then yea it's okay to add 👍

**Comment by svelle** [comment]
fixed in: https://github.com/mattermost/docs/commit/1dbf1dbd1ffbbcd1268199a91090f680c43155b9

**Comment by jasonblais** [comment]
Thanks!
