### ISSUE TITLE
docs.mattermost.com: Category links broken

### ISSUE THREAD

**Issue by amyblais** [mattermost/docs#2437]
**Steps to Reproduce**
1. Browse to https://docs.mattermost.com/process/training.html
2. Scroll down to any category, like "Mattermost Avatar"
3. Right-click on the header for that section and copy link address

**Expected**
1. Link address is the current page + anchor for that header, allowing you to link directly to that section

**Observed**
1. Link address is https://docs.mattermost.com/process/training.html#contents for all categories on the page:
![image-2018-12-13-12-58-46-482](https://user-images.githubusercontent.com/29708087/50035310-5ab62600-ffcf-11e8-8fd2-0cdd04902575.png)

**Comment by svelle** [comment]
Can't reproduce this on my end. Is this still an issue?

**Comment by amyblais** [comment]
True, I can't reproduce this now.
