### ISSUE TITLE
Video and Audio Calling documentation link is broken

### ISSUE THREAD

**Issue by sadohert** [mattermost/docs#2441]
There seems to be a broken link displayed at:

https://docs.mattermost.com/deployment/webrtc.html

When I click on the link here:
![image](https://user-images.githubusercontent.com/260544/50184644-a4f71a00-02e3-11e9-98c2-c6deaac894d1.png)

I get:

![image](https://user-images.githubusercontent.com/260544/50184586-842ec480-02e3-11e9-98fa-f43b903f9383.png)

**Comment by jasonblais** [comment]
@sadohert Thanks for the heads up - this should be fixed in 15 minutes, in the next doc update
