### ISSUE TITLE
Add instructions for using sockets to connect to DB

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#2475]
[Arch Wiki](https://wiki.archlinux.org/index.php/Mattermost#PostgreSQL) has instructions on setting up a socket-based connection. We should create an official document on how to use sockets for database connections.

**Comment by justinegeffen** [comment]
Thanks, @icelander. I don't see instructions in the install docs for TCP or Unix sockets, but I do see instructions for WebSockets: **https://docs.mattermost.com/install/installing-ubuntu-2004-LTS.html** so wondering if this request still applies. Thank you!
