### ISSUE TITLE
Can't set up the dev environment.

### ISSUE THREAD

**Issue by vineelya** [mattermost/docs#2478]
Up on trying to do make run-server, I get the error as follows. 
make run-server is causing issues.

11:18 PM

{"level":"info","ts":1548141418.725378,"caller":"utils/i18n.go:79","msg":"Loaded system translations for 'en' from '/Users/vineely/go/src/github.com/mattermost/mattermost-server/i18n/en.json'"}
{"level":"info","ts":1548141418.725854,"caller":"app/server_app_adapters.go:60","msg":"Server is initializing..."}
{"level":"debug","ts":1548141418.726004,"caller":"utils/html.go:31","msg":"Parsing server templates at /Users/vineely/go/src/github.com/mattermost/mattermost-server/templates"}
{"level":"info","ts":1548141418.7331588,"caller":"sqlstore/supplier.go:211","msg":"Pinging SQL master database"}
{"level":"error","ts":1548141418.7753248,"caller":"sqlstore/supplier.go:223","msg":"Failed to ping DB retrying in 10 seconds err=Error 1045: Access denied for user 'mmuser'@'localhost' (using password: YES)"}
{"level":"info","ts":1548141428.77999,"caller":"sqlstore/supplier.go:211","msg":"Pinging SQL master database"}

**Comment by amyblais** [comment]
Hi @vineelya,

This is the Docs repo, would you like to open a troubleshooting Issue on our Forums: https://forum.mattermost.org/?

Another option is to join our Community server and post this in the Developer channel for our devs to take a look: https://community.mattermost.com/core/channels/developers.

**Comment by hanzei** [comment]
See also https://community-daily.mattermost.com/core/pl/36rpn6xztbrz9q9sjbfdax1foo
