### ISSUE TITLE
How to start Mattermost automatically ?

### ISSUE THREAD

**Issue by pito2901** [mattermost/docs#249]
Hi everyone !

Can we start mattermost on startup ?

Now we have to pass `root` and run `./mattermost/bin/platform`

Can we add a mattermost service module to start automatically ?

Thanks.

**Comment by esethna** [comment]
Hi @pito2901, can I ask that you route your question to the [developer forum](https://forum.mattermost.org/c/dev)? Thanks!

**Comment by pito2901** [comment]
I won't.
