### ISSUE TITLE
ADFS SAML Instructions are incorrect

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#2615]
On step 7 of [this page](https://docs.mattermost.com/deployment/sso-saml-adfs.html) the ADFS server trust URL should be set to `https://<your-mattermost-url/login/sso/saml` and not `https://<your-idp-url>/adfs/services/trust`. The screenshot will need to be re-generated.

**Comment by justinegeffen** [comment]
I've taken a look through https://docs.mattermost.com/deployment/sso-saml-adfs.html and it looks like the corrections have been made. @icelander, if you're able to confirm that would be great. :)
