### ISSUE TITLE
NGINX proxy instructions incorrect for RHEL7

### ISSUE THREAD

**Issue by bweslowski** [mattermost/docs#2673]
The latest NGINX on RHEL 7 has the configuration file in a different location than specified in the installation instructions.  The following corrections should be made:

In section To configure NGINX as a proxy, #2 :
sudo touch /etc/nginx/sites-available/mattermost 
should be: sudo touch /etc/nginx/conf.d/mattermost

#3: Open the file /etc/nginx/sites-available/mattermost
should be: Open the file /etc/nginx/conf.d/mattermost

#4: sudo rm /etc/nginx/sites-enabled/default
should be: sudo rm /etc/nginx/conf.d/default

#5: sudo ln -s /etc/nginx/sites-available/mattermost /etc/nginx/sites-enabled/mattermost
should be: sudo ln -s /etc/nginx/conf.d/mattermost /etc/nginx/conf.d/default.conf

Hopefully this saves someone some time with their installation.

**Comment by amyblais** [comment]
Hi @bweslowski,

Thank you for noticing this. Would you be interested in making these edits to the documentation?

**Comment by amyblais** [comment]
Hi @bweslowski,

I opened a doc PR to add notes for RHEL 7: https://github.com/mattermost/docs/pull/2678.

Since the "To configure NGINX as a proxy" section is used for different docs (e.g. https://docs.mattermost.com/install/install-ubuntu-1804.html), do you know if the changes you suggested only apply to RHEL 7 or also for other environments?

**Comment by bweslowski** [comment]
I haven't tested this on other environments, only RHEL 7.  I agree that the
NGINX Proxy configuration might be different for other operating systems,
so I don't know if it's best to edit the main install document or leave
comments in the comments section.  I can edit the main document, or I can
re-write my changes to the instructions for RHEL7 as a comment.  I'll do
whichever you think is best.  Thank you.

-Brian Weslowski

**Comment by amyblais** [comment]
Thank you @bweslowski,

I opened a doc PR to add notes for RHEL 7: https://github.com/mattermost/docs/pull/2678. Let me know if this is what you were thinking and feel free to make any changes to the formatting on the notes that I added.

**Comment by bweslowski** [comment]
@amyblais, I think that's perfect.  Thank you.
