### ISSUE TITLE
Integration Guide Information Architecture

### ISSUE THREAD

**Issue by wiersgallak** [mattermost/docs#2712]
Improve the information architecture of the Integration Guide. Consider the following aspects
 - Order of information presented
 - Accessing information from one topic to the next in a sequenced flow
 - Improved information retrieval from search and browsing

**Comment by tapaswenipathak** [comment]
@wiersgallak There are lot of tickets where you have suggested improving the already present doc. Can you write what improvements you want fixed?

**Comment by justinegeffen** [comment]
This has been addressed in docs 2.0. 🎉 Closing! :)
