### ISSUE TITLE
Feature Documentation Template

### ISSUE THREAD

**Issue by wiersgallak** [mattermost/docs#2713]
Create a template to documenting product features improving consistency of presentation and retrieval of information of product features.  Consider the following types of information to be included (not exhaustive)
 - Enabling the feature
 - Use cases supported
 - A technical explanation of how the feature works
 - Troubleshooting issues

**Comment by cwarnermm** [comment]
This work is underway now as a cross-functional team effort between docs and PMs. Closing as this will be tracked elsewhere.
