### ISSUE TITLE
“How to” Documentation Template

### ISSUE THREAD

**Issue by wiersgallak** [mattermost/docs#2714]
Create a template for "How to" type documentation so that all instructions follow a similar format and order for consistency to our doc users.  

Consider (not an exhaustive list): 
 - Before getting started instructions
 - Troubleshooting instructions

**Comment by fataljoy** [comment]
Hello, I would like to help create this template)

**Comment by SanjeevYadavcr7** [comment]
Hi, i want to donate my work to create this template.

**Comment by cwarnermm** [comment]
@justinegeffen - I've assigned this to you since it's a docs initiative that we're looking to focus on later this year.
