### ISSUE TITLE
GitLab Mattermost Guide

### ISSUE THREAD

**Issue by wiersgallak** [mattermost/docs#2715]
Review and revision of information at https://docs.gitlab.com/omnibus/gitlab-mattermost/

Consider: 
 - Order of information presented
 - Accessing information from one topic to the next in a sequenced flow
 - Improved information retrieval from search and browsing

**Comment by cwarnermm** [comment]
The GitLab Omnibus product documentation is being reviewed as part of January 2022 Growth Spike initiatives. Closing.
