### ISSUE TITLE
Product Recipes Information Architecture

### ISSUE THREAD

**Issue by wiersgallak** [mattermost/docs#2719]
Propose how Product recipes should be organized and accessible through our doc and linked back to our blog.  This likely includes coordinating with our Marketing department and other internal stakeholders on a solution.   

When writing a recipe, please follow [this format](https://docs.mattermost.com/process/guest-article.html#mattermost-recipes)

**Comment by cwarnermm** [comment]
@wiersgallak - Is there value in keeping this docs request open?

**Comment by wiersgallak** [comment]
Closing issue as this is handled in other initiatives.
