### ISSUE TITLE
Product Recipe: How to use Python to talk to Mattermost

### ISSUE THREAD

**Issue by wiersgallak** [mattermost/docs#2721]
Make a simple incoming and outgoing webhook with Python. 

There are a couple of Python/Flash examples to use as a starting point at https://github.com/cvitter/mattermost-standup-slash

Category Suggestion: Developers

When writing a recipe, please follow [this format](https://docs.mattermost.com/process/guest-article.html#mattermost-recipes)

**Comment by cwarnermm** [comment]
@wiersgallak - Are docs for how to write webhooks in Python something that continues to be desired in Mattermost developer documentation?

**Comment by wiersgallak** [comment]
I think this can be closed for now.
