### ISSUE TITLE
Product Recipe: How to make a Mattermost Raspberry Pi appliance

### ISSUE THREAD

**Issue by wiersgallak** [mattermost/docs#2722]
How to set up Mattermost on a Raspberry Pi and make it discoverable on a network. (ie: Shared drive with an invite link?)

Category Suggestion: Enthusiasts

When writing a recipe, please follow [this format](https://docs.mattermost.com/process/guest-article.html#mattermost-recipes)

**Comment by justinegeffen** [comment]
I'll take this one.

**Comment by jasonblais** [comment]
Thanks @justinegeffen! Linking your recipe here for reference https://github.com/justinegeffen/mattermost_raspberrypi_recipe/blob/master/README.md

**Comment by esbeeb** [comment]
Based on Justine's excellent recipe, I wrote an up-to-date recipe (Ubuntu 64-bit 18.04.4 and 19.10), posted [here](https://www.raspberrypi.org/forums/viewtopic.php?f=36&t=269505).

@justinegeffen is free to use it as a basis to update her recipe again.

**Comment by justinegeffen** [comment]
Thanks, @esbeeb, that's really helpful and much appreciated! You obviously put a lot of work into this, and it looks great. I'll have a chance to look at it in the next two weeks or so. :)
