### ISSUE TITLE
Product Recipe: How to Set Up Mattermost with Azure ADFS

### ISSUE THREAD

**Issue by wiersgallak** [mattermost/docs#2723]
A comprehensive guide to setting up Mattermost with Azure ADFS providing authentication via SAML and LDAP group syncing

Suggested Category: Integrations

When writing a recipe, please follow [this format](https://docs.mattermost.com/process/guest-article.html#mattermost-recipes)

**Comment by cwarnermm** [comment]
@wiersgallak - Is a comprehensive guide to setting up Mattermost with Azure ADFS continue to be something valuable to add to the product documentation?

**Comment by wiersgallak** [comment]
Let's close this for now until we get more demand from customers/community.
