### ISSUE TITLE
Extended Support Release (ESR) upgrade guide

### ISSUE THREAD

**Issue by torgeirl** [mattermost/docs#2725]
A new ESR was announced last month (related discussions in issue #2665), but there doesn't seem to any dedicated migration guide for upgrading from 4.10 to 5.9. [The docs](https://docs.mattermost.com/administration/extended-support-release.html) does mention a clear path to upgrade will be provided:

> When an ESR is at the end of its life cycle, there will be announcements ahead of time to provide time for people to test, certify, and deploy a newer ESR version before support ends. **There will be a clear upgrade path provided between ESR versions**.

Reading the [Important Upgrade Notes](https://docs.mattermost.com/administration/important-upgrade-notes.html) I get the impression the only required change is renaming `bin/platform` -> `bin/mattermost` in the systemd file, but that was not my experience earlier today.

Specifically [LDAP stopped working after the upgrade](https://github.com/mattermost/mattermost-server/issues/10878), without providing an error message.

**Comment by amyblais** [comment]
Hi @torgeirl, letting you know that I've forwarded your feedback on these two doc issues for our product managers. As a next step they will be discussing with our devs about what we can document for upgrade paths and how to handle issues requiring a downgrade. Thank you for bringing these up,

**Comment by torgeirl** [comment]
@amyblais: thank you. Please let me know if you need any feedback on this.

**Comment by amyblais** [comment]
Closing via https://github.com/mattermost/docs/pull/2740.
