### ISSUE TITLE
Downgrade guide should be updated to include 5.9 (ESR)

### ISSUE THREAD

**Issue by torgeirl** [mattermost/docs#2726]
After a failed upgrade from 4.10 (last ESR) to 5.9 (current ESR) as mentioned in issue #2725, I tried downgrading using [the downgrade guide for 5.0](https://docs.mattermost.com/administration/downgrade.html) (I know it doesn't say 5.x, but there isn't any other guide available).

There are no errors when appling the the database reverts:

```
mattermost_prod=> UPDATE Teams SET SchemeId = NULL;
UPDATE 4
mattermost_prod=> UPDATE Channels SET SchemeId = NULL;
UPDATE 203
mattermost_prod=> UPDATE TeamMembers SET Roles = CONCAT(Roles, ' team_user'), SchemeUser = NULL where SchemeUser = true;
UPDATE 62
mattermost_prod=> UPDATE TeamMembers SET Roles = CONCAT(Roles, ' team_admin'), SchemeAdmin = NULL where SchemeAdmin = true;
UPDATE 8
mattermost_prod=> UPDATE ChannelMembers SET Roles = CONCAT(Roles, ' channel_user'), SchemeUser = NULL where SchemeUser = true;
UPDATE 712
mattermost_prod=> UPDATE ChannelMembers SET Roles = CONCAT(Roles, ' channel_admin'), SchemeAdmin = NULL where SchemeAdmin = true;
UPDATE 18
mattermost_prod=> UPDATE TeamMembers SET SchemeUser = NULL, SchemeAdmin = NULL;
UPDATE 66
mattermost_prod=> UPDATE ChannelMembers SET SchemeUser = NULL, SchemeAdmin = NULL;
UPDATE 712
mattermost_prod=> DELETE from Systems WHERE Name = 'migration_advanced_permissions_phase_2';
DELETE 1
```

Running the database with your backed up 4.10 binaries does not work however:
`Database schema version 5.9.0 is no longer supported. This Mattermost server supports automatic upgrades from schema version 3.0.0 through schema version 4.10.0. Downgrades are not supported. Please manually upgrade to at least version 3.0.0 before continuing`

I assume others will have to do the same upgrade, and if they too run into issues it would be good if the downgrade guide got extended to support 5.9 to 4.10 downgrades.

**Comment by amyblais** [comment]
Closing via https://github.com/mattermost/docs/pull/2740.

The ESR page has now been updated: https://docs.mattermost.com/administration/extended-support-release.html.
