### ISSUE TITLE
Print is truncated at 1 page

### ISSUE THREAD

**Issue by it33** [mattermost/docs#2733]
Repro

- Go to https://docs.mattermost.com/overview/product.html and print 

Expected

- Print the entire document 

Observed

- Print is only for first page, see screenshot: 

![image](https://user-images.githubusercontent.com/177788/58423259-7bd47580-8049-11e9-9c48-95f605f27690.png)

Possible fixes: 

- Propose opening this as a Help Wanted ticket

**Comment by toni517b** [comment]
This might be helpful info.  If I print the document in Firefox and then choose the "simplify page" option at the top, it prints all 3 pages.  Otherwise, only the first.

![MatterMost Print](https://user-images.githubusercontent.com/51376973/59050751-1b1f1700-8859-11e9-8144-398736b341eb.JPG)

**Comment by it33** [comment]
thanks @toni517b super helpful, hopefully we can figure out how to default to full page print...

**Comment by nizarmah** [comment]
@jespino Apparently this issue is still relevant today. I tried cherry picking @icelander's fix but the fix did not work.

Therefore, I added some print medias in the PR shown above.

Before:
