### ISSUE TITLE
Wrong SHA 256 for Mattermost Enterprise 5.12.0

### ISSUE THREAD

**Issue by Mayeu** [mattermost/docs#2812]
Hello 👋 

In the [Version Archive](https://docs.mattermost.com/administration/version-archive.html) documentation the SHA256 sum of the Mattermost Enterprise Edition v5.12.0 seems to be the wrong one.

In the documentation we can find:
* `https://releases.mattermost.com/5.12.0/mattermost-5.12.0-linux-amd64.tar.gz`
* SHA-256 Checksum: `df1615d9c3bfe25c8d9dbad201e5f938bd40daaf93701d3954638212fb54425d`

But after having downloaded this file multiple time (using various VPN and machine in different physical places with different internet access), I always get the following sum instead: `ce4b1b182e12ca499ba3e1a115f7635e0747430b741b3e10b4de54b8bcbfdfd7`

Can you confirm which is the good SHA sum to ensure a safe upgrade path?

**Comment by Mayeu** [comment]
Additional info, the GPG signature is the good one:
```
➜ keybase pgp verify -d mattermost-5.12.0-linux-amd64.tar.gz.sig -i mattermost-5.12.0-linux-amd64.tar.gz
▶ WARNING Bad subkey: openpgp: invalid data: Subkey wasn't signed; expected a 'binding' signature
▶ WARNING Bad subkey: openpgp: invalid data: Subkey wasn't signed; expected a 'binding' signature
Signature verified. Signed by mattermost 1 week ago (2019-06-15 11:22:06 +0200 CEST).
PGP Fingerprint: a1b31d46f0f3a10b02cf2d44f8f2c31744774b28.
```

**Comment by amyblais** [comment]
Thank you, this is fixed now in the docs.
