### ISSUE TITLE
mattermost export compliance - `exportFrom` should be in Epoch Milliseconds

### ISSUE THREAD

**Issue by sadohert** [mattermost/docs#2820]
Ran into this when using the compliance export from the command line.

In [the docs](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-export-actiance) we specifically say:

>  Unix timestamp (seconds since epoch, UTC) to export data from.

But this should be in milliseconds since Epoch.

**Comment by grundleborg** [comment]
Fix merged to docs.
