### ISSUE TITLE
MATTERMOST account is blocked

### ISSUE THREAD

**Issue by Roshchenya** [mattermost/docs#2831]
Hi! I received a message that my MatterMost account is BLOCKED due to a lot of attempts using an invalid password. I tried to reset it using my email, but I didn't receive any reset emails. 
Could you help me to resolve this situation?  

Kind regards, 
Ksenia

**Comment by amyblais** [comment]
Hi @Roshchenya, please check your spam / junk email folder in case those emails went there. Otherwise, you will need to contact your System Admin of your server to help reset your email.

**Comment by amyblais** [comment]
I'll close this issue for now because we haven't received feedback. Please re-open this issue if the problem persists.
