### ISSUE TITLE
Add another SAML troubleshooting topic

### ISSUE THREAD

**Issue by NOP64** [mattermost/docs#2858]
A customer had used Migratemost and may not have used the proper parameter since they had SAML. That parameter is `--authentication-data-field`.

As a result, the `AUTHDATA` column in the `USERS` table was empty. That was causing SAML to throw an error: "An account with that username already exists."

Please consider adding this as a possible cause for SAML issues in https://docs.mattermost.com/install/troubleshooting.html#common-saml-issues.

**Comment by amyblais** [comment]
Hi @NOP64, is the issue you're describing similar to this one: https://docs.mattermost.com/install/troubleshooting.html#an-account-with-that-username-already-exists-please-contact-your-administrator?

If not, I can help open a PR for this. If you're interested in opening a PR for this too, let us know.

**Comment by justinegeffen** [comment]
Hi @NOP64. I wanted to follow up on this and find out whether the link @amyblais provided addresses the issue? There have been some new SAML additions to the Troubleshooting guide which possibly address this issue. Thanks! :)

**Comment by NOP64** [comment]
We were able to work around the customer issue so I'll close this issue. My apologies for missing the link from @amyblais so long ago, too.
