### ISSUE TITLE
Broken Link on CLA page

### ISSUE THREAD

**Issue by janvt** [mattermost/docs#2871]
Not sure where to report this, can't find this text in any docs repos.

The link on https://www.mattermost.org/mattermost-contributor-agreement/ to the Karl Fogel book is broken (404) (https://producingoss.com/en/copyright-assignment.html)

**Comment by jasonblais** [comment]
Thanks for the report @janvt! We'll look at getting this fixed

**Comment by jasonblais** [comment]
We've removed the link for now 👍
