### ISSUE TITLE
Add instructions for indicating SLA level

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#2950]
[Add to this document](https://docs.mattermost.com/process/support.html#general-questions-for-any-issues)

**Comment by justinegeffen** [comment]
Following up on this to confirm whether you've had a chance to add this content, @icelander. Let me know if I can help with it. :)

**Comment by cwarnermm** [comment]
@svelle - Do we have SLA levels documented somewhere publicly as well as internally?

**Comment by cwarnermm** [comment]
Documented via https://mattermost.com/support-terms/
