### ISSUE TITLE
Request for Documentation: Test; Please Ignore

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#2967]
Mattermost user `joram` from https://community-release.mattermost.com has requested the following be documented:

```
This is a test message for documenting
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/duwboyguqj8y9mdpar1p8z47nw).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by jwilander** [comment]
Closing as this was a test
