### ISSUE TITLE
Request for Documentation: Something that should be documented

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#2971]
Mattermost user `paul.rothrock` from https://community.mattermost.com has requested the following be documented:

```
Nope, on experience with Suse, but it's not in our docs as a supported version.
```

See the original post [here](https://community.mattermost.com/_redirect/pl/p6gu5dhnfty39n1rbsabu8nior).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by icelander** [comment]
Closing as an example
