### ISSUE TITLE
Request for Documentation: HTTPS + WSS protocol usage for Posts

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#2973]
Mattermost user `ahmad.danial` from https://community.mattermost.com has requested the following be documented:

>Q: When a message is posted to channel, does it only use HTTPS / SSL protocol for encryption since WSS is mainly for facilitating real time data transfer between the client and server or are both protocols being used at the same time?
>
>A: Both HTTPS and WSS are used simultaneously. (SSL is typically enabled for both, unless only HTTP or WS is used)

See the original post [here](https://community.mattermost.com/_redirect/pl/agaqe88q6t865kdeuc6n6w8hzh).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
Comprehensive encryption product documentation is available at docs.mattermost.com. Closing.
