### ISSUE TITLE
Link to Openssl Site doesn´t exist anymore in generate-certificates/gencert.md

### ISSUE THREAD

**Issue by tuxmanu** [mattermost/docs#2985]
Link is broken
https://www.openssl.org/docs/apps/x509v3_config.html#Subject-Alternative-Name

**Comment by tuxmanu** [comment]
https://github.com/mattermost/docs/blob/master/source/scripts/generate-certificates/gencert.md

**Comment by amyblais** [comment]
@jasonblais After research, I wasn't able to find a link that could replace https://www.openssl.org/docs/apps/x509v3_config.html#Subject-Alternative-Name. Do we remove the link from https://github.com/mattermost/docs/blob/master/source/scripts/generate-certificates/gencert.md or do you know the correct link?

**Comment by jasonblais** [comment]
@amyblais Let's remove for now
