### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by ZouHongxue** [mattermost/docs#2993]
![image](https://user-images.githubusercontent.com/20573881/65015642-b2196600-d954-11e9-96e1-c6fa69b5d74e.png)
![image](https://user-images.githubusercontent.com/20573881/65015658-bb0a3780-d954-11e9-8621-81b43e103f9f.png)

I only can switch on two pages in my mac, in my browser can connect correctly.
I think this because I use my personal email, so how can I clean all the cache?
I uninstall & install is not work.

**Comment by amyblais** [comment]
@ZouHongxue On Mac, you can go to your top of the screen > View > Clear Cache and Reload. 

If that doesn't work, please help us with more information from this page for further troubleshooting: https://docs.mattermost.com/process/support.html#general-questions-for-any-issues.

**Comment by amyblais** [comment]
We haven't received feedback for a while so I'll close this issue for now. Please re-open this issue if the problem persists,
