### ISSUE TITLE
Request for Documentation: Poll results from 10/17/2019

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#2994]
Mattermost user `jelena.gilliam` from https://community-release.mattermost.com has requested the following be documented:

```

```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/phm1736hhidfidsmo7qs61piua).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by jgilliam17** [comment]
test

**Comment by jgilliam17** [comment]
> test

test
