### ISSUE TITLE
Request for Documentation: Usage of config.json file when server configuration has been migrated to the database

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#2996]
Mattermost user `jason.blais` from https://community-release.mattermost.com has requested the following be documented:

```
Question: What is the expected behavior for the config.json when you've migrated it to the database? Will the file be kept in sync with the DB? If the config file is deleted, should it get re-created with default values?

Answer: The file is obsolete and will be completely ignored by the server.
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/7gjm16xb6bfzpkiwobtshgi7ka).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
Comprehensive product documentation for migrating server configuration to the database is available on docs.mattermost.com. Closing.
