### ISSUE TITLE
Request for Documentation: Fix Set-ADFSRelyingPartyTrust description in SAML doc to refer to correct step

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#2997]
Mattermost user `sven.huester` from https://community.mattermost.com has requested the following be documented:

```
We also need to change that line because it refers to a step 7 that is actually a step 4
```

See the original post [here](https://community.mattermost.com/_redirect/pl/zju8fn54a3d5m8mtitsk99qwya).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by justinegeffen** [comment]
Hi @svelle! Could you share the link for this doc change - there are now two ADFS documents, one for 2012 and one for 2016, let me know if both are affected. Thanks! :)

**Comment by cwarnermm** [comment]
@svelle - Can you please confirm whether the requested product documentation updates are still required?
