### ISSUE TITLE
clarify setcap step in upgrade docs

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#3004]
right now it says that the setcap step only needs to be run when using TLS.

>If you have TLS set up on your Mattermost server,

But it's also needed when using port 80 (which some companies use for MM instances running only in intranet)

**Comment by justinegeffen** [comment]
Thanks, @svelle. Could you confirm whether these are the upgrade docs in question: https://docs.mattermost.com/guides/administrator.html#upgrade-mattermost and, if so, which section needs to be updated? :)

**Comment by justinegeffen** [comment]
If you're interested in taking on this documentation request, let us know by commenting on the issue. The submitter of this issue may have additional links and content available. 

- If you're a new contributor take a look through the [Technical Writing Handbook](https://handbook.mattermost.com/operations/research-and-development/product/product-technical-writing-team-handbook#processes) to learn more about our processes. 

- For technical advice or questions, please join our [Developers community channel.](https://community.mattermost.com/core/channels/developers).

- For stylistic, formatting, or other questions join the [Documentation community channel](https://community.mattermost.com/core/channels/documentation).

We look forward to your contribution!

**Comment by svelle** [comment]
@justinegeffen looks like that additional info got added to the upgrade docs. I could've sworn that wasn't the case before. I think we can close this imo.

**Comment by justinegeffen** [comment]
Thanks, @svelle! That's great news. Closing this. :)
