### ISSUE TITLE
Request for Documentation: Add note to upgrade docs for users migrating from 4.x to 5.x versions

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3007]
Mattermost user `sven.huester` from https://community.mattermost.com has requested the following be documented:

```
we should add some note in the upgrade docs for users upgrading from 4.x releases to 5.x that they'll probably need to upgrade their service files to use the "new" binary (/opt/mattermost/bin/mattermost) and workdirs (/opt/mattermost). Seems like some users are confused when upgrading from old versions and there's only one old article that mentions this (as far as I could tell)
```

See the original post [here](https://community.mattermost.com/_redirect/pl/yxt4jshhcbfndj6z8jtq3b8bbo).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by justinegeffen** [comment]
Hi @svelle. I've taken a look at the documentation here: https://docs.mattermost.com/administration/upgrade.html and agree that there is no explicit mention of this. Could you let me know which document you saw that note in, so I can align them? 

I also noted that this is mentioned in the upgrade notes: https://docs.mattermost.com/administration/important-upgrade-notes.html
"platform binary is renamed to mattermost for a clearer install and upgrade experience. You should point your systemd service file at the new mattermost binary. All command line tools, including the bulk loading tool and developer tools, are also be renamed from platform to mattermost." 

If that's the information that's missing, I can add a note in the upgrade documentation indicating that the ``systemd`` service file needs to be updated. 

Could you confirm whether this is done pre or post upgrade and whether the bolded fields below below are the ones that would need to be changed from /bin/platform to /opt/mattermost?

[Service]
Type=notify
**ExecStart=**
TimeoutStartSec=3600
Restart=always
RestartSec=10
**WorkingDirectory=**
User=mattermost
Group=mattermost
LimitNOFILE=49152

Thanks!

**Comment by svelle** [comment]
Hey @justinegeffen sorry for taking so long with this. I tried finding the blog post I mentioned here but for some reason I simply can't find it. 

I'll see if I can remember the differences and note them down here. Later today.

**Comment by justinegeffen** [comment]
hey @svelle, just following up on this to find out whether you were able to find the blog content. :) Otherwise maybe @amyblais might be able to help?

**Comment by svelle** [comment]
Hi Justine, sorry again.
Github notifications go under so easily.

I didn't find it. 

Working directory would need to be set to /opt/mattermost
and ExecStart to /opt/mattermost/bin/mattermost

I think in new configurations this shouldn't be an issue but as we apparently communicated this differently in the past it might be worth putting up an article for users migrating from earlier versions as I'm sure there are still some out there.

**Comment by justinegeffen** [comment]
Thanks, @svelle! Do you have the bandwidth to make this update in the docs? :)

**Comment by svelle** [comment]
> Thanks, @svelle! Do you have the bandwidth to make this update in the docs? :)

Not till the 27th unfortunately. But after that I can do it no problem.

**Comment by justinegeffen** [comment]
That works for me! :)

**Comment by justinegeffen** [comment]
Hey @svelle, following up on this to find out whether I can help with this in any way. :)

**Comment by svelle** [comment]
Hey @justinegeffen I knew I forgot something.

I've opened a PR for this and assigned you as reviewer ;)
