### ISSUE TITLE
PDF Export of Documentation

### ISSUE THREAD

**Issue by Prodian0013** [mattermost/docs#3039]
Unable to find a link to download the documentation in pdf format.

**Comment by amyblais** [comment]
@Prodian0013 Thank you for the report, I'll close this as a duplicate of an existing Help Wanted issue https://github.com/mattermost/docs/issues/355.

**Comment by Prodian0013** [comment]
@amyblais i was able to get a pdf i just forked the repo and used readthedocs site to generate it.

https://buildmedia.readthedocs.org/media/pdf/mattermost-docs/latest/mattermost-docs.pdf
