### ISSUE TITLE
session expires suddenly

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/docs#3042]
- client is running
- communicated an hour ago or so via mattermost
- suddenly a popup appears "your session has expired"

???
given that the cumbersome client not even remembers credentials, this constantly breaks my workflow

**Comment by amyblais** [comment]
@2019-05-10 Did you mean to open these issues in the desktop app repo https://github.com/mattermost/desktop/issues?

Can you help with more details about your environment from here https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

**Comment by 2019-05-10** [comment]
a) didn't know there were separate repos
b) no idea whether this is caused by the client or server
c) don't have access to the server

**Comment by amyblais** [comment]
Thank you for transferring into the desktop repo, I responded to your issue reports,
