### ISSUE TITLE
Kubernetes installation doc suggestions

### ISSUE THREAD

**Issue by NOP64** [mattermost/docs#3057]
Most of the following comes from someone very new to Kubernetes. I think it's in our interest to err on the side of being overly explicit since it's a relatively new aspect to Mattermost.

* Is it possible to document the Kubernetes platform & version being used/tested as well? The docs simply say 1.12 and higher but I had issues with it not working on 1.16.
* When editing the installation manifest file, can you expand on what happens when you, for example, select `5000users` vs `1000users`? Does it configure more pods?
* For `spec.database.storageSize` and `spec.minio.storageSize` there is a description about needing volumes.
  * Can you expand on this a little? Perhaps say that you need to have a PV created or what happens if the `DefaultStorageClass` admission plugin is active.
  * I noticed the YAML files don't have `storageClassName` values which lead me down a path.
  * For someone new to Kubernetes, even just having tips or pointers to other places make getting it running much faster.
* What's the possibility of documenting a few basic Kubernetes things (i.e. start, stop, redeploy, update) for new people? I'm following instructions and loosely know why.
  * For example, I have no idea how to stop or un-deploy. The operator kept re-spawning components which, I suppose, part of its' purpose.
* Since there is an operator, what's going to happen to the Helm Chart and when would someone want to use one over the other? Can that be documented as well?

I don't think we want this to be a Kubernetes 101 course but a little context and helpful suggestions may go a long way.

**Comment by justinegeffen** [comment]
Thanks, @NOP64. These are very good points and I agree with you. 

Could you tell me a bit more about the issue with ``storageClassName`` and some of the pointers you think may be helpful? It's definitely far better to provide some context to the process so that users don't feel like they're just following instructions. 

I'm working on your other questions and will revert shortly.

**Comment by NOP64** [comment]
I'm going to try and make sense of what I learned but I'm equally happy to talk more with others to nail it down for new users.

------------------
There is no explicit `storageClassName` set in the MySQL operator YAML file. I think that means it makes a `PersistentVolumeClaim` with no storage class. That's reasonable. I had to learn more about PV, PVC, storage classes, etc. to understand the simplicity of that original statement. [Hopefully, it's accurate.]

What I had to do was explicitly setup a `PersistentVolume` to have `storageClassName: ""` in order for it to work. Perhaps I could have modified the MySQL operator YAML to use an existing storage class? Is that a good alternative to document? I'm not sure. I also don't know if it's typical for Kubernetes systems to have PVs without storage class names. We should not specify an arbitrary storage class in the YAML. 

I read the following to help me understand more.

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class
>A PV can have a class, which is specified by setting the storageClassName attribute to the name of a StorageClass. A PV of a particular class can only be bound to PVCs requesting that class. A PV with no storageClassName has no class and can only be bound to PVCs that request no particular class.

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
>PVCs don’t necessarily have to request a class. A PVC with its `storageClassName` set equal to `""` is always interpreted to be requesting a PV with no class, so it can only be bound to PVs with no class (no annotation or one set equal to `""`). A PVC with no `storageClassName` is not quite the same and is treated differently by the cluster, depending on whether the `DefaultStorageClass` admission plugin is turned on.

The MySQL operator YAML needs storage with the `ReadWriteOnce` access mode. That's fine but maybe describe how that affects the database cluster operation? Does it mean any other DB nodes in a cluster can read the data or are they just sitting around waiting for the first node to fail?

**Comment by justinegeffen** [comment]
Thanks for raising this, @NOP64. I wanted to follow up and include @jwilander in this conversation as he'll be able to answer your questions regarding db behavior. 

In terms of the information around PVs, I'm working on the documentation to incorporate that.

**Comment by justinegeffen** [comment]
Hi @NOP64. Update on this: The docs have been reviewed and some changes made. WRT your question about the Helm Chart, it is still available and a note has been added in the documentation to indicate that as well as the differences between the Helm Chart and MM Operator. 

I'd like to get your feedback on this if you have the bandwidth to take a look at the updates and confirm whether they address your points. :)

**Comment by justinegeffen** [comment]
Hi @NOP64. Following up on this to find out whether you have any feedback on the changes, and whether they're aligned with your questions. :)

**Comment by cwarnermm** [comment]
Closing.
