### ISSUE TITLE
Request for Documentation: Add Instructions on adding the first or additional MFA Method to a OneLogin Account

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3075]
Mattermost user `dschalla` from https://community.mattermost.com has requested the following be documented:

```
When adding the MFA device on the OneLogin Website, can you select above the barcode at "Choose Vendor: OneLogin Protect" instead "Google Authenticator"? Then scanning the barcode should work.

OneLogin Protect is a in-house app of OneLogin that is entirely standalone. It can be used as well, but needs to be downloaded from the AppStore separately.
```

See the original post [here](https://community.mattermost.com/_redirect/pl/nmc4hqk4bibgpfhqocph3ennah).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
@DSchalla - Are you open to creating a PR with these updates?

**Comment by DSchalla** [comment]
@cwarnermm OneLogin is owned by IT (@danielsischy) nowadays. We have some information here https://handbook.mattermost.com/company/how-to-guides-for-staff/how-to-change-mobile-device#onelogin-two-factor-authentication on the subject, but I dont think as detailed.

@danielsischy Let me know if I can help somehow!
