### ISSUE TITLE
Images do not render at ../formatting-text.html#in-line-images

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#3081]
See below
![image](https://user-images.githubusercontent.com/13119842/67011505-c1a7de00-f0bd-11e9-97d8-bb56e8d2c17a.png)

https://docs.mattermost.com/help/messaging/formatting-text.html#in-line-images

**Comment by anayroy0007** [comment]
I am working on this.

**Comment by jasonblais** [comment]
Thanks @anayroy0007! :tada:

**Comment by anayroy0007** [comment]
please merge the pull request.

**Comment by justinegeffen** [comment]
Fixed in https://github.com/mattermost/docs/pull/3619. :)
