### ISSUE TITLE
Request for Documentaiton Update: Migrating from Slack

### ISSUE THREAD

**Issue by CDRO** [mattermost/docs#3092]
The [migration guide](https://docs.mattermost.com/administration/migrating.html#migrating-from-slack) suggests to spin up the platform docker image which doesn't really do anything (at least on linux). It seems that `docker-compose` is the way to go.

Please clarify or update the documentation accordingly.

Best Regards

**Comment by justinegeffen** [comment]
Hi @CDRO. Thanks for raising this issue. Would you mind confirming whether you clicked through to https://docs.mattermost.com/install/docker-local-machine.html and used the one-line install command? 

I have also requested confirmation on the command as there is a discrepancy between that and the one listed in the install document.

**Comment by CDRO** [comment]
Hi @justinegeffen. I can confirm that the way described on your link effectively starts the container (and rather quickly at that), but I did not click this one through at first, since the migration suggested first starting the other one.

**Comment by justinegeffen** [comment]
Thanks for confirming! I'll update the migration page.
