### ISSUE TITLE
Request for Documentation: Add FAQ for localization docs

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3100]
Mattermost user `jason.blais` from https://community-release.mattermost.com has requested the following be documented:

```
QUESTION

Should text inside brackets be translated in these cases?

1) Size Limit Exceeded. Try checking your **[max page size]**(https://docs.mattermost.com/deployment/sso-ldap.html#i-see-the-log-error-ldap-result-code-4-size-limit-exceeded)
2) Unable to upload file **{{.Filename}}**. Rejected by plugin: **{{.Reason}}**
3) Invalid **RemoteImageProxyOptions** for atmos/camo. Must be set to your shared key.

ANSWER

1 - Square brackets []: Yes, that's link text
2 - Curly brackets {}: never
3 - Yes, must match in all translations if not an external definition like ad fields
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/oyco4cztmtggzpzik4we4qzrww).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
Shared with Tom DeMoor to share more broadly with Mattermost's Translation Community. Closing.
