### ISSUE TITLE
Enhance documentation for TLS Overwrite Ciphers 

### ISSUE THREAD

**Issue by DSchalla** [mattermost/docs#3102]
Our current documentation for the `TLSOverwriteCiphers` should contain some examples how to use it and make a mention that it does not affect TLS 1.3

**Comment by justinegeffen** [comment]
Hi @DSchalla. These are the two docs that I could find that potentially matched: https://docs.mattermost.com/administration/prev-config-settings.html?highlight=ciphers#tls-cipher-overwrites and https://docs.mattermost.com/administration/config-settings.html?highlight=ciphers#tls-cipher-overwrites. Let me know if I missed any and if you need any help with the updates. :)

**Comment by DSchalla** [comment]
Thanks for the reminder! I think I can make the docs a bit more clear and show one example of limiting it, just for clarity. I'll see if I can find time this week for it.

**Comment by cwarnermm** [comment]
@DSchalla - Is this documentation request still valid, and are you open to creating a PR with the changes?

**Comment by cwarnermm** [comment]
Replaced by: https://github.com/mattermost/docs/issues/6593
