### ISSUE TITLE
Windows App showing white screen

### ISSUE THREAD

**Issue by boschkundendienst** [mattermost/docs#3119]
Hi,

I am running the Mattermost Desktop Client for Windows `Version 4.3.1` and have it setup to autostart automatically. It starts up well, the top bar shows the last communication, the menu items `File`, `Edit`, `View`, `History`, `Window` and `Help` are there and usable to the rest of the application only shows a white screen like this:

![2019-10-31_10h03_41](https://user-images.githubusercontent.com/2026234/67933536-461e5480-fbc6-11e9-9a91-901348fafe7f.png)

When opening `View -> Developer Tools for Application Wrapper` (Ctrl+Shift+I), the developer tools show on the right hand side and immediately on the left the usual content arrives. I close the Developer toolbar and everything is fine. This happens only when my computer is started up after login (where many other things start also).

So it seems that all the other startups that are going on somehow prevent this first, initial screen refresh within the application.

I connect to a self-hosted Mattermost server with GitLab authentication where my authentication is still valid when I startup the client.

Any ideas?

Kind regards

Peter

**Comment by JtheBAB** [comment]
@boschkundendienst 

Wrong Repo.

Here is the desktop repo.
https://github.com/mattermost/desktop/issues/new/choose

Best regards

**Comment by boschkundendienst** [comment]
Thanks for pointing me in the right direction. I openend the case there.
