### ISSUE TITLE
Clarifying is needed for CJK search explanation in Administarator's Guide.

### ISSUE THREAD

**Issue by focusonmx** [mattermost/docs#3125]
https://github.com/mattermost/docs/blob/master/source/install/i18n.rst

In this part of Installing Mattermost Guide Line, there are explanations about special configuration for  Chinese,Japanese and Korean Search .

There is no explanation of Korean but only about Chines and Japanese. I think this because  there is no problem for Korean Search. But there is no mention that special configuration of Korean isn't required.

If special configuration is also required to Korean Search, WHY are there no explanations about Korean search ? 
 
I think some modifications are needed to this part of document. And I want to commit by changing code for document.

**Comment by justinegeffen** [comment]
Hi @focusonmx. Thanks for raising this. You're welcome to make the edits to the documentation and you can do so directly on the GitHub page. Let me know if you run into any issues or have any questions.

**Comment by justinegeffen** [comment]
Hi @focusonmx, I wanted to follow up on this and find out if I can help with anything on this issue. :)

**Comment by focusonmx** [comment]
Hi @justinegeffen, Thank you for your reply :) I wonder that is it right that Korean doesn't need any special configuration  unlike Chinese and Japanese?

**Comment by justinegeffen** [comment]
That's a very good question. I can't answer that conclusively and I'm wondering if this channel might be able to provide more info: https://community.mattermost.com/core/channels/i18n-korean.

**Comment by focusonmx** [comment]
I'm new to open source and have joined hoping to learn and hopefully contribute. So can I ask you what is your role in Mattermost?  Because I want to ask you properly about this issue. Do you  manage the issues of docs and commit them to main branch?

**Comment by justinegeffen** [comment]
Absolutely - I'm a Technical Product Writer and I write feature documentation for the Administration Guide. I also work on issues that are raised, but there is also a big community component which means that everyone is welcome to work on any of the issues in the queue. 

One of the best things about Open Source is that anyone can contribute and, when you do, the changes/suggestions you make are open to the wider community for their input. This page has some guidance around how to get started with documentation contributions: https://github.com/mattermost/docs. In terms of how the changes are published, there is a workflow we follow with approval steps before anything is merged into the master branch. 

This page also has some information about the various ways you can contribute to Mattermost: https://mattermost.com/contribute/. In this case, the "Localization Process" is the section you'd want to read. 

As a first step, we always recommend joining our community server as there are a large number of channels, each dealing with different aspects of Mattermost. The channel I linked you to is the Localization channel for the Korean translation of the documentation. 

Let me know if you'd like any more information or anything is unclear. :)

**Comment by focusonmx** [comment]
@justinegeffen Thank you for your help, I communicated with Localization channel members and [this issue](https://github.com/mattermost/docs/issues/3159) is opend. So this excisting issue can be closed.

**Comment by justinegeffen** [comment]
It's a pleasure, and I am glad I could help. :)
