### ISSUE TITLE
Request for Documentation: FaceID for EMM devices

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3140]
Mattermost user `ahmad.danial` from https://community.mattermost.com has requested the following be documented:

```
I won’t be able to help you out until next week. Perhaps Linda or Daniel can help you enroll your iOS device on the Airwatch EMM test instance. You don’t need a specific MM server for this.

The way it works: you open the app from cold start and it should requiere your FaceID to be able to open the app.

Case 2: the app is sitting in the background for a minimum of 5 minutes, when you bring the app to the foreground it will requiere your FaceID, if it has been less than 5 minutes no FaceID auth is needed.
```

See the original post [here](https://community.mattermost.com/_redirect/pl/k1mjj8dgytdkmq8xsjtm3sstee).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
@ahmaddanialmohd - Can you please confirm whether this request for product documentation continues to be a valid request? If so, would you be open to creating a PR with the changes?
