### ISSUE TITLE
Request for Documentation: If all the posts from a given channel are purged by a retention job, does the channel still remain in place?

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3145]
Mattermost user `george` from https://community-daily.mattermost.com has requested the following be documented:

```
Yes, the channel remains in place. It just won't have any messages in it anymore.
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/xra3quxcppnbbqptrehxnz6k1h).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
Closing.
