### ISSUE TITLE
Mobile Usability issues detected on https://docs.mattermost.com/

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#3147]
Google Search Console has identified that docs.mattermost.com site is affected by 3 Mobile Usability issues:

- Text too small to read
- Clickable elements too close together
- Content wider than screen

**Comment by justinegeffen** [comment]
Thanks, @jasonblais. Is there a report available to look at with more details so we can open a Jira ticket or PR for it and have QA take a look?

**Comment by jasonblais** [comment]
@justinegeffen I forwarded you the report via email

**Comment by justinegeffen** [comment]
Thanks, I've received it and took a look at the search console. The console isn't reporting those issues at the moment - wondering if they were possibly resolved in one of the recent releases as part of unrelated work. No other errors are displaying so I'll close this issue. :)
