### ISSUE TITLE
Request for Documentation: Update windows installer documentation for 4.3.X windows installs

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3148]
Mattermost user `guillermo.vaya` from https://community-release.mattermost.com has requested the following be documented:

```
after going a bit crazy with this, I might have found a solution: if it's a new install, the  `%APPDATA%\Mattermost` doesn't exist yet, and it fails to be created as it can't write the text into a non-existant folder.
having the next line:
```bash
mkdir %APPDATA%\Mattermost
```
should solve the problem.

I've tested this approach with the MSI, which uses /quiet for that to run silently
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/ymog3brg7fyxxr977hq8wdrbpe).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by bvineyar** [comment]
I will take this one.

**Comment by justinegeffen** [comment]
Hi @bvineyar! Thanks for taking this on. I wanted to follow up and find out if you have any questions or concerns that I can assist with. :)

**Comment by vilsi12** [comment]
Can you assign

**Comment by cwarnermm** [comment]
@Willyfrog - Can you confirm whether this continues to be information that would be beneficial to include in the product documentation, please?

**Comment by devinbinnie** [comment]
Agreed, the MSI installer should be working without this.

**Comment by cwarnermm** [comment]
Thank you both! Closing.
