### ISSUE TITLE
Request for Documentation: How do I delete a webhook message attachment after someone clicks on an interactive button?

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3149]
Mattermost user `jason.blais` from https://community-release.mattermost.com has requested the following be documented:

```
Try this

```json
{
  "update": {
    "message": "TEXT MESSAGE",
    "props":  {
      "attachments": []
    }
  }
}
```
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/ubk7egn8k3r68rzugq31fjzkkc).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by hanzei** [comment]
@jasonblais Is https://docs.mattermost.com/developer/interactive-messages.html#how-do-i-manage-properties-of-an-interactive-message not enough?

**Comment by jasonblais** [comment]
It wasn't immediately obvious to me, but I'm not a developer so may just have a gap in technical understanding. Also, the community member part of the original discussion that generated that FAQ had a question after the FAQ was created.

0/5 though, if not needed, we can close this issue

**Comment by cwarnermm** [comment]
Closing.
