### ISSUE TITLE
Update documentation about Incomming Webhooks

### ISSUE THREAD

**Issue by craph** [mattermost/docs#3157]
I open this issue related to [this one](https://github.com/mattermost/mattermost-server/issues/13079)

I was unable to see the Add Incoming Webhook in Mattermost.

Please could you update the documentation to avoid misunderstanding here : https://docs.mattermost.com/developer/webhooks-incoming.html#simple-incoming-webhook

Please could you add to switch back to the Team view after enabling the Incomming / Outgoing Webhooks because the :

> Go to "Main menu" 

is not to clear I think

Thank you very much.

Best regards,

**Comment by justinegeffen** [comment]
Hi, @craph! Would you be open to reviewing [this updated content](https://docs.mattermost.com/developer/webhooks-incoming.html#simple-incoming-webhook) and confirming whether it addresses your request? :)
