### ISSUE TITLE
Request for Documentation: Update push proxy documentation to use systemd service files instead of upstart

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3162]
Mattermost user `sven.huester` from https://community.mattermost.com has requested the following be documented:

```
Right now we're providing an upstart service file, this should probably be moved to use systemd instead as most major distros moved to using this as the default service manager
```

See the original post [here](https://community.mattermost.com/_redirect/pl/mrfpbuaxo3bydfdqwck6brs3wa).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
@svelle - Would you or a member of your team be open to drafting a PR with this documentation update?

**Comment by svelle** [comment]
already done per: https://github.com/mattermost/mattermost-developer-documentation/pull/514
