### ISSUE TITLE
Add info on formatting for DB connection strings

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#3184]
DB connection strings need to be formatted with [URL escaping](https://www.w3schools.com/tags/ref_urlencode.asp) not 'regular' escaping.

So for example a `,` would be escaped using `%2C` instead of `\u002C` or `\x2C`. 
This should be noted somewhere in the documentation because the default connection strings we provide break for example when trying to add those to the DataReplicationSource setting through an environment variable as the `,` will be interpreted as the delimiter instead of part of the connection string.

**Comment by justinegeffen** [comment]
Thanks @svelle! Do you have an idea of where the updates need to be made (e.g., which pages, which doc set etc)? It'd be good to know the scope of the issue so we can plan accordingly. :)

**Comment by svelle** [comment]
@justinegeffen I've opened a PR for this, maybe you can have a quick look :)
