### ISSUE TITLE
Docs with `md` file formatting show the file name for images below or beside the image

### ISSUE THREAD

**Issue by amyblais** [mattermost/docs#3205]
This is an issue with any file with ``md`` file format.

Example docs with this issue:
https://docs.mattermost.com/deployment/sso-google.html
https://docs.mattermost.com/deployment/sso-office.html

Found while reviewing: https://github.com/mattermost/docs/pull/2622

<img width="544" alt="file-name" src="https://user-images.githubusercontent.com/29708087/70067038-afc1c200-15bb-11ea-9a9c-c9c5eab789e9.png">

**Comment by trishitapingolia** [comment]
What changes do you want? Can you explain !
@amyblais image names are below the images, where else do you want them to be or should they be removed?

**Comment by amyblais** [comment]
@trishitapingolia I was thinking the image names could be removed if there is a way to do it.

**Comment by trishitapingolia** [comment]
@amyblais can you review my pr !
So that I can do it for other files too.
