### ISSUE TITLE
Request for Documentation: Document silent install of MSI

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3220]
Mattermost user `eric.sethna` from https://community.mattermost.com has requested the following be documented:

```
Permalink: https://community.mattermost.com/core/pl/m6yh3rifnpb8xm37ajatnsye4r

Solution: I just installed 4.3.1 MSI silent without any problems with this command:

msiexec /i mattermost-desktop-v4.3.1-x64.msi /qn

Related ticket: https://mattermost.atlassian.net/browse/MM-19888
```

See the original post [here](https://community.mattermost.com/_redirect/pl/ueoctp9eb3d75cazsdto636waw).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by hack3r-0m** [comment]
I want to work on this issue, can anyone guide me regarding what all things to include? and it must be placed in docs/source/install/?

**Comment by justinegeffen** [comment]
Hi @hack3r-0m! Thank you, that would be excellent. You can find the contribution guidelines [here](https://github.com/mattermost/docs). 

I believe [this](https://docs.mattermost.com/install/desktop-msi-gpo.html) is the documentation that needs to be updated, but @esethna can confirm that. :)

**Comment by esethna** [comment]
Yes, we should add another section to that doc after the "Installation Guide" section that is the "Silent Installation Guide"

**Comment by haardikdharma10** [comment]
Hey @esethna, I'd like to work on this. Also, just to be clear here, we need to create a new section as you mentioned above and add the command to install 4.3.1 MSI silent. Can you please confirm so I'll go ahead and open up a PR?

**Comment by esethna** [comment]
@haardikdharma10 yes makes sense! However please note that our lastest version is now 4.6.1
