### ISSUE TITLE
Setting siteUrl in config.json for Ubuntu 18.04

### ISSUE THREAD

**Issue by src-r-r** [mattermost/docs#3224]
Regarding the instructions here: https://docs.mattermost.com/install/install-ubuntu-1804.html#installing-mattermost-server

A minor step is missed to set the siteUrl option (about step 7/8). Otherwise the server will not start. A warning is produced regarding this option, but it would be better to include this in the documentation.

**Comment by svelle** [comment]
Closing per this PR https://github.com/mattermost/docs/pull/3227
