### ISSUE TITLE
Improve troubleshooting/docs for gfycat integration

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#3225]
Currently we have zero troubleshooting for the gfycat integration.
99% of cases the gif preview is not working because admins don't know that the images from gfycat in chat (unlike the preview in the emoji picker) is being loaded through the Mattermost server.

We should add a section that has the following info included:

### What to do if gifs are not loading even though they show up in the emoji picker

1. check if the server has access to the gfycat servers if it's behind a proxy or firewall blocking outgoing connections.
2. check if the server reaches the link metadata timeout (see system console -> experimental -> link metadata timeout)

**Comment by justinegeffen** [comment]
Hey, @svelle! Would you be open to updating the docs to reflect this new content? It seems like it'd fit well into the [Configuration > Integrations section of the Troubleshooting guide](https://docs.mattermost.com/install/troubleshooting.html#configuration-issues)?

**Comment by svelle** [comment]
Yeah sounds like a good idea. I'll add it later today. Thanks for looking that up :)

**Comment by justinegeffen** [comment]
Thank you for helping out, much appreciated!
