### ISSUE TITLE
Add note to config in database docs about CLI usage

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#3236]
Just got off a call with a customer that had database connection errors when running the CLI commands after they ingested the config into the database as described here: https://github.com/mattermost/docs/blob/master/source/administration/config-in-database.rst

They are supplying the Mattermost service with the envvars using a systemd envvar file but the CLI of course does not have access to this. We should add a note to the troubleshooting steps or anywhere else in this document to make this clear. In their case the server was trying to connect to the dockerhost because it was reading the config.json when running CLI commands as there was no `--config` parameter appended to the command nor was the `MM_CONFIG` variable set.

**Comment by jKostet** [comment]
Hi, I have a similar issue.

I'm trying to use mattermost CLI on gitlab omnibus installation. The CLI commands require --config, but the mattermost's config.json does not have the same external database options set in gitlab.rb, and tries to connect to dockerhost instead.

Is there a way to use the CLI in this situation?
