### ISSUE TITLE
Request for Documentation: What is our recommended max latency between app servers and DB and read replicas across DC's in a clustered set up?

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3248]
Mattermost user `jason.blais` from https://community-release.mattermost.com has requested the following be documented:

```
The answer given to us was 20ms avg with spikes to 100ms. We need to provide the guidance  on how to configure the system for such a scenario.
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/34dpoqk6aif6df64zsj65phnch).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
@sadohert - Adding you for visibility on this one given the various performance improvement initiatives in flight that will require product documentation updates.
