### ISSUE TITLE
We're having trouble connecting to Mattermost. If refreshing this page (Ctrl+R or Command+R) does not work, please verify that your computer is connected to the internet.

### ISSUE THREAD

**Issue by neethumoltp** [mattermost/docs#3258]
I have followed below instructions to install mattermost. While accessing it with http://localhost:8065 seeing below error.
We're having trouble connecting to Mattermost. If refreshing this page (Ctrl+R or Command+R) does not work, please verify that your computer is connected to the internet.

**Comment by amyblais** [comment]
Hi @neethumoltp,

1. What Mattermost server version are you on? What OS / device / browser are you using?
2. Can you help check if this troubleshooting guide might help https://docs.mattermost.com/install/troubleshooting.html#cannot-connect-to-the-server-please-check-your-server-url-and-internet-connection?
3. Would you be open to check if this previous troubleshooting thread might help https://forum.mattermost.org/t/solved-server-started-but-app-not-connecting-and-no-logs/6425?

**Comment by amyblais** [comment]
I'll close this for now as we haven't received any feedback on this, but I hope that you will re-open this issue if the problem hasn't been solved yet.
