### ISSUE TITLE
Style Guide: Standardize numbers under ten from digits to spelled out

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/docs#3269]
Proposal to review documentation to bring it in line with our style guide regarding numbers - numbers under ten are written out in full, numbers over ten are presented as digits (https://docs.mattermost.com/process/documentation-guidelines.html#numbers). 

Suggest working with @AninditaBasu on this and folding it into the stopWords Hackthon project and including it in phase one application.

**Comment by justinegeffen** [comment]
See also: https://github.com/mattermost/mattermost-developer-documentation/pull/442.

**Comment by spielers** [comment]
I would like to work on this issue: looking like beginner-friendly issue

**Comment by justinegeffen** [comment]
Hi @spielers! Thank you so much! It is very beginner-friendly in terms of what needs to be done. However, it is quite an extensive body of work so I recommend working section by section, starting here: https://docs.mattermost.com/guides/administrator.html#getting-started. That said, there are likely other ways of approaching the updates so please don't be constrained by that suggestion. :) 

One guideline is to try keep each PR relatively small (no more than 10 files) so it's easy to review and merge. :)

**Comment by spielers** [comment]
Definitely, I wipo try to keep it as simple as possible
Thanks

**Comment by justinegeffen** [comment]
Awesome, thank you! Please feel free to post in the [Documentation channel](https://community.mattermost.com/core/channels/documentation) if you'd like to chat further or have any questions. :)

**Comment by ModdedGamers** [comment]
I will also be working on this.

**Comment by justinegeffen** [comment]
Thanks, @ModdedGamers! That's great news.

I wanted to clarify which documentation needs to be updated, as the original information isn't very specific:

- https://docs.mattermost.com/guides/user.html
- https://docs.mattermost.com/guides/administrator.html
- https://docs.mattermost.com/guides/integration.html
- https://docs.mattermost.com/guides/education.html

Do you have any plans as to how the work will be split so that there aren't merge conflicts and to minimize duplicate work? I didn't have a specific plan in mind when I created this issue but I am happy to give feedback if needed. :)

**Comment by ModdedGamers** [comment]
If the entire documentation needs to be updated, see my paragraph labeled 2. If not, see 1.

1. We each take 2 sections of the work, so @spielers takes user and administration, and I will take integration and education.

2: I think we should split up the sections, so @spielers gets admininstration through help, and I will take install through samples.

**Comment by justinegeffen** [comment]
Thanks, @ModdedGamers. All the docs need to be updated and both of your proposals make sense to me. 

The only suggestion I have is to submit the PRs based on each directory, as opposed to a PR with all the file changes from the entire doc set as it's easier to review and merge. Other than that, I look forward to seeing these much-needed changes. :)

**Comment by spielers** [comment]
Cool !

**Comment by ModdedGamers** [comment]
I'm so sorry, but I can't work on this. I have a lot that is more important to me personally. I would love to do this, but there are things that are more important in my life right now. I wish best of luck to @spielers doing this project, but I am unable to do this for the foreseeable future.

**Comment by justinegeffen** [comment]
That is absolutely no problem, @ModdedGamers. We completely understand and we really appreciate you letting us know. :)

**Comment by cwarnermm** [comment]
@justinegeffen - Is this guideline documented in the Handbook? If it is, we're able to close this ticket.

**Comment by justinegeffen** [comment]
Yeah, it is. :)
