### ISSUE TITLE
Jira plugin: Troubleshooting "/jira install" error in local developer environment

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3280]
Mattermost user `jason.blais` from https://community-release.mattermost.com has requested the following be documented:

Problem:  After enabling [Jira plugin for Mattermost](https://github.com/mattermost/mattermost-plugin-jira) and running `/jira install` with site URL set to `LOCALHOST`, an error about an invalid site URL is received.

Solution:

1. Setup an [Ngrok connection](https://ngrok.com/) to your local developer environment. This exposes your local web server to Jira.
2. Setup your Mattermost SITEURL in the system console to the ngrok connection URL you are assigned.
3. Then try run `/jira install` 

Note: This may also use an accompanying update to the error message to clarify the error to the admin running `/jira install`

See the original post [here](https://community-release.mattermost.com/_redirect/pl/kratnyne3bdfbjonjyndz6defa).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by galihmelon** [comment]
CMIIW, but it seems that the change needs to be done in [a different repo](https://github.com/mattermost/mattermost-plugin-jira).
It's because [the relevant page on docs.mattermost.com](https://docs.mattermost.com/integrations/jira.html) says that it's moving to [gitbook](https://mattermost.gitbook.io/plugin-jira/admininstrator-guide/troubleshooting), which uses the other repo as the content source.

**Comment by cwarnermm** [comment]
@aaronrothschild - Is this still an active issue that users would encounter?

**Comment by aaronrothschild** [comment]
@cwarnermm It's a fairly edge case, but can certainly be a complexity an admin testingout MM and Jira could encounter if they have them both on their local machines.  We should simply say somewhere: "You cannot use `LOCALHOST` to connect the Jira plugin to your server, you can use a proxy if needed"
