### ISSUE TITLE
Help Wanted: Update Mobile Troubleshooting Docs

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#3288]
Relevant page: https://docs.mattermost.com/deploy/mobile-faq.html

Notification messages have been placed in their own log file, `notifications.log`, so the docs should be updated to include checking that file for errors related to push notifications.

**Comment by justinegeffen** [comment]
Thanks, @icelander! Would you be open to updating the docs with that change?

**Comment by jfrerich** [comment]
@justinegeffen, @icelander this is pretty old, but if still applicable, I was wondering if if could be added as HW ticket with the `Up For Grabs` label?

**Comment by justinegeffen** [comment]
Thanks @jfrerich. That works for me! Do you need anything from my side?

**Comment by jfrerich** [comment]
Unless you want to explicitly write out the text, we could leave this as Help Wanted.  Interestingly, I don't see an `Up For Grabs` label for this repo.  If you feel there are docs improvements that could be done by community members, that would be something to consider. 

Do you know why there is no `Up For Grabs` label for this repo?

**Comment by justinegeffen** [comment]
We don't currently have ``Up for Grabs`` as we've used ``Help Wanted`` (and referenced that filter in community posts about doc contributions). I don't see any reason not to add ``Up for Grabs`` though. :)

**Comment by vilsi12** [comment]
Can you assign me

**Comment by cwarnermm** [comment]
Replaced by: https://github.com/mattermost/docs/issues/6594
