### ISSUE TITLE
Update Slack and Bulk import common issues

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#3292]
Just a list of common issues when running a large slack import or bulk import.

1. Run the command as mattermost user, else it'll screw up permissions on attachments
2. Make sure you have enough space for attachments
3. If you're using a version < 5.17 make sure to change the default password requirements to be 5 characters and nothing else. Otherwise the account creation will fail!
4. Make sure you have enough space for logs for the Mattermost server **and** also on the DB Server.
5. Disable Anti-Virus or other plugins that interfere with attachment uploading. They might block uploading of attachments and cause the import to fail if configured incorrectly. 
If you need anti-virus scanning scan the attachment folder before the import.

**Comment by justinegeffen** [comment]
Thanks, @svelle. This is very helpful and could really provide a better customer experience. Do you think this would work best here: https://docs.mattermost.com/deployment/bulk-loading.html? Or is this more of a Troubleshooting list?

I have a few questions and was wondering if you'd be open to updating the docs at the link above and possibly address these questions: 

- Does this apply only to Slack imports or is it general best practice? 
- With regard to point 3, which password needs to be changed and where should this be done (and at what stage)? 
- For point 4, how much space is recommended? 
- If this is Troubleshooting, do we have examples of the errors a customer would experience? 

Thank you! :)

**Comment by svelle** [comment]
Hey Justine,
good questions.

1. I think this could very well be added to the bulk loading docs because it applies to all imports. It just came up during a customer migration from Slack to Mattermost
2. Basically all extended password requirements need to be disabled (no uppercase, no special characters, no numbers and password length needs to be 5)
3. Totally dependent on the size of the import. There's not really a recommended size here. At least a few gigabytes of course. Worst case the importer writes a new line for each message imported. So maybe 5GB per server. Seems like a sensible number to me.
4. I can see if I can find an example, don't have one at hand unfortunately.

**Comment by justinegeffen** [comment]
Thanks, @svelle, that's very helpful! Let me know if have the bandwidth to do the update - I've marked it as Help Wanted in the meantime. :)

**Comment by svelle** [comment]
If the internet on my flight tomorrow is okay'ish then I'll be happy to update it.

**Comment by justinegeffen** [comment]
Thank you! :)

**Comment by ewwollesen** [comment]
@cwarnermm I could grab this one for the Docathon. I am pretty sure I was the one that worked with @svelle on this originally anyway.

**Comment by cwarnermm** [comment]
Thanks so much @ewwollesen! I've assigned this one to you.

**Comment by svelle** [comment]
Closing as the assigned PR was merged :) thanks @ewwollesen !
