### ISSUE TITLE
SMTP/Email configuration still says to use /bin/bash in docker

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#3303]
Since the switch to alpine linux we don't have bash installed in the docker images. 

[This page](https://docs.mattermost.com/install/smtp-email-setup.html) however still refers to using it.
We should change it to use /bin/sh instead **or** install bash in the docker images.

**Comment by svelle** [comment]
Also it says to use telnet but we don't install telnet on the app image.

**Comment by PackElend** [comment]
is `openssl `part of alpine linux?
As `SMTP `shall be encrypted, `openssl `is the right tool to use.
