### ISSUE TITLE
Auto login(skip login page) for ADFS and identity server 4

### ISSUE THREAD

**Issue by NeelBhatt** [mattermost/docs#3307]
Hello Guys,

Just wondering if anyone can help me with this question on StackOverflow: https://stackoverflow.com/questions/59731578/auto-loginskip-login-page-for-adfs-and-identity-server-4

Thanks in advance

**Comment by svelle** [comment]
@NeelBhatt is that question related to mattermost?

**Comment by NeelBhatt** [comment]
I guess no sorry. you may close this thread
