### ISSUE TITLE
List of Supported Languages for Syntax Highlighting is out of date

### ISSUE THREAD

**Issue by christian-steinmeyer** [mattermost/docs#3326]
I have just noticed that not all languages given in the [documentation](https://github.com/mattermost/docs/blob/master/source/help/messaging/formatting-text.rst) do render correctly but some that are not given actually do. I assume there have been some updates in the rogue library that have been integrated but not made their way into the documentation.

For example, when writing:

    ```ps1
    some-powershell-command "some string" #comment
    ```

This should look like
```powershell
some-powershell-command "some string" #comment
```

But actually looks like
```
some-powershell-command "some string" #comment
```
However, using `powershell` instead of `ps1` as language identifier works like a charm.

The current list of identifiers and supported languages by rogue can be found [here](https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers).

Sidenote: Interestingly, Github supports the union of identifiers for those examples, I've tested.

**Comment by justinegeffen** [comment]
Hi @christian-steinmeyer. Thanks for raising this, it's very helpful. Would you be open to updating the documentation with your findings? If you have any additional documentation examples that would also be great!

**Comment by christian-steinmeyer** [comment]
Hi!

I can certainly update the list in the existing documentation to the one published by rogue. And perhaps add a link to their list for future changes. However, I believe that it would make sense to test or varify that list first, for which I lack the time, unfortunately.

**Comment by justinegeffen** [comment]
Thanks, @christian-steinmeyer that's a good point. I'm cc'ing @lieut-data: is there a way we can verify the languages listed in the "Syntax Highlighting" section? Or is there a list we can link to?

**Comment by lieut-data** [comment]
@justinegeffen, I /think/ we depend on https://highlightjs.org/ for the highlighting. @hmhealey, is that correct?

I wonder if we shouldn't just link out to their documentation, identifying the version we're using for reference?

**Comment by hmhealey** [comment]
We use Highlight JS, but the languages are enabled manually, so we haven't enabled them all. If we were to add something like lazy loading of languages, we could turn them all on and just link out to their docs, but that's not possible currently.

We shouldn't be linking to Rogue's list of languages though since that's not the library that we use.

**Comment by justinegeffen** [comment]
Perhaps we should add a disclaimer such as: We use Highlightjs.org for highlighting. Not all languages are enabled however they can be manually enabled as required."

If that is accurate, could we add some steps for manually enabling them or, if inaccurate, any alternative suggestions would be appreciated.

**Comment by christian-steinmeyer** [comment]
Possibly not my cup of tea, but isn't it weird, that Gitlab uses another library for syntax highlighting than Mattermost? As a user, I find this confusing, as I would expect Mattermost and Gitlab to coordinate their efforts.

Having said that, Gitlab [clearly states](https://docs.gitlab.com/ee/user/project/highlighting.html) they are using rogue (which is why I assumed that to be the case for Mattermost, too). I would recommend to align both applications and not more third party dependencies as necessary.

Regarding the integration of said library, I'm sure, some code snippets from the GitLab codebase could be used?

**Comment by lieut-data** [comment]
@christian-steinmeyer, sorry for the confusion here. While it's true that GitLab and Mattermost have a very close relationship, with Mattermost included with the GitLab Omnibus, the products are completely distinct. In particular, Mattermost isn't written using Ruby, and thus can't use Ruby gems like Rogue.

@hmhealey, I love the idea of lazy loading languages. This seems like the most viable approach, as I suppose manually enabling languages would require customizing the build. Should we create a help wanted ticket for such an effort?

**Comment by hmhealey** [comment]
That's a good idea. I've filed a ticket to discuss as a team before we could open it up as a Help Wanted ticket: https://mattermost.atlassian.net/browse/MM-22249

**Comment by ewwollesen** [comment]
@cwarnermm I could grab this one.

@hmhealey I want to make sure I'm following this correctly, but looking through everything it appears that the definitions moved from the [syntax_highlighting.tsx](https://github.com/mattermost/mattermost-webapp/blob/master/utils/syntax_highlighting.tsx) file over to the [constants.jsx](https://github.com/mattermost/mattermost-webapp/blob/master/utils/constants.jsx) file, but that you're still only able to use highlighting for the languages in that list?

Then I guess the next question would be do we want to include the aliases in the documentation as well? For example for `MarkDown` you can use `MarkDown` but also `md` and `mkd`. Do we want to maybe convert that section to a table listing the languages and all of the available aliases? Or is that a little too messy/unwieldy?

**Comment by cwarnermm** [comment]
Thanks, @ewwollesen! I've assigned you to this ticket.

**Comment by ewwollesen** [comment]
@cwarnermm How do you feel about something like this instead of how the languages are listed currently? It seems potentially more useful, but on the other hand it's kind of big so I don't know.
![image](https://user-images.githubusercontent.com/50209602/127596698-5bb1f16b-7dd3-465e-8a2f-41ae44cc1ba4.png)

**Comment by cwarnermm** [comment]
Thanks! @ewwollesen - A table-based approach is likely easier to read and scan quickly. This approach also lends itself well to listing many aliases, where necessary. Let's go with this approach!
