### ISSUE TITLE
Wrong iOS version in mobile app requirements

### ISSUE THREAD

**Issue by faase** [mattermost/docs#3336]
It's really just a typo in the [mobile app requirements](https://docs.mattermost.com/install/requirements.html#mobile-apps).

wrong: `iPhone 5s devices and later with iOS 12+`
correct: `iPhone 5s devices and later with iOS 11+`

thanks to @enahum for reporting it.

**Comment by justinegeffen** [comment]
Thanks, @faase!

**Comment by faase** [comment]
ok my bad! looks like i jumped the gun. just read this

> @enahum This was changed via https://github.com/mattermost/docs/pull/3087 based on our [software requirement guidelines](https://docs.mattermost.com/process/software-requirements.html#mobile-apps) that we support latest and next-to-latest versions.

_Originally posted by @amyblais in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzQ4MzI2NjE3/pull_request_reviews/more_threads_

so it was correct in the mobile app requirements, but not in the change logs.

**Comment by faase** [comment]
closing the issue

**Comment by enahum** [comment]
@faase, @amyblais and @esethna so this means that we should then bump the supported OS to iOS 12+ and Android 9+? And then why does the changelog is different than the doc? I’m really confused here.

**Comment by enahum** [comment]
Re-opening until we decide where to correct the disparity

**Comment by amyblais** [comment]
@enahum I will fix the changelog for iOS.

Android version is correct since the guideline is any versions supported by Google.

**Comment by enahum** [comment]
@amyblais is not only the changelog BUT also the app in itself.

**Comment by amyblais** [comment]
@enahum What is the work involved in changing it in the app itself?

**Comment by enahum** [comment]
@amyblais is just changing a setting, but do we bump it just like that?

actually there is this ticket in the backlog https://mattermost.atlassian.net/browse/MM-20643

**Comment by amyblais** [comment]
I've merged the PR for now to change it back to iOS 11 since it's not changed in the app itself.

Will open a new discussion with PMs on how our software guidelines can be improved and planned ahead properly.
