### ISSUE TITLE
Add sample SAML responses to docs

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#3352]
I think it would be really helpful if we'd add sample saml assertion responses to the docs for all the service providers we support so that admins can check if the one's they get match the type mattermost is expecting.

It's more of a suggestion so any feedback here is greatly appreciated :)

**Comment by justinegeffen** [comment]
Thanks @svelle. I've taken a look at our SAML docs to make sure I'm looking at the correct sections. For example, we have a list of provider docs here: https://docs.mattermost.com/deployment/sso-saml.html and each provider section has some screenshots. We also have an update going out about the SAML metadata URL which can be used for this configuration. 

Do those docs address the issue at all or would the SAML metadata URL update resolve it?

If not, let me know and if possible provide some examples/links so we can update the docs. :)

**Comment by svelle** [comment]
Hey Justine,
with the upcoming changes in SAML configuration I think we can close this for now. If the saml configuration is still an issue after those changes I'll just reopen and add some more info on what I'm specifically looking for :)
