### ISSUE TITLE
Request for Documentation: This is a test for Docup

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3384]
Mattermost user `der_test` from https://community.mattermost.com has requested the following be documented:

```
I have to support @kayazeren in this case. As posted before, working with pootle is kind of frustrating. I've had private messages with @jason in 2017 about pootle throwing around various error messages that make working on the translations so incredible ineffective.
```

See the original post [here](https://community.mattermost.com/_redirect/pl/8xhagfbe7prn3ewnxqqngxb1ao).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by der-test** [comment]
Test post, pls ignore.

**Comment by der-test** [comment]
@jasonblais Please close.
