### ISSUE TITLE
Add push message if app is not connected to a server

### ISSUE THREAD

**Issue by NicFaecks** [mattermost/docs#3408]
Due to security concerns the app disconnects from the server after 30 days without any notification. The app user can not know if there are no new messages or if the app disconnected until opening the app.

**Comment by amyblais** [comment]
@NicFaecks What mobile app and server version are you on?

**Comment by NicFaecks** [comment]
Andriod App Version: 1.28.0 (Build 268)
Server Version: 5.17.0 (Build 5.17.3)
Database: postgre

**Comment by amyblais** [comment]
@NicFaecks Would you mind re-opening this issue in the mobile repo along with information on whether your device is still in the list of active sessions when this bug happens https://github.com/mattermost/mattermost-mobile/issues.
