### ISSUE TITLE
Remove "production docker" setup docs

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#3412]
Right now we have the production docker deployment listed under the admin docs but in light of recent conversations it's not recommended for production use so we should remove it asap and then replace it with some basic guidance about the official docker hub images.

**Comment by justinegeffen** [comment]
Thanks, @svelle. It looks like this issue is related to: https://github.com/mattermost/docs/pull/3425 - what are your thoughts?

**Comment by svelle** [comment]
@justinegeffen yup, looks like it. Thanks for pointing it out. I linked them :)
