### ISSUE TITLE
Jumping window location

### ISSUE THREAD

**Issue by jshackatpair** [mattermost/docs#3433]
Running Linux desktop v 4.4.0 on Ubuntu Linux 18.04

IF: I move the application window, and subsequently minimize it
THEN: when I restore the application window, it shows up in the top left corner of my workspace desktop and not at the location where I put it.

**Comment by amyblais** [comment]
Would you be open to re-opening this in the desktop repo https://github.com/mattermost/desktop/issues?

**Comment by jshackatpair** [comment]
Yes, of course. My bad, a rookie mistake.
