### ISSUE TITLE
Broken examples on Configuring Proxy to Mattermost Transport Encryption document

### ISSUE THREAD

**Issue by amyblais** [mattermost/docs#3456]
**Before** and **After** examples in the "Configuring Mattermost" section are not rendering on this doc: https://docs.mattermost.com/install/transport-encryption/config-mattermost.html.

There were attempts to fix it here but it wasn't clear how to fix it: https://github.com/mattermost/docs/pull/3206.

**Comment by justinegeffen** [comment]
I forgot about this one, @amyblais. Thanks for reopening. 

@DSchalla, do you perhaps have the output available to send to me? I just need to see the indenting so I can try fix this. A screenshot would be fine. :)

**Comment by justinegeffen** [comment]
Following up on this, @DSchalla, when you have a moment! :)

**Comment by DSchalla** [comment]
Sorry for the delay @justinegeffen and @amyblais! Just opened a pull request to fix the issue.
