### ISSUE TITLE
Hamburger menu

### ISSUE THREAD

**Issue by martinwilczak** [mattermost/docs#3459]
How do I disable hamburger menu and enable menu bar that is standard accross apps in whole system? I have no idea why is everyone so eager to create yet another version of this user-unfriendly stupidity.

**Comment by justinegeffen** [comment]
Hi @martinwilczak. Thanks for raising this issue. I understand you're frustrated and would like to find out if you're open to raising this in the [Ask Anything](https://community.mattermost.com/core/channels/ask-anything) channel or on the [Mattermost Forum](https://forum.mattermost.org/). The community members on both platforms may have experience with this and be able to provide you with some solutions and suggestions that they've implemented.

**Comment by svelle** [comment]
Closing as it's the wrong repo for this kind of issue.
Thanks @justinegeffen for giving pointers for the right locations to report this :)
