### ISSUE TITLE
Request for Documentation: Okta Setup instruction changes

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3461]
Mattermost user `scott.bishel` from https://community.mattermost.com has requested the following be documented:

```
Oh I see, you have to click to access their "Classic UI"... hopefully this doesn't indicate that they plan to deprecate this level of access.. anyway, I'll leave this info here in case it's useful
```

See the original post [here](https://community.mattermost.com/_redirect/pl/rpztb9yx8j8uzxkyup1x7xpsfh).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by justinegeffen** [comment]
Thanks, @sbishel! I can't access the link in the issue for some reason. Could you share a screenshot for context?
