### ISSUE TITLE
Themes causing white screen.

### ISSUE THREAD

**Issue by rubberneck** [mattermost/docs#3468]
For example the [Gruvbox Dark theme](https://github.com/mattermost/docs/blob/master/source/help/settings/theme-colors.rst#gruvbox-dark-theme) causes a blank white screen after you paste the JSON in.

I played around with it if you add the `"dndIndicator": "#be5046"` to the JSON it will stop giving you the blank screen.

The `dndIndicator` seems to be missing from all of them execpt.
[One Dark](https://github.com/mattermost/docs/blob/master/source/help/settings/theme-colors.rst#one-dark)

**Comment by amyblais** [comment]
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-23456.

**Comment by amyblais** [comment]
Closing as this is fixed for upcoming v5.22 release,
