### ISSUE TITLE
Add documentation for changes to bulk import

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#3472]
More of a note to myself.

We need to add documentation for the changes introduced to the bulk import with this PR:
https://github.com/mattermost/mattermost-server/pull/14034

Basically the post object now has a new attribute called props which can contain message attachments.

**Comment by justinegeffen** [comment]
Awesome, thanks @svelle! This is a very helpful change. :)

**Comment by justinegeffen** [comment]
Hi @svelle. Wanted to follow up and find out whether you've had a chance to update the docs for this? If not, let me know what the change is and I'll be happy to sort it out. :)

**Comment by svelle** [comment]
> Hi @svelle. Wanted to follow up and find out whether you've had a chance to update the docs for this? If not, let me know what the change is and I'll be happy to sort it out. :) 

Hey @justinegeffen ,
I'm out for the long weekend because of Easter holidays. I'll get on to it this week (ideally before the release of the new server version ;))

**Comment by justinegeffen** [comment]
Thanks @svelle! I've opened [this PR](https://github.com/mattermost/mattermost-server/pull/14034) in the meantime and will sync up with you when you're back. :)
