### ISSUE TITLE
Improve License Deployment Docs

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#3474]
Things to add [to this location](https://docs.mattermost.com/install/ee-install.html#changing-a-license-key):

 - Deploying licenses across a cluster
 - Replacing a license
 - Deploying licenses as files rather than through the System Console

**Comment by justinegeffen** [comment]
Thanks, @icelander! Would you be open to updating the docs with the content you've listed? Alternatively, if you have the steps/content available to share we could open this up as a Help Wanted issue. :)

**Comment by justinegeffen** [comment]
Following up on this, @icelander. Let me know if you have any available content and if you're open to updating the docs. Also happy to collaborate on this. :)

**Comment by cwarnermm** [comment]
Comprehensive license deployment documentation is available at docs.mattermost.com. Closing.
