### ISSUE TITLE
Request for Documentation: Add (optional) pgpass steps to postgres installation in docs

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3483]
Mattermost user `sven.huester` from https://community-daily.mattermost.com has requested the following be documented:

```
So .. postgres recommends the standard way to pass passwords is through a `.pgpass` file. It is a special file that HAS to be 0600 in permissions otherwise it doesnt work. One can also pass the location of the file using the PGPASS env variable.
This leaves the security to the user running the application. If you run it as a service, then you need sudo permissions to start a service file. Therefore, this file can be only root read-write and disabled for everybody else. After all, if you are root, there's nothing you can't do.
https://www.postgresql.org/docs/current/libpq-pgpass.html
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/f98sb8g873fj7esw63kfiuhtkr).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by justinegeffen** [comment]
Thanks, @svelle. Do you have an idea of where this content should be added in the docs? I've taken a look through the original post but if you have more context that'd be great. :)

**Comment by svelle** [comment]
Hey @justinegeffen that would be here: https://docs.mattermost.com/install/install-ubuntu-1604.html#installing-postgresql-database-server

and on the same section of the other OS's

**Comment by justinegeffen** [comment]
Thanks, @svelle. Would you be open to updating that doc, and then I could replicate it across the other docs if it's one-size-fits-all?

**Comment by svelle** [comment]
sure once I find the time :)

**Comment by justinegeffen** [comment]
Thanks, @svelle! :) :)

**Comment by fakela** [comment]
@justinegeffen has this doc been updated.

**Comment by svelle** [comment]
@fakela that would be fantastic!
Unfortunately I haven't had the time to do so yet.

**Comment by justinegeffen** [comment]
Thanks so much, @fakela, that would be awesome. Please let me or @svelle know how we can help. :)
