### ISSUE TITLE
Request for Documentation: Update docs to reference NAS

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3486]
Mattermost user `aaron.rothschild` from https://community-daily.mattermost.com has requested the following be documented:

```
It would be lovely if you could update your documentation at https://docs.mattermost.com/deployment/cluster.html#file-storage-configuration to show the NAS suggestion, under the Plugins and High Availability section... You can rif off what you say under File Storage Configuration
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/8rubpfimofnqtq9nmiaicp5ngw).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by justinegeffen** [comment]
Hi @aaronrothschild. Thanks for raising this. Would you be open to updating [the doc](https://docs.mattermost.com/deployment/cluster.html#file-storage-configuration) with the required information? Happy to assist with the process, let me know if you have any questions. :)

**Comment by justinegeffen** [comment]
Following up on this, @aaronrothschild - let me know if I can help with anything. :)

**Comment by fakela** [comment]
@justinegeffen if this is not worked on I would love to work on this with your guidance.

**Comment by justinegeffen** [comment]
> @justinegeffen if this is not worked on I would love to work on this with your guidance.

Hi @fakela! Thanks for picking this up. It has not been worked on yet, and it would be awesome working with you to update the docs. Let me know how I can help you get started. :)

**Comment by fakela** [comment]
@justinegeffen thanks I will start with this first
