### ISSUE TITLE
Please add the time in the Direct Messages session

### ISSUE THREAD

**Issue by wildbodom** [mattermost/docs#3487]
Hello,

Please add a sort option (currently only alphabet sorting is available) to the Direct Messages session.
After having a conversation with someone via direct message. If I go to another channel, there is no way to find the recent direct message other than having to remember the name of the person, which is a difficulty when communicating with multiple people with different nationalities. 

I am sure this request has been made by many. Please consider it.

Thank you,

**Comment by justinegeffen** [comment]
Hi @wildbodom. Thanks for raising this! Would you be open to joining our [Contributors channel](https://community.mattermost.com/core/channels/tickets) on the Community server? That way you can get feedback on how best to go about initiating this request and then at the end of the process the documentation gets updated. :) 

As this isn't directly related to our documentation I'm going to close this issue. 

Let me know if you have any questions about the process or need any more assistance. :)
