### ISSUE TITLE
Non alpha numeric characters are escaped in chat

### ISSUE THREAD

**Issue by MirceaAndreiAlbu** [mattermost/docs#3527]
I am using Mattermost 4.4.0 and almost all non alpha numeric characters get escaped only in the chat box.

I've tried different fonts, but the result is the same.

![mattermost encoding](https://user-images.githubusercontent.com/7541796/79307582-ca0f9300-7eff-11ea-83e1-1fa1fa910da8.png)

**Comment by amyblais** [comment]
@mirceaeu What Mattermost server version are you on?

**Comment by mirceaeu** [comment]
Most of my colleagues don't seem to have this problem. So it looks like an account settings. But I cannot find anything in the profile settings dashboard or in the documentation.

The server version I think is 2.1.0
![image](https://user-images.githubusercontent.com/7541796/79344054-f21ae880-7f37-11ea-9678-0528f8a557f6.png)

**Comment by amyblais** [comment]
v2.1.0 is quite old, would you be able to upgrade to a more recent version? Our most recent version is v5.21.0.

**Comment by mirceaeu** [comment]
I know, but it is not my decision to take for upgrading this server. 

Given the fact that other colleagues don't have this encoding problem, I suppose there is an account settings.
From were can I change the encoding of my account as the documentation doesn't say anything about this.

**Comment by justinegeffen** [comment]
Hi @MirceaAndreiAlbu. I wanted to follow up on this and find out whether you've been able to resolve your query. :)

**Comment by MirceaAndreiAlbu** [comment]
We updated to a new version and everything is fine now. Thanks
