### ISSUE TITLE
SAML Service Provider Identity

### ISSUE THREAD

**Issue by amyblais** [mattermost/docs#3529]
Original report: https://forum.mattermost.org/t/saml-service-provider-identity/9488

When configuring SAML, one of the steps is to configure the identity provider with the service provider identity URL or URI. Normally this would be done using the SP URL or some other unique ID. However, Mattermost has coded theirs to use the Identity Provider request URL. This is incorrect as if every SP did this the IDP would have no way of telling them apart.

This can be seen here in step 8 https://docs.mattermost.com/deployment/sso-saml-adfs.html. This link refers to the “relying party trust identifier” and links it to begin synonymous with the “identity provider issuer url” but these are two very different things. It is actually synonymous with the service provider identity as service provider and relying party are interchangeable references.

This value should be a unique SP value not the value of the IDP. e.g. ``https://mattermost.example.com/login/sso/saml`` or ``urn:federation:mattermost``.

**Comment by justinegeffen** [comment]
Thanks, @amyblais. I've checked in with the Enterprise team to find out what the next steps are.

**Comment by amyblais** [comment]
It turns this doesn't seem to be a documentation issue after all, but probably a code bug. I'll see if Enterprise team responds or if support team can step in.

**Comment by johnthompson365** [comment]
Is there any progress on this potential bug? Thanks.

**Comment by amyblais** [comment]
Latest update is that we are getting additional information from the reporter https://forum.mattermost.org/t/saml-service-provider-identity/9488/4.

**Comment by amyblais** [comment]
Closing as this is not a documentation issue and is tracked via https://mattermost.atlassian.net/browse/MM-24467.
