### ISSUE TITLE
Privacy policy desktop application

### ISSUE THREAD

**Issue by jvs64893** [mattermost/docs#3572]
I checked the website and didn't find any privacy policy which covers the desktop application of mattermost.

There is a privacy policy regarding the server application and there is a special excerpt about telemetry in the Android application. It doesn't say anything about the desktop application though.

Is the desktop application collecting and sending any data (to 1st or 3rd parties), that is different to using Mattermost in the browser (if you're using a self-hosted version)?
Any telemetry?

I think this should be added to the telemetry information.

**Comment by justinegeffen** [comment]
Hi @jvs64893. Thanks for this question and your suggestion. I am following up on this and will revert as soon as I have an answer to your question.

**Comment by wiersgallak** [comment]
@jvs64893 The Desktop application is a wrapper around our web application, so it is covered by our standard privacy policy (https://github.com/mattermost/mattermost-server/blob/master/build/PRIVACY_POLICY.md). There is no difference in what data is being collected.  You can review the telemetry data collected on our Telemetry docs: https://docs.mattermost.com/administration/telemetry.html 

Please let us know if you have any further questions.
