### ISSUE TITLE
Request for documentation: radio button for interactive dialog

### ISSUE THREAD

**Issue by kaakaa** [mattermost/docs#3589]
Radio button have been supported for interactive dialog by https://github.com/mattermost/mattermost-server/issues/10465, but [`Interactive Dialogs` page](https://docs.mattermost.com/developer/interactive-dialogs.html#dialog-submission) doesn't have any mentions about `radio` type.

**Comment by justinegeffen** [comment]
Hi @kaakaa, thanks for picking this up! Would you be open to updating the page with your feedback?

**Comment by justinegeffen** [comment]
Following up on this, @kaakaa, to find out if you'd be open to updating the docs for this. I'm happy to answer any questions you have. :)

**Comment by kaakaa** [comment]
I'm sorry for my late replay. @justinegeffen 
I'm interested in updating docs, however, I can't promise when I'm going to start working on it because I don't have much time right now.

**Comment by justinegeffen** [comment]
That would be extremely helpful, thank you so much. :) I totally understand time constraints so if you are able to find the time that would be awesome. Please let me know if I can assist in any way. :)
