### ISSUE TITLE
http://docs.mattermost.com/administration/command-line-tools.md **is forbidden**

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/docs#36]
http://docs.mattermost.com/deployment/on-boarding.html this page has "Command Line Tool" links to this page.

**Comment by it33** [comment]
Thanks @chengweiv5, 

@esethna please help fix?

**Comment by esethna** [comment]
Thanks @chengweiv5, [fixed](https://github.com/mattermost/docs/pull/37/files).
