### ISSUE TITLE
Incorrect link on kubernetes page

### ISSUE THREAD

**Issue by robsoncassol** [mattermost/docs#3609]
I think the link "Using a Custom Configuration"  [here](https://docs.mattermost.com/install/install-kubernetes.html#setting-up-a-kubernetes-cluster) is not correct, is linking to [Nginx page](https://kubernetes.github.io/ingress-nginx/deploy/).

**Comment by justinegeffen** [comment]
Hi @robsoncassol. Thank you for letting us know about this. That sentence has been removed and the docs are pending an update which will link to that section. 

If there's anything we can assist with in the interim, please let us know.
