### ISSUE TITLE
Broken images in "in-line images" section

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#3615]
See: https://docs.mattermost.com/help/messaging/formatting-text.html#in-line-images

![image](https://user-images.githubusercontent.com/13119842/81840521-2245af00-9517-11ea-8e13-66dbee47a0ea.png)

**Comment by fakela** [comment]
@justinegeffen I would love to work on this

**Comment by justinegeffen** [comment]
That would be awesome, @fakela! Thanks. :)
