### ISSUE TITLE
Request for Documentation: Update HA Docs to indicate how the multi-server configuration behaves (no error catching)

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3625]
Mattermost user `aaron.rothschild` from https://community-daily.mattermost.com has requested the following be documented:

```
Add to Admin documentation on setting up HA clusters: 
- What the setting does 
- how it behaves - not as you expect. 
- how should it be setup properly to avoid downtime? 
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/wh1mbxmubbfzjf5pc5yg1ijqgr).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by fakela** [comment]
@justinegeffen can I take this up

**Comment by fakela** [comment]
@justinegeffen  if I can get more info on this I could work on this

**Comment by justinegeffen** [comment]
Thanks, @fakela, that would be awesome. @aaronrothschild raised the issue and he would be the best person to get more info from. Let me know if I can help with anything! :)

**Comment by fakela** [comment]
Alright sure

**Comment by aaronrothschild** [comment]
Unfortunately I'm not that familiar with the issue - I
think @dennis.kitrell is more aware of it.

**Comment by fakela** [comment]
Okay @aaronrothschild would wait for more info from @thefactremains on this

**Comment by thefactremains** [comment]
Sorry for the delay on this everyone - and I apologize because I do not have the answers you're seeking. 

@wiersgallak can you point us in the right direction?
[original conversation here](https://community.mattermost.com/private-core/pl/gxes5oqr7frdprzwafn9x3exrc)

**Comment by cwarnermm** [comment]
Comprehensive HA documentation is available at docs.mattermost.com. Closing.
