### ISSUE TITLE
Can not open conversation with three people

### ISSUE THREAD

**Issue by pulkownik1803** [mattermost/docs#3626]
I have created conversation with two other users and now non of us can close it nor open it. It's showing in the left pane 
![image](https://user-images.githubusercontent.com/59015743/82286941-4124c500-999f-11ea-95c3-8b30e7d59463.png)
and while I'm clicking on it another entry pops up in the pane
![image](https://user-images.githubusercontent.com/59015743/82286997-729d9080-999f-11ea-8107-d604f9284187.png)

I'm using desktop app - version 4.4.2 on Windows 10
I was trying to reload app with clearing cache without success.
In the browser it looks exactly the same.
It's not possible to close entry from pic. 1

**Comment by amyblais** [comment]
@pulkownik1803 What Mattermost server version are you on?

**Comment by justinegeffen** [comment]
Hi @pulkownik1803. I wanted to follow up on this and confirm whether it's been resolved.

**Comment by cwarnermm** [comment]
Closing.
