### ISSUE TITLE
Add note about DB performance to LDAP docs

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#3630]
The nature of LDAP syncs can put significant load on a database server. To let customers know we should add a note like this to the [LDAP Sync Interval configuration docs](https://docs.mattermost.com/administration/config-settings.html#synchronization-interval-minutes)

> **Note:** Because LDAP syncs cause a large number of database read queries you should monitor database load during a sync to determine how often these syncs should happen in your environment.

**Comment by justinegeffen** [comment]
Thanks, @icelander! Would you be open to adding the update to the doc?

**Comment by yash2189** [comment]
@justinegeffen is this issue available?

**Comment by justinegeffen** [comment]
It is, @yash2189! You're welcome to take it. :)

**Comment by yash2189** [comment]
@justinegeffen one of my PR in mattermost-docs is yet to be reviewed , since I can't delete my existing repository is it fine if I raise a PR from the same repository?

**Comment by yash2189** [comment]
@justinegeffen can you please review my PR #4027 ?
Thanks.

**Comment by justinegeffen** [comment]
There shouldn't be any issues with opening a new PR from your forked repo as it's a separate file, although I stand corrected on that. The PR you previously submitted is awaiting review which may take a day or so but it has had an editorial review already. And I have reviewed your most recent PR as well. Thank you for your contributions and enthusiasm! :)

**Comment by yash2189** [comment]
Thanks @justinegeffen for providing the opportunity :)
