### ISSUE TITLE
Help Wanted: users.json generation code samples don't say what language they're in

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#3634]
[On this page](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-user-migrate-auth) we provide code samples for generating a users.json file from various providers, but give no instructions on how to run this code or even what language it's in. I think it might be Python but whoever wrote it should clarify.

**Comment by justinegeffen** [comment]
Thanks, @icelander. The docs have been written by multiple contributors so it's difficult to isolate the author of this section. @wiersgallak may have some insight into this though.

**Comment by achintya-7** [comment]
> @achintya-7 - Do you continue to be interested in working on this docs request?

Sure, I will look into it.

**Comment by achintya-7** [comment]
@cwarnermm I looked into the docs and all the three user file generation methods are written in Python. Can you suggest to me what further action should I take here?

**Comment by cwarnermm** [comment]
Thanks, @achintya-7! The next step for this documentation ticket would be to create a PR with requested changes. As noted in the original request, the sample OneLogin, OKTA, and ADFS scripts provided in the product documentation are missing important context that will help users succeed, including a confirmation that the scripts are written in Python, and details on how to run those Python scripts in a real-world scenario.

One thing I'd like to clarify with our Product Management team is how far we want to take this content update request, given that the CLI has been replaced, as of Mattermost v6.0, with the mmctl command line tool. 

@wiersgallak - What are your thoughts on applying content clarifications for our CLI product documentation?
