### ISSUE TITLE
Integration Docs: When to use webhooks vs plugin vs a slash command?  

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/docs#3639]
Provide some context for admins based on what they are trying to do. Perhaps a chart showing the pros/cons of each approach?  Use cases?

**Comment by cwarnermm** [comment]
@aaronrothschild - Are you open to drafting a PR for this docs request?

**Comment by aaronrothschild** [comment]
@cwarnermm yes, we could make something comparing these different ways to integrate with mattermost.  Perhaps a flowchart?

**Comment by cwarnermm** [comment]
A visual flowchart would be a great approach!

**Comment by cwarnermm** [comment]
@aaronrothschild - Are you open to helping draft a docs update for this issue?
