### ISSUE TITLE
Request for Documentation: How is away status triggered

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3642]
Mattermost user `eric.sethna` from https://community-daily.mattermost.com has requested the following be documented:

```
Afaik the away status rules are similar to this, we should work on documenting these to make this more visible.

Desktop v4.4+ bases activity on any mouse movement on the computer (so you'll stay online as long as your mouse is moving). If your mouse is still for 5 minutes or more, you'll be set to away

Browser is based on activity in Mattermost itself, meaning you are set to away:

1. When the tab is unfocused for 5 minutes 
2. You have not typed or switched channels for 5 minutes

Would need dev to confirm cc//@deanwhillier then we should doc this.
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/ghhngxgpei8g3y6gq8nwiayfce).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by justinegeffen** [comment]
Thanks, @esethna. It looks like the update would be [here](https://docs.mattermost.com/help/getting-started/signing-in.html?highlight=away%20status#setting-your-status). @deanwhillier, would you be open to confirming this behavior ahead of the update being made? Thanks!

**Comment by esethna** [comment]
Correct, that would be the right place. We should try to be as detailed as possible for the ambiguous terms. ie what does "interacting" mean in the case of browser vs desktop

**Comment by deanwhillier** [comment]
I'd propose a slight adjustment as follows:

```
Desktop v4.4+ bases activity on any user interaction on the computer, so if you are typing or using your mouse, your status will remain online. Your status will be set to away only after 5 minutes of inactivity.

Browser is based on activity in Mattermost itself, meaning you are set to away when:

1. You have not typed or switched channels for 5 minutes
2. The tab is unfocused for 5 minutes
3. The browser is in the background or minimized for 5 minutes
```

**Comment by fakela** [comment]
@justinegeffen I would love to take this up

**Comment by justinegeffen** [comment]
That's awesome news, thanks @fakela! It looks like there should be enough info to go on for now but if you get stuck or anything is unclear please don't hesitate to ping me. :)
