### ISSUE TITLE
Request for Documentation: Data Retention FAQ

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/docs#3647]
Two new FAQs added to [data](https://docs.mattermost.com/administration/data-retention.html) retention doc based on additional comments in: https://github.com/mattermost/docs/issues/3131. 

Context around the original question was provided: 

- Data retention runs the actual deletion query in batches. It deletes data in blocks of 1,000 records per query in order to not lock-up the database for extended periods of time with slow, long-running queries (keeping to this limit keeps the query down to a few milliseconds execution time on the database itself). Each batch of data is deleted based on indexes, so the queries are generally quite quick to execute on such small batches meaning the server will stay fully responsive while the process is running.

- What is shown in logs:
When the job scheduler identifies that it is time for the data retention job to be scheduled again for immediate running (i.e. at the time they have configured for it to run each day), a debug level log line is printed: _Scheduling data retention job.._
When a jobserver then picks up that scheduled job in order to execute it there will be a debug log as follows: _Worker EnterpriseDataRetention: Received a new candidate job.._
When the job is complete there is an info level log line: _Worker EnterpriseDataRetention: Job is complete_

Suggested new FAQs:
_FAQ 1: How long does it take to run a deletion query and does it affect server performance?
FAQ 2: How do I know whether the data retention job is running/scheduled?_

@wiersgallak is a good person to contact for this.

**Comment by fakela** [comment]
@justinegeffen I would love to work on this

**Comment by justinegeffen** [comment]
> @justinegeffen I would love to work on this

Awesome! It's all yours. :)
