### ISSUE TITLE
[Help Wanted] Momentum scroll on mobile devices

### ISSUE THREAD

**Issue by esethna** [mattermost/docs#368]
Navigate to docs.mattermost.com on a mobile device and notice that the website scroll is fixed to your finger movement.

Expected: momentum scroll observed on most other websites.

**Comment by shieldsjared** [comment]
If somebody doesn't get to this before me, I'll knock it out. Just at a css attribute.

**Comment by shieldsjared** [comment]
PR submitted.

**Comment by esethna** [comment]
Resolved, thanks to @shieldsjared!
