### ISSUE TITLE
Feature request: Hyperlink support + Keyboard shortcut 

### ISSUE THREAD

**Issue by slt-uxd** [mattermost/docs#3681]
Requesting the capability to have hyperlinks via a keyboard shortcut (like Cmd+K).

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @slt-uxd,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by slt-uxd** [comment]
Done: https://mattermost.uservoice.com/forums/306457-general/suggestions/40654393-hyperlink-support-keyboard-shortcut
