### ISSUE TITLE
[Help Wanted] Bug: Linking to a section heading of a document causes the scroll to offset by the width of the Mattermost header bar

### ISSUE THREAD

**Issue by esethna** [mattermost/docs#369]
Repro:
1. Click a link to a specific section header in a document (for example, https://docs.mattermost.com/deployment/cluster.html#file-storage-configuration)

Observed: The section header is hidden behind the "Mattermost" header bar because the scroll is offset. This only seems to happen the first time the link is visited.

Expected: Page is scrolled so linked section starts just below the "Mattermost" header bar

See screenshot:
![image](https://cloud.githubusercontent.com/assets/14333569/17710347/0e829b9c-63aa-11e6-8568-6d82177eefcf.png)

**Comment by shieldsjared** [comment]
I'm having a little trouble reproducing this, but I can definitely see how the named-anchors aren't lining up _well_.  There are common fixes for this sort of thing, but they tend to lead down dangerous roads of unpredictable behavior (judging by the fixes I've found and the responses to each).  In lieu of resolving this issue directly, I think a more reliable approach might be to correct the underlying reason that the pages are scrolling "underneath" of the header (which causes the browser to fail to properly scroll the named-element into view).  If you notice, the right-hand scrollbar falls _under_ the header (which is fixed positioned).  I'm sure that with some tinkering we can update the layout to prevent this overlay of layers, which should then resolve the issue you're describing.  Just a thought...

Nevertheless, what browser did you repro this in?

**Comment by shieldsjared** [comment]
@enahum - After the merge of #502 Im no longer able to reproduce.  Can you?

**Comment by esethna** [comment]
Cannot repro anymore, thanks @shieldsjared! Closing as resolved.
