### ISSUE TITLE
I want edit/delete message's addtional file

### ISSUE THREAD

**Issue by gshmu** [mattermost/docs#3692]
I can edit and delete message, but wen I delete the message's addtional file. the message deleted too.

I edit this message, no way to change the addtional.

**Comment by gshmu** [comment]
Any one know how to recovery the message?

**Comment by gshmu** [comment]
Why not forbidden deleted pinned message?

**Comment by amyblais** [comment]
@gshmu What Mattermost server version are you on? What OS and version are you on?
How are you deleting the file attachment on a message?

**Comment by gshmu** [comment]
Mattermost version: 5.23.1
db Schema version: 5.23.0
db: postgres

server OS: Ubuntu
PC OS: MAC
Client: chrome browser

Because the message and the attachment is one message, I delete both message content and attachment, and all the reply of this message.  @amyblais It's a pinned message, I really want restore it.

**Comment by amyblais** [comment]
I'm guessing you deleted the first message in a thread which also deletes the rest of the thread (this is expected behaviour). Deleted messages are stored in the database, so you should contact your System Admin about recovering the message.

**Comment by gshmu** [comment]
The first message has attachment, post them same time. and I can't delete the attachment.
<img width="497" alt="image" src="https://user-images.githubusercontent.com/1797676/84846380-3da95a00-b081-11ea-9bac-c14eb4970a2f.png">

any restore guide? @amyblais

**Comment by amyblais** [comment]
@gshmu It is currently not possible to delete/edit an attachment from a posted message.

What you could do is copy the text you posted, delete the post, and then re-post the text without the attachment.

**Comment by gshmu** [comment]
@amyblais any guide to restore the message and reply. some sql or guide url, thx.

**Comment by justinegeffen** [comment]
Hi @gshmu. I wanted to check in with you and find out whether you were able to resolve the issue. :)

**Comment by gshmu** [comment]
@justinegeffen what should I do?

**Comment by justinegeffen** [comment]
Hi @gshmu, one option is to post your question on the [Mattermost forum](forum.mattermost.org) along with a link to this issue. Someone in our community may have had the same question, or if not, your post could assist others who may have this question in future. 

Have you been able to contact your System Admin as @amyblais suggested?

**Comment by gshmu** [comment]
I found the message in the notification, and post the message again, but lost some reply

**Comment by gshmu** [comment]
@justinegeffen
