### ISSUE TITLE
Request for Documentation: using mac's default archive utility prevents users from openning the app

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3698]
Mattermost user `guillermo.vaya` from https://community-release.mattermost.com has requested the following be documented:

```
also, on some setups, using mac archive utility (mac's default for handling zips) causes it to not open, using a third party software (like keka or unarchiver) seems to fix that
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/9ze4ju3rzjfk9b86g3z341ji8y).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by Willyfrog** [comment]
related info: https://github.com/mattermost/desktop/pull/1110#issuecomment-571352980
