### ISSUE TITLE
Changing border around images to 1px and grey, similar to image border in product? 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#372]
The borders in docs are BLACK and HEAVY around images. They seem out-of-place. 

![image](https://cloud.githubusercontent.com/assets/177788/17713897/1714aa86-63b2-11e6-8822-cbee432178ff.png)

Propose switching to a 1px grey border similar to image borders in the product on default theme. 

![image](https://cloud.githubusercontent.com/assets/177788/17713904/1df2879c-63b2-11e6-98a1-8b731c6f7810.png)

**Comment by jasonblais** [comment]
@it33 That's probably for my images...I can go and update them when I get the chance. Probably not until I come back in two weeks.

Would the border in the attached image work? The program I use doesn't have 'pixels', so it's approximating 1px here.

![image](https://cloud.githubusercontent.com/assets/13119842/17722119/c527fe20-63fd-11e6-9130-6b4113a22b80.png)

Below is the original image for comparison:

![image](https://cloud.githubusercontent.com/assets/13119842/17722173/327250b6-63fe-11e6-839b-eaea3643d5e1.png)

**Comment by it33** [comment]
Thanks @jasonblais, yes, the lighter grey works, I didn't realize it had to be all manually done... I don't know if it's worth the mana, 

How about just make future ones grey and leave the black ones as is? 

Closing the issue.
