### ISSUE TITLE
Integrations: Update Message Buttons example

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/docs#3725]
Update https://docs.mattermost.com/developer/interactive-messages.html?highlight=matterpoll#message-buttons for https://github.com/mattermost/mattermost-webapp/pull/4993.

**Comment by yash2189** [comment]
hi @justinegeffen can you please tell me what needs to be done for this issue?

**Comment by justinegeffen** [comment]
Hi @yash2189! The [PR](https://github.com/mattermost/mattermost-webapp/pull/4993) contains the history of the change and screenshots. However, as you will see in my last comment, I am waiting additional confirmation on the changes made. I have not yet received that feedback but I believe @hanzei is a great resource and may be able to guide you in terms of what needs to be updated on the [relevant page](https://docs.mattermost.com/developer/interactive-messages.html?highlight=matterpoll#message-buttons).

**Comment by yash2189** [comment]
Thanks @justinegeffen . @hanzei Can you please tell me what needs to be updated on the page?

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-webapp/pull/4993 did add support for different styles to message buttons. This should be reflected in a new section in https://docs.mattermost.com/developer/interactive-messages.html that explains with a screenshots the different supported styles. The PR does contain a list of all of these.

Let me know if that helps you get started.

**Comment by yash2189** [comment]
Sure @hanzei ,thanks I'll have a read on the content provided by you and will get back once I'm done with my reading.

**Comment by yash2189** [comment]
@hanzei I read the content , so is it just like a small section that needs to be added for Message buttons only?

**Comment by hanzei** [comment]
Yes, there should be a new section for style of message buttons with screenshots.

**Comment by yash2189** [comment]
@hanzei As for the screenshots do I need to setup the local environment?

**Comment by hanzei** [comment]
Either that or you use the one from https://github.com/mattermost/mattermost-webapp/pull/4993

**Comment by larkox** [comment]
May I take this one?
