### ISSUE TITLE
MM with apache2 Proxy / Windows Client / Links to another path of subdomain not working

### ISSUE THREAD

**Issue by sonsofabraxas** [mattermost/docs#3727]
**Environment:**
Mattermost Version: 5.24.1
Database Schema Version: 5.24.0
Database: mysql
Mattermost Site URL: "https://mysubdomain.mydomain.ch/mattermost"

Apache2 **Proxy** Config on Linux Debian:
[apache2_config_mydomain.txt](https://github.com/mattermost/docs/files/4858226/apache2_config_mydomain.txt)

**Reproduction**
1. As any user, post a link to a domain, that is a "sister" domain of the Mattermost site url. (For example: https://mysubdomain.mydomain.ch/AnyOtherServiceOrSite)
2. Try to klick the Link in the **Windwos Client.**

**Problem Description**
Nothing happens. No new Browsertab is opened, nothing in the logfiles. 
The same link on the same machine works from the browser-client of Mattermost.
Any other link with other domains works.

**Expectation**
The link to another path of the same subdomain should open in a new tab in the browser.

**Comment by amyblais** [comment]
@sonsofabraxas What Windows OS version as well as Mattermost desktop app version are you on?

**Comment by sonsofabraxas** [comment]
> 
> 
> @sonsofabraxas What Windows OS version as well as Mattermost desktop app version are you on?

Windows OS 10 Pro, Version 1909, Build 18363.900 and Mattermost Desktop App v4.5.0

**Comment by amyblais** [comment]
As this sounds like a desktop app issue, would you be open to re-opening this issue in the desktop app repo https://github.com/mattermost/desktop/issues?

**Comment by sonsofabraxas** [comment]
Sure.

> 
> 
> As this sounds like a desktop app issue, would you be open to re-opening this issue in the desktop app repo https://github.com/mattermost/desktop/issues?

**Comment by justinegeffen** [comment]
Confirmed [issue has been opened in the recommended repo](https://github.com/mattermost/desktop/issues/1336). Closing.
