### ISSUE TITLE
Improve feature deprecation in Configuration Settings

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#3729]
Under [Allow which users to delete messages](https://docs.mattermost.com/administration/config-settings.html?highlight=config%20settings#allow-which-users-to-delete-messages) and [Allow users to edit their messages](https://docs.mattermost.com/administration/config-settings.html?highlight=config%20settings#allow-users-to-edit-their-messages) it says "Removed in June 16, 2018 release."

This could be improved by linking to the [Advanced Permissions documentation](https://docs.mattermost.com/deployment/advanced-permissions.html) as that replaced the functionality of those configuration options for the various places this occurs on the [config settings page.](https://docs.mattermost.com/administration/config-settings.html)

**Comment by fakela** [comment]
@justinegeffen I would love to work on this

**Comment by justinegeffen** [comment]
@fakela, apologies for the delay. You are absolutely welcome to take this one. :)

**Comment by justinegeffen** [comment]
Hi @fakela, I've just done this update, my apologies - I had too many tabs open and started the work without double-checking the comments. Sorry about that!
