### ISSUE TITLE
Kubernetes Deployment is not working

### ISSUE THREAD

**Issue by rajashekhargundeti** [mattermost/docs#3735]
Hi,
I'm following https://docs.mattermost.com/install/install-kubernetes.html guide to install on kubernetes.

it is failing while executing the following command, with error of unable to create CustomResourceDefinitions.
kubectl apply -n mattermost-operator -f https://raw.githubusercontent.com/mattermost/mattermost-operator/master/docs/mattermost-operator/mattermost-operator.yaml

rajashekhar_gundeti@Azure:~/clouddrive/mattermost$ kubectl apply -n mattermost-operator -f https://raw.githubusercontent.com/mattermost/mattermost-operator/master/docs/mattermost-operator/mattermost-operator.yaml
serviceaccount/mattermost-operator unchanged
clusterrole.rbac.authorization.k8s.io/mattermost-operator configured
clusterrolebinding.rbac.authorization.k8s.io/mattermost-operator unchanged
deployment.apps/mattermost-operator configured
unable to recognize "https://raw.githubusercontent.com/mattermost/mattermost-operator/master/docs/mattermost-operator/mattermost-operator.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "https://raw.githubusercontent.com/mattermost/mattermost-operator/master/docs/mattermost-operator/mattermost-operator.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"

Please help me here.

**Comment by justinegeffen** [comment]
Hi @rajashekhargundeti. I'm sorry you're having this issue, and I'd like to recommend posting in our [Kubernetes channel](https://community.mattermost.com/core/channels/kubernetes) on our community server if you haven't already. You can also post in our forum, in the [Troubleshooting section](https://forum.mattermost.org/c/trouble-shoot/16).

You are also welcome to update the documentation with your findings and submit a PR. We welcome community feedback on the docs! :)

**Comment by justinegeffen** [comment]
Hi @rajashekhargundeti. I wanted to follow up on this and find out whether you were able to resolve the issue you were having. :)

**Comment by cwarnermm** [comment]
Closing ticket
