### ISSUE TITLE
Clarify how to generate users.json for SAML ID migration

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#3741]
Relevant docs page: https://docs.mattermost.com/administration/command-line-tools.html#mattermost-user-migrate-auth

To migrate users to SAML admins have to generate a users.json file and we have code samples in (maybe) Python to generate these JSON files.

We should provide clearer instructions for how to use the code, including the language and a link to how to set up an environment to run them and how to find the required URLs and API tokens for OneLogin, Okta, and ADFS for Windows Server 2012, 2012R2, and 2016.

**Comment by justinegeffen** [comment]
Thanks, @icelander! I'm not sure whether this will be migrated to mmctl. I'm tagging @mgdelacroix for that and @faase as he's the technical writer for mmctl.

**Comment by cwarnermm** [comment]
@icelander - Would you be open to drafting a docs PR with these updates?
