### ISSUE TITLE
Request for Documentation: Kubernetes Operator and HA configuration

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3752]
Mattermost user `katie.wiersgalla` from https://community-daily.mattermost.com has requested the following be documented:

```
You are correct that the Mattermost server clustering functionality is currently only part of E20: https://docs.mattermost.com/deployment/cluster.html

Obviously, k8s does a great job of running multiple Mattermost servers with `>1` replicas, but you will encounter the message sync issues you noted unless clustering is supported and enabled.
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/1jhbjqtpbtribxt88krg9f3qur).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
Comprehensive Clustering documentation is available. Closing ticket.
