### ISSUE TITLE
Request for Documentation: Create Forum post: Mattermost GitLab plugin vs. Mattermost integration in GitLab

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3778]
Mattermost user `justine.geffen` from https://community-daily.mattermost.com has requested the following be documented:

```
Hello, I have a question regarding mattermost integration in gitlab vs [mattermost-plugin-gitlab](https://github.com/mattermost/mattermost-plugin-gitlab).
I have setup a local Gitlab community edition instance, which comes with integrated mattermost server. Gitlab also includes a built-in integration with Mattermost. Using incoming webhooks it allows Gitlab to e.g. notify about merge requests and ci job failures, etc.

Does [mattermost-plugin-gitlab](https://github.com/mattermost/mattermost-plugin-gitlab) offer more features than the already built-in functionality?
Can I run both in parallel?
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/xzfbn84ytjyq3konpe9pysi97w).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by philipreimer** [comment]
@justinegeffen I had also created [an issue in mattemost-plugin-github repository](https://github.com/mattermost/mattermost-plugin-gitlab/issues/187).

**Comment by cwarnermm** [comment]
@aaronrothschild - We could use your help with this one. Are you open to drafting a content update?
