### ISSUE TITLE
Add guide for RHEL 8

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#3800]
RHEL 8 has been out for a while, there should be a guide on how to install Mattermost on it.

**Comment by Malvika18** [comment]
Hey i wanna contribute to this can you please guide me.

**Comment by svelle** [comment]
Hi @Malvika18,
thank you for you interest in contributing.

So basically the basic steps for this would be to setup RHEL 8 on a server or virtual machine and then going through each of the steps in [this guide](https://docs.mattermost.com/install/install-rhel-7.html) fixing every step that doesn't work and/or adding needed steps to get Mattermost running on RHEL 8.

Feel free to post here or on our [Community Server](https://community.mattermost.com) if you need help with any of the steps.

Cheers!

**Comment by justinegeffen** [comment]
Hi @Malvika18. To add to @svelle's reply, please let us know if you encounter any blockers in terms of creating the new content. The README of this repo has instructions around how to get started, and links to our style guide. :)

**Comment by Ganzabahl** [comment]
Hi guys,
I started on this one and are almost in goal on Centos 8.2. The RHEL7 can roughly be used, but there are still a lot of small differences. I just lack the last part, before I am ready to focus on the documentation. I hope this one is still up for grabs?

**Comment by justinegeffen** [comment]
Hi @Ganzabahl! As far as I know there hasn't been a PR for this yet! Tagging @Malvika18 for confirmation. :)

**Comment by Ganzabahl** [comment]
I think I'm more or less done and only need to review the RHEL 8 addition now (ironically have issues with sphinx with building offline).

**Comment by Ganzabahl** [comment]
I finished testing and I'm pretty happy with it. PR https://github.com/mattermost/docs/pull/3976 

Sorry @svelle and @Malvika18  if you are still spending time on this. I just figured you left it untouched since there was no updates for 8 days
