### ISSUE TITLE
Request for Documentation: In environments with separate App and Job servers, the Job server should still be configured to "RunScheduler"

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3845]
Mattermost user `stu.doherty` from https://community-daily.mattermost.com has requested the following be documented:

```
I believe we have guidance in a few places in our docs on how to run high scale Mattermost clusters where the Application and Job roles are separated on different hosts.  We previously directed customers to set `RunScheduler` to false on the job servers.  The issue this introduces is that a JobServer could end up being designated as the cluster leader, and if this happens then the scheduling of jobs will no longer happen as the "Leader" is the only node that can actually run the schedule.
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/4w81dfccwin53nmqpimeo8no3h).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by justinegeffen** [comment]
Thanks, @sadohert. Would you be open to sharing some of the doc links for reference and assisting with the changes? :)

**Comment by sadohert** [comment]
Hi @justinegeffen  - Sorry for the delay.  I just looked at a few of the docs points and it appears we had already done updates related to this 9 months ago:

https://docs.mattermost.com/deployment/cluster.html#job-server
https://docs.mattermost.com/administration/config-settings.html#jobs

"When running Mattermost in High Availablity mode, this setting should always be enabled."

I didn't see this (the original customer was ssetup before those docs updated).  I think we may want to rework the messagint to essentially frame the "RunScheduler" property as a "Do not change from `true` unless you really know what you're doing"...

**Comment by justinegeffen** [comment]
Docs done.
