### ISSUE TITLE
Is migrating from Slack idempotent?

### ISSUE THREAD

**Issue by huyz** [mattermost/docs#3847]
https://github.com/mattermost/docs/blob/master/source/administration/migrating.rst says
> The import is not idempotent, which means that duplicate posts are created if you import the same data more than once.

However, https://github.com/mattermost/docs/blob/master/source/deployment/bulk-loading-about.rst says:
> The bulk loading command is interruptible and idempotent
> If the import is interrupted for any reason, it continues from where it left off the next time you run it. You can run the command repeatedly with the same data file, and the data is imported only once. From v5.20, posts with matching timestamps to incoming posts will have their attachments replaced by the incoming data. Prior to v5.20 any updates to posts with matching timestamps were appended to older posts.

So I'm not sure what will happen if I run the import twice.  Am I conflating the two steps?  Or is it just that the docs for migrating.rst need to be updated for v5.20?

**Comment by justinegeffen** [comment]
Hi @huyz. Thanks for picking this up! The docs have been updated. Please let me know if they answer your question. :)

**Comment by huyz** [comment]
@justinegeffen Great, good to know that mmetl is the way forward now.

**Comment by justinegeffen** [comment]
Glad I could help, @huyz! Please let us know if you have any questions or feedback.
