### ISSUE TITLE
Request for Documentation: Adapt our recommendations on the systemD service file

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3857]
Mattermost user `stu.doherty` from https://community-daily.mattermost.com has requested the following be documented:

```
Can you try adding `KillMode=mixed` under the `[Service]` section and see if anything changes?

See conversation in Ask R&D
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/umqni58adpbt8prbohpd9qawuo).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by puranjaymohan** [comment]
I want to work on this, please assign it to me and also help me get started.
Thanks

**Comment by yash2189** [comment]
@justinegeffen Can I work on this if it's available?

**Comment by justinegeffen** [comment]
Thanks, @yash2189! I assigned it to @puranjaymohan as requested but am not sure of the current status. @puranjaymohan, would you be open to sharing where you are with this and whether you need any help? :)

**Comment by ewwollesen** [comment]
@cwarnermm @justinegeffen Even though this was assigned to someone else it hadn't been updated since October so I just went ahead and grabbed it and submitted a PR.

**Comment by cwarnermm** [comment]
Thanks, @ewwollesen! Closing.
