### ISSUE TITLE
Request for Documentation: Improve the instructions in this section to include sample screen shots and detailed steps

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3859]
Mattermost user `ahmad.danial` from https://community.mattermost.com has requested the following be documented:

```
Got it. I believe that we can improve the instruction in the [Bot Account Creation](https://developers.mattermost.com/integrate/admin-guide/admin-bot-accounts/) section here. 

> Add the bot account to teams and channels you want it to interact in.

For example.

1. Navigate to **Invite** people
2. Under **Add or Invite People**, add the bot account and click **Invite Members**

Screen shots can be added for clarity.
```

See the original post [here](https://community.mattermost.com/_redirect/pl/h458ywytgfd5mekcwm3wiju8wo).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by ng29** [comment]
Heya Jespino,

Can I got more clearly what needs to be achieved here so that I can pick it up 👍 

Cheers,

**Comment by ewwollesen** [comment]
I can work on this for the Docathon.

**Comment by justinegeffen** [comment]
Hi @ewwollesen! Just a note that these docs have been moved to a new location: https://developers.mattermost.com/integrate/admin-guide/admin-bot-accounts/. 

This doc set uses Hugo and is written in Markdown. For this issue you shouldn't run into any technical issues but if you do please let me know! :)

**Comment by ewwollesen** [comment]
@justinegeffen 
So I don't need to bother with updating this page? https://docs.mattermost.com/developer/bot-accounts.html#bot-account-creation

Or should I do both?

**Comment by justinegeffen** [comment]
They're the same page, and the one on the docs site has been deprecated (but not deleted), so you can ignore https://docs.mattermost.com/developer/bot-accounts.html#bot-account-creation and update https://developers.mattermost.com/integrate/admin-guide/admin-bot-accounts/. :)

Thank you!

**Comment by ewwollesen** [comment]
@justinegeffen @cwarnermm I submitted a [PR](https://github.com/mattermost/mattermost-developer-documentation/pull/867) for this over in the developer docs repo.

**Comment by cwarnermm** [comment]
Thanks, @ewwollesen! Closing!
