### ISSUE TITLE
Request for Documentation: ElasticSearch FAQs

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3860]
Mattermost user `katie.wiersgalla` from https://community-daily.mattermost.com has requested the following be documented:

```
# Questions on ElasticSearch

3 Questions from a customer on our Elastic integration:

1.  What kind of authentication do we use?  Is it basic?  Do we go through a login flow to get a token?
2.  What is the customer sniffing configuration about? "Enable Cluster Sniffing"  Is that some kind of ElasticSearch related sniffing?
3.  What is the primary driver for needing the ICU Analyzer Plugin?

Thanks in advance.  
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/h8tugwa18f8p9qy8bm93q8musc).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by fakela** [comment]
@justinegeffen I will work on this 😊

**Comment by cwarnermm** [comment]
@wiersgallak - Which member of the PM would be an ideal person to work to get these answers documented?

**Comment by wiersgallak** [comment]
@cwarnermm Please work with Neil Barnett

**Comment by cwarnermm** [comment]
@nab-77 - I could use your help with this elasticsearch docs request.

**Comment by nab-77** [comment]
No worries. Let me look into the items above.
