### ISSUE TITLE
Request for Documentation: Deploy Mattermost on Docker (regarding "sudo chown -R 2000:2000")

### ISSUE THREAD

**Issue by R8s6** [mattermost/docs#3883]
In the [docker-compose installation doc](https://docs.mattermost.com/install/prod-docker.html#), under "3. Deploy the Mattermost Docker setup by running:", we have:

```
sudo chown -R 2000:2000 ./volumes/app/mattermost/
```

Is this assuming the user:group of the user is 2000:2000, or does it have to be 2000:2000?

For example, should people check with this first:
`$ id my_username`, which is usually `1000:1000`, then replace the guide with:
```
sudo chown -R 1000:1000 ./volumes/app/mattermost/
```
?

Thanks!

**Comment by justinegeffen** [comment]
Hi @R8s6. Thanks for raising this. The documentation for Docker is maintained by our community, and is not yet officially supported by Mattermost. With that in mind, I recommend posting in the [Mattermost forum](forum.mattermost.org). This opens the question up to our community and provides valuable feedback to all Mattermost users. If you're open to updating the docs with the feedback, that would be awesome. :)

**Comment by avats-dev** [comment]
@justinegeffen I want to work on this. UID is different for everyone (along with GID), and so it is user dependent, default being `1000:1000` in most cases. Should I update the docs and open a PR?

**Comment by justinegeffen** [comment]
Hi @avats-dev! Thank you so much for offering to update the docs. That would be highly appreciated. :) I have also replied to the other ticket, thanks for the reminder.

Please let me know if I can assist with anything! :)

**Comment by avats-dev** [comment]
Thanks @justinegeffen , I will get started on this one.

**Comment by R8s6** [comment]
Hi,

Just to follow up on this case, will it be updated? Thanks!

**Comment by justinegeffen** [comment]
Hi @R8s6! Thanks for following up on this. The offer to update the docs was made a while back, so I'd like to confirm with @avats-dev whether there is still an opportunity for them to do the update. If not, it will remain as a Help Wanted issue for the community. Would you be open to doing the update?
