### ISSUE TITLE
More Options in Post Formatting

### ISSUE THREAD

**Issue by mspisarev** [mattermost/docs#3893]
If i click Enable Post Formatting

"If enabled, posts will be formatted to create links, show emoji, style the text, and add line breaks. By default, this setting is enabled."

But i want only links to be formatted, no smiles  & emojies.
Its no way to do it

**Comment by justinegeffen** [comment]
Hi @mspisarev. Thanks for raising this. From what I understand, you'd like to only be able to format links so they appear as hyperlinks, but have emojis appear in their unformatted form?

I've put together examples of formatting on and formatting off:

With post formatting on, this is what I see when I use Markdown formatting:

<img width="739" alt="Screen Shot 2020-09-12 at 13 21 26" src="https://user-images.githubusercontent.com/4223530/92994488-df163f80-f4fa-11ea-955b-112864f5f5ba.png">

This is the same post with post formatting turned off:

<img width="607" alt="Screen Shot 2020-09-12 at 13 21 13" src="https://user-images.githubusercontent.com/4223530/92994499-f05f4c00-f4fa-11ea-82bf-68dacc5fb196.png">

Let me know if this is what you're looking to do. You're also welcome to post on the [forum](forum.mattermost.org) where one of our community members may be able to assist you. :)

**Comment by justinegeffen** [comment]
Hi @mspisarev! I wanted to follow up on this and find out whether you've been able to find the information you needed. :)

**Comment by mspisarev** [comment]
Hi!

Yes, it'll be great to set only link or only emos. Separetly from each
other. For me - i want for work to see links, but not emos.

Thank you!

сб, 12 сент. 2020 г., 14:38 Justine Geffen <notifications@github.com>:

**Comment by justinegeffen** [comment]
Thanks for clarifying, @mspisarev. I recommend posting your suggestion on [uservoice](https://mattermost.uservoice.com/forums/306457-general) so others can see and vote on it. :)
