### ISSUE TITLE
LATIN1 DB encoding error

### ISSUE THREAD

**Issue by DavidePrincipi** [mattermost/docs#3943]
I want to insert an € (euro sign) in a chat message text, but I get an error:

![immagine](https://user-images.githubusercontent.com/2920838/94421627-21d84880-0186-11eb-8790-17a03544e5ad.png)

In `mattermost.log`

```json
{"level":"error","ts":1601288852.6284842,"caller":"mlog/log.go:190","msg":"Unable to save the Post.","path":"/api/v4/posts","request_id":"579m3tr71pn9dq6hd5uihw46nr","ip_addr":"127.0.0.1","user_id":"mc4xjqo6rpgdbfbr5o3daumbow","method":"POST","err_where":"SqlPostStore.Save","http_code":500,"err_details":"pq: character with byte sequence 0xe2 0x82 0xac in encoding \"UTF8\" has no equivalent in encoding \"LATIN1\""}
```

What I did is just running this (weird) command in a CentOS 7 system:

    localectl set-locale LANG=en_US.iso88591

...then installed PostgreSQL 12 and run `CREATE DATABASE mattermost;` (full story here https://github.com/NethServer/dev/issues/6286).

Actual database encoding information is:

```
[root@vm5 ~]# su - postgres  -c "scl enable rh-postgresql12 -- psql --port=55434"
psql (12.1)
Type "help" for help.

postgres=# \l
                                     List of databases
    Name    |  Owner   | Encoding |    Collate     |     Ctype      |   Access privileges   
------------+----------+----------+----------------+----------------+-----------------------
 mattermost | postgres | LATIN1   | en_US.iso88591 | en_US.iso88591 | =Tc/postgres         +
            |          |          |                |                | postgres=CTc/postgres+
            |          |          |                |                | mattuser=CTc/postgres
 postgres   | postgres | LATIN1   | en_US.iso88591 | en_US.iso88591 | 
 template0  | postgres | LATIN1   | en_US.iso88591 | en_US.iso88591 | =c/postgres          +
            |          |          |                |                | postgres=CTc/postgres
 template1  | postgres | LATIN1   | en_US.iso88591 | en_US.iso88591 | =c/postgres          +
            |          |          |                |                | postgres=CTc/postgres
(4 rows)
```

What I expect is to get an error somewhere (as the system encoding is not fully functional) and to see a big warning in the docs: https://docs.mattermost.com/install/install-rhel-7.html#installing-postgresql-database

**Comment by justinegeffen** [comment]
Hi @DavidePrincipi. Thank you for raising this - I apologize for not having responded sooner. I see the linked bug report has been closed and it looks like the bug is verified. Would you be open to confirming whether the issue has been resolved? 

cc: @svelle

**Comment by DavidePrincipi** [comment]
Hi @justinegeffen thank you for the heads up. I confirm the bug has been fixed in the Mattermost installation script of NethServer by the [linked patch](https://github.com/NethServer/nethserver-mattermost/pull/56/files#diff-5382ec4bbe9fae01c094f3cf6ea8e2ca25def54554ec26c9f25ac50e80efc4f1). As said, I'd expect a similar command to appear in the Mattermost docs, at least saying that UTF-8 is a requirement for the DB encoding options.

**Comment by justinegeffen** [comment]
Thanks, @DavidePrincipi! Would you be open to updating the Mattermost docs with your feedback? :)
