### ISSUE TITLE
No Channels under User Management

### ISSUE THREAD

**Issue by Dystharia** [mattermost/docs#3944]
I just started to use Mattermost, but directly run into a problem.
The docs say: 
"Configure a channel so that members can post/reply/react but guests can only read and react.
 1.  Navigate to System Console > User Management > Channels."

But under User Management I only got Users. I created 3 Channels already, so there should be something or what is the problem here?

Best regards

**Comment by amyblais** [comment]
@Dystharia Which documentation page did you read this in? Are you on Team Edition or Enterprise Edition?

**Comment by Dystharia** [comment]
@amyblais I don't know which one this is:
[Link to the Page](https://docs.mattermost.com/deployment/team-channel-management.html)

**Comment by amyblais** [comment]
Channel moderation is currently available in Enterprise Edition.

You can check your Edition by going to Main Menu > About Mattermost. It should say whether it's Team or Enterprise.

**Comment by Dystharia** [comment]
Oh okay. Thanks for the Information!
