### ISSUE TITLE
Request for Documentation: Add documentation for the `ElasticsearchSettings.IndexPrefix` setting

### ISSUE THREAD

**Issue by grundleborg** [mattermost/docs#3948]
By setting this, all ES indexes created by MM are given the provided prefix. This will make it possible for two MM installs to share an ES cluster by setting different prefixes so the index names don't collide.

**Comment by justinegeffen** [comment]
Thanks, @grundleborg!

**Comment by yash2189** [comment]
Hello @grundleborg Can you please tell me what needs to be done for this issue. I would like to contribute.

**Comment by justinegeffen** [comment]
Hi @yash2189. I believe the content that needs to be updated is this: **https://docs.mattermost.com/administration/config-settings.html#index-prefix**. The content does exist but it looks like this is an enhancement to further explain the usage of the setting.

@grundleborg, is that accurate?

**Comment by yash2189** [comment]
> Hi @yash2189. I believe the content that needs to be updated is this: **https://docs.mattermost.com/administration/config-settings.html#index-prefix**. The content does exist but it looks like this is an enhancement to further explain the usage of the setting.
> 
So will this issue be resolved by adding a note below the `Index Prefix`?

**Comment by justinegeffen** [comment]
Yes, I think the suggested content would be appended to the current content. A note could work or just a line break with a new sentence. It's completely up to you - whatever option you take can be discussed in the PR and changed if needed. :)

**Comment by yash2189** [comment]
sure @justinegeffen I'll add the suggested content. Can this be taken under Hacktoberfest or is the label removed?

**Comment by justinegeffen** [comment]
Thanks, @yash2189. Would you be open to sharing the PR link here so we can link the issue and the PR? Thank you!

**Comment by yash2189** [comment]
Sure I am working on the same @justinegeffen.

**Comment by yash2189** [comment]
@justinegeffen Can you please review my PR #4021
