### ISSUE TITLE
How to make rst files after making changes in HTML files ?

### ISSUE THREAD

**Issue by PranoveAB** [mattermost/docs#3962]
Hello,

I was able to build HTML files from the repo after using `make html` . Now that I have made changes, I need to build it back to .rst to push and compare changes. How do I do it??

**Comment by justinegeffen** [comment]
Hi @PranoveAB! Would you be open to sharing the process you followed to edit the docs that you built? For example, are you working locally, and if so, are you using an authoring tool such as Atom?

In most cases, if you're using a local editor you'd write the docs in the editor and running ``make html`` just generates the HTML files. It doesn't change the content that's in the editor to HTML. :) 

There are a few possible suggestions I can think of but they apply in different use cases. Any information you can provide in terms of your process and local environment will be great.

If you could also confirm whether you forked the repo that'd be great. :)

**Comment by justinegeffen** [comment]
You're also welcome to come and discuss this in the [Documentation channel](https://community.mattermost.com/core/channels/documentation) as this type of discussion can be really helpful to the wider community. :)

**Comment by justinegeffen** [comment]
Hi @PranoveAB. Wanted to follow up on this and find out whether you've been able to resolve your question? :)
