### ISSUE TITLE
Feature Request: allow for conversation threads to be collapsed

### ISSUE THREAD

**Issue by joeyfb** [mattermost/docs#3964]
Searching through open issues and upcoming features I saw no mention of conversation threading. Other services (namely slack), have the ability to reply to a given comment and get those replies hidden within a thread of that comment.

It can help for large teams where lots of discussion happens on main channel, for example a school general chat where lots of announcements occur and replies to announcements. Replies to big topics on mattermost end up just getting lost in a sea of comments and can discourage talk because users don't want to disrupt discussions.

If it's a design choice, I know services like Discord just allow quoting instead of replying in a thread, could it be added as a server level toggle to let large servers have that streamlined comment experience?

Thank you for the time!
Joey

**Comment by justinegeffen** [comment]
Hi @joeyfb! Thanks for raising this issue. We have a very active channel dedicated to the [Folded Reply Threads](https://community.mattermost.com/core/channels/folded-reply-threads) feature. The PM for the feature, @esethna, has provided the project plan in the channel header and is really responsive to discussions and questions. 

If you'd be open to sharing some of the links you used which didn't answer your question, I'd be happy to take a look and see where we can improve them and add the correct information. :)

**Comment by joeyfb** [comment]
That's pretty clear! Sorry for looking/asking in the wrong place and thank you so much for taking the time to respond!

**Comment by justinegeffen** [comment]
Awesome, that's great news. :) 

There's never a wrong place to ask questions - I'm very glad I could help!
