### ISSUE TITLE
Add Hindi documentation to international documentation page

### ISSUE THREAD

**Issue by kichloo** [mattermost/docs#3974]
@jespino I saw an issue regarding the same in another language, so adding the translation for Hindi language would cater to a larger audience. I can work on this issue

**Comment by justinegeffen** [comment]
Hi @kichloo! Thanks for opening this issue. We really appreciate you offering to do this. Would you be open to detailing which issue you saw and which guides you plan to translate? We have some other translations pending so it'd be great to know what's coming down the line. :)

**Comment by kichloo** [comment]
@justinegeffen Reference issue: #3664 
Regarding the type of file, can you paste some links of the files to be translated? I will choose a file and will do it with 100% accuracy and efficiency.

**Comment by kichloo** [comment]
Havent got any reply yet. Kindly reply regarding the same. And if not interested, kindly tell so that I do not work on issue which is not to be considered by the organization.

**Comment by justinegeffen** [comment]
Hi @kichloo. I apologize for the delay! Here are the two PRs that are currently open https://github.com/mattermost/docs/pull/3457 and https://github.com/mattermost/docs/pull/3664. Both PRs have an extensive collection of files as they've translated the Getting Started Guide.

In terms of your contribution, I recommend joining the [i18n channel](https://community.mattermost.com/core/channels/localization) on our community server. You'll find documentation related to processes as well as information about the tools we use. 

We really appreciate your interest and I look forward to your PR. :)

**Comment by kichloo** [comment]
@justinegeffen Thanks for reverting. I searched through the files and found [Readme.md](https://github.com/mattermost/mattermost-developer-documentation/blob/master/README.md) a workable file to start the documentation in Hindi for the organization. Kindly tell so that I can start working on this same.

**Comment by justinegeffen** [comment]
Hi, @kichloo! Thanks for getting back to me. One suggestion I can offer is that you post your proposal in the i18n channel if you haven't already. The reason for this is the channel contains all the information you need to get started with translations in terms of the tools and processes we use. In addition, the community members could also assist you in terms of the next steps once you've completed your proposed work (for example, review process, publishing the content etc). 

The file you've linked is a great start, however it's in a separate repository to this one and I am not certain what the translation process is or whether we have a requirement for it to be translated. 

The [Getting Started guide](https://docs.mattermost.com/guides/administrator.html#getting-started) is one I'd recommend looking at in terms of this project. 

All that said, I know the localization community are extremely happy to help and answer questions around the best way to get started so I definitely recommend joining that channel first. 

Hope this helps! :)

**Comment by kichloo** [comment]
@justinegeffen Joined the community. And just a question, you want me to translate the whole  `Getting Started guide` or the subsequent links such as 

- Light Install Guide

1. Installation
2. Add Users
3. Create a Notifications Hub

**Comment by justinegeffen** [comment]
In the example you've provided, those links are sub-headings within a single article so if you open https://docs.mattermost.com/help/getting-started/light-install.html you'll see that it's all on one page. I'd say that that article is a great place to start. :)

**Comment by kichloo** [comment]
@justinegeffen Ok. I will start translating this page. Also, since this month is Hacktoberfest, this organization is participating Hacktoberfest? Also, are there any prerequisites to be completed before starting the contribution like DCO,CLA etc.

**Comment by justinegeffen** [comment]
We are participating in Hacktoberfest, and when you submit a PR you need to sign the CLA. The information around the CLA is posted when you submit your PR. :) @jasonblais can confirm that your PR would be included as a Hacktoberfest contribution.

**Comment by jasonblais** [comment]
@kichloo Yes, we are participating in Hacktoberfest and your PR would count towards the event. Thanks for your interest in contributing!

**Comment by kichloo** [comment]
@justinegeffen Now, I have started the translation. And wanted to know that should the software names such as Ubuntu be written in English/ Hindi, whichever seems good with the organization.

**Comment by justinegeffen** [comment]
Thanks, @kichloo. We don't currently have a preference as the translations have primarily been in-product. We're very open to working with the community to put together a standard for translating the documentation which would include naming conventions. One option is to raise this in the i18n channel as there are very experienced community members who may have considered this previously and have feedback to share. :)

**Comment by kichloo** [comment]
@justinegeffen No problem. First will make the PR. Then, will make the suggested changes, if any.

**Comment by wget** [comment]
@jasonblais I see the others PR are ready to get merged for a long time and I have been quite a blocker here since I was disagreeing at that time with you to translate these guides /outside/ any translation tool.

Since I changed my mind about this, please revive the other 2 PRs o that they get can pass the test and be finally merged ;)

I'm in a catchup period right now and I see the CI build failing constantly as notifications in my mail box ;)

**Comment by jasonblais** [comment]
Hi @wget, there is in fact some work left to fully support translated documentation, so the other two PRs haven't yet been merged. But @justinegeffen is actively working on it.

**Comment by wget** [comment]
Ah ok ;) I'll mute these PRs for now then ;) Note: I won't be receiving any new notification unless if you mention me there explicitly ;)

**Comment by justinegeffen** [comment]
Hi @wget! I've also been a blocker for this and am going to be reviving them as Jason mentioned. I've moved my comments to [this thread](https://community.mattermost.com/core/pl/r7syteuic7bm5e5bgia44q4kcw) for visibility.

**Comment by kichloo** [comment]
@justinegeffen @jasonblais Kindly check the PR
