### ISSUE TITLE
Upgrade_mattermost.sh `find` command fails to delete non-empty directories in opt/mattermost dir

### ISSUE THREAD

**Issue by Ant0wan** [mattermost/docs#3983]
I am having troubles deploying new mattermost version using the upgrade script.
This issue is not a big deal but would be great to have it fixed.

In cases directories in path `/opt/mattermost` are not empty the folowwing: 
```
# Clean up mattermost directory
find "${mattermostdir}" -mindepth 1 -maxdepth 1 -not \( -path "${mattermostdir}/config" -o -path "${mattermostdir}/logs" -o -path "${mattermostdir}/plugins" -o -path "${mattermostdir}/data" \) -delete;
```
will fail to delete the no-empty directories and then avorting script because of the `set -e` enabled.

If you don't mind, I would suggest we replace `-delete` by the `-exec rm -rf {} \;` argument, therefore forcing the delete.

**Comment by justinegeffen** [comment]
Thanks for raising this, @Ant0wan. @JtheBAB is the maintainer of the upgrade script doc, so I have looped them in here.

**Comment by Ant0wan** [comment]
Not sure whether this is relevant in general though.
Thanks a lot for the existing script.
We are upgrading mattermost servers at the company , still having some troubles with the script.
I was about making our own version. I do not know whether you would like me to share what worked out for us.
Anyway - if you need - we have time to work on it. Many thanks
