### ISSUE TITLE
Adding Table of Content to Readme.md

### ISSUE THREAD

**Issue by ng29** [mattermost/docs#3993]
The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.

I would like to work on this issue.

**Comment by justinegeffen** [comment]
Hi @ng29! Thank you for raising this issue. Would you be open to elaborating on the proposed changes? One option is to open a PR with your suggestion, so we can collaborate on it. Let me know if you have any questions around the process to do so. :)

**Comment by ng29** [comment]
> Hi @ng29! Thank you for raising this issue. Would you be open to elaborating on the proposed changes? One option is to open a PR with your suggestion, so we can collaborate on it. Let me know if you have any questions around the process to do so. :)

Hey @justinegeffen , iahve proposed a pr with my idea for table of contents, please review and suggest changes if required.


Cheers
