### ISSUE TITLE
Request for Documentation: Document that Elasticsearch progress bar can be inaccurate for large post tables

### ISSUE THREAD

**Issue by grundleborg** [mattermost/docs#4000]
For installs with large numbers of posts (typically in excess of 1 million but not strictly defined) the progress percentage for Elasticsearch reindexing can be inaccurate, in particular it may stay at 99% for a long time.

**Comment by yash2189** [comment]
Hi I'm new to opensource. Can you please tell me what is to be done for this particular issue?

**Comment by yash2189** [comment]
@grundleborg can you please tell me what is to be done for this issue?

**Comment by grundleborg** [comment]
@justinegeffen I see you added an "up for grabs" label to this - any chance you can assist @yash2189 with getting set up to contribute to the docs?

**Comment by justinegeffen** [comment]
Thanks, @grundleborg! I definitely can.

Hi, @yash2189! Thanks for your interest in this issue. The documentation that needs to be updated is the [Elasticsearch page](https://docs.mattermost.com/deployment/elasticsearch.html). From what it looks like, @grundleborg is suggesting adding a disclaimer around the progress bar for large deployments when indexing.

To get started with contributing to the docs, take a look at the [README.md file](https://github.com/mattermost/docs) as it contains all the instructions to get started with submitting your first PR.

@grundleborg, one question I have is whether there are remediation steps for this issue or something the user needs to do in order to prevent/mitigate it?

**Comment by yash2189** [comment]
I would definitely work on this issue! Please tell me if there's anything more to add

**Comment by justinegeffen** [comment]
Thanks, @yash2189! From what I understand, the progress bar would be in the Mattermost UI when using Elasticsearch to index. In this instance I'd sync up with @grundleborg and confirm whether this is the case. If so, I'd consider adding a note to the docs along the lines of:

"If your installation has a large number of posts (typically in excess of 1 million but not strictly defined) the reindexing progress percentage may stay at 99% for a long time." > followed by whatever remediation steps are recommended. 

Hope this helps answer your question. :)

**Comment by grundleborg** [comment]
> @grundleborg, one question I have is whether there are remediation steps for this issue or something the user needs to do in order to prevent/mitigate it?

there's nothing the user can do to mitigate it - it's just a known limitation of the feature as implemented currently which they may run into. I've had questions about it from users, and so would like the docs to note this so that they can see it's "expected behaviour".

**Comment by justinegeffen** [comment]
Perfect, thank you!

**Comment by yash2189** [comment]
Can I work on this @justinegeffen ?

**Comment by justinegeffen** [comment]
You definitely can, thank you! :)

**Comment by yash2189** [comment]
Thanks @justinegeffen I have started and will raise a PR shortly

**Comment by yash2189** [comment]
Hi @grundleborg @justinegeffen Please review my PR  #4011  and let me know if there are any changes.

**Comment by justinegeffen** [comment]
Hi @yash2189. I'll take a look shortly.

You can disregard the deploy error, as it relates to our preview server build which unfortunately doesn't apply to forked repos. The CLA error can be remedied by signing the CLA - the steps are provided in the PR just beneath your commit message. :)

**Comment by yash2189** [comment]
@justinegeffen I have made the changes , please review the same.
Thanks
