### ISSUE TITLE
Theme examples page has themes that are not compatible with newer versions of the server

### ISSUE THREAD

**Issue by esethna** [mattermost/docs#4020]
We need to update the sharable theme codes on this page since they are out of date and some are not compatible anymore. 

https://docs.mattermost.com/help/settings/theme-colors.html

Example issue with incompatibility: https://mattermost.atlassian.net/browse/MM-29631

**Comment by justinegeffen** [comment]
Thanks, @esethna! Would you be open to updating the docs and submitting a PR? Happy to review it once it's ready. :)

**Comment by esethna** [comment]
@justinegeffen done
