### ISSUE TITLE
Upgrade Guide should mention that you may need to set Mattermost account as directory owner again after upgrading

### ISSUE THREAD

**Issue by pmccarthy01** [mattermost/docs#403]
I upgraded to the Enterprise Edition from the Team Edition, and then ran into an issue when uploading the Identity Provider Public Certificate for SAML: https://docs.mattermost.com/deployment/sso-saml-okta.html

It turns out I had to run the following commands after the upgrade, to be able to upload the certificate:

`sudo chown -R mattermost:mattermost /opt/mattermost`
`sudo chmod -R g+w /opt/mattermost`

These are mentioned in the Install documentation, but should probably be mentioned in the Upgrade guide: https://docs.mattermost.com/administration/upgrade.html

**Comment by jasonblais** [comment]
Thanks @pmccarthy01  for the report and very sorry for the delay in the resolution.

#472 has been submitted for review to address the issue you've raised

**Comment by jasonblais** [comment]
#472 has been merged, thanks again @pmccarthy01 for reporting the issue!
