### ISSUE TITLE
Release checklist: Add review of Upgrade Guide and Install Guide each release 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#404]
Propose adding a checklist item for dev to review the upgrade and install guides and make sure we're not missing any steps, e.g. `Dev Meeting review for any missing steps in Upgrade or Install Guides`

Example of something we missed: https://github.com/mattermost/docs/issues/403

**Comment by lfbrock** [comment]
Upgrade guide should already be tested, but added a step to review any changes to install guides + to test upgrade from team edition to enterprise edition

https://github.com/mattermost/docs/pull/466

**Comment by jasonblais** [comment]
#466 has been merged that should resolve the issue, closing
