### ISSUE TITLE
typo in screenshot in documentation is no longer present in latest release; screenshot needs updated

### ISSUE THREAD

**Issue by pmccarthy01** [mattermost/docs#405]
This image, which is used in the documentation, contains a typo that is no longer present in the latest release: https://github.com/mattermost/docs/blob/master/source/images/okta_10_mattermost_basics.PNG

The typo is "Pubilc"

The image needs to be updated with a new screenshot of latest release

**Comment by jasonblais** [comment]
Thanks @pmccarthy01! Fixed with this commit: https://github.com/mattermost/docs/commit/1060e8b4ee967b13bf84afab9c07038764026427

I think it was fixed before SAML was released in v3.2, but it didn't get reflected in the docs. 

Nice catch
