### ISSUE TITLE
Document how to work with SELinux in enforcing mode

### ISSUE THREAD

**Issue by nigelhorne** [mattermost/docs#4101]
This line is missing from [https://docs.mattermost.com/install/install-rhel-8.html](url):

`sudo restorecon -R /opt/mattermost/`

It should come after the line saying

`sudo chmod -R g+w /opt/mattermost`

**Comment by justinegeffen** [comment]
Thank you for letting us know, @nigelhorne! Would you be open to updating the doc and opening a PR for it?
