### ISSUE TITLE
TLS documentation headless machine

### ISSUE THREAD

**Issue by nigelhorne** [mattermost/docs#4102]
The documentation for TLS. [https://docs.mattermost.com/install/config-tls-mattermost.html](url) does not mention how to configure your system on a headless machine (step 1 "System Console > Environment > Web Server") is not available.

**Comment by streamer45** [comment]
Hi @nigelhorne , most System Console fields map one-to-one to settings in `config.json`. You can find the complete list documented in https://docs.mattermost.com/configure/configuration-settings.html. For the specific case you mentioned:

[Listen Address](https://docs.mattermost.com/configure/configuration-settings.html#listen-address) --> `ServiceSettings.ListenAddress`
[Connection Security](https://docs.mattermost.com/configure/configuration-settings.html#connection-security) --> `ServiceSettings.ConnectionSecurity`
[Forward port 80 to 443](https://docs.mattermost.com/configure/configuration-settings.html#forward-port-80-to-443) --> `ServiceSettings.Forward80To443`

To set them you could either manually edit your server's `config.json` or use `mmctl config set` command. More info on how to do that in https://docs.mattermost.com/manage/mmctl-command-line-tool.html#mmctl-config-set.
