### ISSUE TITLE
Making executable mode typo

### ISSUE THREAD

**Issue by nigelhorne** [mattermost/docs#4103]
On [https://docs.mattermost.com/install/install-rhel-8.html](url) there is this typo:

```
Make the service executable.
sudo chmod 664 /etc/systemd/system/mattermost.service
```

The command is correct (you should run that), the point is however that the service file does _not_ need to be executable.

**Comment by justinegeffen** [comment]
Thank you for raising this, @nigelhorne. :) I noted the other issues you raised, which were related to this. If you're open to updating the docs with your feedback that'd be extremely helpful. Let me know if you encounter any problems. :)

**Comment by ewwollesen** [comment]
I could grab this one.
