### ISSUE TITLE
Request for Documentation: Hi Team, in Allow untrusted internal connections is the whitelist based on DNS resolution?

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#4106]
Mattermost user `george` from https://community-daily.mattermost.com has requested the following be documented:

```
It depends on the elements in the list. First we match IP addresses and hostnames without even resolving. If that fails we resolve using the local resolver (it means we read the `/etc/hosts` file first) and check for matching CIDR rules. So to answer your question, only CIDR rules will require DNS resolution.
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/yahfyna3ffd7bmpupbxhxgfw6y).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
Documentation updated via: https://github.com/mattermost/docs/pull/4327
