### ISSUE TITLE
Developer Setup omits installation of VirtualBox

### ISSUE THREAD

**Issue by scouten** [mattermost/docs#411]
On the [Developer Setup page](https://docs.mattermost.com/developer/developer-setup.html#mac-os-x), under Mac OS X setup, step 1.2 "Start a new docker host" fails as follows:

```sh
$ docker-machine create -d virtualbox dev
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
```

Perhaps there should be a step before this to describe a preferred way to install VirtualBox?

**Comment by yangchen1** [comment]
Hey there @scouten,

I wasn't able to reproduce this on my Mac using a fresh install of Docker and VirtualBox. Hopefully a re-install the latest version of VirtualBox should fix it - your suggestion to include that as a step is great, though. PR created - https://github.com/mattermost/docs/pull/457. Thanks!

**Comment by jasonblais** [comment]
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, please reopen this issue with the relevant information.
