### ISSUE TITLE
Request for Documentation: Clarify the role's/tradeoffs/recommendations on using `mmctl` versus the legacy `cli`

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#4120]
Mattermost user `stu.doherty` from https://community-daily.mattermost.com has requested the following be documented:

```
We need to put appropriate callouts in the docs for `cli` versus `mmctl` (which is in BETA).

E.g.,
* If using CLI with an HA environment admins need to be aware that any configuration changes will require a service restart.  `mmctl` does not have this requirement

We should put clear callouts under the `cli` that `mmctl` is more appropriate for HA environments (assuming this is what we believe)
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/zgzbngpggfrfjp73jafaishpic).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by sadohert** [comment]
Also might need to have a call out on this page:

https://docs.mattermost.com/administration/config-in-database.html

Making note that "HA Deployments should use `mmctl` for modifying configuration" in the cluster... we need to confirm this line, but this is the conclusion I'm coming to.

**Comment by cwarnermm** [comment]
Documentation updated via: https://github.com/mattermost/docs/pull/4326
