### ISSUE TITLE
[Help Wanted] Document how team admins can see their teams' statistics

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#4141]
This is following a conversation with Dennis regarding this feature request: https://mattermost.uservoice.com/forums/306457-general/suggestions/17208602-allow-team-admins-to-see-statistics-for-their-team

Today, this use case can be achieved via new admin roles and mmctl in the scenarios where ALL Team admins were allowed to see ALL team stats (E20 only). An iteration would be needed on New Admin Roles to add more granularity for team admins to only see their own team's statistics.

Below is a description from Dennis on how this can be achieved today:

```
The system admin would have to designate one of the new roles for team admins (likely the read-only admin). Then via mmctl remove everything but the reporting section. Then assign that role manually to team admins. 

It's a work around, but it could hit a good number of use-cases for now.

two important notes:

- it would not be linked to the team admin role, so each time a team admin is demoted/promoted system admin would need to also remove the read-only admin role as a separate step
- they would have access to system level stats (not just their team)
```

**Comment by jasonblais** [comment]
@cwarnermm might be a good early documentation ticket for you to take on? Helps you get more familiar with a few areas of the product including mmctl, permissions system and admin roles.

**Comment by cwarnermm** [comment]
First iteration documentation updated via: https://github.com/mattermost/docs/pull/4247
