### ISSUE TITLE
Request for Documentation: Add required inbound and ports to admin documentation

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#4143]
Mattermost user `paul.rothrock` from https://community.mattermost.com has requested the following be documented:

```
## Inbound Connections
Mattermost Server uses these ports as default when listening to inbound connections:

- Web Application: 8065 (HTTP)
- Cluster Gossip Port: 8074
- Cluster Streaming Port: 8075
- Performance Metrics: 8067

Also, the Mattermost Push Proxy listens for HTTP connections on port 8066.

## Outbound Connections
To connect with integrations Mattermost will try to connect on these ports unless otherwise configured:

- Database
	- MySQL: 3306
	- PostgreSQL: 5432
- LDAP: 389
- S3 File Storage: 443
- Push Notifications: 443
- Mail Notifications: <no default>

In order to receive push notifications, your network must allow traffic on [port 5223 for iOS devices](https://support.apple.com/en-us/HT203609) and [ports 5228-5230 for Android](https://firebase.google.com/docs/cloud-messaging/concept-options#messaging-ports-and-your-firewall).
```

See the original post [here](https://community.mattermost.com/_redirect/pl/gkx3c6x8hpy43q5ff4ph6bjxfc).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by justinegeffen** [comment]
Thanks for this, @icelander! Do you have an idea of where this should live and would you be open to updating the docs with this content?

**Comment by haardikdharma10** [comment]
Hi @cwarnermm, where should this content live? Can you link the necessary file, I'll be happy to update:)

**Comment by cwarnermm** [comment]
Hi @haardikdharma10! We're in the process of gathering these details internally. I've removed the "Help Wanted" and "Up for Grabs" labels accordingly. These port details will likely live here in the product documentation here: https://docs.mattermost.com/overview/architecture.html
