### ISSUE TITLE
FAQ for Mattermost Software terms and licensing has a table that does not render

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#4165]
See https://docs.mattermost.com/overview/faq.html#mattermost-software

![image](https://user-images.githubusercontent.com/13119842/101670486-386e0c00-3a21-11eb-9faa-1b8b29e8d314.png)

There should be a table below the "Mattermost Software" heading. It is there in raw .rst format when editing the GitHub file, so it's likely a formatting error.

https://github.com/mattermost/docs/edit/master/source/overview/faq.rst

**Comment by justinegeffen** [comment]
Thanks, @jasonblais. I've opened a PR.
