### ISSUE TITLE
Request for Documentation: Improve scope documentation for autolink plugin

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#4168]
Mattermost user `jesse.hallam` from https://community-release.mattermost.com has requested the following be documented:

```
I think there's an opportunity to improve the autolink documentation around use of the scope feature, as there's just a single example currently in the docs.
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/dcajb4f45prqfdh1xxy8rwc7uh).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by larkox** [comment]
May I take this one? :smile:
