### ISSUE TITLE
Help Wanted: kubernetes installation doesn't work well with Team version

### ISSUE THREAD

**Issue by Philmod** [mattermost/docs#4234]
This [doc](https://docs.mattermost.com/install/install-kubernetes.html) doesn't specify that the setup won't work with the Team version, because it will create more than 1 pod.

With more than 1 pod, users won't receive all the new messages because they can be connected to different pods (websocket). 

Also, it makes any bot very flaky.

See https://forum.mattermost.org/t/hubot-mattermost-missing-messages/11075/7

**Comment by justinegeffen** [comment]
Thanks for raising this, @Philmod! Would you be open to helping us update this content and opening a PR? :)
