### ISSUE TITLE
Typing error in mattermost database changes.

### ISSUE THREAD

**Issue by sjstyle** [mattermost/docs#425]
At https://docs.mattermost.com/administration/changelog.html#database-changes-from-v3-2-to-v3-3 ,
( Commit
https://github.com/mattermost/docs/commit/e30c3fa605a83779e81bc6b4ac17d20f676d047b#diff-6d8bc7fdf1108df5a6734816051a32e3R191
)

**Users Table**

 - Added `LastActivityAt` column.
 - Added `LastPingAt` column.
 - Removed `ThemeProps` column.

But, Actually `Users` table's column `LastActivityAt` and `LastPingAt` removed at v3.3.

( https://github.com/mattermost/platform/blob/c3ae3f20f58b25aa6aba480ddc2239fd09e610cb/store/sql_upgrade.go#L172 )

I try to fix typos, but I found that document database change logs have more errors than I expected.

Can you check document change logs?

**Comment by jasonblais** [comment]
Thank you @sjstyle for bringing it to our attention -- this has now been fixed.

Much appreciated! If you notice other errors or typos, please let us know.

![image](https://cloud.githubusercontent.com/assets/13119842/18113650/7993a344-6eff-11e6-9f03-5612fbf3d853.png)
