### ISSUE TITLE
Request for Documentation: Verify SAML setup documentation for NameID

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#4267]
Mattermost user `scott.bishel` from https://community.mattermost.com has requested the following be documented:

```
My customer upgraded to 5.31 and looks like the new SAML library kicked some errors for their SAML setup. They got the below error:

```
{"level":"error","ts":1611606192.868646,"caller":"mlog/log.go:229","msg":"An error occurred while parsing the response from the Identity Provider. Please contact your System Administrator.","path":"/login/sso/saml","request_id":"terbt9r67bg4zc3xttaw3wq83e","ip_addr":"10.222.139.243","user_id":"","method":"POST","err_where":"SamlInterfaceLibImpl.DoLogin","http_code":302,"err_details":"err=missing NameID element"}
```

And in response to me suggesting they fix their outgoing claims and SAMLResponseSignature they changed the namespace to be the below. Is `NameID` something needed coming into Mattermost now? I'm a bit unfamiliar with ADFS setups so i'm not 100% sure here.
```

See the original post [here](https://community.mattermost.com/_redirect/pl/ejk8ftgcf7nippuj9hfonpcwzc).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
Documentation updated via: https://github.com/mattermost/docs/pull/4296
