### ISSUE TITLE
Import Slack history using the WebApp

### ISSUE THREAD

**Issue by FBartos** [mattermost/docs#4270]
Hi, we were interested in switching to Mattermost and wanted to import our Slack channel history, but I couldn't find the ``Import'' button in the Web Application.

According to the [help page](https://docs.mattermost.com/administration/migrating.html#migrating-from-slack-using-the-mattermost-web-app), there should be an `Import` tab inside the `Team Settings` menu. However, I can't find it here (I just created the channel and I should have all the privileges).

![image](https://user-images.githubusercontent.com/38475991/106043970-6695d100-60df-11eb-95ea-3362b6221e47.png)

Thanks
Frantisek

**Comment by amyblais** [comment]
@FBartos What Mattermost server version are you on? (You can find the version from Main Menu > About Mattermost)

**Comment by FBartos** [comment]
Hi @amyblais ,

this is the complete info from the page:

Mattermost Version: cloud-tag
Licensed to: Mattermost
Mattermost is made possible by the open source software used in our server, desktop and mobile apps.
Copyright 2015 - 2021 Mattermost, Inc. All rights reserved
Build Hash: efe2eba227295fee55e2d3cfabc47353a22d0af4
EE Build Hash: 2bd65f08897e3b0739a59ac14e2de41338c19504
Webapp Build Hash: 4215ffa786cb5207b7d4ba9df32ec0de8cc8a58a
Build Date: Wed Jan 27 16:01:19 UTC 2021

**Comment by amyblais** [comment]
@FBartos This is helpful!

It looks like you are using our **Cloud** offering. Slack import is currently not supported on **Mattermost Cloud**.

Slack import is, however, supported for **Self-Managed** servers. This requires you to install your own server -- instructions are here https://docs.mattermost.com/guides/administrator.html#installing-mattermost.

You can find more details here https://mattermost.com/get-started/.

Let me know if this helps to clarify things?

**Comment by FBartos** [comment]
ah ok, thank you! I must have missed this information in the documentation.

Thank you very much for the help and have a nice weekend!
Frantisek
