### ISSUE TITLE
Request for Documentation: Elastic Search indexing progress bar gets stuck for a long time.

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#4277]
Mattermost user `george` from https://community-daily.mattermost.com has requested the following be documented:

```
Another question:

> out of curiosity, why does the ElasticSearch Index fly through the first 95% of indexing then take almost 20 minutes for the last 5%?

The size of the data to be indexed is estimated, and on large databases this can be somewhat inaccurate, leading to the progress bar getting stuck near the end for an extended period. The indexing is still going on behind the scenes, it's just the progress estimate can be quite inaccurate.
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/ehqd1j1fkbrx78n7n1gucfcaso).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
Documentation updated via: https://github.com/mattermost/docs/pull/4338
