### ISSUE TITLE
Update statement on who has access to remove members from a channel

### ISSUE THREAD

**Issue by amyblais** [mattermost/docs#4287]
At https://docs.mattermost.com/help/getting-started/welcome-to-mattermost.html#channels under **Private Channels** section there is a sentence that says "Channel members can choose to leave at any time, **but only the channel owner or Team Admin can remove other members.**"

The highlighted section is inaccurate and is correctly described here https://docs.mattermost.com/help/getting-started/organizing-conversations.html#removing-members-from-a-channel.

By default we are giving users the ability to remove users from public and private channels. If you have access to Advanced Permissions (https://docs.mattermost.com/cloud/cloud-user-management/advanced-permissions.html), then you can change the behaviour. https://docs.mattermost.com/help/getting-started/welcome-to-mattermost.html#channels should be updated to clarify it.

For https://github.com/mattermost/mattermost-server/issues/16857

**Comment by cwarnermm** [comment]
Documentation updated via: https://github.com/mattermost/docs/pull/4339
