### ISSUE TITLE
UseGossip setting should be UseExperimentalGossip

### ISSUE THREAD

**Issue by amyblais** [mattermost/docs#4342]
More context at: https://community.mattermost.com/core/pl/q5uw3iig9i8niesfd6gjtewo3c

The docs for https://docs.mattermost.com/administration/config-settings.html#use-gossip needs updating. The change from ``UseExperimentalGossip`` to ``UseGossip`` was done only to the UI. The config setting is still called ``UseExperimentalGossip``.

This is part of a two step process we are taking in transitioning the feature from beta to stable. We have kept the config field as is to avoid breaking changes, and have just flipped the default to true now. And changed the text in UI.

Later, we will be entirely removing the ``UseExperimentalGossip`` setting altogether and make it the only mode.

**Comment by cwarnermm** [comment]
Documentation updated via: https://github.com/mattermost/docs/pull/4347
