### ISSUE TITLE
Sidebar on MM new update is broken

### ISSUE THREAD

**Issue by christinagee** [mattermost/docs#4349]
I just updated to the latest MM release and I'm now unable to see any individual messages. How do I go back to a previous version?

**Comment by amyblais** [comment]
@christinagee 

1. Can you help share a screenshot of what you're seeing? 
2. What OS and version are you on?
3. Can you also help share a screenshot of your Main Menu > About Mattermost screen?

**Comment by justinegeffen** [comment]
Hi @christinagee! I wanted to follow up on this and find out whether you've been able to resolve the issue or whether we can still help you. Let us know, and we'll be happy to assist. :)

**Comment by cwarnermm** [comment]
Closing ticket.
