### ISSUE TITLE
Add note for Postgres 11 Support

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#4385]
As we're using cloud and also have customers already successfully running postgres 11 in production we should add a note for support

> I believe Cloud uses Postgres 11 and we've been using that as well to run our load-test so I don't see any issue. If anything they should upgrade since version 9 is getting rather outdated.

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/poip6yquhifkiqfbjtpgqxfcre) *by @streamer45*._

**Comment by Sayanta66** [comment]
@svelle can you tell me in which document the postgres 11 note is required?

**Comment by svelle** [comment]
You could put it here for example: https://docs.mattermost.com/install/software-hardware-requirements.html#database-software

@cwarnermm what's your thought on this?

**Comment by cwarnermm** [comment]
Thanks, @svelle! That's a good place to add this information.

@Sayanta66 - I appreciate your willingness to contribute to these open documentation tickets.

**Comment by cwarnermm** [comment]
@svelle - Is action still needed on this issue?

**Comment by svelle** [comment]
> @svelle - Is action still needed on this issue?

No I think since we now say 10+ this should be fine
