### ISSUE TITLE
Channels and users disappear from Categories after computer restart

### ISSUE THREAD

**Issue by nz-alex** [mattermost/docs#4445]
I have my channels and users neatly organised in Categories in the sidebar, but every time I restart my laptop (it's a company-controlled Windows laptop, so I have to do it every 1-2 weeks), I lose all the channels and users that were assigned to the Categories (the categories themselves are still visible, there's just nothing assigned to them). 

![image](https://user-images.githubusercontent.com/40783553/113542028-f8f1ae00-9615-11eb-930d-b69f73c15d6f.png)

**Comment by amyblais** [comment]
@nz-alex We did a bug fix for this in v5.32.0 release, and it was also backported to v5.31.1 dot release. Would you be open to upgrading to a more recent version?

**Comment by nz-alex** [comment]
Thank you so much for the quick response! Unfortunately updating our Mattermost version is very much outside my sphere of influence as it's owned by a large enterprise where I'm a contractor at the moment. Hopefully they'll apply the upgrade soon, looks like we're not far off in terms of versions!

**Comment by nz-alex** [comment]
Not sure if anyone will see this comment but our version of Mattermost got updated today and we're on 5.34.1 now, yay! :-)
