### ISSUE TITLE
Learn how to implement Sphinx tabbed content

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#4487]
Learn how to create tabbed content in Sphinx documentation when building HTML. 
- [Examples](https://sphinx-tabs-rtd-test.readthedocs.io/en/latest/)
- [Readme docs & repo](https://github.com/executablebooks/sphinx-tabs)

Use this tabbed content approach to update [this section of the User’s Guide](https://docs.mattermost.com/help/getting-started/organizing-conversations.html#favoriting-a-channel) to provide details for Mattermost Desktop versus Mobile.

**Comment by SubhasmitaSw** [comment]
Hello, @cwarnermm I wish to start working on this issue if no one's already assigned.

**Comment by Sayanta66** [comment]
I am taking this issue @cwarnermm

**Comment by justinegeffen** [comment]
Hi @Sayanta66! That's awesome news. It's a pretty complex project with huge impact - let us know if we can help with anything. :)

**Comment by Sayanta66** [comment]
@cwarnermm can you assign me to this issue??

**Comment by cwarnermm** [comment]
@Sayanta66 - I've unassigned you from this ticket because we've learned how to incorporate a Sphinx extension to provide this functionality. We'll be taking full advantage of this tabbed content functionality starting with the upcoming Mattermost v6.0 release.

**Comment by Sayanta66** [comment]
Congratulations to team Mattermost
