### ISSUE TITLE
Learn how to use the Sphinx link check feature

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#4488]
Learn how to use the link check feature that is available through Sphinx that identifies broken URL links. 
- [Introduction to the feature](https://www.writethedocs.org/guide/tools/testing/#sphinx)
- [Sphinx documentation](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder)

**Comment by larkox** [comment]
I have been looking into this. The usage is pretty simple (`make linkcheck`). There would be several possible action points here:
- Adding this check to the workflow
  This seems complicated. There are tons of links, and many of them are expected to fail (github users in the changelogs that may have been disabled for whatever reason). We can ignore those, but it is for sure something we cannot do for every single new PR. Either way, we should do this after we hit 0 breaks.
- Fix what is broken
  We can spend some time going through the results fixing everything that is broken.
- Fix redirects
  Redirects also may mean something is broken. We should review the redirects and use the expected URL instead of the old one.

Do you want me to take care of any of these points?

**Comment by cwarnermm** [comment]
Thank you SO MUCH for digging into this, @larkox. 

You make an excellent point about why not to add this check to our GitHub workflows. That alone is amazing to have confirmed!

The Docs team would benefit greatly from being able to run checks on demand and review the output to find both broken links and broken redirects. 

I just tried the ``make linkcheck`` myself locally. It works as advertised -- it spits out a LOT. In fact, it's been running the ENTIRE time I've been writing this response! :)

From your perspective, it is possible to take the output from this command, and split it out into multiple files we could then take action on, one at a time? I'm imagining something like an output file for links that return OK, one for broken links, one for redirect problems, etc? Even better if we could them pull those results into a tool like a spreadsheet where we can track each issue & fix (at least until we're at 0 issues, and **then** we can work on ignoring the rest and adding build-level process in to assist. What do you think?

**Comment by larkox** [comment]
Hi @cwarnermm !

You can find there a breakdown of what I considered relevant from the links. https://docs.google.com/spreadsheets/d/1eNtyjKBO9IO0xZSwZG9FF_wCWfEY76Z2dWuwzOq3Wjc/edit?usp=sharing

All `http://github.com/` links are ignored.

Let me explain a bit what is there and why:
- broken: Pretty obvious. All the broken links. We should look into them to fix them.
- redirect: There are many redirects here and there. I feel many of this has been just websites that have moved the files from one place to another. On those cases, I feel we should use the updated link. Nevertheless, it could also mean the link is not exactly what it is expected.
- docs direct links: Direct links to `docs.mattermost.com`. I guess we should use anchors to different pages using reStructuredText, so maybe those have to be updated.
- weird links: Links that felt wrong. Google Drive files, links to messages in community... Each have a reason field on why I put them there.
- mattermost: Links to mattermost owned pages. The potential problem here is that I am not sure if we want to keep a single source of truth for documentation, and if we want to move part of that documentation (and stop referencing it) to these docs or not.

I think that from this breakdown, your team can start creating new tickets to start solving these problems one by one. Please, let me know if you would need / want more help with this.

**Comment by justinegeffen** [comment]
Thanks so much, @larkox!

Just a note on this, to prevent unnecessary work, the process and archive directories are not used in our documentation and, as such, their links don't need to be addressed as they're generally set up as redirects in the conf.py file and the page itself is no longer used. For example, some of the broken links aren't an issue as the page itself may redirect to a current page in the Handbook which has the updated links. 

There are also a number of pages that are being deprecated and there's an open PR for that which hasn't been merged yet and those pages have generally moved to a new doc set/section. 

I'll definitely take a look at all the identified links but just wanted to mention that so the focus can be shifted from those files and lean more toward the docs/content we use. :)
