### ISSUE TITLE
Update documentation pin button

### ISSUE THREAD

**Issue by biva** [mattermost/docs#4504]
With reference to this issue https://github.com/mattermost/mattermost-server/issues/17440, I suggest modifying the page https://docs.mattermost.com/help/messaging/pinning-messages.html

The pin button is not on the top right anymore, it's on the top left, below the channel name.

**Comment by biva** [comment]
Thanks @cwarnermm , I see the updated page. 
I guess the issue can be closed now?

**Comment by cwarnermm** [comment]
Hi @biva! Thanks so much for circling back on this documentation issue. Yes, an update has been made to accurately capture the Pin functionality. Are there any additional changes you'd like to see made to this content? If not, let's close this issue.

**Comment by biva** [comment]
Nothing for me, thanks :)
