### ISSUE TITLE
RTL Documentation is not fully explained

### ISSUE THREAD

**Issue by erezo9** [mattermost/docs#4525]
https://docs.mattermost.com/help/messaging/sending-messages.html
On the section on Right-to-left, it states 
"Mattermost automatically detects and displays messages written using right-to-left scripts, such as Arabic, Hebrew, or Persian."
But if we go down and write on Mattermost, it will be written correctly right-to-left
but, it will not show from right to left, unless the system admin will install the RTL Plugin:
https://github.com/QueraTeam/mattermost-rtl
So, the plugin is needed to display from right-to-left

**Comment by cwarnermm** [comment]
Updates merged to master. Closing.
