### ISSUE TITLE
https://pad.coop.tools/ doen't work

### ISSUE THREAD

**Issue by jmpoulhes** [mattermost/docs#4629]
Hello
I don't know if you are the concerned organisation, but the pads at "**https://pad.coop.tools/**" doesn't work I get 
the message "502 Bad Gateway" (nginx) 
Thanks in advance
Best regards****

**Comment by justinegeffen** [comment]
Hi @jmpoulhes! Thanks for reaching out. It doesn't look like that URL is part of our documentation so we aren't able to assist you.
