### ISSUE TITLE
5.35 Settings Potentially Missing from Docs

### ISSUE THREAD

**Issue by ewwollesen** [mattermost/docs#4645]
The `5.35 `release has a couple of [additions to config.json](https://docs.mattermost.com/administration/changelog.html#changes-to-team-edition-and-enterprise-edition) that I don't think are documented, or at least I can't find them or have misunderstood something.

The first one is `EnableFileSearch`. I don't see that anywhere in the [config settings docs](https://docs.mattermost.com/administration/config-settings.html), There is a reference to it [here](https://docs.mattermost.com/administration/config-settings.html#enable-document-search-by-content) for one of the other settings (I think), but I don't see a direct reference to that settings or what its values should be (presumably it's just `true`/`false`).

The second one is `EnableRemoteClusterService`. I also don't see a reference to it directly in the  [config settings docs](https://docs.mattermost.com/administration/config-settings.html), but there is a reference to `RemoteClusters`. It looks like that might be the setting, but it's named differently [in the docs](https://docs.mattermost.com/administration/config-settings.html#remote-clusters)?

**Comment by cwarnermm** [comment]
Thanks for opening this Documentation issue, @ewwollesen. https://github.com/mattermost/docs/pull/4647 has been logged to address the first issue you've raised about the ``EnableFileSearch`` configuration setting option missing from the Mattermost product documentation.

The Shared Channels functionality was released in v5.35 as experimental, and it's taken us a bit longer to publish documentation for this feature. Please note that this feature requires an Enterprise Edition E20 license, and is disabled by default from v5.35.

**Comment by cwarnermm** [comment]
https://github.com/mattermost/docs/pull/4670 has been logged to capture the work required to publish the Shared Channels product documentation.
