### ISSUE TITLE
Production Docker Setup instructions need updating

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#4662]
Relevant URL: https://docs.mattermost.com/install/prod-docker.html

The main issue is that the repository it links to - https://github.com/mattermost/mattermost-docker - is unmaintained and stopped at v5.31.0 of the server.

**Comment by justinegeffen** [comment]
Thanks, @icelander. This content is in the process of being updated by me and Marco from Support. I'll close this issue once it's been resolved.

**Comment by cwarnermm** [comment]
Updates being tracked via https://github.com/mattermost/docs/pull/5277
