### ISSUE TITLE
Help Wanted: For Mattermost operator, document how state is maintained across nodes/how inter-node communication works

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/docs#4683]
https://docs.mattermost.com/install/install-kubernetes.html seems to indicate that a multi-node setup works as expected but how is state maintained across nodes/how does inter-node communication work for Mattermost operator? https://docs.mattermost.com/deployment/cluster.html uses gossip but that only works on E20 version whereas operator sounds like it works with all versions.

**Comment by justinegeffen** [comment]
Thanks for raising this, @bbodenmiller! These are great questions. One person who may be able to help is @gabrieljackson. I've tagged him and if he isn't able to assist he can definitely refer you to someone who can. If that is the case, would you be open to helping us update this content?
