### ISSUE TITLE
Help Wanted: Add mobile-specific documentation for Messaging tasks

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#4709]
The Messaging product documentation focuses on how to use Mattermost using the Desktop App and using a browser.

In some cases, the user's experience using Mattermost on a mobile device would be different than using either the Desktop or Web. Document the steps a user needs to take to complete Messaging tasks using the Mobile App.
Both Android and iOS content is most welcome.

**Comment by cwarnermm** [comment]
The problem space that this ticket is looking to solve is to include end user documentation for Messaging functionality that's specific to mobile Mattermost users.

In Messaging, some tasks are performed differently using a Mattermost Mobile App than when using the Desktop App or a web browser. It's these specific cases where we have different user experiences between platforms that we're looking for in this ticket. 

Take our [Sending and Receiving Messages](https://docs.mattermost.com/messaging/sending-receiving-messages.html#sending-and-receiving-messages) as an example. Under [Send a Message,](https://docs.mattermost.com/messaging/sending-receiving-messages.html#send-a-message) we have this documentation:

"Write a message by typing into the text input box, then press ENTER to send it. Use SHIFT+ENTER to create a new line without sending a message. To send messages by pressing CTRL+ENTER, go to Main Menu > Account Settings > Advanced > Send Messages on CTRL/CMD+ENTER > Edit."

A mobile user would not send a message by pressing ENTER, nor would they use SHIFT+ENTER to create a new line without sending a message. Right now, the product docs for Messaging focus mainly on how the Desktop App and web version of Mattermost work, and gloss over or ignore how the mobile experience works.

So, an ideal PR contribution for this particular ticket requires:
- Reviewing the functional tasks described in the Messaging section of the product docs to identify cases where the user's experience differs on mobile
- Running through each topic on using the Mobile App and identifying the places where additional mobile-specific details are missing/need updates
- Documenting the specific steps a mobile user would take to complete the same task in parallel with the existing docs content. 
- Screenshots are a great way to provide an alternate visual learning path. They're not a requirement in this case, but they can provide great value.

**Comment by Rutam21** [comment]
@justinegeffen Please assign this ticket to me. I would be happy to work on this.

**Comment by cwarnermm** [comment]
@Rutam21 - You're currently assigned to this ticket. Is this something you're working on, or would you rather this ticket return to the pool of available docs work?

**Comment by Rutam21** [comment]
@cwarnermm I will complete this one.

**Comment by cwarnermm** [comment]
Awesome! Thanks so much @Rutam21!

**Comment by cwarnermm** [comment]
@Rutam21 - Are you actively working on this? Would you like to keep it assigned to you?
