### ISSUE TITLE
Help Wanted: Improve the user's mobile documentation experience

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#4710]
Currently, using the Mattermost product documentation on a mobile device isn't an ideal experience:

- Download links don't work as expected
- Long code samples require horizontal scrolling
- Screenshots and images are resized inconsistently

These issues may require a case-by-case investigation, a new Sphinx theme that includes full mobile support, or may take additional paths towards resolution. All options are currently on the table. Our goal is to provide a positive documentation experience regardless of how and where users access the content.

Some examples of pages to test on mobile and a good starting point:

- https://docs.mattermost.com/install/install-kubernetes.html
- https://docs.mattermost.com/install/desktop-app-install.html
- https://docs.mattermost.com/scale/performance-monitoring.html

Let us know how we can help you get started!

**Comment by sighclone** [comment]
Hi! I'll take this up. Do assign it to me!
