### ISSUE TITLE
Resolve documentation build warnings: unexpected unindent

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#4711]
Mattermost product documentation is written in RST, generated using Sphinx, and formatted using a Sphinx theme called ReadTheDocs.

When the documentation builds, the following common Sphinx build warnings are returned: 
- ``Enumerated list ends without a blank line; unexpected unindent``
- ``Block quote ends without a blank line; unexpected unindent``
- ``Bullet list ends without a blank line; unexpected unindent``
- ``Definition list ends without a blank line; unexpected unindent``
- ``Unexpected indentation``

The Technical Writing team welcomes some assistance identifying what's causing these warnings in the content source files, how to resolve the warnings, and how to avoid the warnings altogether going forward with new content development.

VS Code-based linters and other RST format checking tools compatible with Sphinx 3.4.3 and later are also most welcome additions to our existing toolset.

**Comment by larkox** [comment]
May I take this one?

**Comment by larkox** [comment]
There doesn't seem to be any "autofixer" for SRT files, so a lot of manual fixing would be needed to get up to date. (I will try to do it)

We could add a linter to check the errors once we are back to 0 warnings, and add it to the CI pipeline, so new commits have to comply with that. I have seen there are mainly two big linters for reStructuredText: [doc8](https://pypi.org/project/doc8/) and [restructuretext-lint](https://pypi.org/project/restructuredtext-lint/). We can assess both when we are at 0 or near 0 warnings.
