### ISSUE TITLE
Upgrade Script somehow lost within the Doc

### ISSUE THREAD

**Issue by JtheBAB** [mattermost/docs#4719]
Hi 

Since the reorganisation the Update Script here https://github.com/mattermost/docs/blob/master/source/administration/upgrade-script.rst is lost. There is no section in the docs for that. You can find it by searching but then it looks strange.

**Comment by cwarnermm** [comment]
Thanks, @JtheBAB, for logging this issue! It was dropped in error and it will be added back with a link in the LHS.

**Comment by justinegeffen** [comment]
@JtheBAB, thanks for picking this up. I'm handling the migration of the content and will have this up shortly. Thank you!

**Comment by justinegeffen** [comment]
Hi @JtheBAB! Sorry about the delay on this. I've moved the upgrade script article to [the forum](https://forum.mattermost.org/t/upgrading-mattermost-server-with-a-script/12251). Please take a look at it and let me know if you have any issues or feedback. :)
