### ISSUE TITLE
Redux Documentation

### ISSUE THREAD

**Issue by larkox** [mattermost/docs#4744]
Right now we export the redux repo for plugins to use. Nothing regarding this is documented (AFAIK) in the developer documentation. It would be great to have some documentation at least for the most relevant parts for plugins.

**Comment by mickmister** [comment]
@larkox Does this page satisfy the requirement for this ticket? 
https://developers.mattermost.com/extend/plugins/webapp/actions

**Comment by larkox** [comment]
This indeed solves part of the problem, but there is no more in depth information on at least commonly used selectors / actions that the plugins can use.

**Comment by justinegeffen** [comment]
Thanks for this, @larkox! We'd like to add this as a Docathon issue. Would you be open to working with a potential contributor to get this content added? :)

**Comment by larkox** [comment]
More than happy :smile:

**Comment by Rutam21** [comment]
I would love to work on this. Please assign this to me.

**Comment by mickmister** [comment]
To add some more context to this ticket:

The `mattermost-redux` library exports types and functions that are imported by the web application and mobile application. These functions can be imported by plugins, and used the same way. There are a few different kinds of functions exported by the library:

- [actions](https://github.com/mattermost/mattermost-redux/tree/master/src/actions) - Actions perform API requests and change the state of Mattermost.
- [client](https://github.com/mattermost/mattermost-redux/tree/master/src/client) - The `client` package can be used to instantiate a `Client4` object, to interact with the Mattermost API directly. This is useful in plugins as well as javascript server applications communicating with Mattermost.
- [constants](https://github.com/mattermost/mattermost-redux/tree/master/src/constants) - An assortment of constants within Mattermost's data model
- [selectors](https://github.com/mattermost/mattermost-redux/tree/master/src/selectors) - Selectors return certain data from the Redux store, such as [getPost](https://github.com/mattermost/mattermost-redux/blob/3d1028034d7677adfda58e91b9a5dcaf1bc0ff99/src/selectors/entities/posts.ts#L46) which allows you get a post by id from the Redux store.
- [store](https://github.com/mattermost/mattermost-redux/tree/master/src/store) - Functions related to the Redux store itself
- [types](https://github.com/mattermost/mattermost-redux/tree/master/src/types) - Various types of objects in Mattermost's data model. This is useful in plugins as well as javascript server applications communicating with Mattermost.
- [utils](https://github.com/mattermost/mattermost-redux/tree/master/src/utils) - Various utility functions shared across the web application and mobile application

**Comment by mickmister** [comment]
@Rutam21 On the [current redux page](https://developers.mattermost.com/extend/plugins/webapp/actions), we can remove all of the sections that are below the "Prerequisites" section. We should rename the page "Interaction with Redux".

We can add this content below:

-----

Here's an [example](https://github.com/mattermost/mattermost-plugin-jira/blob/master/webapp/src/components/modals/create_issue/index.ts) of a webapp plugin making use of [mattermost-redux](https://github.com/mattermost/mattermost-redux)'s functions:

```js
import {connect} from 'react-redux';
import {bindActionCreators} from 'redux';

import {getPost} from 'mattermost-redux/selectors/entities/posts';
import {getCurrentTeam} from 'mattermost-redux/selectors/entities/teams';

import {closeCreateModal, createIssue, fetchJiraIssueMetadataForProjects, redirectConnect} from 'actions';
import {isCreateModalVisible, getCreateModal} from 'selectors';

import CreateIssue from './create_issue_modal';

const mapStateToProps = (state) => {
    const {postId, description, channelId} = getCreateModal(state);
    const post = (postId) ? getPost(state, postId) : null;
    const currentTeam = getCurrentTeam(state);

    return {
        visible: isCreateModalVisible(state),
        post,
        description,
        channelId,
        currentTeam,
    };
};

const mapDispatchToProps = (dispatch) => bindActionCreators({
    close: closeCreateModal,
    create: createIssue,
    fetchJiraIssueMetadataForProjects,
    redirectConnect,
}, dispatch);

export default connect(mapStateToProps, mapDispatchToProps)(CreateIssue);
```

**Comment by Rutam21** [comment]
@mickmister Thanks. Noted.
