### ISSUE TITLE
CollapsedThreads listed options

### ISSUE THREAD

**Issue by TheStu** [mattermost/docs#4756]
https://docs.mattermost.com/configure/configuration-settings.html#collapsed-reply-threads-beta says the acceptable config options for CollapsedThreads are `disabled` and `default-off` but it should be `default_off`

**Comment by justinegeffen** [comment]
Thanks for letting us know, @TheStu! Would you be open to helping us update this and submitting a PR for the change? :)

**Comment by cwarnermm** [comment]
Hi @TheStu - Thanks for logging this documentation error. This correction has been applied via https://github.com/mattermost/docs/pull/4774

**Comment by TheStu** [comment]
Why ask me to submit a PR and then duplicate my PR? Was there something wrong with it? 🤷‍♂️

**Comment by cwarnermm** [comment]
Hi @TheStu - I'm sorry about the mixup here. Your PR was fantastic! I too had a PR in final review for the very same important update, and I wasn't aware at the time the update was merged that your PR was incoming.
