### ISSUE TITLE
[Help Wanted] Create install guide variant with MySQL commands for Ubuntu 16.04, RHEL6 and RHEL7

### ISSUE THREAD

**Issue by it33** [mattermost/docs#489]
While MySQL is more popular than Postgres, the Mattermost install guides default to Postgres. 

This ticket is to create a variant of [the Ubuntu, RHEL6 and RHEL7 install guides](https://docs.mattermost.com/#install-guides) that offer step-by-step instructions for MySQL. 

Please post-fix the names of the new files with `mysql`, so for `prod-rhel-6` please call it `prod-rhel-6-mysql`.

**Comment by jasonblais** [comment]
You can see an example provided in [Ubuntu 14.04 guides](https://docs.mattermost.com/install/prod-ubuntu-1404.html#set-up-mysql-database-server)

**Comment by JeffSchering** [comment]
I've added the MySQL instructions to the Ubuntu 16.04, RHEL 6.6, and RHEL 7.1 install guides. See PR #742

**Comment by JeffSchering** [comment]
The MySQL instructions are included in the new install guides for Ubuntu and RHEL.
