### ISSUE TITLE
Help Wanted: New diagram for source available license

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/docs#4923]
Linked to https://github.com/mattermost/docs/issues/4794, we need to update the diagram in the Source Available License content to remove the E20 mention and make it more generic.

**Comment by kaeptnkrunch** [comment]
Hello, i would like to help with that Issue :)

**Comment by Rutam21** [comment]
Hello @justinegeffen @cwarnermm, I would like to update this diagram. You can assign this to me.
