### ISSUE TITLE
Cannot access to "Creating Teams" page

### ISSUE THREAD

**Issue by Titome** [mattermost/docs#495]
Hi,

Thank for your work !

I have a problem with docs, I cannot access to "Creating Teams" page, return me 403 HTTP code :(
See screenshot :

![capture d ecran_2016-09-16_17-18-30](https://cloud.githubusercontent.com/assets/748679/18591256/2ea7ba1a-7c32-11e6-9693-39072067e8c8.png)

Thank for your help.

**Comment by jasonblais** [comment]
Thanks @Titome! 

We just pushed Mattermost v3.4 documentation to production, so you might have landed to the page during the update.

Can you try again if the issue reproduces for you?

If so, which browser are you using?

**Comment by Titome** [comment]
It's work, it's ok for me, thank for your quick answer :)
