### ISSUE TITLE
Upgrade Instructions advise skipping from Step 7 to 8, but then noclobber will foil the upgrade

### ISSUE THREAD

**Issue by cliff1976** [mattermost/docs#4959]
Hi, I'm new here.  Never opened an issue on GitHub before, ever.  I skimmed the guidelines; apologies if I miss something.

I think I'm the guy who provided the impulse for the documentation enhancements in https://github.com/mattermost/docs/pull/4943.  It looks MUCH better now (on the [docs site](https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html)), but I think there is still a small point to be corrected.

TL;DR: does the sentence from Step 7 ending in “you can jump to step 8 below.” need to disappear? I think if it doesn’t, lots of important stuff won’t be copied that should be.

Details:

I see in Step 7 the following:

> Run `ls` on your Mattermost install directory to identify what default folders exist. If your folders match the structure specified in the following note, you can jump to step 8 below.

OK, cool, that is my situation.

And then Step 8 tells me:

> The `n` (no-clobber) flag and trailing `.` on source are very important. The `n` (no-clobber) flag preserves existing configurations and logs in your installation path. The trailing `.` on source ensures all installation files are copied.

Umm, I don't think that's true.  Since I didn't erase anything (skipping from Step 7 to Step 8), the no-clobber flag will preserve the stuff the command is meant to copy into that directory.

I did a fast check by copying my existing mattermost installation into `/tmp/mattermostclobberme` and then adjusted the Step 8 instructions to simulate it with `cp -an /tmp/mattermost-upgrade/. /tmp/mattermostclobberme/`

Results of an `ls -lh` after that:

```
root:/tmp# ls -lh ./mattermost-upgrade/bin ./mattermostclobberme/bin
./mattermostclobberme/bin:
total 108M
-rwxr-xr-x 1 mattermost mattermost  85M Jun 10 13:53 mattermost
-rwxr-xr-x 1 mattermost mattermost  21M Jan 13  2021 mmctl
-rwxr-xr-x 1 mattermost mattermost 2.2M Jun 10 13:53 platform

./mattermost-upgrade/bin:
total 110M
-rwxr-xr-x 1 root root 89M Jul 29 13:38 mattermost
-rwxr-xr-x 1 root root 22M Jul  6 15:46 mmctl
```
We see, thanks to the timestamp on the files, that the `cp -an` command did not overwrite the mattermost binary in `/tmp/mattermostclobberme/bin/`, which leads me to believe that the hint in Step 7 about jumping to Step 8 is very counter-productive.

Thank you for reading my first-ever GitHub issue!  :-)

**Comment by cwarnermm** [comment]
It's a pleasure to meet you, @cliff1976, and thank you for logging this Mattermost product documentation issue for the upgrade documentation. I'm looping in @mrckndt to assist us in this quest to ensure that the upgrade docs are rock solid and entirely usable. I really appreciate your patience with this work.

@mrckndt - Thanks so much for your help with this.

**Comment by mrckndt** [comment]
The step 7 is mandatory as the `find | rm -r` (shortened for readability) command will find every folder except the persistent ones like config, logs, plugins, client/plugins and data as well as the own folders. Afterwards everything will be deleted leaving you with the data you want to keep and the `cp` will rotate the server binary and client files into the directory without overriding files like logs/mattermost.log or config/config.json.

**Comment by cliff1976** [comment]
So, erase the sentence that indicates that one can jump to Step 8, right?

> If your folders match the structure specified in the following note, you can jump to step 8 below.

While we're at it, how about switching out the word "before" with "after" in step 10?  The copying was already done in step 8.

**Comment by cwarnermm** [comment]
@mrckndt - It looks like the line in step 7 about "jumping to step 8 below" is incorrect, given that aspects of step 7 are mandatory. Do you agree?

@cliff1976 - I agree that step 10 needs to change based on your feedback above. Great catch, by the way!

**Comment by mrckndt** [comment]
@cwarnermm Yes, the `find` command is needed to wipe the old server and client components.

**Comment by cwarnermm** [comment]
@mrckndt @cliff1976 - These documentation corrections will be made via https://github.com/mattermost/docs/pull/4978
