### ISSUE TITLE
[Help Wanted] CSS to fix line wraps in titles for left-hand sidebar

### ISSUE THREAD

**Issue by it33** [mattermost/docs#506]
After the [re-org PR](https://github.com/mattermost/docs/pull/502) goes in, propose having someone fix CSS for line wraps in left-hand sidebar.

Right now, formatting is all broken: 

![image](https://cloud.githubusercontent.com/assets/177788/18622436/e2670b66-7de3-11e6-8254-bc9e8b5c708f.png)

**Comment by esethna** [comment]
Closing as resolved, thanks @shieldsjared!
