### ISSUE TITLE
Bug UX: Paste from clipboard to message editor when focus on chat box

### ISSUE THREAD

**Issue by slonm** [mattermost/docs#5073]
We could strart input from keyboard anytime and if last clicked control have no input ability like chat box or contacts box then message editor got focus and take input instantly.

That's not  true if we paste text from clipboard by Ctrl+v. That's often case for me then i copy-past message parts from chat box.

Slack hande such case as expected.

Environment: Windows 10, MM 4.6.2

**Comment by slonm** [comment]
Wrong project

**Comment by cwarnermm** [comment]
@amyblais - Is it possible to re-home this incoming Mattermost issue to the correct repository? (This issue doesn't appear to be product documentation related).

**Comment by amyblais** [comment]
@slonm You can open this issue at https://github.com/mattermost/mattermost-server/issues.

**Comment by slonm** [comment]
Thanks for help. New issue opened here https://github.com/mattermost/mattermost-server/issues/18461
