### ISSUE TITLE
Update AWS Elastic Beanstalk Docker Setup docs

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5097]
Review the existing [AWS Elastic Beanstalk Docker Setup](https://docs.mattermost.com/install/setting-up-aws-elastic-beanstalk-docker.html) product documentation for technical accuracy and update as needed.

The following user feedback has been shared with Mattermost about this page of product documentation:
    - These instructions do not match the steps or labels now used at the AWS Elastic Beanstalk web interface.
    - Multi-Container Docker is no longer an option for Environment Type.

Prerequisites: Experience with and access to AWS Elastic Beanstalk is needed to complete this technical review and apply required updates.

**Comment by Hard-Coder05** [comment]
@cwarnermm I would like to work on this issue

**Comment by cwarnermm** [comment]
We appreciate your help with this, @Hard-Coder05! Thank you!
