### ISSUE TITLE
Help Wanted: Review and update Desktop App Custom Dictionaries documentation

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5098]
Review the existing [Desktop App Custom Dictionaries](https://docs.mattermost.com/install/desktop-custom-dictionaries.html) product documentation for technical accuracy and update as needed.

The following user feedback has been shared with Mattermost about this page of product documentation:
    - The 'Setting up' directive does not work. 
    - When I press Save and restart Mattermost, the directory is not shown anymore and it does not work with the selected dictionary. Used a local folder which holds the file.

Prerequisites: Experience with and access to the latest release of the Mattermost Desktop App is needed to complete this technical review and apply required updates.

**Comment by AnshMishra2001** [comment]
Would like to work on this @cwarnermm

**Comment by cwarnermm** [comment]
We appreciate your help with this, @AnshMishra2001! Thank you!

**Comment by cwarnermm** [comment]
@AnshMishra2001 - Are you actively working on this? Would you like to keep it assigned to you?

**Comment by MM-Mikhail** [comment]
Excuse my intrusion here but this dictionary thing is all broken - Windows App

How the hell can you set it up now to do checking for language you need ?

Currently it looks for system language and ignores everything else, previously it was an easy selection what you needed to check and with what to check, like in most current browsers,.

Error reporting on what you setup in the url link is none existent

How can you work with several languages at the same time ?

**Comment by TomerPacific** [comment]
@cwarnermm - Still need help here?

**Comment by cwarnermm** [comment]
I'd love your help with this one, @TomerPacific!

**Comment by TomerPacific** [comment]
@cwarnermm - I'll try to see if I can get the Desktop App set up and update you.

**Comment by TomerPacific** [comment]
@cwarnermm - Is there a test server/mock server I can use in order to login to the Desktop app?

**Comment by cwarnermm** [comment]
@TomerPacific - You're welcome to connect to the Mattermost Community Server any time for such testing. Alternatively, you could also connect to the [Localization Community Server](https://localization.cloud.mattermost.com).

**Comment by TomerPacific** [comment]
@cwarnermm - I see that part of the instructions require to host the language files on an external web server. Is there any guidance here on how one would do that? Trying to understand how much effort this will take on my end.

**Comment by cwarnermm** [comment]
@devinbinnie - @TomerPacific is looking to test the desktop app custom dictionaries functionality and update our documentation. Is there a recommended way forward for setting everything up for testing? Do we have an environment that could be used for this effort?

**Comment by devinbinnie** [comment]
@cwarnermm To clarify, are we talking about the custom spellchecker URL?
If so, I think you just need to provide a URL in the config file (seems like we don't have an interface for it). I've never messed with that functionality myself, but here's the relevant Electron API method: https://www.electronjs.org/docs/latest/api/session#sessetspellcheckerdictionarydownloadurlurl

**Comment by TomerPacific** [comment]
Thanks @cwarnermm for helping out and @devinbinnie for the feedback. What I noticed was that, while you need to put a URL as a custom dictionary, that means the file needs to be hosted somewhere. What I was asking is, if I can use something simple like Google Drive (as an example) or if I need to boot up a my own server for this?

![mm](https://github.com/mattermost/docs/assets/23402988/5e87b353-eeb2-4076-bcc9-c98a8ab5afcb)

**Comment by devinbinnie** [comment]
@TomerPacific I would assume as long as the file is publicly accessible via URL it should be fine. Google Drive might not be ideal, it might need to be hosted somewhere. You could always try hosting it locally.

**Comment by TomerPacific** [comment]
@cwarnermm - I followed the steps detailed in the current documentation, and uploaded a language file to be used as a directory where definitions can be found and saw no issues.
