### ISSUE TITLE
Help Wanted: Review and Update iOS Setup documentation

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5100]
Review the existing [iOS Setup](https://docs.mattermost.com/collaborate/install-ios-app.html) documentation steps for accuracy and update as needed.

Additional Mattermost Mobile App steps may be missing from this content, such as Apple Authentication using a code.

Prerequisites: Experience with and access to Mattermost Mobile Apps and an Apple mobile device is needed to complete this technical review and apply required updates.

**Comment by shiyanshirani** [comment]
Hi @cwarnermm, I'd like to contribute to this issue.

**Comment by cwarnermm** [comment]
We appreciate your help with this, @shiyanshirani! Thank you!

**Comment by cwarnermm** [comment]
@shiyanshirani - Are you actively working on this? Would you like to keep it assigned to you?

**Comment by shiyanshirani** [comment]
I am not working on this project.

**Comment by cwarnermm** [comment]
Thanks for confirming, @shiyanshirani.

**Comment by Rutam21** [comment]
@cwarnermm I would like to take this up. Also, do we need to use an iPhone only or iPads would be okay as well?

**Comment by cwarnermm** [comment]
Thanks, @Rutam21! I appreciate your help with this ticket!

Please prioritize iPhone devices first, then note any change in the user's experience via iPad (if applicable).
