### ISSUE TITLE
Request for Use of Github templates for issues 

### ISSUE THREAD

**Issue by divshacker** [mattermost/docs#5130]
GitHub have rolled out new issue forms for public repository. 
https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/
Please check this out. 
If maintainers can give some suggestions then I can make some templates for opening issues for this repository. 
Thank you

**Comment by divshacker** [comment]
I would like to work on this Please 
Thank you

**Comment by divshacker** [comment]
Hey @cwarnermm 
Thanks for allowing me. This github templates are used when some want to report a issue or open a PR. Then he/she would go through this template. It is sort of like a form which one have to fill in order to report a issue or open a PR. Github have announced some new features in there forms which improve the contributor experience to contribute in the repository.  
I hope this help 
Thank you

**Comment by cwarnermm** [comment]
Thanks! That's a great overview of this new GitHub functionality. Would you be willing to open a PR against the docs repository in order to review and assess the areas where our PR process would benefit from these new features? We'd love your fresh set of eyes on this!

**Comment by divshacker** [comment]
Sure! I will open a PR once I get some suggestions about the templates. I need answers of some of the questions that I am posting here. 

1. What things should be there in a issue which makes a good and well defined issue.? eg. Expected results, steps to reproduce problem
2. what type of issue are  generally get reported in this repository. eg Feature request, bug etc
3. Do one need to define the environment specifications while  reporting a issue? 

There are more questions but I will make a PR based on answers of these question. then it will go in review process then it can be easily altered.
