### ISSUE TITLE
PostgreSQL installation instructions for RHEL 7 still using deprecated version 9.4

### ISSUE THREAD

**Issue by rmontag-ap** [mattermost/docs#5173]
https://docs.mattermost.com/install/install-rhel-7-postgresql.html

The installation instructions for PostgreSQL are for version 9.4, which isn't supported since Mattermost 5.32.0. Can we have an update for any supported version 10+ of PostgreSQL?
Unfortunately I cannot tell if just using a newer version from a yum repo is sufficient and if all the configuration steps after the "yum install" are exactly the same as for version 9.4 to setup a Mattermost database using PostgreSQL10+.

**Comment by cwarnermm** [comment]
Thanks for raising this issue, @rmontag-ap! Updates have been implemented via https://github.com/mattermost/docs/pull/4643 for this issue. Please reach out if you encounter any other details that would benefit from an update.
