### ISSUE TITLE
Broken links on Desktop Changelog

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/docs#5175]
The v5 link works, but the remaining links either do not exist or link to strange areas of the page.

https://docs.mattermost.com/install/desktop-app-changelog.html#id4

https://community-daily.mattermost.com/core/pl/3zwoy884u3gk5mmp8r69o67hdh

**Comment by amyblais** [comment]
I can own this, a v5.0.1 dot release is planned and I'll be updating the changelog once it's done.
