### ISSUE TITLE
Help Wanted: Replace badge implementation with a streamlined programmatic solution

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5201]
As part of the Mattermost v6.0 release, plan and deployment badges were been added to the product documentation to clarify the subscription plans and deployment methods supported for a given feature or function.

These plan and deployment badges are currently implemented as in-line images in the code like this:

```
|all-plans| |cloud| |self-hosted|

.. |all-plans| image:: ../images/all-plans-badge.png
  :scale: 30
  :target: https://mattermost.com/pricing
  :alt: Available in Mattermost Free and Starter subscription plans.

.. |cloud| image:: ../images/cloud-badge.png
  :scale: 30
  :target: https://mattermost.com/deploy
  :alt: Available for Mattermost Cloud deployments.

.. |self-hosted| image:: ../images/self-hosted-badge.png
  :scale: 30
  :target: https://mattermost.com/deploy
  :alt: Available for Mattermost Self-Hosted deployments.
```

The current implementation approach requires badges to be defined on every docs page. Badge maintenance would be greatly improved by replacing existing inline image code on each page with a programmatic solution (such as the introduction of Bootstrap components, for example).

Identify a more streamlined implementation approach where the badges are defined once and simply referenced where necessary. The implementation approach proposed must be compatible with our current tech stack and tools.

Please ensure that you can show your implementation working in a local development environment that clones our docs repository, and ensure that your PR includes comprehensive instructions on how to incorporate your solution into our codebase.

**Comment by Sayanta66** [comment]
Can I work on this?

**Comment by cwarnermm** [comment]
Thanks, @Sayanta66! Looking forward to what you come up with for this docs request. Assigning to you.

**Comment by Sayanta66** [comment]
Thanks again :)

**Comment by cwarnermm** [comment]
@Sayanta66 - Are you actively working on this? Would you like to keep it assigned to you?

**Comment by Sayanta66** [comment]
Yeah I am researching and finding ways

**Comment by cwarnermm** [comment]
@Sayanta66 - Are you actively working on this issue?

**Comment by Sayanta66** [comment]
Yes but the issue is a bit difficult.
