### ISSUE TITLE
Clarify wording around Slack webhook compatibility

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#5226]
We talk a lot about Slack webhook compatibility and interchangeability on this docs page: https://docs.mattermost.com/developer/webhooks-incoming.html

However with the release of the Blocks system we don't support slackwebhooks as much as we used to so we should definitely make that more clear on this page as it can lead to confusion and frustration when customers are wondering why slack webhooks are not being displayed correctly in Mattermost.

**Comment by cwarnermm** [comment]
@svelle - Would you be open to creating a PR to update the developer documentation to incorporate this information? (There's no need to update the product docs since that duplicate content is scheduled to be archived).
