### ISSUE TITLE
Unable to scroll down on Cloud changelog doc

### ISSUE THREAD

**Issue by amyblais** [mattermost/docs#5241]
For https://docs.mattermost.com/install/cloud-changelog.html, I'm unable to scroll down and see the rest of the content. Unsure how to fix it. Also unsure if this is an issue only on my end, however I checked and other changelogs scroll normally.

**Comment by amyblais** [comment]
This didn't get posted in the Documentation channel.

@cwarnermm Just a FYI on this, I don't think this is urgent to fix now, unless this starts happening with other docs pages. Also unsure if this is an issue only on my end.

**Comment by cwarnermm** [comment]
Fixed by https://github.com/mattermost/docs/pull/5244
