### ISSUE TITLE
New Custom User Group Documentation Needed

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/docs#5297]
We need a section for administrators to understand how to:
- Turn it off
- What it does
- Configuration options
- Tips/Tricks/gotchas

For end-users - we need to make sure they understand how to:
- Create/Add members to a group
- Add a Group to a channel (ie: add 20 ppl at once) 
- how to use the @mention capabilities (may already exist) 

API Docs:
- Verify that the endpoint docs become visible once the code is checked in
- Question for @mkraft Is there Plugin API endpoints that need to be documented? 

Breaking Changes?
- @mkraft Will PNC be affected by any changes to the DB?  (no need to publish in docs, just need to reach out to them)

**Comment by aaronrothschild** [comment]
@justinegeffen @cwarnermm Me and @laneycs are working on the docs for this, and could use your assistance in figuring out where the info should live in the docs, etc.

**Comment by cwarnermm** [comment]
Sounds great, @aaronrothschild & @laneycs! 

Custom User Groups config setting:

https://docs.mattermost.com/configure/configuration-settings.html
- If it's available via the System Console, add it to the applicable section based on where it appears in the System Console UI
    - Describe what the setting does 
    - Define the plans/deployments supported via badges
    - Include it's config.json setting ID, default value, and possible values
    - Include any additional tips/tricks/gotchas that should be communicated to System Admins to help them be successful with this setting
    - Follow the approach used for other config settings
- If it's NOT available via the System Console (and only enabled via ``config.json``), it would go in the "Settings configurable only in config.json section instead

- https://docs.mattermost.com/manage/telemetry.html
    - Update the Telemetry page to include the new config setting via 

-----------------------

End User docs:

Note: I'm making an assumption that this feature is for Channels specifically and doesn't apply (yet) to Boards or Playbooks. Please let me know if that assumption is incorrect.

- In the Channels section of the docs, there's a section called "Manage Teams, Channels, and Members" that feels like a good home for this content:
    - Manage User Groups
        - Create
        - Add members
        - Add a group to a channel
    - Note: @mention functionality is documented and available via https://docs.mattermost.com/messaging/mentioning-teammates.html

Note: Additional updates are needed to the code to add the new end user page to the LHS (navigational sidebar) and we can help with that effort.

@laneycs - If you would like an introduction to our docs processes and tools, I'm happy to walk you through the pieces you need for this PR any time.

**Comment by laneycs** [comment]
@cwarnermm Would love a walk-through on Monday! Thanks so much for your help :-D

**Comment by laneycs** [comment]
@cwarnermm Here's the test environment for custom groups! 

- https://mattermost-server-pr-18839.test.mattermost.cloud/pr18839/
- Just in case you need log in credentials, they're here: https://github.com/mattermost/mattermost-server/pull/18839#issuecomment-993931266

**Comment by laneycs** [comment]
@cwarnermm just verifying the [Google doc](https://docs.google.com/document/d/1CdTYtOaE5U4WWEOzdguCFK5rFGNosnOWb5ovyzKeYpY/edit) I filled out for this works for documentation. Thanks!

**Comment by cwarnermm** [comment]
Thanks, @laneycs! This is amazing and a huge help! There's one small gap remaining around configuration settings for this feature:
- Where is this feature configurable via System Console?
- What's the config's config.json equivalent option/values?
CC @mkraft

**Comment by cwarnermm** [comment]
Thanks, @mkraft! Are the valid values ``true`` and ``false``, and the default set to ``true`` for both self-hosted and Cloud deployments?

**Comment by mkraft** [comment]
> Thanks, @mkraft! Are the valid values `true` and `false`, and the default set to `true` for both self-hosted and Cloud deployments?

Yes.

**Comment by cwarnermm** [comment]
Documentation for this feature is being tracked via https://github.com/mattermost/docs/pull/5406
