### ISSUE TITLE
Help Wanted: Ways to add alt text are unclear

### ISSUE THREAD

**Issue by myasonik** [mattermost/docs#5331]
As I found out in https://github.com/mattermost/mattermost-server/issues/19193, there is at least _some_ way to add alt text but it's not very discoverable. 

Adding a docs section dedicated to accessibility or making "alt text" an easier to search for term could help make this easier.

**Comment by cwarnermm** [comment]
Hi @myasonik - Would you be open to creating a PR with this documentation update?

**Comment by myasonik** [comment]
Sorry, I don't think that's something I'll have time for

**Comment by cwarnermm** [comment]
Thanks for letting me know, @myasonik!

**Comment by rukundob451** [comment]
@myasonik, is this still available?

**Comment by myasonik** [comment]
I don't use Mattermost anymore and don't work there so I've got no idea. @cwarnermm would be the person to ask.

**Comment by cwarnermm** [comment]
Hello, @rukundob451! We'd welcome a docs PR from you to address this docs issue.

**Comment by rukundob451** [comment]
> Hello, @rukundob451! We'd welcome a docs PR from you to address this docs issue.

Alright @cwarnermm, going to look into it.

**Comment by TomerPacific** [comment]
@cwarnermm - is this issue still relevant, and if so what would you like to be done here (I looked at the attached issue)?

**Comment by cwarnermm** [comment]
Thanks, @TomerPacific. Adding the ability to specify ALT text in Mattermost is a product feature request. I'm going to close this issue.
