### ISSUE TITLE
2021/22 Recommended Hardware Sizing Update

### ISSUE THREAD

**Issue by sadohert** [mattermost/docs#5334]
This is a placeholder issue to track changes required to our recommended hardware sizing (we can point our recent KB article to this)

We have:

1. https://docs.mattermost.com/scale/scaling-for-enterprise.html
2. https://docs.mattermost.com/install/software-hardware-requirements.html#hardware-requirements
3. Example configurations in [this LucidChart Diagram](https://lucid.app/lucidchart/invitations/accept/inv_133cfbe3-4ccd-4b5a-aa3a-baf5e1da4af4) (Mattermost internal file used in docs)?

_Note - We shouldnt' assume the above is an exhaustive list.  We should dig for other areas that need updated as well_

As an input, we also have a definition of the setups Mattermost uses in our load testing here:

* https://github.com/mattermost/mattermost-load-test-ng/blob/master/docs/setups.md

@neillcollie will be looking at how to take the load test setups and project it into the concrete values in the listed docs.

cc @cwarnermm @esethna

**Comment by esethna** [comment]
Thanks @sadohert. @cwarnermm let's work on this when we come back in the new year. 

Also looping in @nab-77 given the impacts to distribution/deployment

**Comment by cwarnermm** [comment]
@sadohert - Is there an update available for this docs request? Do you or members of your team have updated hardware sizing details available for inclusion in the docs?

**Comment by esethna** [comment]
cc// @nab-77 @sadohert @zefhemel ^
