### ISSUE TITLE
Request for Documentation: migrate from on-prem to cloud

### ISSUE THREAD

**Issue by dddw** [mattermost/docs#5335]
Due to company changes we want to move our on-prem mattermost server to the cloud-hosted one.
really couldn't find how to migrate that.

**Comment by svelle** [comment]
Hey @dddw we've got some documentation on that in our support team's knowledge base: https://support.mattermost.com/hc/en-us/articles/4412503667604

Feel free to reach out if you're still having trouble after this by opening a ticket through the support center or via email.
