### ISSUE TITLE
Clarify the possibility for GitLab SSO 

### ISSUE THREAD

**Issue by oguera** [mattermost/docs#5338]
[This page](https://docs.mattermost.com/onboard/sso-gitlab.html) states that GitLab SSO is available in all tiers as it was previously with MM Versions <6.0

However the page also states that the GitLab SSO Auth is using OAuth2 which is deprecated and should be replaced by OpenID Connect. I updated a MM Instance from 5.39 to 6.0 and GitLab SSO is still working (and even has a dedicated place in the system console sidebar).

[This page](https://docs.mattermost.com/onboard/convert-oauth20-service-providers-to-openidconnect.html), which links from the GitLab SSO documentation, states that OpenID Connect requires the Enterprise or Professional Tier.

To me as the reader of the documentation it's not clear if
1) GitLab SSO stays "first class citizen" and is available for every tier including the free tier
2) If not: At which point in time GitLab SSO will be available with a paid tier only

I think this should be clarified on the GitLab SSO page (https://docs.mattermost.com/onboard/sso-gitlab.html)

:v:

**Comment by cwarnermm** [comment]
Documentation updated via https://github.com/mattermost/docs/pull/5317.

**Comment by cwarnermm** [comment]
Documentation updated via https://github.com/mattermost/docs/pull/5317.
