### ISSUE TITLE
Update Changelog Known Issues

### ISSUE THREAD

**Issue by amyblais** [mattermost/docs#5339]
Add the following entry for v6.2 Known Issues section (for [self-managed changelog](https://docs.mattermost.com/install/self-managed-changelog.html)):

"When clicking the **Upgrade to Enterprise Edition** button, the upgrade progress bar and the restart button are no longer shown once the progress reaches 100%. Thus users cannot restart the server directly from the user interface and they need to manually go to the server and restart it."

**Comment by cwarnermm** [comment]
Updated the Self-Managed Change log via https://github.com/mattermost/docs/commit/b51a688a275759125c09b793328fdfaebbc8339e#diff-eba248b2c1a66750343693c8d84e6909fc3c26f299880afcc7261837a0465323

**Comment by amyblais** [comment]
Thank you Carrie!
