### ISSUE TITLE
Add Install docs for Debian 11 "bullseye"

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#5361]
Currently we only provide docs for Debian 10, however Debian 11 has been out since late last year and we haven't added docs for that yet. 

On a side note I think we shoud have both the codename "bullseye/buster" as well as the version number in the title.

**Comment by cwarnermm** [comment]
Thanks, @svelle! Is the Support team open to providing the specific install details needed for this platform?

**Comment by pipedream** [comment]
FWIW, Debian 12 bookworm is out.
