### ISSUE TITLE
Add install docs for RHEL 9

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#5363]
Same with Ubuntu RHEL 9 is also releasing ealry this year. Beta is already out so we can start testing against this version by using the RHEL 8 guide as a baseline.

**Comment by cwarnermm** [comment]
Thanks, @svelle! Is the Support team open to providing the specific install details needed for this platform?

**Comment by coltoneshaw** [comment]
@cwarnermm - On the same thought as merging the PR for Ubuntu 22.04. This would need to be done, but also, if it needs to be simplified.

**Comment by Sonichigo** [comment]
@cwarnermm Is this still available to work upon?
