### ISSUE TITLE
Keyboard Shortcuts wrongly mapped/Documentation faulty?

### ISSUE THREAD

**Issue by spaceKelan** [mattermost/docs#5385]
Hi, when I want to respond to the most recent message I need to write SHIFT UP instead of CTR SHIFT \ as described in the docu (https://docs.mattermost.com/messaging/keyboard-shortcuts.html). I use Ubuntu 20.04. I use Mattermost Desktop client 5.0.2.

**Comment by justinegeffen** [comment]
Hi @spaceKelan! Thanks for opening this issue. :) I've taken a look at the documentation and wanted to confirm whether the circled area is the one you're referring to.
![Screen Shot 2022-01-26 at 16 08 36](https://user-images.githubusercontent.com/4223530/151178110-ad8155fa-bd3e-45aa-a37e-3b4ebf0cb75f.png). If not, please let me know which content is problematic so we can assist you further. :)

**Comment by spaceKelan** [comment]
hi @justinegeffen , thank you for the quick response!

No, I refer to this one
![image](https://user-images.githubusercontent.com/51329415/151364813-48d68441-96dd-4cd1-84d1-4e730199c458.png)

Thank you :)

**Comment by spaceKelan** [comment]
sorry for the late response. Haven't use Linux in a while. I tried it again and still have the same issue. I do not use keymapping on top as far as I know. At least definitely not for that combination. The other keymappings work.

**Comment by cwarnermm** [comment]
@spaceKelan - No worries at all! If you're continuing to see an issue, I encourage you to log an issue against the [mattermost/server](https://github.com/mattermost/mattermost-server/issues) repository so that our Engineering teams can review in more detail. Thanks!
