### ISSUE TITLE
Link to documentation about group constrains

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#5404]
The `[mmctl group team disable/enable](https://docs.mattermost.com/manage/mmctl-command-line-tool.html#mmctl-group-team-disable)` commands control something called "group constrains" but it is unclear what this will do when enabled.

**Comment by cwarnermm** [comment]
@isacikgoz - Do we have documentation on group constrains that the existing mmctl docs could link to?

**Comment by isacikgoz** [comment]
Good point, I think when this is enabled if there is a group associated with the entity (eg. a Team, a Channel), the entity will be accessible for the group members. cc @mkraft

**Comment by mkraft** [comment]
https://mattermost.atlassian.net/browse/MM-42061

**Comment by cwarnermm** [comment]
Thank you, @mkraft!!
