### ISSUE TITLE
Extra step to see 'import process' status after slack import

### ISSUE THREAD

**Issue by glennschler** [mattermost/docs#5449]
Hi. There is possibly one helpful debugging step to add to the [The 6.4-documentation for migrating from slack using the mattermost mmetl tool and bulk import](https://github.com/mattermost/docs/blob/v6.4-documentation/source/onboard/migrating-to-mattermost.rst#migrating-from-slack-using-the-mattermost-mmetl-tool-and-bulk-import) section. Following line 205 `mmctl import process <IMPORT FILE NAME>` step, the addition of the `import job list` command using the `--json` flag shows status and error messages of the import process. Without the json flag, only the job status is shown.  Some status are 'error' or 'success', and if 'pending' then run the command again.

This is a helpful debugging step when status is error. The most recent job status is shown at the top of the long history, so redirecting output to a file or pipe to 'more' is suggested.

example:
`mmctl --json import job list | more`

output:
```json
[
  {
    "id": "cpxtb8taw7gbjr5kdqa7fa5ewc",
    "type": "import_process",
    "priority": 0,
    "create_at": 1646275919905,
    "start_at": 1646275933361,
    "last_activity_at": 1646275933685,
    "status": "success",
    "progress": 0,
    "data": {
      "import_file": "o9hpd5f3f7dw8y4p7ngucux1zy_mattermost-bulk-import.zip"
    }
  },
  {
    "id": "8de4dk9ikjnf8f8jm8gcdnmiow",
    "type": "import_process",
    "priority": 0,
    "create_at": 1646275821242,
    "start_at": 1646275828338,
    "last_activity_at": 1646275828359,
    "status": "error",
    "progress": -1,
    "data": {
      "error": "Error importing channel. Team with name \"testteam\" could not be found. — resource: Team id: name=testteam",
      "import_file": "o9hpd5f3f7dw8y4p7ngucux1zy_mattermost-bulk-import.zip",
      "line_number": "4"
    }
  }
]
```

https://github.com/mattermost/docs/blob/v6.4-documentation/source/onboard/migrating-to-mattermost.rst#L205-215

**Comment by cwarnermm** [comment]
Thanks, @glennschler, for logging this documentation issue, and for identifying a way to update the content to help others succeed with their migrations! Would you be open to creating a PR with this documentation update? If so, an easy way to get started is to navigate to the docs page and click on the **Edit** button to go to the source file in GitHub. From there, you'd edit the file, make your changes, and submit the PR. Let me know what you think!

**Comment by glennschler** [comment]
Yes @cwarnermm. I can submit a PR to resolve. Thanks!
