### ISSUE TITLE
Add note that mmctl user delete requires config change to work

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#5466]
By default mattermost blocks the mmctl user delete command due to a config setting that defaults to false, namely:

https://docs.mattermost.com/configure/configuration-settings.html#enable-api-user-deletion

This also goes for mmctl team delete.

We don't mention this on the mmctl page as far as I can tell, so we should add a note to make sure it's visible. There also should be a note in the error message from mmctl as it's note entirely clear what the admin needs to do when the command is run unsuccessfully.

**Comment by glennschler** [comment]
The mmctl channel delete is similar to requirements of the "user delete" and "teams delete". The command has the same config settings requirement as these two commands, so can also be improved with similar changes as PR #5503. Is it possible to submit a similar PR related to this issue, or should I create a new issue first?

**Comment by cwarnermm** [comment]
Thanks, @glennschler! You're most welcome to submit a PR for this additional documentation update. Please include me as a reviewer, and I'll ensure it's added to the v6.6 release scheduled for April 14th.
