### ISSUE TITLE
Mattermost apply error Kubernetes

### ISSUE THREAD

**Issue by cleitonpena** [mattermost/docs#5572]
Hello!

Error trying to apply mattermost-installation.yaml (v1bta1 or v1, both version) in microk8s, 1.23.

> error: unable to recognize "mattermost-installation.yaml": no matches for kind "Mattermost" in version "installation.mattermost.com/v1

> error: unable to recognize "mattermost-installation.yaml": no matches for kind "Mattermost" in version "installation.mattermost.com/v1bta1"

**Comment by amyblais** [comment]
Hi @cleitonpena, would you be open to posting this troubleshooting question either on our [troubleshooting forum](https://forum.mattermost.com/) or on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help)? One of our developers or other community members can likely help with this.

**Comment by cleitonpena** [comment]
Hello, @amyblais 
Thank you for your reply.👏
I solved  not from Mattermost's docs but from this link:
[INSTALL MATTERMOST KUBERNETES](https://computingforgeeks.com/install-and-configure-mattermost-on-a-kubernetes-cluster/#comment-10575)
