### ISSUE TITLE
User unable to join teams, & documentation is ambiguous

### ISSUE THREAD

**Issue by robrecord** [mattermost/docs#5696]
**On desktop, a user is unable to join themselves to available teams.**

The documentation [states](https://docs.mattermost.com/welcome/about-teams.html):

> A user can access the Team Selection page by also clicking the "+" icon at the bottom of their team sidebar or from the Main Menu > Join Another Team.

1. There is no "Main Menu"
2. The "+" icon does not show a list of teams (or even show at all if the user is unable to create teams). 

Thus, on desktop (app or web), a user who is past the initial welcome stage is completely unable to join themselves to available teams.

Only on the mobile (iOS) app are they able to do this.

**Comment by jprusch** [comment]
Can not reproduce. I get "Join another team" on the current team main menu and, if I'm already a member of more than one team a + button on the sidebar. Desktop app 5.1.0.

**Comment by robrecord** [comment]
Where is this main menu you speak of? Does it have the link mentioned in the docs?

**Comment by jprusch** [comment]
Click on the team name. The drop down should display: Join another team.
I'm not sure, if this is shown, if there's only one team & the user isn't allowed to create a new team.

**Comment by cwarnermm** [comment]
Thanks, @jprusch! @robrecord - Are you able to reproduce the steps @jprusch has provided? Do you feel the product documentation would benefit from an update? Would you be open to creating a PR to update the product documentation based on your user experience?

**Comment by robrecord** [comment]
Hi @cwarnermm , 

I understand that if there is an available team to join, a user should see an option to "join a team" in these two places, and there would be no such option if there were no available teams to join (except if the user has the power to create a team, in which case the plus button allows this). If the "main menu" that is referred to is the one with the team name title at the top and tiny disclosure triangle next to it, at the top of the channel sidebar, then I guess the documentation is fine - but I would suggest that this is clarified or a screenshot provided to show the location of the menu. I could open a PR if time allows, thank you.

In my situation the above is possible but **only** using the iOS app. On our mattermost installation, using the desktop (web or app) interface, the behaviour described above isn't happening. I am seeing no options for users to join teams, even when one is available.

**Comment by robrecord** [comment]
Thanks very much for this.

I forgot the issue was in the docs repo! I'll do the steps you suggested.

Thanks again!
