### ISSUE TITLE
Bug update mattermost 7.0.1

### ISSUE THREAD

**Issue by Ornella452** [mattermost/docs#5767]
Hello,

We have put the latest version of mattermost, we are having some problems:
- a user has told us that they no longer see their private messages, they are like deleted
- on our side as admin in the system console, when we are looking for a person with their id, we have no results:/

Looking at our logs, we are getting errors:

_- "err_where":"GetUser","http_code":500,"err_details":"failed to unmarshal user props: json: cannot unmarshal number into Go value of type string"}_

_- "level":"error","msg":"We encountered an error while finding user profiles.","caller":"web/context.go:105","path":"/api/v4/users /ids"
"method":"POST","err_where":"GetUsersByIds","http_code":500,"err_details":"failed to find Users: sql: Scan error on column index 16, name \"Props\": json: cannot unmarshal number into Go value of type string"}_

Are we the only ones who encounter these errors?

Thank you in advance for your answers

**Comment by justinegeffen** [comment]
Hi @Ornella452. I'm sorry you're experiencing this issue - it sounds very frustrating. As this is not directly related to the documentation, would you be open to posting this issue in the [Developers: Channels](https://community.mattermost.com/core/channels/messaging) channel on our Community server? Another option is to take a look at our [Support knowledgebase](https://support.mattermost.com/hc/en-us) and open a ticket for assistance. 

I hope this information helps!
