### ISSUE TITLE
Define "Workspace"

### ISSUE THREAD

**Issue by it33** [mattermost/docs#5843]
Need somewhere in the docs to define a workspace, and link to relevant information about a workspace. Trying to update docs and can't find a definition. 

Apologies if I missed one that's in there somewhere.

**Comment by cwarnermm** [comment]
@it33 - Good catch on this gap. We'll add a definition of a workspace to https://docs.mattermost.com/guides/welcome-to-mattermost.html.

**Comment by justinegeffen** [comment]
Thanks for raising this, @it33. For some additional context, there [is a page in the Handbook](https://handbook.mattermost.com/operations/research-and-development/product/technical-writing-team-handbook/our-terminology) that covers the work we're doing around terminology and it has a link to the [Google project doc](https://docs.google.com/document/d/1ImzS3UhCkFzMF2-6FNByw9W2r8Gvx1sudBA0FjazVH0/edit#heading=h.crjl4fz9pz1n) if that helps in the meantime. 

@cwarnermm, awesome idea! Very much in agreement that this should be in the user docs. :)
