### ISSUE TITLE
Help Wanted: Display code copy button for all inline code formatted text

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5912]
**Problem space**
Currently, visitors on the product documentation site can only use the copy code option for code blocks. This option isn't available for inline formatted code text lines.

Code block copy option in published documentation:
![image](https://user-images.githubusercontent.com/74422101/194125776-e227cc93-f329-4e22-93a5-4097458026f7.png)

Inline code text with no copy option:
![image](https://user-images.githubusercontent.com/74422101/194126138-d39c4189-7055-49d3-853f-1120a2492528.png)

**Target audience**
All users, and particularly system admins, developers, and integrators.

**Goal**
Enable the copy code option on all code samples across the product documentation site.

**Delivery expectations**
- 1 PR with all proposed changes
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- Sphinx
- RST, MD formats
- See the [documentation PR](https://github.com/mattermost/docs/pull/5569) that introduced the code copy extension to the tech stack and the documentation site for details. 
- The request is to extend this functionality so that the copy code option appears on inline formatted code as well as code blocks.

**Affected repository**
mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket.

**Comment by jpphilips** [comment]
Hello, I would like to work on this issue.

**Comment by lindy65** [comment]
Thanks @jpphilips - I've assigned the issue to you. Let @cwarnermm know if you have any questions :)

**Comment by jpphilips** [comment]
If I understand the issue correctly, I'm supposed to modify the sphinx extension to effect the change. yes?

Specifically, I need to add the selector for the inline code text.

Going through the documentation, sphinx adds the copy button to the code block because it matches the selector "div.highlight pre" while the inline code is a span with a class of "pre". 

What i'm thinking is to set the selector to "div.highlight pre, span.pre"

**Comment by justinegeffen** [comment]
Yep, that sounds right, @jpphilips! We do have a preview server that spins up on PRs, so it's easy to see the change before it's merged. :)

**Comment by cwarnermm** [comment]
@jpphilips - I'm excited to see what you come up for this documentation ticket! I suspect that modifying the copy/paste extension code is a good way through. What I'm less sure about is how that the copy copy option will look on the page once applied to inline formatted code examples.

**Comment by jpphilips** [comment]
I made a PR. Pls check and see if I made the PR the right way

**Comment by cwarnermm** [comment]
@neflyte - Are you open to reviewing this PR from a technical perspective?

**Comment by justinegeffen** [comment]
@neflyte, the PR is here (I couldn't add you as a reviewer for some reason): https://github.com/mattermost/docs/pull/5927

**Comment by cwarnermm** [comment]
Closing this ticket because it intended to introduce a copy/paste option for inline code text across the product documentation site. We're going to change direction on this and look to convert these code examples to code blocks for consistency and predictability instead.
