### ISSUE TITLE
Help Wanted: Extend code copy button option to display a mouse pointer icon

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5913]
**Problem space**
Currently, it's not necessarily obvious that the code copy option available for code blocks is selectable/clickable/tappable for code samples.

**Target audience**
All users, and particularly system admins, developers, and integrators.

**Goal**
Incorporate a mouse pointer icon that displays when the user hovers over the copy code option on code samples.

**Delivery expectations**
- 1 PR with all proposed changes
- See the [developer docs PR](https://github.com/mattermost/mattermost-developer-documentation/pull/1118/commits/963a7405a08f29ac0418bca5fe2b4ec2585d2bef) where this update was applied, and repurpose the code to make the code copy button on the product documentation site function in the same way. 
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- CSS, 
- RST, MD formats

**Affected repository**
mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket.

**Comment by Mustafa-Azad025** [comment]
Hey @cwarnermm ,
Will You Provide The Path To Code To Modify .
and Please Assign This Task To Me I Will Try To Solve This Issue

**Comment by neflyte** [comment]
@Mustafa-Azad025 You will need to add a CSS style for one or both of `.highlight:hover button.copybtn` and `.highlight button.copybtn:hover` selectors to the `source/_static/mytheme.css` file; those styles should cover the cases where the user hovers over the copy button.

**Comment by Mustafa-Azad025** [comment]
Ok I will see it

**Comment by Mustafa-Azad025** [comment]
Hi @cwarnermm ,
I Have Added The Hover Effect As You Said Please Merge the Code 
and Thanks For Giving Me Opportunity.

**Comment by cwarnermm** [comment]
Thanks, @Mustafa-Azad025! Can you share a link to your PR with these changes, please?

**Comment by Mustafa-Azad025** [comment]
Which link mam??

**Comment by Mustafa-Azad025** [comment]
I Have Again Push Changes and This Is The Link .Please Merge In Your Repo.
https://github.com/mattermost/docs/pull/5928

**Comment by cwarnermm** [comment]
This ticket is up for grabs.

**Comment by TomerPacific** [comment]
Hey @cwarnermm, would you like assistance with this?
