### ISSUE TITLE
Help Wanted: Open all external links in a new browser tab

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5915]
**Problem space**
Currently, links to external sites from the Mattermost product documentation take the visitor away from [docs.mattermost.com](http://docs.mattermost.com/).

**Target audience**
All users

**Goal**
All external links across the product documentation site open in a new browser tab, rather than the current tab.

**Delivery expectations**
- 1 PR with all proposed changes
- Leave all links to other pages of the product documentation site as-is.
- Links to the Mattermost Developer or API documentation sites count as an external site link and should be updated.
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- HTML, 
- RST, MD formats
- Sphinx

**Affected repository**
mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket.

**Comment by Abhishek-Vaidya** [comment]
I can help in solving this issue can you assign me this issue?

**Comment by cwarnermm** [comment]
Happy to have your help with this documentation improvement, @Abhishek-Vaidya!

**Comment by Abhishek-Vaidya** [comment]
can I know the path of the HTML and JavaScript files of the website, so that I can edit it and solve your issue? I was unable to find these files.

**Comment by neflyte** [comment]
HTML templates can be found in `source/templates`, and CSS/JS files can be found in `source/_static`.

**Comment by cwarnermm** [comment]
Hi @Abhishek-Vaidya! One approach to a ticket like this might be to format all links site-wide to open in a new tab. However, this particular documentation site features a mix of links that point to other pages of the same doc set as well as external links to other websites. With this in mind, formatting all links to open a certain way may impact more links than intended.

Another approach to this ticket may include encoding only the external links on a given docs page to open in a new tab. This would ensure that only the links that include such configuration would open that way, and all other links would open within the same tab.

**Comment by cwarnermm** [comment]
@Abhishek-Vaidya - Are you actively working on this ticket?

**Comment by cwarnermm** [comment]
This ticket is up for grabs.

**Comment by devharipragaz007** [comment]
I'm ready to grab this issue. Please assign this to me.

**Comment by cwarnermm** [comment]
Thank you, @devharipragaz007!

**Comment by chessmadridista** [comment]
Hi @cwarnermm and @devharipragaz007, may I also contribute to this ticket if it is still open?

**Comment by chessmadridista** [comment]
Is this issue the same as #7059?

**Comment by cwarnermm** [comment]
@chessmadridista - Yes, it's the same issue with potentially the same root cause (pending further investigation).

**Comment by chessmadridista** [comment]
Hi @cwarnermm, I have created a PR for this issue.

Usually, how much time does it take to merge a PR?

**Comment by cwarnermm** [comment]
Thanks, @chessmadridista! Next steps for your PR is a technical and editorial review. The docs team aims to review & merge docs PRs within a business week, though timelines can vary.
