### ISSUE TITLE
Help Wanted: Convert all internal absolute links to relative links

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5916]
**Problem space**
Currently, many internal links to other product documentation pages are formatted as absolute links ``https://docs.mattermost.com/channels/save-pin-message.html`` rather than relative links in the format ``:doc:`link name </channels/save-pin-messages>` ``

When absolute links are in place, and target destination pages move within the docs site, absolute links typically break which results in the docs visitor seeing an error.

**Target audience**
All users

**Goal**
Convert all internal absolute links across the product documentation site to relative links that are less fragile when content moves across the product documentation site.

**Delivery expectations**
- 1 PR with all proposed changes
- Leave all links to other pages of the product documentation site as-is.
- All external links should be left as-is and shouldn't be updated to be relative links, including links to the Mattermost Developer or API documentation.
- Some docs pages are in Markdown format rather than RST format. The syntax needed for Markdown pages will be different from that of RST pages.
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- RST, MD
- Sphinx
- HTML

**Affected repository**
mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket

**Comment by devXprite** [comment]
Hii @cwarnermm I want to work on this Issue.

**Comment by cwarnermm** [comment]
Thank you so much, @devXprite, for helping us with this documentation improvement!
