### ISSUE TITLE
Help Wanted: Add ALT text for embedded docs videos

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5917]
**Problem space**
Currently, video collateral across the documentation site don't include ALT (alternative) text which results in video assets not being accessible to documentation visitors using screen reader technologies.

**Target audience**
All users

**Goal**
Ensure that all video collateral includes appropriate ALT text that is detected and read aloud using supported screen reader technologies.

**Delivery expectations**
- 1 PR with all proposed changes
- Many pages of Mattermost product documentation contain image assets with well-formed ALT text. Please use these pre-existing examples as a starting point.
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

Tech needed
- Sphinx
- RST, MD formats
- HTML

Affected repository: mattermost/docs

Where to get help
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket

**Comment by shikhar13012001** [comment]
I want to work on this issue @cwarnermm

**Comment by adithyaakrishna** [comment]
@cwarnermm I guess this issue has been partially fixed as part of https://github.com/mattermost/docs/pull/5918 and there was one more video that was missed I guess so added the alt text for that one wrt to the above PR 😶
