### ISSUE TITLE
Help Wanted:  Document Mattermost user administration workflows

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5923]
**Problem space**
The Mattermost Product Documentation doesn't offer comprehensive information for system administrators on how to manage users in the System Console via https://docs.mattermost.com/configure/user-management-configuration-settings.html.

**Target audience**
System administrators

**Goal**
Develop and publish comprehensive documentation on how system administrators can manage users via the System Console that describes:
- how to active/deactivate users
- how to manage a user's roles
- how to manage a user's teams
- how to reset a user's password
- how to update a user's email
- how to revoke a user's sessions
- how to search for a user to manage
- how to review a user's profile details and authentication method
- how to filter user search to narrow down results using the team and user status filters

**Delivery expectations**
- 1 PR with all proposed changes
- Use existing system admin documentation content as a guideline towards voice and tone
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- Sphinx
- Mattermost system administration
- RST format

**Affected repository**
mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket

**Comment by Valliammai-SM** [comment]
Please assign me to this

**Comment by cwarnermm** [comment]
Thank you, @Valliammai-SM, for helping us with this important documentation update for system administrators!

**Comment by ayrotideysarkar** [comment]
I want to try 
Can you assign this to me?

**Comment by cwarnermm** [comment]
@ayrotideysarkar - Are you actively working on this ticket?

**Comment by ayrotideysarkar** [comment]
Yup... Sorry @cwarnermm  my grandma's health is not well, so was busy with stuffs.. I will work on this PR and sorry for the delay 🙂

**Comment by Rutam21** [comment]
@cwarnermm I would love to take this up. Feel free to assign this to me. Also, do let me know if this will be a completely new page titled `Admin User Management` under the `Get Started` section or will these details be added to some existing page. Thanks.

**Comment by cwarnermm** [comment]
Looking forward to working with you on this, @Rutam21! Thank you! These details will be added to the administrator section of the Mattermost Product Documentation via https://docs.mattermost.com/configure/user-management-configuration-settings.html.
