### ISSUE TITLE
Help Wanted: Develop mobile v2 end user documentation for Channels user tasks

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5924]
**Problem space**
Currently, the existing [Channels end user documentation](https://docs.mattermost.com/guides/channels.html
) on focuses on the webapp/Desktop App user experience, and doesn't typically cover the user's mobile experience.

With Mattermost mobile app v2 in beta release, this is a great time to start developing end user channels documentation for tasks users would perform using the Mattermost mobile app.

**Target audience**
All mobile users

**Goal**
- for every documented end-user task that a user can perform within Mattermost Channels, write out the steps to perform the same task on Mattermost mobile v2 (android or iOS)
- goal is to publish both webapp/desktop app and mobile app end user step details to all end users regardless of the client the user prefers to use

**Delivery expectations**
- 1 PR per Channels end user documentation page 
- use the Mattermost app v2 to develop this new documentation
- use the existing **Mark channels as favorites** [documentation page](https://docs.mattermost.com/channels/favorite-channels.html) and [source code](https://github.com/mattermost/docs/blob/master/source/channels/favorite-channels.rst) as a guideline for your submission. 
- Introduce tab-based content, where the first tab focuses on a web browser/desktop app experience, and the second tab focuses on the mobile experience.
- The existing web browser content published in the documentation should be moved to the new tab you create
- Don't include screenshots, animated gifs, or videos for the mobile content since mobile v2 is in beta and is subject to change for now.
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- Sphinx
- RST format
- Mattermost Channels product functionality
- Mattermost mobile app v2 (in beta)

**Affected repository**
mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket

**Comment by ayrotideysarkar** [comment]
I want to work on this☺

**Comment by cwarnermm** [comment]
Excellent! Thanks, @ayrotideysarkar! Comment here with the next Channels documentation page you plan to work on.

**Comment by Rutam21** [comment]
Hello @cwarnermm , I would pick up the `Renaming a Channel` page to work on. Thanks.

**Comment by michizhou** [comment]
Hello @cwarnermm, I would like to work on the `Join and leave channels` page. Thanks!

**Comment by cwarnermm** [comment]
Thanks, @michizhou! I've added you as an assignee for this ticket!

**Comment by ayrotideysarkar** [comment]
Hey @cwarnermm  i want to work on channel types. 
Can you assign this to me?

**Comment by cwarnermm** [comment]
@ayrotideysarkar - Given that the Channel Types documentation page is conceptual information that explains the types of channels supported in Mattermost, and isn't a step-by-step task that users perform in-product, do you feel that this page would benefit from mobile updates?

**Comment by ayrotideysarkar** [comment]
> @ayrotideysarkar - Given that the Channel Types documentation page is conceptual information that explains the types of channels supported in Mattermost, and isn't a step-by-step task that users perform in-product, do you feel that this page would benefit from mobile updates?

Just read the channel type documentation.. I think there is no need to add mobile documentation because this documentation is more than enough.. So can i work one rename channel?

**Comment by cwarnermm** [comment]
I agree with your assessment, @ayrotideysarkar. The Rename Channel topic feels like a great fit. Please feel free!

**Comment by ayrotideysarkar** [comment]
> I agree with your assessment, @ayrotideysarkar. The Rename Channel topic feels like a great fit. Please feel free!

Thanks @cwarnermm 🙂

**Comment by ayrotideysarkar** [comment]
I want to work on Add members to a channel
 for my next one 😊
@cwarnermm and @justinegeffen

**Comment by ayrotideysarkar** [comment]
@cwarnermm I am going to work on React to messages using emojis please assign this one to me🙂

**Comment by cwarnermm** [comment]
Thanks, @ayrotideysarkar!

**Comment by cwarnermm** [comment]
@ayrotideysarkar - Please note @michizhou's note [above](https://github.com/mattermost/docs/issues/5924#issuecomment-1279667894), too. The Join and leave channels page has already been updated.

**Comment by ayrotideysarkar** [comment]
I want to work on  Share files in messages
@cwarnermm and @justinegeffen

**Comment by cwarnermm** [comment]
Thanks, @ayrotideysarkar!

**Comment by ayrotideysarkar** [comment]
@cwarnermm  can i do all the rest of the channels? 
Thanks ☺

**Comment by cwarnermm** [comment]
Please feel free to continue with any topic in channels you choose. Currently, you're the only contributor working on this ticket :)

**Comment by ayrotideysarkar** [comment]
@cwarnermm  okays 🙂

**Comment by cwarnermm** [comment]
This ticket has been fully resolved and will now be closed.
