### ISSUE TITLE
Help Wanted: Document that guest accounts support the ability to use different authentication than other user accounts

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5952]
**Problem space**
A common question system admins ask on the Community Server is whether guest accounts can be configured to use different authentication than other user accounts. This common question indicates that the product documentation is missing this information.

Answer: Yes. Admins can configure the authentication on a per user basis. For example: Guest user to remain with using local authentication while the rest of the user use LDAP/SAML. This is desirable because guest account in LDAP could be a problematic from security perspective for some customer

**Target audience**: System administrators, developers, integrators

**Goal**
Provide clear guidance on the user authentication protocols supported for Mattermost guest accounts by updating both admin-focused and end user-focused documentation pages.

**Delivery expectations**
- 1 PR with all proposed changes
- Update the system admin-focused documentation page
    - Under the [Guest authentication section](https://docs.mattermost.com/onboard/guest-accounts.html#guest-authentication), clarify that guest authentication can be different than authentication configured for other user accounts
        - Add a bullet point under **Guests can** to clarify that guests can use different authentication methods than other users
    - Update the [end user documentation page](https://docs.mattermost.com/welcome/about-user-roles.html#guest), under **Guest**, to include the new **Guests can** bullet point you added to the admin documentation
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- Sphinx
- RST format

**Affected repository**: mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket

**Comment by adithyaakrishna** [comment]
Can I take this up?

**Comment by cwarnermm** [comment]
Thanks, @adithyaakrishna. I've assigned this ticket to you!
