### ISSUE TITLE
Help Wanted: Clarify the methods of user authentication that Mattermost supports

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5954]
**Problem space**
A common question system admins ask on the Community Server is what user authentication methods are supported, and whether multiple authentication methods can be configured concurrently. This common question indicates that the product documentation is missing this information.

Answer: Mattermost supports up to four distinct, concurrent methods of authentication:
* An OpenID provider
* A SAML provider
* An LDAP instance (ex Active Directory, OpenLDAP)
* Email and Password

**Target audience**: System administrators, developers, and integrators

**Goal**
Provide clear details on what user authentication protocols are supported in Mattermost.

**Delivery expectations**
- 1 PR with all proposed changes
- Update the system admin-focused [authentication configuration page](https://docs.mattermost.com/configure/authentication-configuration-settings.html)'s introduction text to specify the 4 concurrent methods of auth supported
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- RST format
- Sphinx

**Affected repository**: mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket.

**Comment by adithyaakrishna** [comment]
Can I take this up?

**Comment by cwarnermm** [comment]
Thanks, @adithyaakrishna! I've assigned this ticket to you.
