### ISSUE TITLE
Help Wanted: Update Insights product documentation

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5956]
**Problem space**
A common question system admins ask on the Community Server is about Team Insights and whether system administrators can see more insights than end users. This common question indicates that the product documentation is missing this information.

Answer: No. While all public channels are listed for Team Insights, private channels are only included when the System Admin is a member of that channel. Private channel access, whether directly or through Team Insights, are based on membership rather than user permissions.

However, System administrators who can't see public threads without joining them first indicates that compliance export is enabled for the Mattermost deployment. When enabled, compliance export requires a record of every user having joined a channel so that a compliance system knows who has access to messages.

**Target audience**: System administrators

**Goal**
Update Insights product documentation to clarify what system admins can/cannot see via Insights > Team Insights.

**Delivery expectations**
- 1 PR with all proposed changes
- Update the [Insights documentation page](https://docs.mattermost.com/welcome/insights.html) to clarify that **Team Insights top threads** data is based on all public channels available but is based on private channel membership
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- RST format
- Sphinx

**Affected repository**: mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket.

**Comment by adithyaakrishna** [comment]
Hey @cwarnermm 
Can I take this up?

**Comment by cwarnermm** [comment]
Thanks, @adithyaakrishna! I've assigned this ticket to you.

**Comment by adithyaakrishna** [comment]
@cwarnermm I am a bit confused about the description, it says **based on all public channels available but is based on private channel membership** and the current one is **Most active threads across the team.** 

Could you please let me know if I should replace it with that new one in description?

**Comment by adithyaakrishna** [comment]
Hi @cwarnermm :)
Could you please let me know if you have any updates on this?

**Comment by cwarnermm** [comment]
Thank you for your patience, @adithyaakrishna! I recommend adding a note under the Team Insights section, after the table that alerts page visitors of the following 2 points:

- Team Insights are based on all public channels available as well as private channel membership. System Admins must be a member of private channels to see threads from those channels.

- System admins who can't see public threads without joining them first indicates that compliance export is enabled for the Mattermost deployment. When enabled, compliance export requires a record of every user having joined a channel so that a compliance system knows who has access to messages.

**Comment by cwarnermm** [comment]
@adithyaakrishna - Are you actively working on this issue?

**Comment by adithyaakrishna** [comment]
Hi @cwarnermm 
Yes, I will submit a PR regarding this issue by EOD
