### ISSUE TITLE
[Bug] - Broken Link at Self Managed Changelog Page

### ISSUE THREAD

**Issue by adithyaakrishna** [mattermost/docs#5976]
**Description:**

The link which directs to the guest accounts section at https://docs.mattermost.com/install/self-managed-changelog.html is broken

**Screenshot:**

<img width="997" alt="Screenshot 2022-10-21 at 1 44 33 AM" src="https://user-images.githubusercontent.com/23498248/197049148-8e608b4d-0a66-45b0-83d3-ac62564ac2d7.png">

**Comment by cwarnermm** [comment]
Thanks, @adithyaakrishna! Are you open to fixing this broken link?

**Comment by uravgkarthik** [comment]
@cwarnermm I am working on this one 
Can you please assign it to me
