### ISSUE TITLE
[Bug] - Broken Link at License FAQ Page

### ISSUE THREAD

**Issue by adithyaakrishna** [mattermost/docs#5977]
Description:

The anchor link at https://docs.mattermost.com/about/faq-license.html#copyright-and-licensing-of-mattermost-server-open-source-code for per our licensing policy is broken

Screenshot:

<img width="1109" alt="Screenshot 2022-10-21 at 1 48 09 AM" src="https://user-images.githubusercontent.com/23498248/197050342-3ba6cb6e-c69c-4ab4-a85a-9be25ff001ce.png">

**Comment by cwarnermm** [comment]
Thanks, @adithyaakrishna! Are you open to fixing this broken link?

**Comment by adithyaakrishna** [comment]
No problem @cwarnermm, I think I will let someone else take it up :)

**Comment by uravgkarthik** [comment]
Hi @cwarnermm 
I'm working on this 
Can you please assign it to me

**Comment by uravgkarthik** [comment]
Hi @cwarnermm 

I am not sure which of these following links is apt here 
Can you please help me here 

1. https://mattermost.com/enterprise-edition-terms/
2. https://docs.mattermost.com/about/faq-license.html

**Comment by cwarnermm** [comment]
Thanks for confirming, @uravgkarthik! Please use the second URL as the correction.

**Comment by uravgkarthik** [comment]
Thanks @cwarnermm 
Noted!
