### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by matthew-src** [mattermost/docs#5985]
The links in the README file to the Documentation Style Guide and reStructuredText Markup section are broken. The working links are:

[Documentation Style Guide](https://handbook.mattermost.com/operations/research-and-development/product/technical-writing-team-handbook/documentation-style-guide)
[reStructuredText Markup](https://handbook.mattermost.com/operations/research-and-development/product/technical-writing-team-handbook/documentation-style-guide#using-restructuredtext-markup-rst)

I am happy to fix this.

**Comment by cwarnermm** [comment]
Thank you so much, @matthew-src! We'd welcome you help fixing these broken links. I'll assign you this issue.

**Comment by matthew-src** [comment]
Great, thank you!
