### ISSUE TITLE
Help Wanted: Improve Kubernetes Operator product documentation

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5991]
**Problem space**
While the Mattermost [Kubernetes product documentation](https://docs.mattermost.com/install/install-kubernetes.html) shouldn't be a comprehensive guide for all things Kubernetes and operators, this content needs to provide clear guidance on how to have success with a Mattermost deployment that is deployed via Kubernetes.

**Target audience**: System Administrators, Developers, Integrators

**Goal**
Clear, comprehensive guidance to be successful deploying Mattermost using the Kubernetes Operator

**Delivery expectations**
- 1 PR for all changes.
- Ensure the following technical feedback is incorporated into the existing content:
    - There is a section called Deploy Mattermost in the [installation steps](https://docs.mattermost.com/install/install-kubernetes.html). 
        - There are 2 steps: create a file, use the name from that file in the second file. 
        - The confusing part for a recent customer was that they thought the value for licenseSecret should have been the file name. 
        - Instead if should be metadata → name from the mattermost-license-secret.yaml file. 
        - There is a comment mentioning name but it's not specific enough to some new Kubernetes users and it makes the experience more confusing.
    - Another point of clarity would be if we had a list/table of the default values for each of the spec.size settings.
        - For example, the customer chose 100users and had no idea that it required 3 replicas with 50 GB provisioned space. 
        - Since the customer didn't have that much space or compute nodes, they never got their database running and, instead, it only said reconciling (once they knew enough about how to even find that information).
    - Some information about how to override it would be great as well
        - Some people just want to play with the operator and not necessarily be subject to a lot of cloud-based costs for unnecessary CPU and disk. I think I see it in the Helm chart.
    - A few more prominent troubleshooting ideas would be great!
        - How to check on the install status (e.g. look at the logs for the operators)
        - What does reconciling mean?
    - Developers have their "go to" list of things to do when something doesn't work. Let's include some in this documentation too. 
    - There is a caveat [here](https://docs.mattermost.com/install/mattermost-kubernetes-operator.html#try-out-the-mattermost-operator) about not using the MinIO and MySQL operators for production. 
        - That's fair but can we recommend or provide pointers to production-grade operators from MinIO, MySQL, PostgreSQL?
        - That has scared a few customers/prospects away from the operator in general.
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- Kubernetes
- Mattermost Kubernetes Operator
- RST format
- Sphinx

**Affected repository**: mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket.

**Comment by adithyaakrishna** [comment]
@cwarnermm Can I take this up?

**Comment by cwarnermm** [comment]
We would welcome your help with this ticket, @adithyaakrishna! Thank you!

**Comment by cwarnermm** [comment]
@adithyaakrishna - Are you actively working on this ticket?

**Comment by cwarnermm** [comment]
Addressed by https://github.com/mattermost/docs/pull/6895
