### ISSUE TITLE
Help Wanted: Fix broken documentation links

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#5993]
**Problem space**
Links in product documentation to legacy changelogs are broken.

**Target audience**: system administrators

**Goal**
All links to legacy changelogs work as expected.

**Delivery expectations**
- 1 PR for all link corrections.
- Within the [Version Archive source file](https://github.com/mattermost/docs/blob/master/source/upgrade/version-archive.rst), correct the following links to the View Changelog page with an updated relative link:
    - v5.31
    - v5.30
    - v4.9.4
    - v5.0.3
    - all v4.x links
- Use other links on the page as a guideline.
- Please note that relative links don't work as expected in generated previews. Please generate the documentation locally to confirm link fixes are working.

**Tech needed**
- RST format
- Sphinx

**Affected repository**: mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket.

**Comment by zafar-hussain** [comment]
hi @cwarnermm,

please assign this issue to me.

cheers

**Comment by ayrotideysarkar** [comment]
I want to work on this☺

**Comment by cwarnermm** [comment]
Thanks, @zafar-hussain! We appreciate your help with this ticket!
