### ISSUE TITLE
No info about how to correctly install handling websocket on mattermost with NGINX

### ISSUE THREAD

**Issue by kz159** [mattermost/docs#6070]
Hi
https://docs.mattermost.com/install/installing-ubuntu-1804-LTS.html here i cant see description of option websocketURL
do i need to fill it? if i need, example of string? (like wss://example.com)
 
https://docs.mattermost.com/configure/environment-configuration-settings.html#websocket-url and can someone please point out that if you use nginx with only TLS 1.3 websocket connections will not work? For now as i can see you can use tls 1.3 WITH 1.2 NOT ONLY 1.3
https://docs.mattermost.com/install/config-ssl-http2-nginx.html - here too

maybe there are more docs that tells nothing about this tls 1.3 bug

**Comment by amyblais** [comment]
This applies for Mobile V1. Mobile V2 will support both TLS1.2 and TLS 1.3 for websocket connections.

**Comment by kz159** [comment]
@amyblais i hope that this will be indicated in docs anyway)

**Comment by cwarnermm** [comment]
Thanks, @kz159! Mobile v2 product documentation is in progress, and will note that both TLS1.2 and TLS 1.3 for websocket connections will be supported.
