### ISSUE TITLE
Help Wanted: 404 - favicon.ico is missing

### ISSUE THREAD

**Issue by azigler** [mattermost/docs#6173]
A hard refresh with developer tools open to the Network tab shows that the subdomain is missing a `favicon.ico`. It seems to be the only Mattermost docs subdomain with this issue. This issue should be fixed by adding the same `favicon.ico` from our other domains/subdomains.

Screenshot of error:

<img width="901" alt="image" src="https://user-images.githubusercontent.com/7295363/213799243-b94bf0d8-9879-4485-aa8a-5867b85e8959.png">

cc @cwarnermm

**Comment by worldworm** [comment]
The favicon is set up correctly here:
`<link rel="shortcut icon" href="_static/favicon.ico"/>`
It looks like your browser is prerendering the favicon before loading the HTML and does not know that it is not in the root directory.
PR is coming right up adding it to html_extra_path.
