### ISSUE TITLE
Help Wanted: Add example for users.json to mmctl docs

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#6180]
For the user migrate-auth command we reference a `users.json` file in the example but we never show the format of that json file.
I think an example or a description of the file/object in question would be super helpful here.

https://github.com/mattermost/docs/blob/master/source/manage/mmctl-command-line-tool.rst

**Comment by speedhs** [comment]
Interested to take this up if not fixed already.
Can you also guide me with the files I would have to work with to fix this
