### ISSUE TITLE
AWS Docker Setup Guide Issue

### ISSUE THREAD

**Issue by ChrisRomp** [mattermost/docs#623]
The AWS setup guide at docs/source/install/docker-ebs.rst specifies to select a t2.small or larger instance, and that the "options on the Additional Resources page may be left at default unless you wish to change them."  However, the t2.\* instances require a VPC environment to be configured as well, otherwise the instance will fail when it is created.

I don't know if the best solution is to recommend an m3 instance, or provide details on configuring the VPC for the setup guide.

> `Creating Auto Scaling group named: [group] failed Reason: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. Launching EC2 instance failed.`

**Comment by jasonblais** [comment]
Thanks @ChrisRomp for the note, and really sorry for the delay in responding

It looks like every account has a default VPC that will be automatically be used unless it's been deleted by the user

> In this case, we create a default VPC for you in each AWS region. Therefore, unless you create a nondefault VPC and specify it when you launch an instance, we launch your instances into your default VPC.

Source: https://forums.aws.amazon.com/thread.jspa?threadID=153112
