### ISSUE TITLE
Render markdown in search results

### ISSUE THREAD

**Issue by esethna** [mattermost/docs#625]
Currently markdown appears but does not render in search results on [docs.mattermost.com](https://docs.mattermost.com/index.html). Ideally markdown would fully render in the search results.

![image](https://cloud.githubusercontent.com/assets/14333569/19820028/9dcad3c0-9d14-11e6-8b4d-fb40713dceb9.png)

**Comment by shieldsjared** [comment]
Without having researched this, I'm not sure which will be quicker - the conversion away from markdown to pure RST, or finding a fix for this.   I'll take a cursory glance to see if there are any obvious solutions tho :)

**Comment by zeddee** [comment]
This is probably related to this sphinx-doc issue and not markdown v.s. rst: https://github.com/sphinx-doc/sphinx/issues/1618

There are three solutions in the thread:

1. Install this plugin: https://github.com/sphinx-contrib/sphinx-pretty-searchresults
2. Manually backport changes to `searchtools.js` from this commit: https://github.com/sphinx-doc/sphinx/pull/4022/files
3. Wait for Sphinx 2.0.0: https://github.com/sphinx-doc/sphinx/issues/1618#issuecomment-456175341

If we want an instant fix, I could give (1) a shot; (2) adds more magic to the docs' sphinx build, so would not recommend.

**Comment by zeddee** [comment]
Before applying `sphinxprettysearchresults` extension:
![screenshot 2019-02-01 at 1 42 04 pm](https://user-images.githubusercontent.com/6762123/52104889-6add9f80-2627-11e9-8550-de375ddda7d2.jpg)

After applying:
![screenshot 2019-02-01 at 1 39 04 pm](https://user-images.githubusercontent.com/6762123/52104907-7df06f80-2627-11e9-9cdd-c32880501ddd.jpg)

On second thought: (2) gives more control over the docs codebase, so would be more secure than installing an extension.

**Comment by avats-dev** [comment]
@jespino what's status on this, as sphinx is now on `3.2.x`?

**Comment by jespino** [comment]
@avats-dev let me check.

**Comment by jespino** [comment]
we are still using Sphinx 1.8.4, probably we should upgrade that.

**Comment by jespino** [comment]
@esethna @jasonblais what do we want to do here? Do we want to create a new ticket to upgrade this?

**Comment by jasonblais** [comment]
@jespino yes, ticket would be great

cc @justinegeffen

**Comment by justinegeffen** [comment]
> we are still using Sphinx 1.8.4, probably we should upgrade that.

We're currently in the final phases of validating the Sphinx upgrade from 1.8.4 to 3.4.3. :) This is the PR: https://github.com/mattermost/docs/pull/4373, and it looks like it resolves this issue to an extent.

**Comment by cwarnermm** [comment]
Upgrading Sphinx to 3.4.3 resulted in much better search results that include rendered markdown. Closing.
