### ISSUE TITLE
MM Omnibus - package download errors.

### ISSUE THREAD

**Issue by MynaITLabs** [mattermost/docs#6250]
I am running a new clean installation of Ubuntu 22.04.2 LTS (Jammy Jellyfish)  and downloaded the latest version of "repo-setup.sh" .  Running that script results in the following errors:

* https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.52 443]
  
* https://deb.packages.mattermost.com jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F8F2C31744774B28
Reading package lists... Done

* http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease:  is not signed.
 The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FCC7D46ACCC4CF8 
  
* http://nginx.org/packages/ubuntu jammy InRelease:  is not signed.
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62

* 'https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy Release' does not have a Release file.

* https://deb.packages.mattermost.com jammy InRelease:   is not signed.
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F8F2C31744774B28

I think the install process should be error free.  So I think there are some missing options [Trusted=yes] ?  Or GPG keys missing ?

DETAILS:
------------------

ROOT@mm2:~# ./repo-setup.sh

Adding component(s) 'universe' to all repositories.
Hit:1 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:2 https://deb.packages.mattermost.com jammy InRelease                               
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]               
Hit:4 http://mirrors.digitalocean.com/ubuntu jammy InRelease
Get:5 http://nginx.org/packages/ubuntu jammy InRelease [3584 B]                                                                       
Get:6 http://mirrors.digitalocean.com/ubuntu jammy-updates InRelease [119 kB]                                                         
Get:7 http://mirrors.digitalocean.com/ubuntu jammy-backports InRelease [107 kB]                                                       
Get:8 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease [91.6 kB]                                                          
Get:9 http://mirrors.digitalocean.com/ubuntu jammy-updates/main amd64 Packages [939 kB]                           
Get:10 http://mirrors.digitalocean.com/ubuntu jammy-updates/restricted amd64 Packages [680 kB]
Get:11 http://mirrors.digitalocean.com/ubuntu jammy-updates/universe amd64 Packages [877 kB]
Get:12 http://mirrors.digitalocean.com/ubuntu jammy-updates/multiverse amd64 Packages [9696 B]
Ign:13 https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy InRelease
Get:14 http://mirrors.digitalocean.com/ubuntu jammy-backports/universe amd64 Packages [19.5 kB]
Get:15 http://mirrors.digitalocean.com/ubuntu jammy-backports/universe amd64 c-n-f Metadata [392 B]
Get:16 http://apt.postgresql.org/pub/repos/apt jammy-pgdg/main amd64 Packages [257 kB]                            
Ign:17 https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy Release           
Ign:18 https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy/main all Packages
Ign:19 https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy/main amd64 Packages
Ign:20 https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy/main Translation-en
Ign:21 https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy/main all c-n-f Metadata
Ign:22 https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy/main amd64 c-n-f Metadata
Ign:18 https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy/main all Packages
Ign:19 https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy/main amd64 Packages
. . . . . [ deletia ] . . . .
Hit:4 http://mirrors.digitalocean.com/ubuntu jammy-backports InRelease                                                                
Get:5 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease [91.6 kB]                                                          
Get:6 http://nginx.org/packages/ubuntu jammy InRelease [3584 B]                                                                       
Hit:7 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                      
Ign:8 https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy InRelease                          
Get:9 https://deb.packages.mattermost.com jammy InRelease [3957 B]
Err:5 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FCC7D46ACCC4CF8
Err:6 http://nginx.org/packages/ubuntu jammy InRelease     
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62
Err:10 https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.52 443]
Err:9 https://deb.packages.mattermost.com jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F8F2C31744774B28
Reading package lists... Done
W: GPG error: http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FCC7D46ACCC4CF8
E: The repository 'http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://nginx.org/packages/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62
E: The repository 'http://nginx.org/packages/ubuntu jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://deb.packages.mattermost.com jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F8F2C31744774B28
E: The repository 'https://deb.packages.mattermost.com jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
ROOT@mm2:~# sudo apt install mattermost-omnibus -y

**Comment by cwarnermm** [comment]
@nab-77 - Want to get this on your radar.

**Comment by MynaITLabs** [comment]
Here's some follow up to my message above (I edited it for clarity).
Some websites with explanation and possible solutions to the above errors.
https://www.linuxfordevices.com/tutorials/linux/fix-updating-from-such-a-repository-cant-be-done-securely-error

The best solution is to fix the authenication/keys/signature files.  
However, there is a 'to be avoided' and 'less-secure' temp way to 'turn-off' checking for GPG security.

**Comment by MynaITLabs** [comment]
(Sorry, I just noticed that maybe this issue belongs instead to https://github.com/mattermost/mattermost-omnibus instead ? )

**Comment by cwarnermm** [comment]
Hi @MynaITLabs! Thank you for logging this issue. You're correct - moving this issue to the mattermost-omnibus project will ensure the right team is looking at the issue you're experiencing. Thanks!
