### ISSUE TITLE
SMTP config for docker installation, add IP range to avoid "relay access denied"

### ISSUE THREAD

**Issue by rikrdo89** [mattermost/docs#6256]
I would suggest adding to the `smtp-email.rst` documentation the need to specify the IP range `192.168.0.0/24` to the email server, because the docker installation does not use the standard docker 172.16.0.0/12 IP range. Otherwise, you will get a lot of `relay access denied` errors. 

For postfix, that would be something like this (under /etc/postfix/main.cf):
`mynetworks =  127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/24`

Also dont forget to open port 25 on your firewall.

**Comment by cwarnermm** [comment]
Thanks, @rikrdo89, for your documentation suggestion. The next step for this issue is to technically review the details you've provided with Engineering.

**Comment by cwarnermm** [comment]
@nab-77 - This may be something to consider incorporating in the upcoming Docker installation docs update.

**Comment by yesbhautik** [comment]
Needed to create file? If yes then i can start working on it.

**Comment by cwarnermm** [comment]
Docs impact note: https://docs.mattermost.com/configure/smtp-email.html#smtp-email-setup
