### ISSUE TITLE
Upstart documentation failing

### ISSUE THREAD

**Issue by jouent** [mattermost/docs#626]
I have gone through the steps outlined in section **[Set up Mattermost Server](https://docs.mattermost.com/install/prod-ubuntu.html)**. 

When I get to step 9 and run the command `sudo start mattermost`, it fails with error message:
[sudo] password for ubuntu: 
start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

The machine is running Ubuntu 16.04.1 x64 (a DigitalOcean droplet).

**Comment by it33** [comment]
I think you're using Ubuntu 14.04 instructions on Ubuntu 16.04, 

Could you try the steps here: http://forum.mattermost.org/t/ubuntu-16-04-support/2406

16.04 instructions are being drafted by the community to be added to the official docs, we'd highly appreciate any feedback you have posted to the forum--whether it worked or it didn't.

**Comment by jouent** [comment]
Thanks @it33, I was able to get over the hurdle by properly installing Upstart. I will add more comments in the forum.

**Comment by it33** [comment]
Excellent, thanks for your help!
