### ISSUE TITLE
[Help Wanted] Add search bar to mobile web experience for docs

### ISSUE THREAD

**Issue by it33** [mattermost/docs#630]
Everyone loves the new search experience for docs on desktop: 

![image](https://cloud.githubusercontent.com/assets/177788/19844345/01d82e3c-9ee9-11e6-9569-fa41f166855f.png)

It's a little more difficult to use on mobile:

![image](https://cloud.githubusercontent.com/assets/177788/19844333/e6aa79c6-9ee8-11e6-80c1-536b4751b438.png)

**Comment by jasonblais** [comment]
Closed via #665, thanks @shieldsjared!
