### ISSUE TITLE
[Help Wanted] Help fix LEFT SIDE menu button on docs.mattermost.com on mobile web

### ISSUE THREAD

**Issue by it33** [mattermost/docs#631]
Repros: 

- Go to docs.mattermost.com on mobile web and click the LEFT SIDE menu button 

![image](https://cloud.githubusercontent.com/assets/177788/19844421/c7fc03fe-9ee9-11e6-88e2-f8d4e0932cc7.png)

Observed: 

- Blank sidebar appears : 

![image](https://cloud.githubusercontent.com/assets/177788/19844376/3ef2df1a-9ee9-11e6-9edd-6b6c77b3301d.png)

Expected: 

- LEFT SIDE menu button should either not appear on docs.mattermost.com on mobile web, or it should redirect to https://docs.mattermost.com/overview/index.html

**Comment by shieldsjared** [comment]
@it33 - this issue has been resolved

**Comment by jasonblais** [comment]
Closed via #664, thanks @shieldsjared!
