### ISSUE TITLE
Help Wanted: Update MFA instructions to include other options

### ISSUE THREAD

**Issue by ewwollesen** [mattermost/docs#6315]
Currently, the page around MFA setup (https://docs.mattermost.com/onboard/multi-factor-authentication.html) seems to indicate that Google Authenticator is the only option when we support any TOTP option.  Something like:

“Users with AD/LDAP or email login can add multi-factor authentication to their account using a multi-factor authenticator app that generates Time-based One-time Passwords (TOTP), such as OneLogin, Google Authenticator, LastPass, Microsoft Authenticator app, Duo, Authy, or 1Password.”

This page should be updated to reflect that. There is also a separate Jira ticket to update the MFA setup page user's see when they configure their account.

**Comment by cwarnermm** [comment]
Thanks for logging this, @ewwollesen! I agree that we need to clarify that Google Authenticator-compatible 2FA tools are supported.

**Comment by cwarnermm** [comment]
This issue is resolved via https://github.com/mattermost/docs/pull/6375.
