### ISSUE TITLE
Scroll/Search issue on product docs pages

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#6334]
On docs.mm.com child pages beyond the landing page, the Search field in the left navigation pane appears to float above the scroll bar instead of resting at the top of the scroll bar.

![image](https://user-images.githubusercontent.com/74422101/232126082-a6594ace-99ef-4370-9145-6cbe23a4921b.png)

**Comment by cwarnermm** [comment]
@emdecr - Are you open to taking a look at this issue, please?

**Comment by emdecr** [comment]
@cwarnermm Sure thing - will get it in the queue and circle-back 👍
