### ISSUE TITLE
Refresh CLI docs to remove deprecated commands, and document new commands

### ISSUE THREAD

**Issue by sadohert** [mattermost/docs#6412]
Based on [this PR](https://github.com/mattermost/mattermost-server/pull/17995) Mattermost CLI no longer supports a number of commands that we should in the database.  The command list is in the PR, and I tested the first 2 which seem to no longer be available as of at least `7.8` (PR says `v6`).

We need to remove the docs (or perhaps file into a separate deprecated section).

There is also a class of command that has been added:

```
$ mattermost db --help
Commands related to the database

Usage:
  mattermost db [command]

Available Commands:
  init        Initialize the database
  migrate     Migrate the database if there are any unapplied migrations
  reset       Reset the database to initial state
  version     Returns the recent applied version number

Flags:
  -h, --help   help for db

Global Flags:
  -c, --config string   Configuration file to use.
```

We document  the `db init` and `db migrate` commands, but not the `db reset` (which can probably just essentially a copy of the `mattermost reset` command docs that will be removed.

**Comment by cwarnermm** [comment]
Addressed via https://github.com/mattermost/docs/pull/6561
