### ISSUE TITLE
Permission scheme export - documentation wrong, functionality still there?

### ISSUE THREAD

**Issue by TwizzyDizzy** [mattermost/docs#6459]
Hi folks,

it seems the documentation on exporting permission schemes is outdated: https://docs.mattermost.com/manage/command-line-tools.html#mattermost-permissions-export

I’m running Mattermost 7.8.5.

Unfortunately though, this command seems to be gone:

```
root@HOSTNAME /opt/mattermost # sudo -u mattermost ./bin/mattermost permissions export
Error: unknown command "permissions" for "mattermost"
Run 'mattermost --help' for usage
```

That being said, historically, a lot of commands moved to mmctl, but unfortunately this command doesn’t seem to have been migrated:

```
root@HOSTNAME /opt/mattermost # mmctl permissions
Management of permissions

Usage:
  mmctl permissions [command]

Available Commands:
  add         Add permissions to a role (EE Only)
  remove      Remove permissions from a role (EE Only)
  reset       Reset default permissions for role (EE Only)
  role        Management of roles
```

Is there currently even any way to export permission schemes in a structured way?

Cheers & Thanks for any hint
Thomas

**Comment by cwarnermm** [comment]
Hi @TwizzyDizzy! I don't believe there's an mmctl-equivalent of this CLI command. However, perhaps the ``GetAllRoles`` API endpoint would be suitable for you as a workaround? https://api.mattermost.com/#tag/roles/operation/GetAllRoles
