### ISSUE TITLE
MatterMost v5.3.1 windows 11 got issue

### ISSUE THREAD

**Issue by kingoframen2020** [mattermost/docs#6476]
Hi, I just having some issue with my MatterMost V5.3.1 on my Windows 11. When I start the app, it will take quite some time to load and show white screen. After a while, it will jump to my servers but I not able to click anythings. After a few second it turn to blue loading screen and it will keep loading forever until I clik the top part of Boards or Playbooks then I click back Channels only it work back as normal. I try uninstall and reinstall again but still the same issue. Please help
![0001](https://github.com/mattermost/docs/assets/136818183/c1c085ee-4b00-4417-a9ed-141793d0b53e)
![0002](https://github.com/mattermost/docs/assets/136818183/f9740728-0a17-4ec3-ac09-ef53bb2310ce)

**Comment by cwarnermm** [comment]
Hi @kingoframen2020 - Please log this issue against the [Mattermost Desktop](https://github.com/mattermost/desktop) GitHub repository where it will be reviewed by our Desktop Engineering team. Thanks!
