### ISSUE TITLE
Add to docs the requirement to use SSL for the copy link feature when using non https or localhost desktop app

### ISSUE THREAD

**Issue by amyblais** [mattermost/docs#6499]
The [ticket](https://mattermost.atlassian.net/browse/MM-45024) was closed since there is no solution or workaround for this specially for the desktop app. Following are the technical reasons. Pasting below comments from the developers:

"It is true that navigator.clipboard is not available for non-secure sites or for localhost, the only and widely used workaround is to use document.execCommand, (which is a deprecated api by several browsers due to the potential security risks it has), and it is already used in our code base as a fallback for the original navigator.clipboard unavailability.
The fact is that Electron uses Chromium as the running app browser and Chromium has already deprecated the document.execCommand, so clipboard is not available because the lack of certificate and document.execCommand is deprecated meaning there is no way to make it work.

TL;DR: for non https or localhost desktop app, the copy link button won’t work and there is nothing technically possible to do about this. Only option is that the customer uses a ssl certificate, even a self-signed certificate would work."

Is there anywhere in the documentation that we could add the requirement of SSL for the copy link feature?

**Comment by cwarnermm** [comment]
Addressed via https://github.com/mattermost/docs/pull/6563
