### ISSUE TITLE
Can't open mattermost desktop app (windows)

### ISSUE THREAD

**Issue by pposadagutrade** [mattermost/docs#6574]
The mattermost app quit unexpectedly. Click "Show Details" to learn more or "Reopen" to open the application again.

Internal error: Current server does not exist

![image](https://github.com/mattermost/docs/assets/141333857/c89444d5-0ae6-45de-8b81-c48446d60b30)

If I press "show details" then this:
![image](https://github.com/mattermost/docs/assets/141333857/d774b8cc-b51e-4c9e-81c9-2dcb1f46541f)

If I press "ok" then the app closes

If I press "reopen" the same error message appears.

I tried closing all "mattermost" process in task manager, restarting computer, and unistalling mattermost and installing again, but nothing helps. What could I solve this? Thanks

**Comment by cwarnermm** [comment]
Hi @pposadagutrade! Please log this product issue in the following repository:
https://github.com/mattermost/desktop if you access it using the desktop app

This repository is for the Mattermost Product Documentation, not for the product itself.
