### ISSUE TITLE
Help Wanted: Document design decision behind allowing discovery of users on the same server

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#6590]
## Context
It's possible for someone with knowledge of the Mattermost API and with regular user credentials to discover and retrieve the usernames and real names of other users on the same Mattermost server, regardless of team and channel membership.

This was a deliberate design decision because the expectation is that if security is a top concern then deployment happens in a private network.

## Docs request

Add the following note to the [Mattermost Product Documentation](https://docs.mattermost.com/):

```
**Note**: Users on the same Mattermost server can view the username and full name of other users so they can communicate with them directly, via direct messages, regardless of team membership.
```

## How you can help

Identify an appropriate place for this note to live in the product documentation, and create a docs PR to update the documentation.

**Comment by Rutam21** [comment]
@cwarnermm I would love tot ake this up. Thanks.

**Comment by cwarnermm** [comment]
Thank you, @Rutam21! Feel free to submit your docs PR for this issue as part of Hacktoberfest 2023!

**Comment by Rutam21** [comment]
Thanks @cwarnermm . I am working on this now. Will draft the PR soon.
