### ISSUE TITLE
Help Wanted: Clarify the impact of changing rate limit settings

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#6591]
## Context

The current [rate limiting product documentation](https://docs.mattermost.com/configure/environment-configuration-settings.html#rate-limiting) describes the configuration settings available to configure rate limiting. However, the documentation doesn't detail the impact of changing these settings.

## Docs request

Answer the following questions in the product documentation:

What happens when the maximum queries per second is changed from the default of 10?
- What happens when it's increased?
- What happens when it's decreased?

What happens when the maximum burst size is changed from the default of 100?
- What happens when it's increased?
- What happens when its decreased?

What happens when the memory store size is set to a value that doesn't match the number of users in the system?
- What happens when it's higher?
- What happens when it's lower?

## How you can help

Create a PR to update the documentation with these answers.

**Comment by TomerPacific** [comment]
Hey @cwarnermm , I'd like to help with this. Any pointers to the code where I can look for answers to these questions?

**Comment by cwarnermm** [comment]
Hi @TomerPacific! I recommend asking this question in the [Hacktoberfest](https://community.mattermost.com/core/channels/hacktoberfest) channel on the Mattermost Community Server where our community may be able to help guide you further.
