### ISSUE TITLE
Help Wanted: Document how Mattermost stores an Active Directory ObjectGUID

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#6595]
## Context

Mattermost product documentation doesn't include details on Mattermost stores an Active Directory ObjectGUID.

## Docs request

Update the existing [SAML Single Sign-On technical documentation FAQs](https://docs.mattermost.com/onboard/sso-saml-technical.html#frequently-asked-questions) to add the following FAQ:

```
Question: Why does the ObjectGUID of a user in Mattermost differ from what I'm seeing in ADFS?
Answer: The Active Directory Object-Guid attribute (LDAP display name `objectGUID`) is a 16 byte array which can be displayed in different ways. However, only Microsoft changes the encoding of the ObjectGUID. All the others keep it the same except for the different base (octal, decimal, hex), as follows:

* The `ldapsearch` linux command displays it as base 64: `Hrz/HqNKnU+lCNTYHx9Ycw==`. This is also the format used in LDIF files.

* The [LDAP Golang package Mattermost uses](https://github.com/go-ldap/ldap)  emits the value as hexidecimal (base 16) array, with each byte separated by a backslash: `\1e\bc\ff\1e\a3\4a\9d\4f\a5\08\d4\d8\1f\1f\58\73`

    You can remove the backslashes (`1ebcff1ea34a9d4fa508d4d81f1f5873`) and parse it with [Golang like this](https://play.golang.org/p/9b8iDPuz0Nm). The snippets prints the base 10 representation of each value: `[30 188 255 30 163 74 157 79 165 8 212 216 31 31 88 115]`

* Windows Powershell displays the value like this: `1effbc1e-4aa3-4f9d-a508-d4d81f1f5873`
```

## How you can help

Create a docs PR to update the documentation with these details.

**Comment by speedhs** [comment]
Is it completed?

**Comment by cwarnermm** [comment]
Hi @speedhs. This issue is available. Are you interested?

**Comment by speedhs** [comment]
Yes I can do it. 
Do I have to build on the answer provided or simple update the docs with just the given answer?

**Comment by cwarnermm** [comment]
Thanks, @speedhs. The request here is to update the docs to add a new FAQ topic that's provided. If you have additional details to add to the answer that helps admins, we're very open to you including those details as well in your docs PR.
