### ISSUE TITLE
Help Wanted: Omnibus docs are mis-leading, claiming for Debian but it only support Ubuntu

### ISSUE THREAD

**Issue by tolgaulas** [mattermost/docs#6598]
I tried to test omnibus per the directives at the [web site](https://docs.mattermost.com/install/installing-mattermost-omnibus.html) and it gives this error

```
ERROR: Unsupported ubuntu release: "bullseye"
```

I think there should be clear notification it only supports Ubuntu, not Debian.

**Comment by cwarnermm** [comment]
@nab-77 for visibility

**Comment by nab-77** [comment]
@tolgaulas thanks for the feedback. Indeed this could be clearer.

**Comment by cwarnermm** [comment]
@tolgaulas - Are you open to creating a docs PR with this correction and clarification? We'd welcome your contribution!

**Comment by aniketh-varma** [comment]
Hi @cwarnermm, can I work on this issue?

**Comment by cwarnermm** [comment]
Thank you, @aniketh-varma! We welcome your contribution to this ticket! I've assigned it to you.

**Comment by Rutam21** [comment]
@cwarnermm As there's no progress on this issue for the past 2 weeks, I would like to pick this up. Thanks.

**Comment by cwarnermm** [comment]
@aniketh-varma - Are you actively working on this issue? If you're not, another contributor has expressed interest in picking it up. Thanks.

**Comment by SanchitMahajan236** [comment]
Can you please assign this issue to me @cwarnermm ? I am looking forward to contributing to this issue.
