### ISSUE TITLE
Help Wanted: Personal access token docs have outdated screenshots

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#6653]
## Context

The screenshots on the following docs page are outdated and reference menus that don't exist in that state anymore (security/token settings have moved from account to profile options):

https://developers.mattermost.com/integrate/reference/personal-access-token/

## Docs request

- Update the docs page with new product screenshots in PNG format.
- Review the docs and GitHub code for any other instances of these specific screenshots being outdated.
- Ensure that ALT text is updated as needed.

## How you can help

- Use the Desktop App, the standard Mattermost **Denim** theme, and **US English** for all official docs screenshots.
- Don't draw arrows, lines, or call outs on screenshot images. (And please don't save and use the screenshots included in this issue. They're here as a guideline.)
- Replace existing screenshot filenames via ``/images``.

**Comment by ayrotideysarkar** [comment]
Can I work on this as well?

**Comment by aniketh-varma** [comment]
Hi @cwarnermm, I would like to work on the issue, if it is still up for grabs.

**Comment by cwarnermm** [comment]
Thank you, @aniketh-varma! We welcome your contribution to this ticket! I've assigned it to you.

**Comment by aniketh-varma** [comment]
Hi @cwarnermm, while going through the codebase of the docs repo, I found that the Personal Access Tokens page which is referred to above (https://docs.mattermost.com/developer/personal-access-tokens.html#creating-a-personal-access-token) is residing in the `docs/source/archive/personal-access-tokens.rst`. Please confirm if I am updating the screenshots in the correct file.
Also FYI, I wanted to point out that the content on the page would not match with the updated screenshots.

**Comment by Rutam21** [comment]
@cwarnermm This issue has been idle for a while now. I would love to pick this up. Thanks.

**Comment by aniketh-varma** [comment]
Hey @cwarnermm, I am working on this issue and will raise a PR soon. Thanks!

**Comment by Rutam21** [comment]
@cwarnermm I would love to take this up and update the screenshot for this page. Feel free to assign this to me. Thanks.

**Comment by cwarnermm** [comment]
Thank you, @Rutam21!!
