### ISSUE TITLE
Help Wanted: Document how to contribute Focalboard translations

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#6656]
## Context

Mattermost Boards has transitioned to a community supported plugin called [Focalboard](https://github.com/mattermost/focalboard). This plugin's string translations are no longer managed using the [Mattermost Translation Server](https://translate.mattermost.com/).

## Docs request

Update the [Focalboard GitHub repository README](https://github.com/mattermost/focalboard#focalboard) to add a new section on how to contribute translations to this plugin as a language expert.

## How you can help

- Identify the process for contributing translations to Focalboard.
- Create a pull request against the Focalboard repository to update the README with the new translation process.

**Comment by cwarnermm** [comment]
Hello @yesbhautik! This ticket is both an an investigation and documentation request. We're looking for contributors open to learning the process first-hand, and then documenting that process in the repository README. Thanks!

**Comment by TomerPacific** [comment]
@cwarnermm - If @yesbhautik is not working on this issue, I'd like to help out.

**Comment by cwarnermm** [comment]
@yesbhautik - Please let us know if you're actively working on this issue. We'll make it available to other contributors if you aren't. Thanks!

**Comment by TomerPacific** [comment]
Hi @cwarnermm , I opened a [PR](https://github.com/mattermost/focalboard/pull/4918).
