### ISSUE TITLE
Document how to use and configure https://hub.docker.com/r/mattermost/webrtc/

### ISSUE THREAD

**Issue by harobed** [mattermost/docs#666]
Document how to use and configure https://hub.docker.com/r/mattermost/webrtc/

More information here: http://forum.mattermost.org/t/where-is-the-mattermost-webrtc-documentation/2508

**Comment by enahum** [comment]
Hi @harobed I updated the mattermost/webrtc docker image to fix the issues not able to connect also created a new [Github repo](https://github.com/mattermost/mattermost-webrtc) for creating the docker image and soon a Vagrant machine. In the repo you'll find documentation on how to setup WebRTC in mattermost
