### ISSUE TITLE
Your https://api.mattermost.com crashing all browsers (Firefox/Brave/Chrome/Edge) on 13900K/128GB DDR4

### ISSUE THREAD

**Issue by mm86133** [mattermost/docs#6735]
Using your documentation is simply impossible, it will freeze for 5-30seconds on all browsers.

Tested on windows 10:
- Firefox
- Brave
- Chrome
- Edge

Seems that it cannot even finish the Google PageSpeed Insights https://pagespeed.web.dev/ so it is not my machine, but it doesn't work properly on all machines if Google cannot measure metrics for it.

Clearly a serious bug. Please clean up this.

**Comment by cwarnermm** [comment]
Thanks @mm86133. Using Firefox 119.0 (64-bit) on Mac and Chrome Version 118.0.5993.88 (Official Build) (arm64) on Mac, and not seeing the freeze you've described.

Any additional reproduction steps/details you can provide will be useful towards identifying and addressing the root cause.
