### ISSUE TITLE
Include mention of `page_load_context` in Performance Monitoring docs

### ISSUE THREAD

**Issue by mickmister** [mattermost/docs#6748]
We added a label `page_load_context` to `mattermost_api_time` metric, that helps approximate which requests are coming from the client during page load or during reconnect. It was added in https://github.com/mattermost/mattermost/pull/24327

https://docs.mattermost.com/scale/performance-monitoring.html

**Comment by cwarnermm** [comment]
@mickmister - Are you open to creating a docs PR for this issue, modelled after the ``mattermost_http_websockets_total`` note via https://docs.mattermost.com/scale/performance-monitoring-metrics.html#login-and-session-metrics?
