### ISSUE TITLE
Missing bit in documentation (preparing database)

### ISSUE THREAD

**Issue by Hombre57** [mattermost/docs#6756]
Just to let you know, `ALTER DATABASE mattermost OWNER TO mmuser;` (see issue mattermost/mattermost#21442) is missing in [the doc](https://docs.mattermost.com/install/prepare-mattermost-database.html) (point 5). Glad Google brought me to that issue, the service can start now. (installing Mattermost via tarball on Fedora 38 with Postgres 15.1)

Anyway, thanks for this great software :1st_place_medal:

**Comment by cwarnermm** [comment]
Thanks, @Hombre57! Great catch! Are you interested in creating a docs PR to add the missing details?

**Comment by rohan-kapse** [comment]
@cwarnermm, Can i be of any help here ?

**Comment by cwarnermm** [comment]
I would welcome your help with this issue, @rohan-kapse! Thank you!

**Comment by rohan-kapse** [comment]
I'm sorry but could you elaborate exactly where i have to make changes, i'm a newbie.

**Comment by cwarnermm** [comment]
Closed via https://github.com/mattermost/docs/pull/6757
