### ISSUE TITLE
Refactor advanced logging docs

### ISSUE THREAD

**Issue by sadohert** [mattermost/docs#6767]
Team - I think we may need to look at restructuring our documentation for "Advanced Logging", "Audit Logging", and "Notification Logging".

Problem:  As an administrator I need to find the advanced logging configuration required for Mattermost service logs.

Observation:  The only documentation that describes how to use "advanced logging" functionality seems to be mainly represented by the documentation for `Audit Logs v2 (Beta)`.

For example, if I look up "Configuration Settings" related to advanced logging here - https://docs.mattermost.com/configure/environment-configuration-settings.html#output-logs-to-multiple-targets, we reference the `Audit Log V2` documentation:

<img width="1114" alt="Screenshot 2023-11-07 at 1 48 31 PM" src="https://github.com/mattermost/docs/assets/260544/537a3654-985d-4f40-b76e-bc9e641e89d7">

This feels like its asking for the admin to make assumptions they would not typically make.  Some figure it out... some need help.

The pseudocode of the docs structure now is:

* Configuration Settings for advanced logging of service logs [here](https://docs.mattermost.com/configure/environment-configuration-settings.html#output-logs-to-multiple-targets).
 * Points to configuration docs for `Audit Log V2` [here](https://docs.mattermost.com/comply/audit-log.html)
* Configuration settings for audit logging
 * Points to configuration docs for `Audit Log V2` [here](https://docs.mattermost.com/comply/audit-log.html)
* Configuration settings for advanced logging "Notifications Log" (e.g. config.json: `NotificationLogSettings.AdvancedLoggingConfig`) <- I don't think we have any documented here, but the settings are there in `config.json`

I think it would help if this was more like:

* Generic "AdvancedLogging" related configuration:  How to configured.  File vs inline `json` string.  Format options.  Endpoint options, etc.  Majority of the `Audit Log v2` page is re-usable here.
 * Link to service log specifics
 * Link to notification log specifics 
 * Link to audit log specifics
* Advanced Logging - Service Logs - Specifics:  - _I'm not sure if there's much here.  Maybe just log levels._
* Advanced Logging - Notification Logs - Specifics  - _Similar to "Service Logs", I don't know what's notifications specific... maybe nothing_
* Advanced Logging - Audit Logs - Specifics  - _Anything that was audit logging specific in the `Audit Log v2` page.  E.g., "Audit Log Levels".

**Comment by cwarnermm** [comment]
Couldn't agree more with your points, @sadohert, and really appreciate your suggested outline. 

https://github.com/mattermost/mattermost/pull/24733 introduces Advanced Logging JSON to the System Console, and this would be an ideal time to start to address the current logging gaps present in the product docs.

I propose we start drafting this content in Google Docs so that all internal stakeholders can help docs tell a clear, compelling, straightforward logging story.

**Comment by sadohert** [comment]
Sounds great.  BTW, just realized my sub bullets didn't format properly so they all look like the same level bullet...either way, loop me into the next steps.

Thanks!
