### ISSUE TITLE
Enhancement about the encryption between mattermost and is database

### ISSUE THREAD

**Issue by Gregesp** [mattermost/docs#6803]
Hello,

Could you fix the document here https://github.com/mattermost/docs/blob/master/source/configure/database-configuration-settings.rst

The information about encryption communication with database provided here :

```rst
To enable SSL:
Add &tls=true to your database connection string if your SQL driver supports it.
Add &tls=skip-verify if you use self-signed certificates.
```
is dedicated to MySQL https://dev.mysql.com/doc/refman/8.2/en/connection-options.html#option_general_ssl-mode, more specifically the GoLang MySQL Driver https://github.com/go-sql-driver/mysql#tls | https://pkg.go.dev/github.com/go-sql-driver/mysql and is implementation and possible parameter to use TLS.

You could indicate the same possibility with PostgreSQL separately :

The dedicated documentation from PostgreSQL https://www.postgresql.org/docs/current/libpq-ssl.html
and the GoLang driver for Postgres : https://github.com/lib/pq | https://pkg.go.dev/github.com/lib/pq

More specifically the SSL Mode you could integrate to the DSN :

![image](https://github.com/mattermost/docs/assets/96314812/9b4e2d98-727a-49e9-bfd6-659782b116e9)

Exemple with the encryption full mode **sslmode=verify-full** :

```md
postgres://mmuser:password@localhost:5432/mattermost_test?sslmode=verify-full&connect_timeout=10
```

**Comment by cwarnermm** [comment]
Thank you so much for your detailed, thoughtful docs issue, @Gregesp! Any interest in creating a docs PR with your proposed changes? No pressure of course, but I'm happy to help you with this PR if you're interested.
