### ISSUE TITLE
Clean up migration guide to remove some marketing verbiage

### ISSUE THREAD

**Issue by mickmister** [mattermost/docs#6816]
There are some pieces of our migration guide that contain some marketing talk comparing some competitor products, e.g. "bespoke". The task here is to remove anything that is not related to actual migration. There may be more pieces in the guide similar to this.

https://docs.mattermost.com/onboard/migrating-to-mattermost.html#migrate-to-mattermost-from-bespoke-messaging-solutions

**Comment by roaslin** [comment]
@mickmister Hi, I would like to help with this one.
What should we do with all the info that is going to be removed?
Should we keep/backup it somewhere? 
thanks :+1:

**Comment by mickmister** [comment]
Thanks @roaslin! Let me try and verify the answer for this

@cwarnermm What are your thoughts on the above? Who may be the right person to make the call for what to do with the content on this page?

**Comment by cwarnermm** [comment]
Thanks, @roaslin, for helping us with these updates! We can access previous versions of content through GitHub history, so no need to keep/backup the content we plan to delete.

Once the docs PR is available, and it's easy to visualize/review what's being removed, we can pull in internal stakeholders from Marketing and Product Management for PR reviews.

**Comment by mickmister** [comment]
@roaslin @cwarnermm Maybe we should just remove the "Why IT teams choose to leave bespoke solutions" and "Why IT teams choose Mattermost over bespoke solutions" sections

**Comment by cwarnermm** [comment]
@roaslin - Let's remove that content from the page. Thank you!

**Comment by roaslin** [comment]
@cwarnermm @mickmister I created the PR

thanks

**Comment by roaslin** [comment]
@cwarnermm :thinking: 
I followed the steps here [](https://github.com/mattermost/docs?tab=readme-ov-file#edit-content-directly-on-github)
and created the fork like that.
Maybe I am missing something else? @mickmister 
Sorry for the confusion
thanks
