### ISSUE TITLE
Incorrect examples in bindings docs page?

### ISSUE THREAD

**Issue by mmontone** [mattermost/docs#6821]
Hi. I think the examples in this page are wrong: https://developers.mattermost.com/integrate/apps/structure/bindings/

It says to use `submit` at the top, but then the examples use `call`.
And it does not work for me with `call`, but it works if I replace `call` by `submit` in the returned bindings.

Feel free to close this issue if I'm wrong.

Thanks.

**Comment by cwarnermm** [comment]
We'd welcome your help with this issue, @rohan-kapse!! Thank you!

**Comment by rohan-kapse** [comment]
@cwarnermm Thanks ! If i am not wrong the issue encountered needs "call": to be replaced with "submit" but in both slash command bindings and binding call response right ?

**Comment by cwarnermm** [comment]
That's a reasonable place to start. If you're able to verify by testing the slash command bindings and call to confirm, that would be excellent. We'll ensure our Engineering team reviews your PR for technical accuracy.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-developer-documentation/pull/1317. Thanks @rohan-kapse :+1:
