### ISSUE TITLE
Help Wanted: Plugin uploads and signatures not supported in Cloud deployments

### ISSUE THREAD

**Issue by jesespi** [mattermost/docs#6830]
Update the following [Plugin Managment](https://docs.mattermost.com/configure/plugins-configuration-settings.html#plugin-management) configuration settings documentation to note that these config settings aren't supported in Mattermost Cloud.
- [Require plugin signature](https://docs.mattermost.com/configure/plugins-configuration-settings.html#require-plugin-signature)
- [Upload plugin](https://docs.mattermost.com/configure/plugins-configuration-settings.html#upload-plugin)

Use the Self-Hosted Only deployment badge for both of these configuration settings via ``/_static/badges/selfhosted-only.rst``, referencing the [Calls](https://docs.mattermost.com/configure/plugins-configuration-settings.html#calls) config setting docs and source code as a guideline.

**Comment by Rutam21** [comment]
@cwarnermm I would love to work on this. Feel free to assign this to me. Thanks.

**Comment by cwarnermm** [comment]
Thanks, @Rutam21!
