### ISSUE TITLE
Confusion with "Available in legacy Enterprise Edition E10/E20" labels

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/docs#6861]
This feature is in free version but the way it appears on https://docs.mattermost.com/configure/environment-configuration-settings.html#enable-document-search-by-content makes it seem like it's only in Enterprise Edition. Appears the same marker is used throughout many entries that are also in free version.

**Comment by cwarnermm** [comment]
Thanks, @bbodenmiller, for sharing your feedback. I can appreciate your perspective on this issue. The legacy E10/E20 italics text throughout the docs site is intended to be temporary, and will be removed in a future release.

Current subscription plan/deployment details are listed at the top of every configuration section, including [File Storage](https://docs.mattermost.com/configure/environment-configuration-settings.html#file-storage). Exceptions appear in yellow for specific configuration settings where needed.

**Comment by Rutam21** [comment]
@cwarnermm I would like to work on this and remove the unnecessary labels in italics texts throughout the docs site. We already have the `Notes` section marked in yellow around each section, so we can start doing this change now. Let me know if I am missing something here. Thanks.

**Comment by cwarnermm** [comment]
Thanks, @Rutam21 - appreciate your willingness to help. I'm following up internally on the life cycle and longevity of these legacy labels in the product documentation to understand when they can be safely removed.

**Comment by cwarnermm** [comment]
Updating styling of these labels via https://github.com/mattermost/docs/pull/6900 to reduce confusion/ambiguity.
