### ISSUE TITLE
Help Wanted: Mattermost for Microsoft Teams documentation would benefit from updated GIFs

### ISSUE THREAD

**Issue by azigler** [mattermost/docs#6907]
# Context

The Mattermost UX team has created animated GIFs that will be used to supplement existing product documentation.

# Docs Request 
Incorporate the following animated GIFs into the Mattermost Product Documentation:

1. [Mattermost for Microsoft Teams](https://docs.mattermost.com/about/mattermost-for-microsoft-teams.html) - position this image to follow the end of the first sentence under **Connect Mattermost with Microsoft Teams**.

![MSTeamsSync-channel-sync](https://github.com/mattermost/docs/assets/7295363/3eb2809f-a89b-4c3f-9f88-8add32774ffa)

2. [Collaborate within Microsoft Teams](https://docs.mattermost.com/collaborate/collaborate-within-connected-microsoft-teams.html) - position this image to follow the introductory sentence on the page.

![MSTeamsSync-DM-sync](https://github.com/mattermost/docs/assets/7295363/264aa505-5dea-4ce3-b3b0-95fbd777eb39)

# How you can help

- The [Organize conversations using Collapsed Reply Threads](https://docs.mattermost.com/collaborate/organize-conversations.html) product documentation includes an animated GIF you can use as a starting point & reference. 
- Download a copy of each animated GIF file from this docs issue.
- Create a docs PR that adds the visuals to the product documentation.
- Don't forget to include ALT Text descriptions for the new images.

**Comment by cwarnermm** [comment]
Thanks, @azigler! I agree that these animated GIFs showcase the product integration well and should be added to the product documentation to supplement the text.

There are 2 relevant docs pages for MS Teams:
- https://docs.mattermost.com/about/mattermost-for-microsoft-teams.html
- https://docs.mattermost.com/collaborate/collaborate-within-connected-microsoft-teams.html

Perhaps we add one to each page? Thoughts?

**Comment by johndavidlugtu** [comment]
@cwarnermm for the first link, it should be under `Connect Mattermost with Microsoft Teams` so as not to be confused with the embedded experience

Thanks @asaadmahmood and @azigler

**Comment by azigler** [comment]
@cwarnermm sounds like a great plan, adjusting for @johndavidlugtu's suggestion!

**Comment by azigler** [comment]
Going to move forward and knock this one out for us! 💥
