### ISSUE TITLE
Update Image on contribute to documentation section of docs

### ISSUE THREAD

**Issue by varghesejose2020** [mattermost/docs#6995]
https://docs.mattermost.com/guides/contribute-to-documentation.html
![Screenshot_2024_0321_235914](https://github.com/mattermost/docs/assets/71702982/992d95e8-5053-460d-8ab5-1b25f59370c8)

**Comment by cwarnermm** [comment]
Thanks, @varghesejose2020! You have a great eye for detail! Would you be open to creating a docs PR for this update?

**Comment by varghesejose2020** [comment]
Will check and update @cwarnermm

**Comment by cwarnermm** [comment]
@varghesejose2020 - When capturing the new Edit option on a given product documentation page, I recommend viewing the docs in light mode (as opposed to dark mode) for that capture.
