### ISSUE TITLE
Contributors Link is Broken in Join our community

### ISSUE THREAD

**Issue by apshada** [mattermost/docs#7018]
Issue in 
https://docs.mattermost.com/guides/community-chat.html
Contributors Link is Broken

Currently, it is pointing to 
https://community.mattermost.com/core/chann0els/tickets

Instead that it should point to
https://community.mattermost.com/core/channels/tickets

@cwarnermm @lindy65

**Comment by lindy65** [comment]
Thank you @apshada! This issue will count towards [QA Contributors Docathon](https://community.mattermost.com/core/pl/wg4grmbak3r598t4ux18c9ri4c).

**Comment by cwarnermm** [comment]
Fixed via https://github.com/mattermost/docs/pull/7028
