### ISSUE TITLE
Overlapping Menu for Resource and Platform

### ISSUE THREAD

**Issue by apshada** [mattermost/docs#7020]
Entry Point -: https://docs.mattermost.com/about/security.html

<img width="1439" alt="Screenshot 2024-04-02 at 11 57 22 PM" src="https://github.com/mattermost/docs/assets/49001649/f4ec0281-ee57-423e-a512-f87070b30a53">

@lindy65 @ cwarnermm

**Comment by lindy65** [comment]
Thank you @apshada! This issue will count towards [QA Contributors Docathon](https://community.mattermost.com/core/pl/wg4grmbak3r598t4ux18c9ri4c). Please direct message me (@lindy.isherwood) on the [Community server](https://community.mattermost.com/) so I can get shipping details from you for the awesome swag!

**Comment by cwarnermm** [comment]
Can no longer reproduce. Closing.
