### ISSUE TITLE
Help Wanted: Config setting notes content forces horizontal scroll

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7025]
## Current

Mattermost configuration settings documentation that contains note content that exceeds the width of available center pane forces docs visitors to scroll horizontally to read the content.

Example: https://docs.mattermost.com/configure/plugins-configuration-settings.html#ice-host-override

The horizontal scroll bar is displayed because of length of the note text. 

## Desired

Eliminate horizontal scroll bars for all impacted configuration settings documentation.

## Effort

1. Identify all Mattermost configuration settings that currently feature a horizontal scroll bar.
2. Move the note text out of the configuration setting table.
3. Format the moved note text as a standard note callout using ``..note::`` located directly after a given table. See https://github.com/mattermost/docs/blob/master/source/collaborate/collaborate-within-channels.rst for an example of the source code format for notes.
4. Deliver all changes in a single docs PR against this GitHub repository.

Reach out here on this issue if you have any questions, concerns, or encounter any blockers.

**Comment by guruprasath-v** [comment]
Hello I'e found it, May i solve this?

**Comment by guruprasath-v** [comment]
@cwarnermm Should i remove every note out of the table or only those scrolling horizontally?

**Comment by cwarnermm** [comment]
Great question, @guruprasath-v! Please prioritize the ones that cause the horizontal scrolling.

**Comment by guruprasath-v** [comment]
The problem here is: Scrolling happens relative to responsiveness
some note content are not scrolling when they responsive to lap screen, but they scrolling when they shrink to Mob devices

**Comment by cwarnermm** [comment]
That's a great point, @guruprasath-v. Given the fact that scrolling is relative to display real estate, what's your recommendation for moving forward on this issue? I think I'm hearing that all notes should be taken out of tables. Would you agree?

**Comment by guruprasath-v** [comment]
![Screenshot from 2024-10-02 23-17-14](https://github.com/user-attachments/assets/9f935bbd-f809-42ca-bad8-892b75e9cc51)

See here i have remove Note out of table but even though horrizontal space occuring

**Comment by cwarnermm** [comment]
Interesting! It's not necessarily the note text that's causing the table scroll, but potentially the code-formatted text that may be forcing a maximum table width beyond ~40 characters. What's interesting is that code-formatted text also wraps to the next line.

I have a theory for this example: If we shorten the ``config.json`` code-formatted text, the horizontal scroll will go away. Open to giving the following a try?

``config.json`` setting: 

```
PluginSettings
   Plugins
      com.mattermost.calls
         turncredentialsexpirationminutes
```

@streamer45 - If we reformatted the ``config.json`` to shorten exceptionally long code-formatted text lines as I propose above (modelled after the ``config.json`` file), any concerns about the readability or clarity of doing so for an admin?

**Comment by streamer45** [comment]
@cwarnermm It makes sense to me in terms of clarity. The main advantage I see with the dotted notation is that it resembles what an admin could use to get/set through `mmctl`, e.g.:

```
mmctl --local config get PluginSettings.Plugins.com.mattermost.calls
```

That said, for plugins specifically, that's not very consistent, as fields need to be pre-existing in the file for that to work.

**Comment by guruprasath-v** [comment]
![Screenshot from 2024-10-03 10-45-00](https://github.com/user-attachments/assets/8f521967-ce4f-4a7c-b089-fb8b353dfab6)
@streamer45 @cwarnermm After a long search, I was only able to split those properties into new lines. However, the issue is that when copying, the copied text includes line breaks. I tried several methods, but this one worked slightly better than others.
I've attached a code image for your reference.
![Screenshot from 2024-10-03 10-47-16](https://github.com/user-attachments/assets/4154cca1-fb18-48ea-b559-5077c37e051e)

**Comment by cwarnermm** [comment]
@guruprasath-v - After spending some time in the code, I completely agree with you that this is a challenging resolution to identify. The center text pane has a finite width, and content that extends beyond that limit, like code blocks and inline code-formatted text, introduces an undesired horizontal scroll result.

I've attempted another possible way forward, subject to @streamer45's feedback:

![Screenshot 2024-10-03 at 2 48 05 PM](https://github.com/user-attachments/assets/7b652ea2-72c9-4397-8901-be347441e539)

^ @streamer45 I recognize that the formatting for the ``config.json`` setting isn't ideal; however, do you feel it's clear and easy to understand to technical audiences, as formatted & documented?

@guruprasath-v - here's a screenshot of VSCode showing you source:
![Screenshot 2024-10-03 at 2 49 09 PM](https://github.com/user-attachments/assets/2c065b0f-ed9b-40a0-acc1-68790236caed)

**Comment by streamer45** [comment]
Yes, looks good to me @cwarnermm , thanks!

**Comment by guruprasath-v** [comment]
Okay @cwarnermm @streamer45, I'll try to eliminate all horizontal bars by taking notes content out of the table and adjusting the alignment in the `config.json`.

**Comment by cwarnermm** [comment]
Thank you, @guruprasath-v!!!

**Comment by guruprasath-v** [comment]
@cwarnermm Sorry for the repeated interruptions, but I need some clarity on this. Although I followed the instructions and managed to remove most of the horizontal scrollbars, there's still a horizontal bar being caused by the "link". The link is creating the problem, how can we shrink it? Is there a way to replace it with a shorter, clickable link?

![image](https://github.com/user-attachments/assets/61a253e6-a0f9-4639-bfe5-f5c9f874dc67)

**Comment by cwarnermm** [comment]
@guruprasath-v - I'm not seeing this issue via production. Long code-formatted text lines appear to wrap as expected:
![Screenshot 2024-10-15 at 11 10 44 AM](https://github.com/user-attachments/assets/4e5282db-d234-4679-928b-a07c89b87fac)

Do you have a PR I can review?

**Comment by cwarnermm** [comment]
@guruprasath-v - Do you have a docs PR I can review for this issue?

**Comment by guruprasath-v** [comment]
@cwarnermm Mam, I'm working on it and need a couple more days to prepare the PR. Please allow some additional time.

**Comment by cwarnermm** [comment]
Thanks, @guruprasath-v! Please take whatever time you need.

**Comment by guruprasath-v** [comment]
Hi @cwarnermm, I have completed the task and am working on raising a PR. I'm currently stuck on inserting the ticket. Could you please guide me on how to raise the PR?

**Comment by cwarnermm** [comment]
Hi @guruprasath-v - Take a look at [this video](https://docs.mattermost.com/guides/contribute-to-documentation.html#first-time-contributor) and let me know what questions you have about getting started.

**Comment by guruprasath-v** [comment]
I've raised PR @cwarnermm
