### ISSUE TITLE
Users can't select the Platform menu option when viewing docs on 2560 x 1440 monitor

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7029]
On a ultrawide monitor (non-curved, 32 inches), the Platform dropdown floats towards the right end of the screen rather than starting below the Platform menu as it occurs with other menu items such as Solutions, Resources and Enterprise.

Hence, the user won't be able to click on the Platform menu items as the dropdown disappears as soon as you try to move the cursor away from it towards the dropdown panel.
Current Testing Resolution: 2560 x 1440
![Screenshot 2024-04-04 002646](https://github.com/mattermost/docs/assets/74422101/0aa5447c-072c-4ee5-ba68-4b78ac8018f8)

**Comment by emdecr** [comment]
Thanks for the flags @cwarnermm – just wanted to let you know I have eyes on the tickets you assigned to me. 
Will try to get to these by end of the week. Feel free to ping me directly if something is super hot though.
