### ISSUE TITLE
Help Wanted: User sees blank page when initiating a search with no search criteria

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7031]
Click on the side bar  -->select search bar and --->click on enter(with out type any text)----> blank page is displayed. Better to show a meaningful msg on the screen.

Not limited to mobile; reproducable via product docs on any form factor.

https://github.com/mattermost/docs/assets/74422101/2ec606f4-1841-4233-bdfa-14fc5b6f21fc

# QA Validation Criteria

In a generated docs preview:
- Performing docs searches that contain nothing in the Search field returns a standard Search Results page message: "Please enter at least one search term."

**Comment by hamzawritescode** [comment]
@cwarnermm May you check my PR at https://github.com/mattermost/docs/pull/7444
