### ISSUE TITLE
Wrong link in page 

### ISSUE THREAD

**Issue by mahdiirar** [mattermost/docs#7047]
in page https://docs.mattermost.com/scale/performance-alerting.html#
'incoming webhook' is a wrong link
![image](https://github.com/mattermost/docs/assets/58485839/0e80fb43-b0f9-4954-ab72-1d6637e285bf)
![image](https://github.com/mattermost/docs/assets/58485839/955957e8-894b-42d7-8552-d5085f2a6ae8)

**Comment by cwarnermm** [comment]
Thanks for logging this issue, @mahdiirar!

We're running a Mattermost Docathon, and if you're interested in participating, this issue would count as participation. You're most welcome to join us on the [Mattermost Community Server](https://community.mattermost.com/core/pl/d6fp1zwixpg6iguixqe4zr5i5r) to learn more.

**Comment by Rutam21** [comment]
@cwarnermm I can take this up and submit a PR right away. Feel free to assign it to me. Thanks.
