### ISSUE TITLE
Prefixing channel names with tilde (~) in product docs not clear 

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7052]
We're doing this inconsistently in the docs, and where the tilde (~) does appear, the user isn't necessarily sure what we are trying to communicate by doing so.

Consider removing from docs links to specific Mattermost Community channels.

**Comment by Rutam21** [comment]
@cwarnermm I would like to work on this. Feel free to assign this to me. Thanks.

**Comment by cwarnermm** [comment]
Thank you so much, @Rutam21! Really appreciate your help with this!
