### ISSUE TITLE
Help Wanted: Entering special characters as search criteria returns "Preparing Search..."

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7053]
When performing a search using the search field, passing special characters, such as (~, +, -, :, ^) as search criteria returns a stuck screen displaying Preparing Search with no results.
![image](https://github.com/mattermost/docs/assets/74422101/c8bbd61d-636e-46da-a090-110aa0e5160a)

Ideally, the search should return "Your search did not match any documents. Please make sure that all words are spelled correctly." as it occurs with other symbols such as !, @, #, etc. when no relevant match is found.
![image](https://github.com/mattermost/docs/assets/74422101/4f6d2b27-b6cc-4575-9c9a-4955ef7b3b6b)

# QA Validation Criteria

In a generated docs preview:
- Performing docs searches that contain _only_ 1 or more special characters (and no text-based criteria) returns a standard **Search Results** page message: "Your search did not match any documents. Please make sure that all words are spelled correctly."

**Comment by TomerPacific** [comment]
Hey @cwarnermm, can I help with this one?

**Comment by cwarnermm** [comment]
Thanks, @TomerPacific! I'd appreciate your help with this!

**Comment by TomerPacific** [comment]
@cwarnermm - Does the search functionality (in general) work when working locally? Because when I try it out after running `make livehtml`, regardless of what I put in the search field, I just see Preparing search...
Is there something else I should be doing?

**Comment by cwarnermm** [comment]
Hi @TomerPacific! I've successfully gotten search to work locally by running a ``make clean html`` first, followed by a ``make livehtml``. Let me know if that works for you.

**Comment by TomerPacific** [comment]
@cwarnermm - Thanks. I have observed that when entering only one of the special characters listed above, there is an error in the console:

```
{lunr.js:2982 Uncaught 
lunr.QueryParseError {name: 'QueryParseError', message: 'expecting term or field, found nothing', start: 0, end: 1, stack: 'Error\n    at https://unpkg.com/lunr@2.3.9/lunr.js:…   at https://unpkg.com/lunr@2.3.9/lunr.js:3475:3'}
end
: 
1
message
: 
"expecting term or field, found nothing"
name
: 
"QueryParseError"
start
: 
0
stack
: 
"Error\n    at https://unpkg.com/lunr@2.3.9/lunr.js:2982:34\n    at https://unpkg.com/lunr@2.3.9/lunr.js:3475:3"
[[Prototype]]
: 
Error at https://unpkg.com/lunr@2.3.9/lunr.js:2982:34 at https://unpkg.com/lunr@2.3.9/lunr.js:3475:3
```
﻿
What I'd like to understand, is what use cases should this feature prevent? Is it only **when one of the special characters is set**? Because if I write the word something+ or +something, the behavior is correct and I see search results.

**Comment by TomerPacific** [comment]
@cwarnermm - I found this helpful [cheat sheet](https://sphinxsearch.com/docs/sphinx3.html#features-cheat-sheet) in Sphinx's documentation. There is also [this section on special characters](https://sphinxsearch.com/docs/sphinx3.html#indexing-special-chars-blended-tokens-and-mixed-codes).

It seems like Sphinx's syntax is based on word operators (I.E. And instead of +).

Let me know how you would like me to proceed with this.

**Comment by cwarnermm** [comment]
Thanks, @TomerPacific! Those are great links for deeper learning on how Sphinx search works! Thank you for sharing them. I've reached out to our [UX](https://community.mattermost.com/core/pl/1xez76z4t7r6b816fusop6ed5y) and [QA](https://community.mattermost.com/core/pl/kd16udxizbgbxbsm5cfd1dtcky) teams on the Mattermost Community Server to gather input towards next steps.

**Comment by cwarnermm** [comment]
@TomerPacific - UX has recommended that we implement a response on the page that looks roughly like this:
<img width="1209" alt="image (38)" src="https://github.com/user-attachments/assets/b224e6ae-9c3a-4d00-b171-7f183eaf6e7c">

Open to giving this a try?

**Comment by TomerPacific** [comment]
@cwarnermm - Sure, but should this be applied only for the cases of a single special character? Or do we want to alter the current logic where if a user types "something+" and search results are indeed returned?

**Comment by TomerPacific** [comment]
@cwarnermm - Did a bit more digging, and debugged the code that actually performs the search. It's abbreviated as lunr. Inside of it, I found the following:

```
lunr.QueryLexer.lexText = function (lexer) {
  while (true) {
    var char = lexer.next()

    if (char == lunr.QueryLexer.EOS) {
      return lunr.QueryLexer.lexEOS
    }

    // Escape character is '\'
    if (char.charCodeAt(0) == 92) {
      lexer.escapeCharacter()
      continue
    }

    if (char == ":") {
      return lunr.QueryLexer.lexField
    }

    if (char == "~") {
      lexer.backup()
      if (lexer.width() > 0) {
        lexer.emit(lunr.QueryLexer.TERM)
      }
      return lunr.QueryLexer.lexEditDistance
    }

    if (char == "^") {
      lexer.backup()
      if (lexer.width() > 0) {
        lexer.emit(lunr.QueryLexer.TERM)
      }
      return lunr.QueryLexer.lexBoost
    }

    // "+" indicates term presence is required
    // checking for length to ensure that only
    // leading "+" are considered
    if (char == "+" && lexer.width() === 1) {
      lexer.emit(lunr.QueryLexer.PRESENCE)
      return lunr.QueryLexer.lexText
    }

    // "-" indicates term presence is prohibited
    // checking for length to ensure that only
    // leading "-" are considered
    if (char == "-" && lexer.width() === 1) {
      lexer.emit(lunr.QueryLexer.PRESENCE)
      return lunr.QueryLexer.lexText
    }

    if (char.match(lunr.QueryLexer.termSeparator)) {
      return lunr.QueryLexer.lexTerm
    }
  }
```

You can see how the plus sign (and other symbols) have special cases there. Since this is code Sphinx is based on, I don't think we can change it.

An option I can propose is to wrap the initial call in a try/catch block and if an exception is raised print out the message you shared above.

What do you think?

**Comment by Anudhyan** [comment]
Hi @cwarnermm , if possible we can implement an autocomplete feature that dynamically suggests valid search options and highlights the invalid special characters before the user completes the search.

**Comment by cwarnermm** [comment]
Thanks, @TomerPacific. The smallest iteration here is to return the "no search results found" message recommended by UX when the user attempts to enter special characters, on their own in combination with other special characters, as search criteria.

You're correct that there's Sphinx code logic in place to take action in particular cases when special characters are used in combination with search criteria. Making changes in any way to that logic is beyond the scope of this ticket. 

In this ticket, we're looking for a way to return a simply "no results found" message to the user in cases where they enter a special character in the search filed without other text-based criteria.

**Comment by TomerPacific** [comment]
@cwarnermm - Got it. I'll post a PR soon.

**Comment by TomerPacific** [comment]
@cwarnermm - Here it is -> https://github.com/mattermost/docs/pull/7451.
