### ISSUE TITLE
Links not opening in new tab as it mentioned

### ISSUE THREAD

**Issue by devharipragaz007** [mattermost/docs#7059]
In the https://docs.mattermost.com/ page, we can a menu item for [Develop with Mattermost](https://developers.mattermost.com/) with a open in new tab icon at the end. The expected behaviour is, it should open in a new tab when we click the link.

**Reproduce**
1. Go to [Mattermost Docs page](https://docs.mattermost.com/)
2. Click the Develop with Mattermost menu at  left sidebar menu (5th menu)

**Expected Behaviour** 
It should open the link in a new tab

**Current Behaviour**
It is opening in the current tab

@cwarnermm @lindy65

**Comment by lindy65** [comment]
Thanks for logging this issue, @devharipragaz007!

We're running a Mattermost Docathon, and if you're interested in participating, this issue would count as participation. You're most welcome to join us on the [Mattermost Community Server](https://community.mattermost.com/core/pl/d6fp1zwixpg6iguixqe4zr5i5r) to learn more.

**Comment by Rutam21** [comment]
@cwarnermm I would like to work on this. Feel free to assign this to me. Thanks.

**Comment by cwarnermm** [comment]
Thank you so much, @Rutam21! Really appreciate your help with this!
