### ISSUE TITLE
How to get started with Mattermost on Kubernetes issue

### ISSUE THREAD

**Issue by nathanle** [mattermost/docs#7061]
I have followed the steps here: https://mattermost.com/blog/how-to-get-started-with-mattermost-on-kubernetes-in-just-a-few-minutes/

Issue #1: nginx controller issues with version used in the doc, corrected with v1.10 https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/cloud/deploy.yaml

Issue #2:  MySQL (https://raw.githubusercontent.com/mattermost/mattermost-operator/master/docs/mysql-operator/mysql-operator.yaml) and the dreaded "PodDisruptionBudget issue with policy/v1beta1

`{"severity":"ERROR","timestamp":"2024-04-11T01:13:47.051670512Z","logger":"kubebuilder.source","message":"if kind is a CRD, it should be installed before calling Start","kind":"PodDisruptionBudget.policy","error":"no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\"","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/presslabs/mysql-operator/pkg/controller/mysqlcluster.add\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/mysqlcluster/mysqlcluster_controller.go:107\ngithub.com/presslabs/mysql-operator/pkg/controller/mysqlcluster.Add\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/mysqlcluster/mysqlcluster_controller.go:56\ngithub.com/presslabs/mysql-operator/pkg/controller.AddToManager\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/controller.go:29\nmain.main\n\t/go/src/github.com/presslabs/mysql-operator/cmd/mysql-operator/main.go:94\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"severity":"ERROR","timestamp":"2024-04-11T01:13:47.051757961Z","logger":"mysql-operator","message":"unable to setup controllers","error":"no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\"","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/presslabs/mysql-operator/cmd/mysql-operator/main.go:95\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}`

**Comment by nathanle** [comment]
is the mysql issue a problem at github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr?

**Comment by nathanle** [comment]
Should I report #2 in the operator repo? https://github.com/mattermost/mattermost-operator

**Comment by cwarnermm** [comment]
Thank you, @nathanle, for logging this issue. This blog article is due to be archived, so while your feedback is appreciated, it won't be incorporated.
