### ISSUE TITLE
Enterprise > Cloud Enterprise menu option results in page not found error

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7065]
In the top menu, going to **Enterprise > Cloud Enterprise** takes the user to ``https://mattermost.com/solutions/enterprise/cloud/`` and shows a **Page Not Found** error.
- Enterprise Overview
- Why Upgrade to Enterprise
- Cloud Enterprise

![image](https://github.com/mattermost/docs/assets/74422101/69b84f71-7937-49c7-b724-6494060cc8d2)

After comparing the Product Docs menu with the mattermost.com menu, it's clear that the two menus differ considerably, and the web menu doesn't include **Enterprise** at all.

**Comment by emdecr** [comment]
Hey@cwarnermm – Yes, the menus have changed recently, and it's on my list to update the docs menus when I'm back in the seat tomorrow. I haven't caught up on all my messages, so Cloud not existing is weird, but maybe it got decommissioned when I was out.

**Comment by cwarnermm** [comment]
Thanks @emdecr! I believe Cloud Enterprise is missing because the Enterprise menu is missing.
