### ISSUE TITLE
GIF picker configuration settings docs still refer to Gfycat (which was replaced by Giphy)

### ISSUE THREAD

**Issue by zsrv** [mattermost/docs#7074]
Gfycat was replaced by Giphy in the GIF picker, but the documentation still refers to Gfycat.

https://docs.mattermost.com/configure/integrations-configuration-settings.html#gif-beta

**Comment by cwarnermm** [comment]
Also remove Beta label: https://mattermost.atlassian.net/browse/MM-56830
