### ISSUE TITLE
"Enable security alerts" configuration setting is shown as being in the wrong config object

### ISSUE THREAD

**Issue by zsrv** [mattermost/docs#7075]
The option to enable/disable security alerts is in the `ServiceSettings` config object in config.json, but the documentation shows this option as being in the `EmailSettings` object.

https://docs.mattermost.com/configure/environment-configuration-settings.html#enable-security-alerts

Definition in the mattermost project: https://github.com/mattermost/mattermost/blob/603c26a5bcda365917285b8f32c6982e170c5cd3/server/public/model/config.go#L331

**Comment by cwarnermm** [comment]
Great catch, @zsrv! Are you open to creating a docs PR to correct this oversight?

**Comment by zsrv** [comment]
Sure, @cwarnermm, I'd be happy to! I'll work on it this weekend.

**Comment by cwarnermm** [comment]
Thank you so much!
