### ISSUE TITLE
Update upgrade guide for TLS setup on Mattermost server

### ISSUE THREAD

**Issue by it33** [mattermost/docs#708]
If TLS is setup on Mattermost server (i.e. no NGINX) there needs to be an extra step during upgrade: https://docs.mattermost.com/install/setup-tls.html

We should either find a way to automate this step or note it in the upgrade guide. 

![image](https://cloud.githubusercontent.com/assets/177788/20871725/59888a30-ba4d-11e6-9f8c-64a407491848.png)

**Comment by jasonblais** [comment]
Added to upgrade guide for now https://github.com/mattermost/docs/pull/789
