### ISSUE TITLE
Notification settings for individual channels on MacOS and iOS

### ISSUE THREAD

**Issue by baiotti2024** [mattermost/docs#7085]
It should be possible to set preferences for notifications for individual channels on the Mattermost Desktop for MacOS and iOS (e.g., Desktop Version 5.7.0 and iOS Version 2.14.0). However, there is currently no mention of that in the documentation site.

**Comment by cwarnermm** [comment]
Hello @baiotti2024. Does https://docs.mattermost.com/preferences/manage-your-notifications.html#get-notified help? Specifically, the **Per-Channel** tab?

**Comment by baiotti2024** [comment]
Thank you @cwarnermm, it helped (and now I can do it), but here is a small suggestion to make the documentation foolproof even for dumb beginner users like me. The documentation page you mentioned states "Select the channel name, then select Notification Preferences." I suggest changing it to something like "Click/tap the channel name at the top of the page of the channel you want to edit the notification settings for, then select Notification Preferences."

What I was wrongly doing was clicking/tapping on the three dots next to the name of the channel in the channel list. There, "Notification Preferences" is not present (the only entries are "Mark as unread", "Favorite", "Mute channel", "Move to...", "Copy link", "Add members", "Leave channel"). That is what confused me.

One more possible thing to fix: In the "Per-Channel" tab of the documentation page, lines 5-8 from the top are almost identical to lines 1-4. Maybe lines 5-8 should be removed?

Thanks a lot!
