### ISSUE TITLE
[Help Wanted] Shorten "Edit on GitHub" to "Edit"

### ISSUE THREAD

**Issue by it33** [mattermost/docs#709]
The "Edit on GitHub" option seems to be causing layout issues on pages with long titles. Shortening the label probably solves a lot of corner cases.

![image](https://cloud.githubusercontent.com/assets/177788/20871803/1cfab254-ba4e-11e6-8675-7c252655b05c.png)

**Comment by tejasbubane** [comment]
I was working on this but running `make html` in the repo failed with the error:

```
writing output... [ 68%] install/heroku
Exception occurred:
  File "/Users/tejas/opensource/mattermost-docs/venv/lib/python2.7/site-packages/docutils/writers/html4css1/__init__.py", line 381, in depart_enumerated_list
    self.compact_simple, self.compact_p = self.context.pop()
ValueError: need more than 0 values to unpack
```

Same as the travis failures for #723, #724 and #725 example: https://travis-ci.org/mattermost/docs/builds/182612761

**Comment by jasonblais** [comment]
Thanks for the note @tejasbubane, I'll check what might be going on here. 

Looks like something is breaking the build on the docs repo.

**Comment by jasonblais** [comment]
Hey @tejasbubane, and sorry for the issues here.

It looks like Travis updated to a bad version of a library (which we use to build the repo) - reverting a commit that potentially caused the issue didn't help resolve it so we'll look into moving this over to Jenkins. 

Thank you so much for your interest in contributing, I'll let you know as soon as the build errors are resolved.

**Comment by jasonblais** [comment]
Hey @tejasbubane, the build errors should now be fixed.

Would you still be interested helping with a fix and participate in [our Holiday Hackfest](https://about.mattermost.com/hackfest/)?  Four PRs wins you an exclusive Mattermost shirt!

**Comment by tejasbubane** [comment]
Thanks @jasonblais PR sent.

**Comment by jasonblais** [comment]
Thank you @tejasbubane, much appreciated! We'll have a PM start the review process soon

**Comment by esethna** [comment]
Closed as resolved, thanks @tejasbubane! 

https://github.com/mattermost/docs/pull/746
