### ISSUE TITLE
Performance metrics plugin docs missing step to enable performance metrics on the server

### ISSUE THREAD

**Issue by svelle** [mattermost/docs#7155]
In the Mattermost configuration steps there is missing a step to enable the performance metrics of the mattermost server, otherwise the plugin will just not be able to collect any data.

https://docs.mattermost.com/scale/collect-performance-metrics.html#

**Comment by cwarnermm** [comment]
@svelle - On the [Collect performance metrics](https://docs.mattermost.com/scale/collect-performance-metrics.html) product docs page, under **Mattermost configuration**, step #5 instructs admins to "Go to System Console > Plugins > Plugin Management. In the Installed Plugins section, scroll to Mattermost Metrics Plugin, and select Enable Plugin."

Are additional steps needed in order for the plugin to collect data beyond what's documented?

**Comment by svelle** [comment]
@cwarnermm yes, the additional step would be to enable performance metrics in the system console 

![image](https://github.com/mattermost/docs/assets/7526550/48f4364a-e1cb-4d78-8a09-49c3574d02b5)

**Comment by cwarnermm** [comment]
Aha! Yes! Really great catch, @svelle! Thank you!
