### ISSUE TITLE
Too Many Redirects when logging in from Mobile Apps when Server is using subpath hosting

### ISSUE THREAD

**Issue by wech71** [mattermost/docs#7160]
#### Summary
Too Many Redirects when logging in from Mobile Apps when Server is using subpath hosting. Tested in 9.7.1 and with 9.7.2

#### Steps to reproduce
* Configure Mattermost Server to use subpath hosting (like https://mattermostserver/chat)
* Ensure Android App or iOS App is logged out
* Try to Connect to the server (I used gitlab authentication, but never got threre)

#### Expected behavior
Connection Form should disappear and Login form should be displayed

#### Observed behavior (that appears unintentional) 
An error is being displayed "Too many redirects (21)"

According the nginx logs a HEAD request proxied to http://mattermost/chat, which gets redirected to http://mattermost/chat/chat then to http://mattermost/chat/chat then to http://mattermost/chat/chat/

The same can be reproduced using curl:

```
curl -L -I http://mattermost-server:8065/chat/
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /chat/chat
Vary: Origin
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 100
X-Ratelimit-Reset: 1
Date: Fri, 26 Apr 2024 10:31:03 GMT

HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /chat/chat/chat
Vary: Origin
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 99
X-Ratelimit-Reset: 1
Date: Fri, 26 Apr 2024 10:31:03 GMT

HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /chat/chat/chat/chat
Vary: Origin
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 98
X-Ratelimit-Reset: 1
Date: Fri, 26 Apr 2024 10:31:03 GMT

HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /chat/chat/chat/chat/chat
Vary: Origin
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 97
X-Ratelimit-Reset: 1
Date: Fri, 26 Apr 2024 10:31:03 GMT
...

HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat/chat
Vary: Origin
X-Ratelimit-Limit: 101
X-Ratelimit-Remaining: 50
X-Ratelimit-Reset: 6
Date: Fri, 26 Apr 2024 10:31:03 GMT

curl: (47) Maximum (50) redirects followed
```

The problem also occurs when starting with http://mattermost/chat/

The problem does not occur when using a GET Request like `curl http://mattermost/chat`.  In this case the main html is correctly being retured.

#### Possible fixes

Ensure the HEAD request does no endless redirects to the subpath even when already on the subpath.

**Comment by duncan-bayne** [comment]
I don't think this has been fixed, exactly: the underlying problem still persists, all that #7188 does is document the workaround.  Could this please be re-opened?

**Comment by agnivade** [comment]
What do you propose the fix should be?

**Comment by wech71** [comment]
The fix would be to behave correctly, just like the same GET request would.

Or the other way: A HEAD request to the mattermost server beginning with the subpath (/chat/) should not perform a redirect append the subpath again and again and again ad infinitum, but respond just like a GET Request to the same path with the information about the requested resource as it does when not using a subpath.

This is definitely a bug in the mattermost server and and should not be fixed trough reverse proxy configurations.

**Comment by agnivade** [comment]
That seems reasonable. As long as an admin has set the SiteURL properly. I'll reopen the JIRA [ticket](https://mattermost.atlassian.net/browse/MM-58042) for a closer investigation. Please feel free to follow that for more updates.

Until then, I think anyone using sub-paths should be unblocked with the above workaround.

**Comment by wech71** [comment]
Thank you :-)

**Comment by alfredo87** [comment]
Same issue: suddenly two iOS clients stopped working with redirect error. Both client were reinstalled on new devices: definitely MM server error … My server is Yunohost and has never shown this error before. My URL is https://myserver.eu/mattermost and redirects at infinitum suddenly! Thanks if somebody at MM can find a solution!

**Comment by ppawiggers** [comment]
Can this issue be reopened?

**Comment by agnivade** [comment]
The JIRA [ticket](https://mattermost.atlassian.net/browse/MM-58042) is already reopened. You can follow that for more updates.

**Comment by ucola** [comment]
i have the same issue with apache as proxy, i open a topic on mattermost forum and found now the issue here on github
https://forum.mattermost.com/t/mattermost-android-app-no-connection-to-self-hosted-server/19040/8


My apache configuration is like bellow

```
RewriteEngine On
RewriteCond %{REQUEST_URI} /mattermost/api/v[0-9]+/(users/)?websocket [NC,OR]
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC,OR]
RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
RewriteRule .* ws://111.111.100.202:8065%{REQUEST_URI} [P,QSA,L]
ProxyRequests     Off
ProxyPreserveHost On
AllowEncodedSlashes NoDecode
<Proxy http://111.111.100.202:8065/mattermost*>
        Order deny,allow
        Allow from all
</Proxy>
ProxyPass         /mattermost  http://111.111.100.202:8065/mattermost nocanon
ProxyPassReverse  /mattermost  http://111.111.100.202:8065/mattermost
ProxyPassReverse  /mattermost  http://master.domain.com/mattermost
ProxyPass         /mattermost  wss://111.111.100.202:8065/mattermost
ProxyPassReverse  /mattermost  wss://111.111.100.202:8065/mattermost
```

The logs on apache (after connect with android app) you see bellow

```
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost HTTP/1.1" 302 6156 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/ HTTP/1.1" 302 242 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost HTTP/1.1" 302 253 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost HTTP/1.1" 302 264 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 275 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 286 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 297 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 308 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 319 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 330 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 341 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 352 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 363 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 374 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 385 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 396 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 407 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 418 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 429 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 440 "-" "okhttp/4.12.0"
88.254.188.101 - - [22/Jul/2024:10:22:00 +0200] "HEAD /mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost/mattermost HTTP/1.1" 302 451 "-" "okhttp/4.12.0"
```

**Comment by nicolasgoudard** [comment]
Hello
My Mattermost instance is hosted in a Docker VM behind an HAProxy, not Nginx proxy. I use a subpath for access. Since updating my server to version 9.11, the Android mobile apps have stopped working and display the message “Too many follow-up requests: 21”. As a temporary workaround, I downgraded the mobile app to version 2.14, which allows me to reconnect. However, I am looking for a more permanent solution.

Please let the ticket opened until a solution will be found.

Best regards.

**Comment by ucola** [comment]
@nicolasgoudard can confirm, with APK 2.14 on Android is working fine... so @cwarnermm can you help us?

**Comment by agnivade** [comment]
Hey all, this is the ticket: https://github.com/mattermost/mattermost/issues/27886 that was created along with the JIRA ticket. Please follow that to get updates.

**Comment by nicolasgoudard** [comment]
@agnivade : it means, today the issue is not yet fixed ?

**Comment by agnivade** [comment]
Correct.
