### ISSUE TITLE
Instruction for stopping docker container is given in developing Mattermost without docker documentation

### ISSUE THREAD

**Issue by chessmadridista** [mattermost/docs#7171]
# What is the issue?
In the section titled "Develop Mattermost without Docker" on [this link](https://developers.mattermost.com/contribute/developer-setup/#develop-mattermost-without-docker:~:text=the%20running%20docker%20containers%3A-,make%20stop%2Ddocker,-Set%20your%20options%3A%20Some), the code for stopping docker container is given.

If we are developing Mattermost without Docker, is there any need for that code snippet?

# Proposed solution

> The stop-server make target does not stop all the docker containers started by run-server. To stop the running docker containers:
> 
> ```
> make stop-docker
> ```
> 

This whole section can be removed for better readability.

**Comment by chessmadridista** [comment]
I would be happy to take up this issue if it is something that needs to be resolved.

**Comment by cwarnermm** [comment]
Thank you, @chessmadridista! I look forward to your PR.

**Comment by chessmadridista** [comment]
Hi @cwarnermm, thanks for assigning this issue to me.

I have a doubt. I noticed two websites: https://developers.mattermost.com and https://docs.mattermost.com. As per my understanding:
1. [mattermost/docs](https://github.com/mattermost/docs) repo is for making changes to https://docs.mattermost.com.
2. [mattermost/mattermost-developer-documentation](https://github.com/mattermost/mattermost-developer-documentation) is for making changes to https://developers.mattermost.com.

The change that I proposed is for developers.mattermost.com. So I need to create an issue in the other repo and this issue is not valid here. 

Please let me know if my understanding is correct.

**Comment by cwarnermm** [comment]
Your understanding is correct, @chessmadridista. Feel free to create a docs issue against the developer documentation GitHub repository. We can close this one and assign the new one to you. Thanks!

**Comment by chessmadridista** [comment]
Thank you @cwarnermm for the clarification! 

In the other repo, I created a new [issue](https://github.com/mattermost/mattermost-developer-documentation/issues/1378).
