### ISSUE TITLE
[Help Wanted] Figure out where to add Community Content Guidelines

### ISSUE THREAD

**Issue by it33** [mattermost/docs#722]
This was [removed from a PR to Community Guidelines page](https://github.com/mattermost/docs/pull/716/commits/e7d94deb7cbde16ccfaee809bcecb8ce9a5db15e). It's looking for a new home. Any thoughts? 

```
Community Content Guidelines 
==============================================================

Content from community in GitHub, Forums, Feature Ideas, Community Mattermost site or any other community content site managed by Mattermost should follow Mattermost guidelines: 

Content that is deemed to be controversial, offensive, potentially defamatory or infringing content from material distributed, broadcast, or posted on websites will be edited or removed. 

We ask the community's help in reporting any such content to feedback@mattermost.com   
```

**Comment by shieldsjared** [comment]
Interesting question, @it33!

We originally had a contributors guide, but changed it to Developer's Guide.  This is more of a "contribution-related" concept, and less of development.  Maybe a section need to be created along the lines of "Ways to contribute", where details can be provided about the many ways to contribute, which includes forum participation, development, document contributions/feedback, etc... with jumplinks to relevant sections.  I could see this potentially living under the Overview guide.

**Comment by avats-dev** [comment]
Is this still relevant?

**Comment by justinegeffen** [comment]
> Is this still relevant?

Hi @avats-dev! Apologies for the delay in responding. This content is best suited to our handbook which I have updated. However, please take a look through the rest of the open issues and let me know if you have any questions about any of them. Looking forward to working with you! :)
