### ISSUE TITLE
Generic Linux install Desktop Client instructions don't work

### ISSUE THREAD

**Issue by mxa** [mattermost/docs#7230]
The 'generic Linux' [install instructions](https://docs.mattermost.com/collaborate/install-desktop-app.html) for the Mattermost Desktop Client don't work.

_A [sic] AppImage distribution (Beta) of a compressed tarball is available. Automatic app updates are supported and enabled. When a new version of the desktop app is released, your app updates automatically._

What is it? An AppImage or a binary in a compressed tarball? Confusing wording. I expected an AppImage, but get a tarball, not an AppImage. I think the sentence should read: "An AppImage distribution AND a compressed tabball of a binary are available." Both are downloadeble here: https://github.com/mattermost/desktop/releases/tag/v5.8.1 but in the docs the AppImage gets and awkward mention convoluted with the tarball and then only the tarball is linked as a download.

Following the instructions:

_2. Extract the archive to a convenient location, then execute mattermost-desktop located inside the extracted directory._

```
$ ./mattermost-desktop 
[19564:0623/180528.261713:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/mxa/Applications/mattermost-desktop-5.8.1-linux-x64/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

**Comment by mvitale1989** [comment]
Thanks for reporting! We have included those resolution steps in the [Desktop app's tarball installation instructions](https://docs.mattermost.com/collaborate/install-desktop-app.html), as on Ubuntu Noble it seems the only way to give `chrome-sandbox` the right ownership and permissions after extracting the tarball as a non-root user.

**Comment by mxa** [comment]
Btw, I appreciate the speedy support and resolution here. That is a good user experience.
