### ISSUE TITLE
Request for documentation: desktop client changelog incomplete (v5.8.1)

### ISSUE THREAD

**Issue by iva-5-middleware** [mattermost/docs#7250]
The changelog for the desktop app is incomplete ( https://docs.mattermost.com/about/desktop-app-changelog.html ). It only contains v5.8.0, not v5.8.1, which has been cut 2-3 weeks ago.
I am very sure, that I already saw the changelog for v5.8.1 on the page in the past, but it seems to have disappeared/been overwritten.

Could this please be fixed?

Best regards!

**Comment by amyblais** [comment]
This will be fixed via https://github.com/mattermost/docs/pull/7249.
