### ISSUE TITLE
GitLab Single Sign-On page is available on all plans

### ISSUE THREAD

**Issue by itaizelther** [mattermost/docs#7291]
The [GitLab Single Sign-On](https://docs.mattermost.com/onboard/sso-gitlab.html) page shows the feature can only be used in enterprise plan, while the feature is actually available on the free plan.

**Comment by cwarnermm** [comment]
Hello @itaizelther. Single Sign-on with [GitLab](https://docs.mattermost.com/onboard/sso-gitlab.html) using the OAuth 2.0 standard is supported through our bundling with Gitlab Omnibus.
