### ISSUE TITLE
Wrong documentation regarding "MaximumPayloadSizeBytes"

### ISSUE THREAD

**Issue by trolfsmeier-di** [mattermost/docs#7292]
#### Summary
Wrong documentation in terms of config parameter "MaximumPayloadSizeBytes". The parameter is located under path "ServiceSettings". Documentation states that it is under path "FileSettings".

Also see [reality](https://github.com/mattermost/mattermost/blob/db138fd23a6984ef94201cc2635ce0cdcf191f50/e2e-tests/cypress/tests/support/api/cloud_default_config.json#L112) vs [documentation](https://docs.mattermost.com/configure/environment-configuration-settings.html#maximum-payload-size).

#### Expected behavior
Adjust the documentation so that it is clear that one has to put "MaximumPayloadSizeBytes" under "ServiceSettings".

**Comment by cwarnermm** [comment]
Thanks, @trolfsmeier-di! Are you open to creating a docs PR to correct this error?
