### ISSUE TITLE
Copy to clipboard button is too big

### ISSUE THREAD

**Issue by chessmadridista** [mattermost/docs#7306]
# Describe the issue
On [this page](https://docs.mattermost.com/install/install-ubuntu.html#:~:text=to%20add%20the-,Mattermost,-Server%20repositories%3A), the copy to clipboard button is too big. In other places, the button is an icon inside the code snippet.

---
# Possible solutions
- [ ] Remove the big button.
- [ ] Add the copy to clipboard icon in the code snippet.

**Comment by cwarnermm** [comment]
While the design of the larger copy to clipboard buttons isn't consistent with the typical code block copy icon, it is an intentional choice.
