### ISSUE TITLE
ESR says its only for enterprise plans

### ISSUE THREAD

**Issue by Movion** [mattermost/docs#7318]
In the about/release-policy.html about the ESR it says its only for Enterprise plans, which is not correct. Support plans should not have a plan mentioned in my taste as it is available for everyone so it could be removed, but thats upon you:

https://github.com/mattermost/docs/blob/6b5c2a93943e3458f2ef4d9e24da04b32cf436ca/source/about/release-policy.md?plain=1#L29

https://github.com/mattermost/docs/blob/6b5c2a93943e3458f2ef4d9e24da04b32cf436ca/source/about/release-policy.md?plain=1#L53

**Comment by cwarnermm** [comment]
Thank you for reaching out, @Movion. Yes, anyone can access extended support releases, but this is something of value, especially to our Enterprise customers. We're currently evaluating whether we should make it Enterprise only in the future.
