### ISSUE TITLE
Help Wanted: Re-create notification flow diagram source files using draw.io

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7348]
Re-create the following 3 Mattermost notification flow charts using [draw.io](https://app.diagrams.net/):

1. [Mattermost desktop notification flow chart](https://docs.mattermost.com/_images/desktop_notification_chart.png) for the [notification FAQ](https://docs.mattermost.com/about/faq-notifications.html#what-determines-if-a-desktop-notification-should-be-triggered) docs section.
2. [Mattermost email notification flow chart](https://docs.mattermost.com/_images/email_notification_chart.png) for the [notification FAQ](https://docs.mattermost.com/about/faq-notifications.html#what-determines-if-an-email-notification-should-be-triggered) docs section.
3. [Mattermost push notification flow chart](https://docs.mattermost.com/_images/push_notification_chart.png) for the [notification FAQ](https://docs.mattermost.com/about/faq-notifications.html#what-determines-if-a-mobile-push-notification-should-be-triggered) docs section.

## Guidelines
- Ensure you save a copy of each flow chart as an XML file with a ``.drawio`` file extension, so that it's an editable source file that Mattermost can modify as needed.
- Please try to replicate the appearance and scale of the current flow charts wherever possible in terms of colours, styles, fonts, etc.
- You can choose to recreate a single flow chart only, rather than owning the re-creation of all 3 flow charts, if preferred. Clearly indicate your preference by commenting on this GitHub issue.
- Comment on this GitHub issue if you encounter any questions, concerns, or blockers to request assistance.

## Out of scope

It's not necessary to:
- Save a copy of each flow chart as PNG 
- Create a docs PR to add updated flow chart images to the product documentation
- Add Mattermost logos/branding to the flow charts

# QA Verification Criteria

For each of the 3 re-created flow diagrams:
- Each uses the same colours/fonts/text and general appearance as the flow diagram published in the product documentation
- Each flow diagram is an XML file with a ``.drawio`` file extension
- Each flow diagram can be opened and edited further using Draw IO

**Comment by SarthakKeshari** [comment]
Hi @cwarnermm,
Does re-creation mean to just replicate the flow using draw.io as shown in PNG file?

**Comment by cwarnermm** [comment]
Hi @SarthakKeshari! Yes, that's correct. Our goal is to have source files for these flow diagrams that we can manage and maintain with changes where needed.

**Comment by SarthakKeshari** [comment]
Sure, May you assign this issue to me.

**Comment by cwarnermm** [comment]
Appreciate your help with this lift, @SarthakKeshari!

**Comment by SarthakKeshari** [comment]
May you let me know where in the docs repo I should place the .drawio files.

**Comment by cwarnermm** [comment]
@SarthakKeshari - Having the source files the Docs PR will be sufficient for now, thanks!

**Comment by cwarnermm** [comment]
@SarthakKeshari - Are you actively working on this issue?

**Comment by SarthakKeshari** [comment]
@cwarnermm, I have unassigned myself. Thankyou

**Comment by TomerPacific** [comment]
@cwarnermm - Is this still relevant? Has any work been done here?

**Comment by cwarnermm** [comment]
This ticket is available if you're interested, @TomerPacific! I'd appreciate your help with it!

**Comment by TomerPacific** [comment]
@cwarnermm - How does this look (as a start) for the first diagram?

![diagram](https://github.com/user-attachments/assets/07c2106f-0867-435d-be2f-d8bcfdcc7373)

**Comment by cwarnermm** [comment]
It's a great start, @TomerPacific, thank you!!

**Comment by TomerPacific** [comment]
@cwarnermm - Once I have the draw.io file (XML), would you like me to take a screenshot of it and put as an image? Or do you want to store it and reference it from the images directory?

**Comment by cwarnermm** [comment]
@TomerPacific - Please save a copy of each flow chart as an XML file with a .drawio file extension, so that it's an editable source file that Mattermost can modify as needed. Internally, we'll manage those source files further before publication.

**Comment by TomerPacific** [comment]
@cwarnermm - Where would you like this file to be saved in the project structure?

**Comment by cwarnermm** [comment]
@TomerPacific - Feel free to add the source files to ``/images``. In this PR, note the filenames of the new images, please. Thank you!

**Comment by TomerPacific** [comment]
@cwarnermm - A PR has been opened -> https://github.com/mattermost/docs/pull/7470
