### ISSUE TITLE
Help Wanted: Define product icons site-wide

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7349]
# Current
Individual product documentation pages define and reference product icons at the top of page, rather than site-wide.

# Desired
All existing product icons referenced across the docs site are defined once, site-wide, so that they can be referenced using only a short code on individual docs pages, as needed.

# Effort

1. Identify all unique product icons referenced across all pages of the Mattermost product documentation.  Product icon references will be located at the top of docs pages in the following format:

```
.. |icon-short-code| image:: ../images/filename.svg
  :alt: Alternate image text.
  :class: theme-icon
```

2. Create a docs PR that defines all identified product icons in the ``/source/conf.py`` file located in this GitHub repository, within the ``rst_prolog`` section, as follows:

```
rst_prolog = """
.. |plans-img| image:: /_static/images/badges/flag_icon.svg
    :class: mm-badge-flag
.. |deployment-img| image:: /_static/images/badges/deployment_icon.svg
    :class: mm-badge-flag
.. |plans-img-yellow| image:: /_static/images/badges/flag_icon_yellow.svg
    :class: mm-badge-flag
.. |deployment-img-yellow| image:: /_static/images/badges/deployment_icon_yellow.svg
    :class: mm-badge-deployment
<your icon definitions go here following the same format>
"""
```

3. Remove the individual page-based icon definition code as you move definitions over.
4. Ensure that there are no duplicate icon definitions in ``conf.py``.
5. Generate and test the docs to ensure that all product icons display correctly in both Light and Dark Mode using the ``:class: theme-icon`` attribute.
6. Submit all changes in a single docs PR.

**Comment by manujgrover71** [comment]
@cwarnermm I've created a PR with the proposed changes, could you please have a look and let me know if anything else needs to be revisited.
