### ISSUE TITLE
Install Desktop App: Wrong path in Windows File Explorer troubleshooting

### ISSUE THREAD

**Issue by Movion** [mattermost/docs#7361]
In the troubleshooting guide for the desktop app, the windows paths are showing double backslashes `\\`

`%APPDATA%\\Mattermost`
Which is wrong - correct would be just one:

`%APPDATA%\Mattermost`

I found the issues on these two lines:
https://github.com/mattermost/docs/blob/70b50ccb6dbc7bb282034171a46f16077dba55d3/source/collaborate/install-desktop-app.rst?plain=1#L242

https://github.com/mattermost/docs/blob/70b50ccb6dbc7bb282034171a46f16077dba55d3/source/collaborate/install-desktop-app.rst?plain=1#L259

**Comment by devinbinnie** [comment]
@cwarnermm Yeah they're should only be one backslash in those paths.

**Comment by cwarnermm** [comment]
Perfect - thanks, @devinbinnie. @Movion - Are you open to creating a docs PR with the necessary changes?

**Comment by Movion** [comment]
@cwarnermm sure, but I just signed the "Mattermost Contributor Agreement", idk how fast I'm allowed to make a PR

**Comment by cwarnermm** [comment]
@Movion - you're most welcome to get started any time (even if you hadn't signed the contributor agreement yet! It would be needed by the time we're ready to merge your changes into the docs code base).

Let us know here if you have any questions about the docs changes -- happy to help!

**Comment by Movion** [comment]
I hope I did everything right.. please check and let me know if I have to improve or change anything :s
