### ISSUE TITLE
Mattermost Support Chatbot trained via official docs

### ISSUE THREAD

**Issue by ylluminate** [mattermost/docs#7375]
Please implement a ChatGPT or other chatbot that ingests the entirety of https://github.com/mattermost/docs source and can have conversations on how to perform Mattermost tasks and facilitates definitive answers readily. It would be quite useful to have such a chatbot to be able to get authoritative answers on how to accomplish various tasks vs resorting to forums and search since often times these other options cannot compose or synergizes information in a way that makes sense in some contexts.

**Comment by cwarnermm** [comment]
Thank you, @ylluminate, for logging this great feedback. Are you open to creating an issue against the https://github.com/mattermost/mattermost-plugin-ai Engineering repository? It's a better fit for this issue where more eyes will see it.

**Comment by cwarnermm** [comment]
@ylluminate - Introducing a new chatbot trained on Mattermost Product Documentation that's capable of providing product answers is something our AI Engineering team would be interested to hear more about. Would you agree, @azigler?
