### ISSUE TITLE
Help Wanted: Add missing plugin configuration setting sections

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7423]
# Context

The [Plugins configuration settings](https://docs.mattermost.com/configure/plugins-configuration-settings.html) product documentation is currently missing subsections for:
- [Microsoft Teams Meetings plugin](https://docs.mattermost.com/integrate/microsoft-teams-meetings-interoperability.html)
- [Microsoft Calendar plugin](https://docs.mattermost.com/integrate/microsoft-calendar-interoperability.html)

# Documentation Request

Add these missing sections, in alphabetical order, to the [Plugins configuration settings](https://docs.mattermost.com/configure/plugins-configuration-settings.html) page, modelled after the [GitLab](https://docs.mattermost.com/configure/plugins-configuration-settings.html#gitlab), [GitHub](https://docs.mattermost.com/configure/plugins-configuration-settings.html#github), [Jira](https://docs.mattermost.com/configure/plugins-configuration-settings.html#jira), and [Legal Hold](https://docs.mattermost.com/configure/plugins-configuration-settings.html#legal-hold) sections. These sections don't include individual configuration setting details, just a link back to the plugin setup content instead.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page directly results in the new configuration sections being visible on the page.

**Comment by 1510janu** [comment]
Hi @cwarnermm 

Could you assign this issue to me?

**Comment by cwarnermm** [comment]
Thanks, @1510janu! I'd love your help with this issue!

**Comment by cwarnermm** [comment]
@1510janu - Are you actively working on this issue?

**Comment by 1510janu** [comment]
@cwarnermm yes. I will close the ticket this week.

**Comment by Rutam21** [comment]
@cwarnermm Feel free to assign this to me if there are no further updates by the weekend. Thanks.
