### ISSUE TITLE
Help Wanted: Access conversations with deactivated users

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7425]
# Context

The Mattermost Product Documentation doesn't specify whether users can access conversations with deactivated users.

# Documentation Request

Clarify in the end user [product docs](https://docs.mattermost.com/collaborate/channel-types.html) that any direct or group message history you had with a deactivated user remains available unless your system admin [disables your ability to do so](https://docs.mattermost.com/configure/site-configuration-settings.html#users-viewarchivedchannels).

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page directly returns a note for both direct and group messages regarding the user's ability to access deactivated users (when enabled).

**Comment by TomerPacific** [comment]
@cwarnermm - Can I help with this one?

**Comment by TomerPacific** [comment]
@cwarnermm - Is the page you referenced where you want this added? Under Users and teams?

**Comment by TomerPacific** [comment]
@cwarnermm - I deleted my previous comment, because I realized I didn't see the link under the Documentation Request.
I am seeing that there is also the page about [communication with messages and threads](https://docs.mattermost.com/collaborate/communicate-with-messages.html) so maybe we want to add something there? Could be just a reference?

**Comment by cwarnermm** [comment]
@TomerPacific - Very open to this approach! Looking forward to your docs PR.

**Comment by TomerPacific** [comment]
@cwarnermm - Let me know what you think.

![mm](https://github.com/user-attachments/assets/08b2414e-fd74-4dfa-8ebb-ace361ef6e2d)

**Comment by cwarnermm** [comment]
@TomerPacific - I wonder if we want to combine both callouts as notes, rather than displaying a tip followed by note. In the combined case, both would be formatted as bullets. Thoughts?

**Comment by TomerPacific** [comment]
@cwarnermm - Sounds like a good approach as it will lead to a more cohesive UI.
