### ISSUE TITLE
Help Wanted: Can't invite a guest user who's already a member of the workspace

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7426]
# Context

The Mattermost Product Documentation doesn't provide guidance on how to successfully resolve the in-product invitation error: "This person is already a member of the workspace. Invite them as a member instead of a guest."

# Documentation Request

Document how to interpret and resolve the error, as described below.

If you try inviting someone who already has an account in your Mattermost instance, invite them to a particular channel instead.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page directly returns a clarification note at the bottom of the page about attempting to invite members and guests who already have accounts on the server.

**Comment by CBID2** [comment]
I want to work on this for Hacktoberfest

**Comment by CBID2** [comment]
Hi @cwarnermm! 😊 There’s an issue that I have with this issue. I want to test this out the feature but I'm not sure how to get started. Also, should the tutorial be standalone or added to another tutorial?

**Comment by cwarnermm** [comment]
Hi @CBID2! You're welcome to test out this feature using the [Mattermost Community Server](https://community.mattermost.com/). I recommend updating [this](https://docs.mattermost.com/collaborate/invite-people.html) docs page tip to clarify the details around inviting a user who's new to the workspace versus inviting someone who already has a workspace account to channels.

**Comment by CBID2** [comment]
> Hi @CBID2! You're welcome to test out this feature using the [Mattermost Community Server](https://community.mattermost.com/). I recommend updating [this](https://docs.mattermost.com/collaborate/invite-people.html) docs page tip to clarify the details around inviting a user who's new to the workspace versus inviting someone who already has a workspace account to channels.

Thanks for clarifying @cwarnermm

**Comment by CBID2** [comment]
> Hi @CBID2! You're welcome to test out this feature using the [Mattermost Community Server](https://community.mattermost.com/). I recommend updating [this](https://docs.mattermost.com/collaborate/invite-people.html) docs page tip to clarify the details around inviting a user who's new to the workspace versus inviting someone who already has a workspace account to channels.

Hi @cwarnermm! :) I made the PR.
