### ISSUE TITLE
Help Wanted: Search documentation clarification

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7427]
# Context

The Mattermost Product Documentation doesn't explicitly state how [search wildcards](https://docs.mattermost.com/collaborate/search-for-messages.html#wildcards) can be used.

# Documentation Request

Clarify that wildcards in search must be added to the end of a word. Wildcards at the beginning or in the middle of a word aren't supported.

# QA Validation Criteria

In a generated docs preview:

- Visiting the docs page directly results in the wildcard usage documentation clarified as only applying to the end of a word stem.

**Comment by 1510janu** [comment]
Hi @cwarnermm 
Could you assign this issue to me?

**Comment by cwarnermm** [comment]
Thanks, @1510janu - looking forward to working with you on this update!

**Comment by cwarnermm** [comment]
@1510janu - Are you actively working on this issue?

**Comment by 1510janu** [comment]
@cwarnermm yes. I will close the ticket this week.

**Comment by Rutam21** [comment]
@cwarnermm Feel free to assign this to me if there are no further updates by the weekend. Thanks.
