### ISSUE TITLE
Help Wanted: Document workaround for white Desktop App screen on login

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7428]
# Context

The Mattermost Product Documentation doesn't provide guidance for users who encounter a white desktop app screen after logging in.

# Documentation Request

Document the following workaround for the white screen desktop app issue via https://docs.mattermost.com/collaborate/install-desktop-app.html#log-in-using-the-desktop-app

Delete the local `Mattermost desktop app` configuration file, and then reinstall the desktop app. 

The location of the Mattermost desktop app configuration file depends on the platform where you’re running Mattermost (and, in the case of macOS, how you’ve chosen to install the app):

- Windows: `Users\<username>\AppData\Roaming\Mattermost`
- macOS installer: `/Users/<username>/Library/Application Support/Mattermost`
- macOS App Store: `/Users/<username>/Library/Containers/Mattermost/Data/Library/Application Support/Mattermost`
- Linux: `~/.config/Mattermost`

**Comment by 1510janu** [comment]
Hi @cwarnermm 
Could you assign this issue to me? I can document the mentioned workaround.

**Comment by cwarnermm** [comment]
Thanks, @1510janu! Really appreciate your help with this issue!

**Comment by cwarnermm** [comment]
Issue resolved. Closing.
