### ISSUE TITLE
Help Wanted: Document missing User Satisfaction Survey plugin configuration

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7429]
# Context

The Mattermost Product Documentation is missing ``config.json`` and environment variable equivalents for the following 2 [User Satisfaction Survey plugin configuration settings](https://docs.mattermost.com/configure/plugins-configuration-settings.html#user-satisfaction-surveys):
- https://docs.mattermost.com/configure/plugins-configuration-settings.html#id5
- https://docs.mattermost.com/configure/plugins-configuration-settings.html#enable-user-satisfaction-survey

# Documentation Request

Update the [User Satisfaction Survey plugin configuration settings](https://docs.mattermost.com/configure/plugins-configuration-settings.html#user-satisfaction-surveys) page to include ``config.json`` and environment variable equivalents, as detailed below.

Ensure that both the search metadata content (located directly above the section header in code) and the table-formatted content is updated as needed.

## Enable Plugin
* `config.json` path - `PluginSettings.PluginStates.com.mattermost.user-survey.Enable`
* Env variable: `N/A`

## Enable user satisfaction survey
* `config.json` path - `PluginSettings.Plugins.com.mattermost.user-survey.systemconsolesetting.EnableSurvey`
* Env variable: `N/A`

# QA Validation Criteria

In a generated docs preview:
- Searching for the 2 updated configuration settings via the Search bar return the correct ``config.json`` data.
- Visiting the docs page directly returns the correct ``config.json`` data.

**Comment by Fabelair** [comment]
Hey @cwarnermm, can I work on that for you?

**Comment by TheInvincibleRalph** [comment]
Hi, @cwarnermm. Can I be assigned to this?

**Comment by TomerPacific** [comment]
@cwarnermm - If this isn't taken, I'd like to help as the other issue I am working on is pending internal feedback.

**Comment by cwarnermm** [comment]
Thanks so much, @TomerPacific!!

**Comment by TomerPacific** [comment]
@cwarnermm - A PR has been opened -> https://github.com/mattermost/docs/pull/7445
