### ISSUE TITLE
Help Wanted: Document deep links, their value, and how to create them

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7430]
# Context

The Mattermost Product Documentation doesn't provide guidance on what deep links are, details about the value of deep links, or details on how to configure a deep link in Mattermost.

## What's a Mattermost Deep Link?

A Mattermost deep link is a URL that takes users directly to a specific location within a Mattermost instance, such as a particular channel, message, user, or other in-app content. Deep linking makes navigation more efficient and enhances the user experience by allowing users to quickly view or interact with relevant content directly.

## Benefits of Configuring Mattermost Deep Links
- Direct Access: Users can directly access specific conversations, messages, or other content without needing to navigate through the app.
- Improved Workflow: Deep links can streamline workflows by providing quick access to relevant content, facilitating easier collaboration and faster decision-making.
- Easy Sharing: Deep links allow users to share specific content within Mattermost with others, improving communication and collaboration.
- Efficiency: Reduces the amount of time spent searching for content, making everyday tasks more efficient.

### Examples of Mattermost Deep Links
- Opening a specific channel: mattermost://<your-mattermost-url>/channels/<channel-name>
- Opening a specific user profile: mattermost://<your-mattermost-url>/users/<user-id>
- Opening a specific post in a channel: mattermost://<your-mattermost-url>/pl/<post-id>

## How to Use Mattermost Deep Links
- For Channels: Use the format mattermost://<your-mattermost-url>/channels/<channel-name> to link directly to a channel. For example:
mattermost://example.mattermost.com/channels/town-square
- For Posts: Use the format mattermost://<your-mattermost-url>/pl/<post-id> to link directly to a specific post.

## Create a Deep Link
1. Navigate to the content you want to link to in Mattermost.
2. Right-click (or use the context menu) and look for an option to copy the link. This usually provides the correctly formatted deep link.
3. Share or use this link as needed within your workflows or communications.

# Documentation Request

Add documentation on what deep links are, where/how/when they're useful, and how to create them.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page directly returns details about deep links in a new subsection.

**Comment by Good-Soma** [comment]
Hi,
Can I document what matter deep links are, where/how/when they're useful, and how to create it,  if nobody is working on it?

**Comment by CBID2** [comment]
I’ll gladly work on this for Hacktoberfest! :)

**Comment by cwarnermm** [comment]
@Good-Soma - You indicated interest first: are you open to taking this on? If not, I'll assign it to @CBID2.

**Comment by Good-Soma** [comment]
Yeah, I am open and ready to write it.
Should I start?

**Comment by cwarnermm** [comment]
Please do, @Good-Soma. And thank you for patience!

**Comment by cwarnermm** [comment]
@CBID2 - Is there another issue on the docs backlog that you're interested in?

**Comment by CBID2** [comment]
> @CBID2 - Is there another issue on the docs backlog that you're interested in?

This one: https://github.com/mattermost/docs/issues/7426

**Comment by Good-Soma** [comment]
> Please do, @Good-Soma. And thank you for patience!

Okay

**Comment by cwarnermm** [comment]
@CBID2 - Please comment on that issue and I'll assign it to you. :)

**Comment by Good-Soma** [comment]
Hello, I have finish writing the document, but I don't seem to know the repo where I should fork it to. Is there a hint on what I should do next?

**Comment by cwarnermm** [comment]
Hi @Good-Soma. This content will be added to this repo: ``/mattermost/docs``. The source file is: ``collaborate/share-links.rst``

I recommend adding a new subsection to the end of that docs page for document deep links. Please use the writing approach, formatting, and tone of this page as a guideline for the new section.

Include a link to this issue in your PR summary to link the issue to the PR.
