### ISSUE TITLE
Help Wanted: Document New Client Configuration Property

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7453]
# Context

https://github.com/mattermost/mattermost-mobile/pull/8220 introduces a new client configuration property that determines whether the mobile app should use the default external browser to perform SSO Authentication instead of the internal one.

# Documentation Ask

Source file: configure/site-configuration-settings.rst

Within the **Customization** section, add the new configuration setting (and its associated search metadata located directly above a section title) as a new section on this page.

Position the new configuration setting immediately following the **App custom URL schemes** section, and format the details of the section modelled after the [report a problem](https://docs.mattermost.com/configure/site-configuration-settings.html#report-a-problem-link) configuration setting.

Include the following configuration setting details:
- Section title: Mobile external browser
- Available only for self-hosted deployments
- Description: Configures the mobile app to perform SSO Authentication using the external default browser.
- String input. 
- System Config path: N/A
- config.json = NativeAppSettings -> MobileExternalBrowser
- Environment variable = MM_NATIVEAPPSETTINGS_MOBILEEXTERNALBROWSER

# QA Validation Criteria

In a generated docs preview:
- Searching for the new configuration setting returns the correct details.
- Visiting the docs page directly returns details about the new configuration setting.

**Comment by Rutam21** [comment]
@cwarnermm I would like to work on this. Please assign this to me. Thanks.

**Comment by cwarnermm** [comment]
Thanks, @Rutam21!!
