### ISSUE TITLE
Help Wanted: Document New Server Configuration Setting

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7454]
# Context

https://github.com/mattermost/mattermost/pull/26980 introduces a new server configuration setting that fixes an issue where YouTube preview shows Video Unavailable instead of the video. 

# Documentation Asks

1. Source file: configure/experimental-configuration-settings.rst

Within the **Experimental system console configuration settings** section, add the new configuration setting (and its associated search metadata located directly above a section title) as a new section on this page.

Position the new configuration setting immediately following the **Enable dedicated export filestore target** section, and format the details of the section modelled after other configuration settings on this page and in this section.

Include the following configuration setting details:
- Section title: YouTube referrer policy
- Description: Resolves issues where YouTube video previews display as unavailable.
- true: The referrer policy for embedded YouTube videos is set to `strict-origin-when-cross-origin`.
- false: (Default) The referrer policy is set to `no-referrer` which enhances user privacy by not disclosing the source URL, but limits the ability to track user engagement and traffic sources in analytics tools.
- config.json = `"ExperimentalSettings.YoutubeReferrerPolicy": false`

2. Source file: manage/telemetry.rst

- add `bool YoutubeReferrerPolicy` directly after `bool AllowSyncedDrafts`

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page directly results in the new configuration setting being visible on the page.
- Searching for the new configuration setting returns the correct page, that page is accessible, and that page contains the new configuration setting details.

**Comment by Rutam21** [comment]
@cwarnermm I would like to work on this. Please assign this to me. Thanks.

**Comment by cwarnermm** [comment]
Thanks, @Rutam21!!
