### ISSUE TITLE
Help Wanted: Remove Deprecated UI option

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7456]
# Context

The **All direct messages** option for the direct messages list has been removed from the product and should be removed from the product documentation to avoid user confusion.

# Documentation Asks

Source file: preferences/customize-your-channel-sidebar.rst

Within the **How many direct messages to display** section:

1. Remove references to the **All direct messages** option.
2. Capture a new animated GIF without that option present, reuse the existing image file name, and model the new GIF animation based on the existing one.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page directly results in the direct message option being removed from the text-based documentation as well as the associated animated GIF.

**Comment by Rutam21** [comment]
@cwarnermm I would like to take this up. Please assign this to me. Thanks.

**Comment by cwarnermm** [comment]
Thanks, @Rutam21!
