### ISSUE TITLE
Help Wanted: Make team creation workflow easier

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7457]
# Context

The option to create a new Mattermost team isn't always easy to find, and updating the product documentation can help make this feature more discoverable.

# Documentation Asks

Source file: collaborate/organize-using-teams.rst

Within the **Create a team** section, capture 2 new animated GIFs:
- GIF 1: Show how to select + and select **Create a New Team** (GIF doesn't need to show the rest of the team creation flow). Add this image directly below the second paragraph on the page and before the 3rd paragraph.
- GIF 2: Show how to select the team name and then select **Create a Team**. Add this image to the Tip near the top of the page.

In both cases, use existing code on the page as a guide for adding images to this documentation page.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page directly results in a new animated GIF being displayed on the page

**Comment by Rutam21** [comment]
@cwarnermm I would like to work on this. Please assign this to me. Thanks.

**Comment by cwarnermm** [comment]
Thanks, @Rutam21!!
