### ISSUE TITLE
Help Wanted: Update documentation on components that are imported/exported

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7458]
# Context

Mattermost v10.1 imports and exports will support:
- direct and group channels
- direct and group channel unread/read state
- threaded discussion memberships

# Documentation Ask

Source files:
- onboard/bulk-loading-data.rst
- manage/bulk-export-tool.rst

On each page, add the following components to the list of what's supported (in alpha order) located at the top of the page:
- direct and group message channels
- direct and group message read/unread status
- threaded discussions 

# QA Validation Criteria

In a generated docs preview:
- Visiting each impacted docs page shows the newly added components.

**Comment by arilloid** [comment]
Hello @cwarnermm , I would like to work on this issue!
Could you assign it to me if possible

**Comment by cwarnermm** [comment]
Thanks, @arilloid! Very much appreciated!
