### ISSUE TITLE
Help Wanted: Acknowledgement icons display incorrectly in docs Dark Mode

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7459]
# Context

The Acknowledge Icons in the [Set message priority](https://docs.mattermost.com/collaborate/message-priority.html#request-acknowledgements) documentation display as red when you view the docs in Dark Mode. This option should always display as green.

# Documentation Ask

Source file: source/conf.py

Remove `:class: theme-icon` parameter from the `|acknowledge-button|` global image definition.

#QA Validation Criteria

In a generated docs preview:
- Viewing the updated docs in both Light Mode and Dark Mode displays the Acknowledge icon in green.

**Comment by aamfahim** [comment]
Looks simple enough. I would like to work on this.

**Comment by cwarnermm** [comment]
Thanks, @aamfahim! Thank you for your help with this!
