### ISSUE TITLE
Help Wanted: Remove deprecated configuration setting from product documentation

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7460]
# Context

A deprecated ProductSettings reference can now safely be removed since it's no longer part of the product code base.

# Documentation Ask

Source file: /configure/deprecated-configuration-settings.rst

Remove the **Enable publicly-shared boards** configuration setting documentation and its associated search meta data located directly above the section title.

# QA Validation Criteria

In a generated docs preview:
- Searching for the deprecated configuration setting (Enable publicly-shared boards) doesn't return a matching result.
- Visiting the docs page directly results in the **Mattermost Boards settings** link being removed at the top of the page table of contents. 
- Visiting the docs page directly results in the deprecated configuration setting being removed from the page altogether.

**Comment by belkhoujaons** [comment]
can you assign this to me ?

**Comment by cwarnermm** [comment]
I'd be happy to, @belkhoujaons! Thank you!

**Comment by Git-Suraj-hub** [comment]
can you assign this to me ?
