### ISSUE TITLE
Feature: Reformat data in the  product feature breakdown table

### ISSUE THREAD

**Issue by TomerPacific** [mattermost/docs#7498]
Following the discussion from #7024,
it was suggested that there could be a better way to structure and present the data shown in the [product feature breakdown table](https://docs.mattermost.com/about/faq-product.html#what-features-are-available-on-different-mattermost-clients).

This issue's purpose is to come up with different solutions to present the data and agree on the one that works.

**Comment by TomerPacific** [comment]
@cwarnermm - I'll work on a Google document that outlines several approaches, with pros/cons for each one and share it here.
I'll allow others to edit/comment so it will be an interactive document, which hopefully will lead us to an agreed upon solution.

Sound good?

**Comment by cwarnermm** [comment]
Sounds amazing! Thank you, @TomerPacific!!

**Comment by cwarnermm** [comment]
I'm thinking that we'll share the link to the GDoc in Mattermost discussion threads on the Community Server.

**Comment by TomerPacific** [comment]
@cwarnermm - [Here is a link to the document](https://docs.google.com/document/d/1GEN13nQgPbol1tT0ImdoOuwAQYo8FsisGEKX7nqCM28/edit?usp=sharing). Which channel would be best to post this? DWG/Contributors? Or should I open a new thread?

**Comment by cwarnermm** [comment]
@TomerPacific - Let's share it in DWG; we'll invite UW and QA to share their thoughts.

**Comment by cwarnermm** [comment]
We received really great input from a number of stakeholders on best practices around table-based content in docs. 

From that input, here's how I'd like to proceed with the table content on the https://docs.mattermost.com/about/faq-product.html docs page:

1. Split out the table into page sections, each with its own H2 level section title, as follows:
 - Messages
 - Channels
 - Teams
 - Collaborative Playbooks
 - Calls
 - Integrations
 - Authentication
 - Additional Features (replacing "Other")

These section headers will display in the far right navigation for easy page-based navigation.

Each docs section will contain a table with the same 4 columns as what's published today: Feature, Web, Desktop, & Mobile.

Replace full support "x" indicators with green checkmarks, using the https://docs.mattermost.com/collaborate/collaborate-with-audio-video.html docs page as a code guide. The green checkmark is defined globally, so all that's needed is the shortform reference (as seen in the docs code). It's expected that the checkmark icons will align left and not centered when displayed on the page.

In cases where partial coverage is indicated (mobile only), replace the "o" with the text "Partial Support" for clarity.

Ensure each feature across all tables on the page is also a link to its respective docs topic. Flag any features whose associated docs page isn't known; @cwarnermm can help identify specific docs pages as needed. Ensure links are formatted as relative links rather than absolute links. Use the https://docs.mattermost.com/collaborate/collaborate-with-audio-video.html code as a guide for this syntax.

Once the single table is broken out into multiple tables across sections on the page, remove the Legend details.

**Tip**: I strongly recommend using https://www.tablesgenerator.com/text_tables to generate reStructuredText syntax for each table. This site makes short work of defining table text, including all necessary RST syntax, such as ``**`` for bolding, and for link text.

**Comment by TomerPacific** [comment]
@cwarnermm - Do you have somewhere I can look or a mock I can see of what you want the page to look like? Which section should be before the other? Do you want Web first and then Desktop and Mobile? I'd really appreciate some clarifications.

**Comment by cwarnermm** [comment]
@TomerPacific - Use the same order as what's published now for both the sections and the features, please.

**Comment by cwarnermm** [comment]
It's a thing of beauty, @TomerPacific! Looking forward to seeing your docs PR. Happy to help identify any link URLs needed too.

**Comment by TomerPacific** [comment]
@cwarnermm - Going over the features under the Messages section, this is what I found (**those without a link mean that I was not able to find the documentation for it**):

- :ref:`Threaded messages <configure/site-configuration-settings:threaded discussions>` (this is the closest I found)
- Markdown 
-  :ref:`Emojis <configure/site-configuration-settings:emoji>` 
- :ref:`Emoji reactions <collaborate/react-with-emojis-gifs:quick emoji reactions>`
-  Viewing emoji reactions  
- :ref:`File sharing <configure/site-configuration-settings:fileshare allowfilesharing>`
- @ mentions   
- Hashtags  
- Search (with in:, from:, before:, on: and after:) 
- Search highlighting 
- View/marking pinned or saved posts
- Image link previews 
- :ref:`Website previews <configure/site-configuration-settings:posts enablelinkpreviews>`
-  Notifications

Could you help me in identifying the correct documentation links for the features I couldn't find?

I'm going to move on to other sections and hopefully, I'll fare better there.

Thanks

**Comment by cwarnermm** [comment]
Thanks, @TomerPacific!

- markdown: :ref:`Format messages with Markdown <collaborate/format-messages:use markdown>`
- Viewing emoji reactions: :ref:`Emoji reactions <collaborate/react-with-emojis-gifs:quick emoji reactions>`
- @ mentions: :doc:`Mention people </collaborate/mention-people>`
- Hashtags: :ref:`Search hashtags <collaborate/search-for-messages:hashtags>`
- Search (with in:, from:, before:, on: and after:): :ref:`Search modifiers <collaborate/search-for-messages:search modifiers>`
- View/marking pinned or saved posts: :doc:`Save and pin messages </collaborate/save-pin-messages>`
- **NEW**: :doc:`Channel bookmarks </collaborate/manage-channel-bookmarks>`
- Image link previews: :doc:`Link previews </collaborate/share-links>`
- Notifications: :doc:`Notifications </preferences/manage-your-notifications>`

I don't have a link to provide for the `Search highlighting` feature. I'll follow up with our product team to learn more.

**Comment by TomerPacific** [comment]
@cwarnermm - Thanks! Just went over the Channels section, I got this there:

- Create a new channel collaborate/create-channels.html
- Join a channel collaborate/join-leave-channels.html#join-a-channel
- Leave a channel collaborate/join-leave-channels.html#join-a-channel (shows up in the same page)
- Favorite a channel collaborate/favorite-channels.html
- Mute a channel preferences/manage-your-channel-specific-notifications.html#mute-channels
- Manage members collaborate/manage-channel-members.html
- Add members collaborate/manage-channel-members.html (shows up in the same page)
- Edit channel collaborate/rename-channels.html
- Archive members - I could only find documentation about archiving channels

**Comment by cwarnermm** [comment]
Thanks, @TomerPacific!! 

For `Archive members`, let's change that to :ref: `Deactivate members <configure/user-management-configuration-settings:activate or deactivate users>`

For `Leave channel`, link it to :ref:`<collaborate/join-leave-channels:leave a channel>`

For `Add members`, link it to `<collaborate/manage-channel-members:add members to a channel>`

**Comment by TomerPacific** [comment]
@cwarnermm - I have gone over all the sections and below are my findings:

**Teams**
- Multi-team support for notifications
- Team switching
- Team-based theming
- Team settings collaborate/team-settings.html#team-settings
- Join existing team collaborate/organize-using-teams.html#join-a-team
- Create a new team collaborate/organize-using-teams.html#create-a-team
- Get team invite link collaborate/invite-people.html#send-a-team-invite-link
- Add members to team
- Manage team members manage/team-channel-members.html#teams
- Leave team collaborate/organize-using-teams.html#leave-a-team

**Collaborative Playbooks**
- Templates and checklists repeatable-processes/work-with-playbooks.html#work-with-collaborative-playbooks

**Calls**
- Join call collaborate/make-calls.html#join-a-call
- Share screen collaborate/make-calls.html#share-your-screen
- Chat in thread collaborate/make-calls.html#chat-in-a-call
- React with emoji collaborate/make-calls.html#react-using-emojis
- Start recording collaborate/make-calls.html#record-a-call

**Integrations**
- Slash commands repeatable-processes/interact-with-playbooks.html#slash-commands
- Server-side plugins
- User interface plugins
- Oauth applications configure/authentication-configuration-settings.html#oauth-2-0
- Incoming webhooks integrations-configuration-settings.html#enable-incoming-webhooks
- Outgoing webhooks configure/integrations-configuration-settings.html#enable-outgoing-webhooks
- Message attachments
- Message buttons
- Message menus
- Message actions
- Right-hand sidebar

**Authentication**
- Email-password login configure/authentication-configuration-settings.html#email
- AD/LDAP onboard/ad-ldap.html
- SAML SSO onboard/sso-saml.html
- GitLab SSO onboard/sso-gitlab.html
- Entra ID SSO onboard/sso-entraid.html
- Google SSO onboard/sso-google.html

**Other**
- Localization for 20 languages configure/site-configuration-settings.html#localization
- Custom user interface themes preferences/customize-your-theme.html
- User profile settings
- Channel settings

**Comment by cwarnermm** [comment]
@TomerPacific - Really great work here!

- Team switching: `collaborate/organize-using-teams.html`
- Team-based theming: `preferences/customize-your-theme.html`
- Add members to team: `collaborate/invite-people.html`
- Server-side plugins: `guides/integrate-and-extend.html`
- Message attachments: `collaborate/share-files-in-messages.html`
- User profile settings: `preferences/manage-your-profile.html`

You can safely leave the following features as-is without a link. I'll follow up with our Product Team to clarify the intention of the following features given that we can't match them directly to docs pages:
- Multi-team support for notifications
- Message buttons
- Message menus
- Message actions
- Channel settings
- Right-hand sidebar
- User interface plugins

**Comment by TomerPacific** [comment]
@cwarnermm - I have opened a draft PR and I would like to ask for your assistance for the links in the **Authentication** section. For some reason, the format I am using there is not working.
Can you help me understand what I am missing?
