### ISSUE TITLE
Document how to manage teams via the System Console

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7643]
## Context

Details on how to manage Mattermost teams as a system admin using the System Console are missing from the Mattermost Product Documentation.

## Docs Request

Develop admin documentation for the following topics:

- Find a team
- Filter team searches
- Review team configuration
- Manage team membership
  - Add members
  - Remove members
  - Sync group members
  - Anyone can join
  - Only specific email domains can join
- Archive a team

**Note**: The ability to add groups to a team also needs to be documented, but requires additional internal investigation/testing first.

## How you can help

- Create a single docs PR that contains all of these changes across as many commits as necessary
- Use the latest Mattermost mobile app and the standard Mattermost Denim theme to capture all workflows.
- Use existing admin docs content as a starting point for voice and tone guidance. The Docs team will review and provide support for publication.

**Comment by Rutam21** [comment]
@cwarnermm Please assign this issue to me.  Thanks.
