### ISSUE TITLE
Document how to manage channels via the System Console

### ISSUE THREAD

**Issue by cwarnermm** [mattermost/docs#7652]
## Context

Details on how to manage Mattermost channels as a system admin using the System Console are missing from the Mattermost Product Documentation.

## Docs Request

Develop admin documentation for the following topics:

- Find channels
- Filter channel searches
- Review channel configuration
- Advanced access controls
  - Create messages
  - Message reactions
  - Manage members
  - Channel mentions
  - Manage bookmarks
- Channel management
  - Sync group members
  - Public channel or private channel
- Groups (Skipped)
- Members
  - Add members
  - Remove members

**Note**: The ability to add groups to a channel also needs to be documented, but requires additional internal investigation/testing first.

## How you can help

- Create a single docs PR that contains all of these changes across as many commits as necessary
- Use the latest Mattermost mobile app and the standard Mattermost Denim theme to capture all workflows.
- Use existing admin docs content as a starting point for voice and tone guidance. The Docs team will review and provide support for publication.

**Comment by Rutam21** [comment]
@cwarnermm Please assign this issue to me. Thanks.
