### ISSUE TITLE
Document how to create a clickable button in markdown 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#771]
Probably create or find a better image, but basically here's the markdown to create a button:  

```
[![button](http://www.presentationpro.com/images/product/medium/slide/PPP_CGENE_LT3_Presentation-PowerPoint-Slide-Graphic_Push_Button_Up.jpg)](https://mattermost.com)
```

[![button](http://www.presentationpro.com/images/product/medium/slide/PPP_CGENE_LT3_Presentation-PowerPoint-Slide-Graphic_Push_Button_Up.jpg)](https://mattermost.com)

**Comment by it33** [comment]
Not priority

**Comment by grzesir** [comment]
this should be a priority. would be very helpful for marketing a library
