### ISSUE TITLE
Default NGINX SSL setup results in weak Diffie-Hellman key exchange parameters

### ISSUE THREAD

**Issue by JeffSchering** [mattermost/docs#780]
If you follow the instructions in the doc https://docs.mattermost.com/install/prod-ubuntu-16.04.html#set-up-nginx-with-ssl-recommended, you end up with an NGINX config that supports weak Diffie-Hellman (DH) key exchange parameters. This prevents an A rating from the site that the docs recommend for testing the SSL config, [Qualys SSL Labs](https://www.ssllabs.com/ssltest/index.html).

The instructions should include how to configure a Mattermost system to get an A rating.

**Comment by justinegeffen** [comment]
@svelle, is this something you can help with? Or perhaps @DSchalla?

**Comment by svelle** [comment]
@justinegeffen I'm not even sure if this still applies. I'll have to check.

**Comment by svelle** [comment]
@justinegeffen I just looked at the ciphers we're using now. I think this has already been fixed.

**Comment by svelle** [comment]
yeah fixed by: https://github.com/mattermost/docs/commit/8605d9cb67fcd4cbafea12fe2381b64888b87452
