### ISSUE TITLE
Changelog not update

### ISSUE THREAD

**Issue by danilvoe** [mattermost/docs#784]
in no information about the changes in version 3.6 file

**Comment by jasonblais** [comment]
Hey @danilvoe, we've got the changelog in final review, should be merged soon, certainly before the official release on the 16th: https://github.com/mattermost/docs/pull/663

**Comment by jasonblais** [comment]
The changelog is here @danilvoe : https://docs.mattermost.com/administration/changelog.html#release-v3-6-1
