### ISSUE TITLE
Document updating system with HA

### ISSUE THREAD

**Issue by it33** [mattermost/docs#785]
Lots of questions on how Mattermost applies update in HA mode. Propose we add something like the below to https://docs.mattermost.com/deployment/cluster.html#id13

This needs someone to draft the step-by-step instructions for the Update Guide at the bottom, and we definitely need tech review here. 

There are some open items to work on (Corey can provide more detail): 

1. Ability to add and remove nodes without requiring rolling cluster 
2. Ability to have code support multiple database schemas 
3. HTTP/2 between servers to hold websocket open when doing inter-server communication 

------

# High Availability (Beta) 

*Available in Enterprise Edition E20.*

High Availability support enables a Mattermost system to maintain service during outages and hardware failures through the use of redundant infrastructure. 

## Overview 

High availability in Mattermost consists of running redundant Mattermost application servers, redundant database servers and redundant load balancers so that the failure of any one of these components does not interrupt operation of the system. 

#### 1) Redundancy at anticipated scale. 

Redundant components (application server, database and load balancer) need to be sized and configured to carry the **full anticipated load of the system** in the event of an outage of other components. If this requirement is not met, an outage of one component may overload its backups, causing a system outage. 

#### 2) Continuous single-server updates 

A high availability Mattermost system can apply most configuration changes and dot release security updates without interrupting service by following a continuous single server update procedure: 

1. **Disconnect redundant servers** - Configure load balancers to consolidate requests to a single application server capable of supporting anticipated traffic during update procedure (depending on resources available, you may choose to run updates during low traffic periods). 
2. **Apply single server update** - Apply update to single server by updating `config.json` and running a command to load the new configuration into the application server, which continues to operate without down time. 
3. **Apply update to redundant servers** - Apply the same updates to the redundant servers. 
4. **Reconnect redundant servers** - Configure load balancers to once again balance traffic across all application servers. 

Step-by-step instructions for these procedures are available: 
- [Update system configuration changes while operating continuously](XXXXXX)
- [Update system with security patch dot release while operating continuously](XXXXXX) 

**Exception:** A brief period of maintenance downtime is required if you are changing any of the following: 

- **Configuration settings requiring server restart** (Default Server Language, Rate Limiting, Webserver Mode, Database or High Availability) - typically update and restart time is less than 5 seconds 
- **Database schema** - typically update and restart time is less than 30 seconds 

Step-by-step instructions for these procedures are available: 

1. [Update with database schema changes requiring maintenance downtime](XXXXXX) 
2. [Update with configuration change requiring maintenance downtime](XXXXXX)

Other than these exceptions, the Mattermost system should be able to run uninterrupted and resilient to outages of individual components. 

// The following section probably goes after [Configuration and Compatibility](https://docs.mattermost.com/deployment/cluster.html#id13) section. 

### Update Guide 

Update procedures to run continuously or, for certain updates, with brief downtimes. 

#### Update system configuration changes while operating continuously

XXXXXX - Needs work: 

To update config in HA - During low load times, consolidate on one app server, reload config.json without stopping server, then bring up other app servers who initialize with new config. Note: Only works with config options that don't require server restart (see docs) 

#### Update system with security patch dot release while operating continuously

XXXXXX - Needs work: 

To upgrade app server in HA (no database changes, e.g. most security patches) - Bring up a duplicate set of app servers with the new version of Mattermost, set NGINX to move all new request to new set of servers. Shut down the old servers, which will disconnect web sockets--for a brief moment, clients will show yellow in their message input boxes to reflect momentary disconnect, then will reconnect to the new upgraded servers. 

#### Update with database schema changes requiring maintenance downtime 

XXXXXX - Needs work: 

To upgrade app server in HA when database changes are involved, or if a config.json change requires server restart - Run script to stop NGINX, run the upgrade procedure in series, first app server started with new version will upgrade the database, once all servers are started turn on NGINX. Mattermost servers, because they are binaries, start very quickly, less than 5 seconds typically. 

#### Update with configuration change requiring maintenance downtime

XXXXXX - Needs work: 

To upgrade app server in HA when database changes are involved, or if a config.json change requires server restart - Run script to stop NGINX, run the upgrade procedure in series, first app server started with new version will upgrade the database, once all servers are started turn on NGINX. Mattermost servers, because they are binaries, start very quickly, less than 5 seconds typically. 

-----

**Comment by JeffSchering** [comment]
Created PR https://github.com/mattermost/docs/pull/825
