### ISSUE TITLE
Get OS consistent across different sections of install guide. 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#804]
For RHEL 6.6 install guide it's confusing to see NGINX with instructions on RHEL, RHEL & Ubuntu, then RHEL, Ubuntu and Debian in different areas in the same guide. 

0/5, propose: 

1. Dropping Debian from official docs, so it's clear you can't call support and ask for Debian troubleshooting (it's in community guide only right now I think, 

2. Have either a) both RHEL and Ubuntu in NGINX install instructions to be consistent with NGINX configuration instructions, or b) have the configuration instructions separate for RHEL and Ubuntu to be consistent with install instructions. 

3. State at the start of NGINX instructions which OS is supported in the instructions--it's confusing because it starts with RHEL 6.6 install, and for NGINX goes all over the place, if we're going to go all over the place, let people know in the intro, so it's not surprising or confusing. The end user should not know that we're using includes. 

![image](https://cloud.githubusercontent.com/assets/177788/22158824/ffedfcce-def2-11e6-8b10-8f73b84032fa.png)

![image](https://cloud.githubusercontent.com/assets/177788/22158846/191846c8-def3-11e6-88ed-5eb962817953.png)

**Comment by swapnilogale** [comment]
Happyto look at this @justinegeffen

**Comment by swapnilogale** [comment]
@justinegeffen as discussed, I'll look at merging the 2 RHEL topics (across 6 and 7) and address these inconsistencies in the process-

**Comment by justinegeffen** [comment]
Hi @swapnilogale - wanted to follow up on this and find out if you have any questions or issues I can assist with. :)

**Comment by justinegeffen** [comment]
I believe this feedback has been addressed by the docs 2.0 work. We're also actively working on improving the installation documentation as part of the 2022 Growth Spike, and Support has added this to their workload. As such, I'm closing this issue. Thanks, @it33!
