### ISSUE TITLE
UX guidelines for on-screen text

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#805]
Since there's a PR to update our UX guidelines (#759), I'll create a new issue to track new guidelines for on-screen text, rather than creating a WIP PR for it which would result in merge conflicts:

1 - The title of a setting should explicitly describe what a setting affects. 
Example: A setting to default the expanded or collapsed state of link previews
       - incorrect: "Link previews"
       - correct: "Automatically expand link previews"

2 - Use the active voice
     - incorrect: "This action will delete..."
     - correct: "This action deletes..."

3 - Be concise
     - incorrect: "Are you sure that you want..."
     - correct: "Are you sure you want..."

4 - Ensure plural interpretations work when applicable
     - incorrect: "...breaks the integration using it"
     - correct: "...breaks any integrations using it"

5 - Test text with machine translation to reduce non-obvious, English-specific jardon: 
     - incorrect: "There are a few configuration settings you might want to fiddle with when setting up your instance of Mattermost"
     - correct: “There are a few configuration settings you can adjust when setting up your instance of Mattermost.”

Note: The incorrect string above machine-translated into German and then back into English looks like this: "There are some configuration settings you could know if your instance Matter Most violin".

See https://pre-release.mattermost.com/core/pl/nf9agdb48ife9yrhzw7z4cj6do for more details

**Comment by it33** [comment]
Great start!

Propose we include the "Thor test", or refer to it as the embodiment of the "Mattermost voice for documentation and help text." The Thor test asks "How would Agent Coulson explain this to Thor?" which means explaining something to an alien being in simple terms without jargon or complexity. 

This is probably the "north star" to think about (include being concise, easy to translate) and the other guidelines seem like finer details/safety net checks.

**Comment by jasonblais** [comment]
1. consideration of surrounding UI, including titles above the input field (e.g. "Notification Preferences for [CHANNEL]) and
2. consistent with naming of input fields with similar actions, e.g. "Send email notifications", "Send desktop notifications".

**Comment by jasonblais** [comment]
See #1084 for proposed changes
