### ISSUE TITLE
Add Mattermost Style Guide update for System Console redirect procedure

### ISSUE THREAD

**Issue by it33** [mattermost/docs#811]
Propose adding guideline to [Mattermost Style Guide](https://docs.mattermost.com/developer/style-guide.html) that we should never hardcode any URL appearing to an end user and instead use only redirects in the form of `https://about.mattermost.com/default-[TARGET PAGE]`

This allows us to update the locations of resources without breaking the product Mattermost. This is also important for working with partners and providing them links. 

Proposed: 

1. Website team would be responsible for adding new redirects to about.mattermost.com 
2. Pages in about.mattermost.com that redirect should have a title prefixed with `Redirect - ` so they're easy to find 
3. Once this ticket is added, we can open new Help Wanted to find and clean up hard coded links remaining in the UI

**Comment by justinegeffen** [comment]
This has been added to the Product Management Handbook [here](https://handbook.mattermost.com/operations/research-and-development/product/product-management-team-handbook#how-do-i-create-redirects-for-in-product-documentation). @jasonblais, could you double-check and confirm? Thank you!
