### ISSUE TITLE
Document best practices for Mattermost open source projects

### ISSUE THREAD

**Issue by it33** [mattermost/docs#812]
Discussing with @jasonblais, thinking we should document our own processes around open source project checklists, 

Document best practices for open source projects, both from Mattermost and from community 

- Including a LICENSE file 
- How to properly display attribution 
- How to include libraries with multiple licenses
- Code of Conduct 
- Contributor's Guide 
- What should go into a README

**Comment by cwarnermm** [comment]
@aspleenic - This is a great ask that may have much farther reaching implications than product documentation. Tagging you for visibility as there may be some new content that can be added or content that's already under consideration.

**Comment by aspleenic** [comment]
Thanks for the add @cwarnermm - I'll keep an eye on things as they progress and adjust/chime in on any documents that may need updating or inclusion.
