### ISSUE TITLE
Change "Mattermost Administrator's Guide" to "Administrator's Guide" to match the rest of the TOC 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#815]
Proposed Help Wanted

"Mattermost" in TOC looks out-of-place

![image](https://cloud.githubusercontent.com/assets/177788/22320116/305f8a72-e33e-11e6-87c4-ac54fe90d5b9.png)

**Comment by JeffSchering** [comment]
This is resolved by the merge of PR https://github.com/mattermost/docs/issues/816.
