### ISSUE TITLE
Typing error in documentation

### ISSUE THREAD

**Issue by plotxy** [mattermost/docs#819]
In the documentation for Ubuntu 16.04 LTS, the point 7b says:

> Start the Mattermost server as the user mattermost:
> sudo -u mattermost /.platform

Command should be
`sudo -u mattermost ./platform`

**Comment by JeffSchering** [comment]
Fixed. See commit https://github.com/mattermost/docs/commit/1d0a1bbc503e28beeb70f3721c03ef3183623ace. The same typo is in the other install docs and I'll fix those too.
