### ISSUE TITLE
Add checklist item for bugs to have either a manual or automated test to find regressions

### ISSUE THREAD

**Issue by it33** [mattermost/docs#821]
Propose we add a checklist item for bug tickets to have a manual or automated test added to detect if the bug arises again. 

If the person verifying the ticket doesn't see that the work has been done, or a ticket created, they should create a ticket to have the automated or manual test added. 

Example: 

- Ticket with bug: https://github.com/mattermost/platform/issues/5215
- Ticket asked for automated test to be added: https://github.com/mattermost/platform/issues/5216

In future, we should avoid tickets with hand-crafted repro steps (e.g. [PLT-5356](https://mattermost.atlassian.net/browse/PLT-5356)) and instead any regression should reference a failed test, e.g. [lists-with-blank-lines-before-and-after](https://github.com/mattermost/platform/blob/master/tests/test-markdown-lists.md#lists-with-blank-lines-before-and-after)

**Comment by amyblais** [comment]
Closing as this is covered in our [release process checklists](https://docs.mattermost.com/process/feature-release.html#d-t-minus-19-working-days-feature-testing).
