### ISSUE TITLE
Add checklist items to run minimal /loadtest routines on PRs for UX

### ISSUE THREAD

**Issue by it33** [mattermost/docs#822]
We need a way for contributors to find obvious UX issues before submitting PRs by helping them more easily access our testing tools. 

We have /loadtest automation to find UX regressions, but they're not being run, propose: 

1. Add requirement in [contributor's guide under preparing a PR](https://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) that any UI PR run at least the markdown loadtests before submitting the PR. 

2. Add a requirement for testing a PR prior to merge that the same load tests are run. 

About load tests: 
- https://github.com/mattermost/platform/blob/master/tests/README.md

Markdown load tests: 
- https://github.com/mattermost/platform/blob/master/tests/test-markdown-basics.md
- https://github.com/mattermost/platform/blob/master/tests/test-markdown-lists.md

**Comment by jasonblais** [comment]
PR for 1) https://github.com/mattermost/docs/pull/824

@doosp is helping prepare a testing doc, which is relevant for 2
