### ISSUE TITLE
Document expectations of pre-release server

### ISSUE THREAD

**Issue by it33** [mattermost/docs#826]
We should document expectations of the pre-release server when people join. 

What community should expect: 

- Latest build off master, updating 11pm California time
- There will be bugs, they'll be fixed before release based on priority 

What core team and Mattermost, Inc. should be doing: 

- If we're pushing an change outside of 11pm California time, let people know in Reception 

P2: 
- It would be nice to have a bot posting a message to Reception when we push new version, and include a link to the documentation on pre-release.

**Comment by justinegeffen** [comment]
This is addressed in: https://handbook.mattermost.com/operations/workplace#what-is-the-mattermost-community-server. Closing. :)
