### ISSUE TITLE
Document quality/development/support level definitions

### ISSUE THREAD

**Issue by lfbrock** [mattermost/docs#827]
1. Quality 
  - Production 
    - Recommended for production 
    - Supported in Mattermost, Inc. SLA
    - Documented
    - Included in security reviews
  - Beta 
    - Not recommended in production without [Premier Support](https://about.mattermost.com/support/) engagement with Mattermost, Inc. 
    - Minimal documentation 
    - Disabled by default, must be turned on via run-time feature flag
    - Tested thoroughly on a small set of platforms, with tickets and work items drafted, made available to public for testing and feedback in more platforms 
  - Experimental (“preview” is so confusing, since we have a “Preview” install on Docker as well)
    - Not recommended for production 
    - Minimal feature is not yet complete 
    - Less than minimum documentation available 
    - Disabled by default, must be turned on via run-time feature flag
2. Development 
  - Under Development
    - Experimental or Beta quality
    - Improved, minimal features not yet complete. Beta or experimental quality. 
  - Active Development (Note: We should figure out what to call this_
    - Production quality
    - Improvements and maintenance changes accepted
  - Maintenance 
    - Production quality 
    - Maintenance changes accepted 
  - Deprecated 
    - To be discontinued 
3. Support 
  - Unofficial peer-to-peer support 
    - Peer-to-peer support on forum.mattermost.org
  - Officially supported

**Comment by JeffSchering** [comment]
Closing. PR is in progress: https://github.com/mattermost/docs/pull/853
