### ISSUE TITLE
Local File Storage in install guides

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#829]
Mostly quoted from @JeffSchering, following a discussion with him:

If people follow the installation instructions, then changing `./data/` to `/opt/mattermost/data` in [step 4 of configuring the Mattermost server](https://docs.mattermost.com/install/install-ubuntu-1604.html#configuring-mattermost-server) may be redundant.

This is because `./data/` is relative to the current directory, which is `/opt/mattermost`. Moreover, `/mattermost/data` might not be what administrators want either.

Finally, the installation instructions say this:

```
Create the storage directory for files.
sudo mkdir /opt/mattermost/data
.. note::
 The storage directory will contain all the files and images that your users post to Mattermost, so you need to make sure that the drive is large enough to hold the anticipated number of uploaded files and images.
```

which implies that the data directory must be `/opt/mattermost/data` when in reality it can be anywhere reachable from the mattermost directory that has sufficient access permissions for the mattermost user.

Thus, propose revisiting how local file storage is set in the install guides.

**Comment by justinegeffen** [comment]
Confirmed that these instructions have been updated since this issue was opened and the path is no longer mentioned. @jasonblais, screenshot attached for reference.

![Screen Shot 2020-09-16 at 13 33 47](https://user-images.githubusercontent.com/4223530/93331893-4268e000-f821-11ea-901d-75e18c8daa81.png)
