### ISSUE TITLE
[Help Wanted] Add Japanese documentation to international documentation page

### ISSUE THREAD

**Issue by it33** [mattermost/docs#83]
While docs.mattermost.com does not yet support localization, [an international section has been created to support documentation for communities where English language is uncommon](https://github.com/mattermost/docs/blob/master/source/install/i18n.md). 

This ticket is to welcome pull requests for Japanese documentation to be added to this section, based on considerable interest from the Japanese community. For example: 
- [Qiita articles on Mattermost](http://qiita.com/tags/Mattermost)
- [Prototype of localization support for docs.mattermost.com](https://github.com/mattermost/docs/pull/80)

**Comment by cwarnermm** [comment]
All localized product documentation content now lives in the User Forum where it can be maintained by the Mattermost Community. Closing.
