### ISSUE TITLE
Document what the "About Mattermost" dialog means

### ISSUE THREAD

**Issue by it33** [mattermost/docs#833]
It's not obvious what release numbers mean in the About Mattermost dialog: 

![image](https://cloud.githubusercontent.com/assets/177788/22580298/140201c6-e98c-11e6-95c2-7362e7755c06.png)

Here's our existing documentation, which doesn't explain it: 
https://docs.mattermost.com/process/release-process.html?highlight=numbering#release-numbering

![image](https://cloud.githubusercontent.com/assets/177788/22580330/4abf4b10-e98c-11e6-9382-d01e9fec001a.png)

**Comment by justinegeffen** [comment]
I've reviewed https://docs.mattermost.com/process/release-faq.html#release-numbering and it has been updated to include more detailed information about release numbering.
