### ISSUE TITLE
Update docs with new "Help Wanted" process

### ISSUE THREAD

**Issue by it33** [mattermost/docs#835]
Not urgent, just opening a ticket to update [Contributor's Guide](https://docs.mattermost.com/developer/contribution-guide.html) and [APR page](https://docs.mattermost.com/process/accepting-pull-request.html).

"APR" no longer exists in labels. 

Propose it's updated to reflect the new process for Help Wanted (after the new process is use for a little while, with rough edges smoothed out),

**Comment by jasonblais** [comment]
Thanks, will do once https://github.com/mattermost/docs/pull/737 is approved

**Comment by jasonblais** [comment]
Will also update [terminology](https://docs.mattermost.com/process/training.html#apr)

**Comment by jasonblais** [comment]
Included in #737
