### ISSUE TITLE
Add "Mattermost Summit" doc

### ISSUE THREAD

**Issue by it33** [mattermost/docs#836]
Opening a ticket for us to create a "Mattermost Summit" doc while we're at our offsite next week in Las Vegas. We can begin with a stub and build more as we go, some topics to include: 

- Goals & principles
- Hackathon/Maker day info 
- Unconference 
- Attending in-person and online

**Comment by it33** [comment]
From Corey's post about Hackathon at Summit: 
```
Developer outline for Hackathon aftermath
    1. Is the code production quality or an experiment?
    2. Do PMs think it's a worthwhile inclusion?
    3. If yes to 1&2 then create a jira tix
        i. Explain the feature in detail for testing
        ii. Outlining any remaining work
        iii. Schedule during sprint planning
Submit PR and setup test server for early feedback even if there is remaining work.
```

**Comment by justinegeffen** [comment]
As this refers to a working document for the event which isn't in the Handbook, I am closing this issue. More than happy to reopen if there's a need to add this to our Handbook archive for reference.
