### ISSUE TITLE
Review for typos: https://docs.mattermost.com/guides/community.html?highlight=thor

### ISSUE THREAD

**Issue by it33** [mattermost/docs#837]
Not urgent, found a pretty clear typo, probably others, @lindy65 could you help review and submit a PR when you have a chance with corrections?

**Comment by lindy65** [comment]
@it33 Did you already correct the typo you found because I've checked this doc a few times and find no typos?

**Comment by JeffSchering** [comment]
Maybe this is what you noticed?
![image](https://cloud.githubusercontent.com/assets/20325173/22612019/dccc918e-ea22-11e6-861a-ae815465a453.png)
If so, it's an artifact of the search highlighting. When you remove the highlight, it looks ok.

![image](https://cloud.githubusercontent.com/assets/20325173/22612074/296715e6-ea23-11e6-9917-a4109f3b408c.png)

I too didn't see any glaring typos.

**Comment by it33** [comment]
Ah, okay, thanks Jeff!

**Comment by it33** [comment]
Thanks @lindy65 as well, sorry, it looked broken, I guess it's as intended,

**Comment by lindy65** [comment]
No worries @it33 !
