### ISSUE TITLE
[Help Wanted] Enable headings in Left Sidebar to collapse when clicked

### ISSUE THREAD

**Issue by it33** [mattermost/docs#84]
Would appreciate help from anyone who knows how to get the headings, e.g. "MESSAGING", "GETTING STARTED", etc. to collapse the links below them when clicked, and expand them when clicked again. 

It's probably a setting in Sphinx, we just need help understanding which setting. 

![image](https://cloud.githubusercontent.com/assets/177788/14224526/93f23de4-f854-11e5-9d0a-d99090253bbd.png)

**Comment by shieldsjared** [comment]
Not really wanting to install Sphinx and python to test it, but have you tried setting the `html_theme_options.collapse_navigation` property to `True` in the `conf.py`?  It looks like the theme defaults to False... Not sure if this will give the desired behavior or not.

see: [https://github.com/snide/sphinx_rtd_theme#project-wide-configuration]

**Comment by shieldsjared** [comment]
Nevermind, I went ahead and built it w/ that option and it just enables/disables the page-level collapsing, but not the headers.

**Comment by shieldsjared** [comment]
Looks like the theme _does not_ have a published setting for this, but I wrote a very short snippet of JavaScript that you can include in `myscript.js` to make this happen. 

```javascript
	$('.wy-menu-vertical .caption').on('click', function(){
		$(this).next().slideToggle();
	});
````

The problem with doing this is that the header provides no UX indicator that it is collapsible.  You would have to _stumble upon_ it.  Would you prefer to also have the + and - images displayed on the headers?  Or some other sort of indicator?  Do you want only one primary section visible at a time?  Let me know and I can whip something up and submit a PR.

**Comment by it33** [comment]
Hi @shieldsjared, 

Would love your help! We like to use [MongoDB Docs](https://docs.mongodb.com/manual/administration/) as a guide, so maybe no indicator and one section shown at a time? 

I think the important thing is that when you find a single page the left hand sidebar expands properly to show it--that removes the need for expand/collapse indicators because _most_ of the traffic is to individual pages--whose view would demonstrate the ability for sections to expand. 

Hugely appreciate your help!!

**Comment by shieldsjared** [comment]
I'll see what I can come up with :)

**Comment by shieldsjared** [comment]
Created PR #347.  I made sure to test in IE11/Chrome/Firefox.

**Comment by it33** [comment]
Sweet! Thanks again @shieldsjared!
