### ISSUE TITLE
Add "© Copyright 2015, 2016, 2017 Mattermost, Inc." to copyright notice in docs repo

### ISSUE THREAD

**Issue by it33** [mattermost/docs#840]
Small polish ticket for anyone interested.

![image](https://cloud.githubusercontent.com/assets/177788/22609870/b60dba42-ea17-11e6-923b-97c0d7828539.png)

**Comment by jasonblais** [comment]
Fixed via https://github.com/mattermost/docs/commit/4062aaa062df8eef98ab1935a2914ed148036aa2

![image](https://cloud.githubusercontent.com/assets/13119842/22610128/f579e4fc-ea31-11e6-82b7-d58bd7a8d482.png)
