### ISSUE TITLE
Add Style Guide note on using "their" instead of "his or her" 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#842]
Add Style Guide note on using "their" instead of "his or her" if this is reasonable. My sense is it's the more modern usage, but open to discussion. 

Got a question on this in a PR review, and just need a decision one-way or another.

**Comment by it33** [comment]
Another instance of `s/he` where we need help. https://github.com/mattermost/docs/pull/737/files#diff-cead9c73b81b42ab6c2f07571856b472R126

**Comment by npcode** [comment]
"singular they" looks good to me. It is shorter and simpler than "she or he".

**Comment by JeffSchering** [comment]
Using "they" or "their" as a singular is probably ok, although its usage in this manner is controversial and you'll run into lots of people who think that "they" and "their" are plural only. In my own work, I try to write sentences in such a way as to avoid the situation altogether.

The case in question, for example:

> CM post questions and/or answers in Contributors room that s/he thinks are well-written.

can be rewritten as:

>The CM monitors the forum for well-written questions and answers, and posts them to the Contributors channel.

The rewrite leaves out the CM's opinion of what is well-written, but it's probably understood that CMs will go by their own view of what is well-written and what is not anyway. On the plus side, it makes the monitoring of the forums explicit, where before it was merely implied, so it ends up being a stronger sentence anyway.

**Comment by it33** [comment]
Sounds good, let's have the guideline to avoid the situation when possible and to be okay with singular they/their? Thanks Jeff, thanks npcode,

**Comment by JeffSchering** [comment]
Closing. Implemented in PR https://github.com/mattermost/docs/pull/865
