### ISSUE TITLE
Update Push Notification doc

### ISSUE THREAD

**Issue by it33** [mattermost/docs#847]
https://docs.mattermost.com/administration/config-settings.html#push-notification-server

^ This doc is out of date, doesn't match UI. 

This doc explains the fields: https://docs.mattermost.com/deployment/push.html#setting-up-hpns-push-notifications-in-enterprise-edition

Propose updating the out-of-date doc with links to Mobile Apps doc

**Comment by JeffSchering** [comment]
Closing. Resolved by https://github.com/mattermost/docs/pull/1357.
