### ISSUE TITLE
[Help Wanted] How to turn on Options for Sphinx site

### ISSUE THREAD

**Issue by it33** [mattermost/docs#85]
Can anyone help us turn on the "Options" for exporting to PDF and EPUB? 

Not sure if this requires custom work, help would be appreciated from anyone might be familiar with Sphinx

Example below of what we're looking for [from MongoDB documentation as an example.](https://docs.mongodb.org/manual/) 

![image](https://cloud.githubusercontent.com/assets/177788/14224541/e204c0c4-f854-11e5-9d2c-be43caf55af8.png)

**Comment by terukizm** [comment]
Hi, @it33.

I think the "Options" is just linked by generated PDF and epub files.

In our Makefile, It is possible to generate.

# How to make

Mac OS X

## epub

```
$ make epub

$ open build/epub/Mattermost.epub
```

## PDF(with LaTeX)

Install TeX Live (for Mac):

```
$ brew install cask mactex
```

Open new Terminal, and type this command.
You need to wait for a loooooong time... (I wasted 2 hours)

```
$ sudo tlmgr update --self --all
```

Generate:

```
$ make latexpdf
(press 'r' is error-skip)

$ open build/latex/Mattermost.pdf
```

In other approach, I had tryed to generate PDF with [rst2pdf](https://github.com/rst2pdf/rst2pdf/commits/master).
But, It is not good.
(*.md file is not supported, and there were some problems with the library dependencies.)

It is easy to generate this documents.
But It is difficult to generate "beautiful" documents, I think.

I hope this will help!

**Comment by shieldsjared** [comment]
Looking at the source of the generated page for this, it looks like it's purely custom by the folks at Mongo.  Are you looking for a quick-coolness factor, or are you looking to solve a problem.  If the later, what are the requirements and Im sure I can whip up something identical.

**Comment by it33** [comment]
Hi @terukizm, 

Thanks for your comment, I'm sorry I missed it for some reason. It's very helpful. We'll work on converting the docs to .rst to support PDF based on your advice. 

Hi @shieldsjared, 

The key feature for us was to export to PDF, and to EPUB would be nice-to-have. We weren't aware this UI was custom, we though it was a setting that was flipped on. I'll update the title to emphasize this. 

Our understanding is PDF would only work with Sphinx's RST format, and we've been starting the process of migrating our .md files to .rst. After the PDF export is enabled we have to continue that work. 

Options might be: 

#### 1. Quick fix with link 

A great addition would be to have a "PDF" link at the top of the page next to the ["Edit on GitHub"](https://github.com/mattermost/docs/pull/346) PR you're working on when the file is .RST. 

#### 2. Full menu 

So similar to screenshot, with some changes: 

- No need for version dropdown 
- Have PDF option with either "PDF (beta)" or "PDF" with the option only showing when file is .RST. 
- If it's easy, the same thing for EPUB, but not necessary
- `Report a Problem` linking to: https://github.com/mattermost/docs/issues
- `Edit on GitHub` to the [other PR you're working on?](https://github.com/mattermost/docs/pull/346) 

^ This is pretty complicated and I'd worry about a custom control needing tweaks here and there after it's created. It is slightly more useful with the addition of `Report a problem` link and has a coolness factor, 

Totally up to you which you feel might work? 

Thanks again for all your help, tens of thousands of people use docs.mattermost.com every month and your improving the experience for every one of them!

**Comment by shieldsjared** [comment]
@it33 - going to digest this a little bit and see how some others have done their _Report a Problem_ links. If I _werent_ an engineer and noticed an issue on a page, my initial reaction wouldn't be to click an "Options" flyout... 

This actually makes me wonder if this could be a great use case for the [site chat feature](https://mattermost.uservoice.com/forums/306457-general/suggestions/8810731-implement-a-site-chat-feature) that's been voiced.  

...just thinking out loud...

I'm going to experiment with the PDF and see how ready the docs are, as-is. I find it crazy that Sphinx won't translate the markdown into PDF... Somebody else has to have run into that wall and solved it already.

**Comment by shieldsjared** [comment]
Good news, @it33 : I spoke too soon... After spending more than a few minutes researching Sphinx and the RTD themes (again, i took this stuff on knowing zilch), the options pane IS built-in, and can be customized however you want it.  Here's a screenshot after minimal massaging of the built-in template (which was tailored for use on RTD).  Would you want to go-live with this _without_ the PDF/EPUB options, and add that as a feature down the road, or would you prefer waiting until at least one option is available?

![mattermostdocsoptionspanescreenshot](https://cloud.githubusercontent.com/assets/600643/17503254/fd1d49de-5db3-11e6-9894-8f92f279532c.gif)

**Comment by it33** [comment]
Thanks @shieldsjared! 

I think every little bit helps, at least the "Report a Problem" link gets created. 

We can open a new ticket to add PDF and EPUB independently to the options dialog later, 

Thanks again for your help!!

**Comment by shieldsjared** [comment]
Excellent. I'll submit very minor PR to make this happen tomorrow. 

Get Outlook for iOS




On Wed, Aug 10, 2016 at 12:27 AM -0500, "it33" <notifications@github.com> wrote:












Thanks @shieldsjared! 



I think every little bit helps, at least the "Report a Problem" link gets created. 



We can open a new ticket to add PDF and EPUB independently to the options dialog later, 



Thanks again for your help!!

**Comment by esethna** [comment]
Closing as solved. Thanks @shieldsjared!
