### ISSUE TITLE
Need article on SSL setup with NGINX 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#850]
Need this: https://docs.mattermost.com/install/install-ubuntu-1404.html#configuring-nginx-with-ssl-and-http-2

Broken out into something like this: https://docs.mattermost.com/install/smtp-email-setup.html

This is for deployment solutions checklist to have people setup SSL after an automated install deploys Mattermost with NGINX

**Comment by JeffSchering** [comment]
Here's the link for SSL on NGINX: https://docs.mattermost.com/install/config-ssl-http2-nginx.html
