### ISSUE TITLE
Document server data 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#858]
[Per request](http://forum.mattermost.org/t/data-privacy-local-installation/2865), we should document more specifically what happens when [Security Fix Alerts and Error and Diagnostics Reporting settings](https://github.com/mattermost/platform/blob/master/build/PRIVACY_POLICY.md) are enabled.

**Comment by jasonblais** [comment]
Thanks! Agree -- as per discussion during offsite, this will be included prior to 3.7 release. Have a task for myself to add it so assigning this issue to myself

**Comment by jasonblais** [comment]
Completed with #912
