### ISSUE TITLE
Document what data is cached on Mattermost clients

### ISSUE THREAD

**Issue by JeffSchering** [mattermost/docs#859]
Need to document what data is on mobile devices and on desktops while the client apps are running and when the apps are closed. Include RN app, Desktop app, and browser app.

From Elias:

>In RN it will store everything on the device until the app is closed.
The things that are stored on a persistent way are:
> - The last team id you were in.
> - The last channel id you were in on each team
> - The url of the server
> - The token of your session
>
>The rest of the info like teams channels, posts,  etc is going to be present in the device until you close the app

**Comment by lfbrock** [comment]
Note: Semi-related [PR](https://github.com/mattermost/mattermost-mobile/pull/429) based on [this conversation](https://pre-release.mattermost.com/core/pl/8oue838h6pfgtkkrdcxz7hutsy)

**Comment by JeffSchering** [comment]
@enahum Do you happen to also know what data is left on the devices by the Desktop app and the Web app?

**Comment by enahum** [comment]
hmm for the desktop and webapp the same data is stored in the localStore, not sure exactly what it is, I know we store the post drafts and we store things like last team viewed and last channel viewed for each team, I think you'll have more luck asking @hmhealey

**Comment by JeffSchering** [comment]
Closing. Resolved by https://github.com/mattermost/docs/pull/1179
