### ISSUE TITLE
Inconsistency in "Installing mattermost on Ubuntu 14.04 LTS"

### ISSUE THREAD

**Issue by FaXaq** [mattermost/docs#860]
Hi,

I went through installing and had to change something from the tutorial to make it work.

On this part particularly : https://github.com/mattermost/docs/blob/master/source/install/install-ubuntu-1404-mattermost.rst

I had to change the point 8b, 

```start on runlevel [2345]
stop on runlevel [016]
respawn
limit nofile 50000 50000
chdir /home/mattermost/mattermost
setuid mattermost
exec bin/platform
```
to : 
```start on runlevel [2345]
stop on runlevel [016]
respawn
limit nofile 50000 50000
chdir /opt/mattermost
setuid mattermost
exec bin/platform
```
since in the first part of the tutorial, we set up the mattermost directory in `/opt/mattermost`.

**Comment by senk** [comment]
@FaXaq you're right, thanks!

**Comment by JeffSchering** [comment]
Thanks @FaXaq ! Fixed in commit https://github.com/mattermost/docs/commit/fdff969e601408279fde4f70357c02cb94533a71
