### ISSUE TITLE
Improve CLI documentation

### ISSUE THREAD

**Issue by lfbrock** [mattermost/docs#891]
Currently, the CLI documentation is unclear about what identifier should be used for a command - for example, [using the Team Name for `platform team` commands doesn't work](https://github.com/mattermost/platform/issues/5336), and you need to use the team url or ID. I think we've also had similar questions about what to use for user / channel commands as well. 

We should update the documentation to make it clear what type of identifier(s) should be used for the different commands.

**Note:** The CLI documentation is generated from the CLI help in the product, so we may want to change it there as well.

**Comment by jasonblais** [comment]
Looks like this is clarified now in the CLI docs, after the new CLI tool was added https://docs.mattermost.com/administration/command-line-tools.html#platform-team-delete
