### ISSUE TITLE
Update README with RST examples

### ISSUE THREAD

**Issue by it33** [mattermost/docs#892]
Propose in README we Include examples of RST headings, TOC, with link to style guide, and maybe other formatting options--or a link to a template page we can use that's not the full style guide. 

It's much faster for people to work out of a template. I find myself always searching for 

```
.. contents::
  :backlinks: top
  :local:
```

It seems many people are using RST for the first time: https://github.com/mattermost/docs/pull/889#issue-208569750

**Comment by justinegeffen** [comment]
Addressed by: https://github.com/mattermost/mattermost-handbook/pull/103.
