### ISSUE TITLE
Proofread and edit Product Overview

### ISSUE THREAD

**Issue by it33** [mattermost/docs#895]
[Merging updated product overview](https://github.com/mattermost/docs/pull/879), asking for someone to review for style and proof read: https://docs.mattermost.com/overview/product.html

**Comment by it33** [comment]
`@lindy65, not urgent, could I ask your help to proofread and correct when you have a chance?

**Comment by lindy65** [comment]
@it33, done.  PR is [here](https://github.com/mattermost/docs/pull/903)

**Comment by JeffSchering** [comment]
Closing... PR is completed and merged.
