### ISSUE TITLE
Quality gates for Mattermost releases

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#902]
Set quality gates for different steps of the release process, reducing ambiguity on what bug warrants a fix prior to the release (so far it's been largely subjective).

This should also include a consideration of goals and principles for the quality gates.

Might be a good project for Linda after she's seen our release process from start to finish with 3.7.

See below for early drafts of quality gates from 2016:

1 - https://github.com/mattermost/process/blob/master/release/quality-gates.md

```
# Quality Gates

Quality Gates are used to gradually raise standards as a product matures. 
New items may or may not be added each release as criteria to declare the Quality Gate met.

### 1. Feature Complete

- Confirm all security reviews were completed
- All install instructions reference tested versions of dependencies and tools
- Draft documentation for all new features
  - IT admin and developer documentation is included under /doc and a link provided from /doc/README.md
  - End user help documentation is included in /doc/help and a link provided from /doc/README.md
- Any feature with a potential privacy or security issue (e.g. YouTube links that include tracking) has a System Console option to turn the feature off, and it is set to off by default
```

2 - https://docs.google.com/document/d/1S4VWtDXCTXw6toXBbbWrdmWuPas1NkKV33YCp9YCy-k/edit#bookmark=id.rrwu4sc307nj

![image](https://cloud.githubusercontent.com/assets/13119842/23107479/f3c90d3a-f6cb-11e6-8ff9-8146ecc91584.png)

**Comment by lindalumitchell** [comment]
@jasonblais I realized I still have this old issue on my assignments, but it looks like everything has since been covered by Amy and others in release process updates. And continued updates happen via release retrospectives and other release team meetings. Shall we close this issue?

**Comment by jasonblais** [comment]
@lindalumitchell Yeah, if this is no longer relevant, you can close this issue.

**Comment by lindalumitchell** [comment]
Thanks Jason; closing.
