### ISSUE TITLE
Add email notification verification procedure

### ISSUE THREAD

**Issue by it33** [mattermost/docs#905]
People are having issues getting SMTP to work properly, and we need an end-to-end procedure to confirm SMTP and notifications are properly working as part of setup, something closer to this: https://docs.mattermost.com/deployment/push.html#setting-up-hpns-push-notifications-in-enterprise-edition

- Existing SMTP troubleshooting is sparse: https://docs.mattermost.com/install/smtp-email-setup.html#troubleshooting-smtp

**Comment by JeffSchering** [comment]
We should include the need to make sure that the **Notification From Address** field is filled out and has a valid email that an SMTP server can verify. My understanding is that SMTP servers verify that the domain part of an email exists (or maybe exists *and* has an active email server? MX record?) as part of anti-spam measures.

Also should add it to the help text in the UI.

![image](https://cloud.githubusercontent.com/assets/20325173/23139936/d0b905aa-f763-11e6-9160-ca8f852f3701.png)

**Comment by justinegeffen** [comment]
Hi @JeffSchering! I've taken a look at the docs and wanted to follow up on this to find out whether you'd be open to updating the docs as they would definitely benefit from the suggested changes. Let me know if you have any questions - happy to assist!

**Comment by JeffSchering** [comment]
Hi @justinegeffen 

Sorry for the late response. I'm not in a position to help out with this right now. Thanks!

**Comment by justinegeffen** [comment]
I've taken a look at the docs and they provide more details about troubleshooting. I couldn't find the UI section in the provided screenshot though (looked under push notifications and SMTP in System Console). Closing based on age of the issue.
