### ISSUE TITLE
Add standard way of describing meeting times 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#906]
Not sure where this goes, but we've been having miscommunication on meeting times lately and we should probably discuss a standard: 

1. When proposing meetings in different time zones use major cities as references for time, since it's clear and [easy to web search](https://www.google.com/search?q=time+in+new+york&oq=time+in+new+&aqs=chrome.1.0l2j69i57j0l3.3135j0j7&sourceid=chrome&ie=UTF-8), Avoid using "UTC", as it has been shown to causes confusion. 

2. When scheduling with customers, include equivalent times in other cities for attendees in brackets. 

Use: 
- `Thursday, February 23 at 9:00 AM San Francisco time` or 
- `Thursday, February 23 at 9:00 AM San Francisco time (12:00 PM New York time, 5:00 PM London time)`

Avoid: 
- `Thursday, February 23 at 9:00 AM UTC-8`

**Comment by JeffSchering** [comment]
Just curious... is there a meetings bot? or a reminder bot somewhere? Are bots allowed to DM people?

**Comment by lindy65** [comment]
PR is [here](https://github.com/mattermost/docs/pull/1053)

Note:  Have not yet included any reference to customers.  Chatting with Steve about how to present customer information in the docs.

**Comment by lindy65** [comment]
@it33, chatted with Steve about 2. above and he is of the opinion that we leave customer-specific information out of the docs for now.

**Comment by jasonblais** [comment]
Thanks! Given #1053 is now merged, I'll close this issue
