### ISSUE TITLE
[Help Wanted] Change Nginx to NGINX 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#91]
In all its documentation NGINX refers to itself in all capitals: https://www.nginx.com/resources/wiki/

**Comment by norganna** [comment]
Ticket is slightly wrong, it's spelling is NGINX not NGNIX (ie it's not nix it's inx)

**Comment by it33** [comment]
thanks @norganna, corrected now, much appreciated!

**Comment by ajerezr** [comment]
Hi.

My PR to change Nginx to NGINX. https://github.com/mattermost/docs/pull/149

**Comment by it33** [comment]
Thanks @ajerezr great work!
