### ISSUE TITLE
WIP - New mindset: Enlighten

### ISSUE THREAD

**Issue by it33** [mattermost/docs#917]
@crspeller and @it33 discussed adding a [mindset](https://docs.mattermost.com/process/training.html#mindsets) to help increase the effectiveness and efficiency of communicating with each other and the community. Sharing a draft from me here based on our conversation and this would be open for discussion: 

#### Enlighten

To deliver the right information to the minds of the appropriate audience. The right information as "light" and lack of it is "darkness". 

In using Mattermost, this means sending enough information in messages so that the receiver can react. 

- Avoid "I've added a ticket", instead use "Here is the ticket [link]" 
- Avoid "Hey" to check if someone is available, instead be explicit about what you need so the receiver can prioritize, e.g. "Not urgent, let me know when you're around to brainstorm offsite activities?" or "I need urgent help on escalated customer issue no one seems able to solve, are you around?" 

TBD, need to write more on communicating through issues, announcements, etc. how to make sure we're able to guide community to the information they need, and not putting critical information people need to know in "public" Mattermost channels with a few dozen people, when there are thousands of people interested in the information.

**Comment by it33** [comment]
Another example of "Enlighten" is making sure public channels where we're discussing features has the vital information in the header about who to talk, that meeting notes make sense to people who missed the meeting, etc.

**Comment by it33** [comment]
Thinking we might make this a value, instead of a mindset. It's about how we should behave under ambiguity.

**Comment by justinegeffen** [comment]
This is a great mindset and there's room for it in: https://handbook.mattermost.com/company/about-mattermost/mindsets. Some of what's laid out is also mentioned here in terms of clarity and precision: https://handbook.mattermost.com/contributors/join-us/recruiting. 

LMK if I can add this to the Handbook, @it33 and @crspeller. Thanks :)

**Comment by it33** [comment]
@justinegeffen the was a COM talk on being open that I should probably move into the handbook as it's a higher level context, it should cover this one, thanks for the note,
