### ISSUE TITLE
WIP: Document customer call procedure

### ISSUE THREAD

**Issue by it33** [mattermost/docs#919]
Opening a ticket to document procedure on customer calls: 

1. Making sure we understand the customer's goals and requirements before going into detailed technical questions, even if that is where technical people on the call want to take the conversation 
2. Guidelines on what we should share and not share. Knowing what NDA we're under. If we're saying "no" that a certain scenario isn't supported, to what extent do we share our roadmap and work under development? (we should share) 
3. Getting the agenda in advance to prepare for the call, possibly send documentation and guides ahead of time to focus on questions not covered. Having a process to turn questions not covered into more documentation for other customers. 
4. Have questions for them on how their deployment is going, how their technical setup looks, e.g. what drivers are they using, etc.

**Comment by justinegeffen** [comment]
@sadohert, I can't find this in the Handbook but wondering if it's part of onboarding/internal content? If not, and you have this at hand, would you be open to adding to to the Handbook either as a link or a section: https://handbook.mattermost.com/operations/sales.

Apologies if you're not responsible for this, feel free to tag onward. :)
