### ISSUE TITLE
Doc issue with cross-origin requests with 3.6.2

### ISSUE THREAD

**Issue by it33** [mattermost/docs#920]
Some users are reporting issues with 3.6.2 that may have to do with the security update. It seems to be related to proxy forwarding and using Mattermost from multiple URLs

Opening a ticket to document the issue in Changelog with link to a ticket to update the community as we track down the issue.

**Comment by jasonblais** [comment]
Added by https://github.com/mattermost/docs/commit/1868d553270caf107500bc825eaa07b556e0b306#diff-6d8bc7fdf1108df5a6734816051a32e3
