### ISSUE TITLE
Clean up Developer's guide based on contributor feedback

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#927]
- give an example of how to run a client unit test
- make it easier to configure DB ports (explain somewhere in the docs?)
- create an admin first before running tests (which automatically makes the first user an admin, making it hard to get admin access later)
 - make the developer docs more user friendly during first contributor experience (particularly when setting up the local dev environment) 
 - consolidate the different community pages (code contribution guidelines, developer setup, developer flow, troubleshooting, running Mattermost, ...)

**Comment by jasonblais** [comment]
- include better guidelines on when unit tests are required (for server and client), and how to include them in the project

**Comment by lfbrock** [comment]
^ Just a note about that, I think it wasn't clear to the person what types of tests are required (they weren't sure if they needed to do UI tests as well as unit tests)

Here's the conversation for reference: https://pre-release.mattermost.com/core/pl/qeo116wqq3ygjxqamzsm6w4etc

**Comment by jasonblais** [comment]
Yea, given the feedback was such a long time ago, it may be outdated. I'd recommend we reach out to contributors to learn opportunities for improving our developer's guide for contributors.
