### ISSUE TITLE
Update post-Bitnamni install instructions

### ISSUE THREAD

**Issue by it33** [mattermost/docs#932]
Update https://docs.mattermost.com/install/install-post-deployment-solution.html to take someone who has just completed a Bitnamni deployment with Mattermost (https://bitnami.com/stack/mattermost) through the instructions to setup SSL, SMTP and complete their server config. 

I'm asking Bitnamni to use the link  https://about.mattermost.com/redirect-customize-install/ so we can rename the draft page that's been pushed (first link in this ticket).

**Comment by justinegeffen** [comment]
Confirmed that https://docs.mattermost.com/install/install-post-deployment-solution.html has the suggested content and the second link redirects to https://docs.mattermost.com/install/install-post-deployment-solution.html. 

![Screen Shot 2020-09-16 at 13 41 41](https://user-images.githubusercontent.com/4223530/93332604-5bbe5c00-f822-11ea-85fb-4f13edbe4eaf.png)
