### ISSUE TITLE
WIP: Video guidelines

### ISSUE THREAD

**Issue by it33** [mattermost/docs#933]
We're working on a video from our Las Vegas offsite and it probably helps to lay out some of our guidelines so future videos are all consistent. 

DRAFT: 

#### Guidelines for Mattermost video production 

The following guidelines are intended to simplify the process for producing quality videos for Mattermost for our community and customers, including creating a consistent look across shots, as well as consistent formatting with titles. 

Look

- Try to get the look of analog film, shallow depth of field, and post-processing to get as close to film as we can (need some details on how). 

Camera setup: 

- For Canon (e.g. Canon C300): EOS standard picture profile, 50 Mbits, 23.98 frame rate 

Logo and branding guidelines: 

- Available from [Mattermost branding guidelines](https://www.mattermost.org/brand-guidelines/) 

Titles: 
- Use Open Sans font with white letters and dark outline 
- For ID titles, introducing locations or people's names and roles, place at the bottom of screen. Justify right, left or center depending on the image on the screen. 
- Keep the same margins for all titles. When cutting from one scene to another with titles, titles shouldn't look like the "jump". 

Use a dark outline around white letters in Open Sans font with consistent margins: 

![image](https://cloud.githubusercontent.com/assets/177788/23342361/cfe3c9fe-fc0d-11e6-8e18-c94f3b2181be.png)

Avoid using drop shadow, as letters bleed into white background, particularly at top and left edges where dark separation line is thin: 

![image](https://cloud.githubusercontent.com/assets/177788/23342380/17bdd09e-fc0e-11e6-9cc7-fb33f2252ead.png)

**Comment by it33** [comment]
Adding title example ![title_example](https://user-images.githubusercontent.com/177788/27252455-e1796ec8-5313-11e7-81bd-9abf79392678.png)

**Comment by justinegeffen** [comment]
We have a great video content guideline doc here: https://handbook.mattermost.com/operations/messaging-and-math/content-marketing/video-content and we also have guidelines around brand usage here: https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/brand-and-visual-design-guidelines. Closing. :)
