### ISSUE TITLE
WIP: Events program 

### ISSUE THREAD

**Issue by it33** [mattermost/docs#936]
Opening a ticket to track development of an events plan 

- We should have goal and principles around a plan for events that includes both online (dev meetings, brownbags) and offline (meetups, conferences), etc. 

High level: 

- There's an opportunity to accelerate engagement with our communities 
- We're probably not doing enough to organize and attend meetups around Mattermost 
- We should be answering more "call for proposals/speakers" for events, particularly OSCON 
- We should open a separate ticket to think about training programs, with conferences as part of an overall program. [Community Leadership Summit](http://www.communityleadershipsummit.com/) should be on the list

**Comment by justinegeffen** [comment]
This is covered in: https://handbook.mattermost.com/contributors/contributors/guidelines. :) Closing.
