### ISSUE TITLE
Add a note to WebRTC doc that it'll be refactored

### ISSUE THREAD

**Issue by it33** [mattermost/docs#937]
https://github.com/mattermost/docs/blob/master/source/deployment/webrtc.rst

We need to write out our roadmap for plug-in architecture and update this WebRTC page to note that we're going to re-write WebRTC as a plug-in and the current version will remain in beta quality and maintenance mode, and eventually replaced with one that works in a plug-in architecture. 

1-1 video/audio calling is intended to remain open source. We haven't finalized a decision on whether group calling would be part of Enterprise Edition or not, but are listing it as enterprise just to be safe https://about.mattermost.com/direction/

**Comment by JeffSchering** [comment]
This has been implemented. See https://docs.mattermost.com/deployment/webrtc.html
