### ISSUE TITLE
Navigation panel disappearing scrollbar

### ISSUE THREAD

**Issue by fishbike** [mattermost/docs#938]
On 3.6.0 desktop / 3.6.2 server, when starting up the desktop app (Windows 10) on a laptop (1366x768), using the team navigation bar on the left, in a team with 20+ channels, I see the scrollbar in the navigation panel (so I can get to offscreen channels). 

Switching between teams, and then back to the team in question, the scrollbar has disappeared, making my only option to browse all channels altering application zoom.

**Comment by JeffSchering** [comment]
Hi @fishbike, this is the docs repository. Can you create an issue for this in the platform repository at https://github.com/mattermost/platform/issues?

**Comment by fishbike** [comment]
I see, my mistake, thanks. https://github.com/mattermost/platform/issues/5614
