### ISSUE TITLE
Update marketing guidelines for whitepapers

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#947]
1. “Objective / Trustworthy” - We should sound like a trusted adviser, avoid subjective references to competing products
2. Text should be easily understood by everyone from North America, Europe (covers Latin America) and Japan/Korea

**Comment by justinegeffen** [comment]
I think this page addresses this issue: https://handbook.mattermost.com/operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-write-mattermost-case-studies#writing-guidelines. That said, it doesn't specifically mention white papers.

Two suggestions:
1. Add "and whitepapers" to the heading and update the content with "objective/trustworthy".
2. Create a new "How to write a whitepaper section".

@aedott, passing this to you for your consideration and possible action. Thank you!
