### ISSUE TITLE
Add guidelines for top bar notifications

### ISSUE THREAD

**Issue by it33** [mattermost/docs#958]
We have [guidelines for error messages](https://docs.mattermost.com/developer/fx-guidelines.html#feedback-error-messages), and we need guidelines for messages in the top bar of the UI: 

![image](https://cloud.githubusercontent.com/assets/177788/23659830/4e34755c-02fc-11e7-9018-7c9770ec0536.png)

Proposed points: 

1. **Top bar message owns the audience's attention** - A top bar message is the "Shout of Mattermost". It interrupts the audience to deliver an important message. The design of every message should reflect this responsibility--we are grabbing someone's attention while they're using the product to tell them something they really need to know. 

2. **Use color for context** - Color should communicate the context of what the audience needs to hear. 

- BLUE top bar used to inform all users of issues related to their experience, e.g. that email is not enabled when in preview mode, that the server is unreachable, if there's a possible issue with the network, etc. 
- PURPLE top bar is used to display messages when developer mode is enabled, to aid in troubleshooting and debugging.  
- RED top bar is used only when there is a critical issue with the system that demands attention, e.g. 15 days after license expiry, all end users will see the message that the license is beyond expiry date and the administrator should either renew the license or remove the license to continue operating Mattermost in Team mode. 

3. **Test your message** - Top bar messages should contain enough information for the intended audience to know why they received it, what action they should take (if any) and how to complete the action. To test for this, after an appropriate audience member sees a top bar message, they should be able to answer a) Why was that message presented to you? b) Do you need to take any action? c) What action do you need to take? If you're not sure if your message works, post it into the Bugs channel on pre-release and ask people to answer the questions above--we have an open source community eager to contribute and help.

4. **Be concise** - Top bar messages should be concise, with links to documentation for further explanation.

**Comment by justinegeffen** [comment]
This is addressed and resolved by: https://zeroheight.com/29be2c109/p/741553-product-design.
