### ISSUE TITLE
Document how to pre-configure account preferences for new users

### ISSUE THREAD

**Issue by it33** [mattermost/docs#972]
There's been a number of asks to pre-configure account settings for new users (e.g. ability to view First Name, Last Name, theme color, time format settings, etc.). 

I think this can be done via APIs, and potentially we could add it to the bulk load system in Enterprise Edition later. 

We should have some guidance on what's available today.

**Comment by justinegeffen** [comment]
This is an interesting suggestion. @dontoisme, I'm passing it on to you for reference/consideration.
