### ISSUE TITLE
Add sample message post-Slack import

### ISSUE THREAD

**Issue by it33** [mattermost/docs#978]
Add a section to [migration guide for Slack import](https://docs.mattermost.com/administration/migrating.html#migrating-from-slack) with example of message to send after Slack import to bring users onto the system (after email notification is set up): 

```
#### Hello @all, 

We've moved from Slack to Mattermost. All our team members and public channels from Slack have been imported. 

1. Please follow the link in the notification email you receive from this message to find our new server. 
2. Please use the "Reset Password" feature in Mattermost to create new credentials. 
3. We can continue our work in Mattermost, just as we did in Slack--with a number of new benefits, including enhanced privacy, security, developer support and international support.
```

**Comment by jostyee** [comment]
Please notice that if you only allowing GitLab OAuth login, you have to update database by yourself for users who haven't been created before importing.

**Comment by justinegeffen** [comment]
@cwarnermm, I think this is an interesting suggestion and could fit into the Growth Spike/Onboarding work? WDYT?

**Comment by cwarnermm** [comment]
It is an interesting idea! I agree that we want to take action on this one, though perhaps later in the year.
