### ISSUE TITLE
Missing font on docs.mattermost.com

### ISSUE THREAD

**Issue by JeffSchering** [mattermost/docs#983]
Requests for the font file https://docs.mattermost.com/_static/fonts/fontawesome-webfont.woff2?v=4.6.3 result in a 403 error

**Comment by shieldsjared** [comment]
@JeffSchering - had a few minutes and saw this.  Submitted a quick and painless [PR](https://github.com/mattermost/docs/pull/1549).

**Comment by tejasbubane** [comment]
Can this be closed?

**Comment by lindy65** [comment]
Yes, thank you @tejasbubane - I will close :)
