### ISSUE TITLE
Incorrect response to missing file on docs.mattermost.com

### ISSUE THREAD

**Issue by JeffSchering** [mattermost/docs#984]
The docs server is misconfigured. When a file that does not exist is requested, the server returns an Access Denied error instead of a File Not Found error.

Furthermore, the error page is an XML page with no styling, and it does not contain the HTTP error code. This is a bad experience for people using the docs site.

``` xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>935E9F04D136EAD6</RequestId>
  <HostId>0lz120KTGdpQ3ymg7fJHKWwjRp4WID+iX/xuFdf1L4hrOR50+gdCZIyHASwpZa5/</HostId>
</Error>
```

### Edit: 2017-07-19

The error page has been improved somewhat, but it's still a circa 1995 "my first website" experience.

```xml
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>install/ee-prod-rhel-7.html</Key>
  <RequestId>0C94DCBA11107EC1</RequestId>
  <HostId>
    4owyOVjMvsANSGnP+OOabKTpLuOUZTRlVvJrXcdbPWhwANFNX3MRuKmC52feJhvz63qZf2+Sl68=
  </HostId>
</Error>
```

**Comment by justinegeffen** [comment]
Jira ticket: https://mattermost.atlassian.net/browse/MM-10674.

**Comment by justinegeffen** [comment]
This has been completed as part of docs 2.0. :)
