### ISSUE TITLE
[Help Wanted] Create a troubleshooting checklist for Mattermost

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#985]
Our [existing troubleshooting docs](https://docs.mattermost.com/install/troubleshooting.html) are okay for troubleshooting specific issues, but we're lacking a general checklist for an admin to go through while resolving issues.

We'd love to get community's help creating such a troubleshooting checklist for Mattermost. If you have any feedback or are interested to contribute, let us know!

Below is a potential start, inspired by IBM troubleshooting checklists

----

Use the troubleshooting checklist to help identify your problem and possible resolution.

You may also check tips for common issues and error messages here // [link to a revised version of this doc](https://docs.mattermost.com/install/troubleshooting.html)

1. Is the configuration supported?
  - See [detailed client software requirements](https://docs.mattermost.com/install/requirements.html#client-software) for PC, mobile and email
  - See [detailed server software requirements](https://docs.mattermost.com/install/requirements.html#server-software) for operating system and database
2. Was SSL/TLS certificate installed successfully (if applicable)? You can confirm it by entering your Mattermost server URL to [Symantec’s online SSL/TLS certificate checker](https://cryptoreport.websecurity.symantec.com/checker/views/certCheck.jsp).
3. Did you at any point deviate from the step-by-step [Mattermost install guides](https://docs.mattermost.com/guides/administrator.html#installing-mattermost)?
4. Have you made any changes to the default settings in the System Console (or in config.json file)?
5. Have any error messages being issued that may point to a specific issue?
  - Do you see any JavaScript errors in the Chrome developer console? [Instructions here how to access it](http://stackoverflow.com/questions/66420/how-do-you-launch-the-javascript-debugger-in-google-chrome).
  - Do you see any errors in Mattermost server logs? These are printed in `mattermost.log` in the directory where Mattermost is installed.
6. How long has the problem been occurring?
  - Did you recently install or begin using Mattermost for the first time?
  - Did the feature work until some point and then start to fail?
7. If the problem occurred subsequent to some period of normal operation, did anything change in the environment?
  - Was the client, host, or server upgraded?
  - Was an operating system update applied?
  - Did the network environment change? For example, was a server moved or a domain migrated?
  - Did the system (client or server) recently fail or abnormally terminate?
8. How many users are impacted?
  - Is this problem affecting one, some, or all users?
  - Is the problem occurring only for a user who was recently added to the environment, such as a new employee?
  - Do differences exist between the users who are affected and the users who are not affected?

If this checklist doesn’t guide you to a resolution, you may [create a new troubleshooting report at our forum](https://forum.mattermost.org/t/how-to-use-the-troubleshooting-forum/150). 

As part of your report, please make sure to include responses to the above checklist items along with your Mattermost server version, operating system type and version, and database type and version.

**Comment by justinegeffen** [comment]
I'll take this.

**Comment by justinegeffen** [comment]
I'll take this one.
