### ISSUE TITLE
Document process for cutting features

### ISSUE THREAD

**Issue by it33** [mattermost/docs#993]
We need a publicly documented process on how to announce to the community when a feature is being removed for whatever reason. 

- This is brought up by conversation of potentially cutting Latex support and letting it come back as a plug-in.

**Comment by it33** [comment]
This is brought up by conversation of potentially cutting Latex support and letting it come back as a plug-in.

**Comment by jasonblais** [comment]
https://docs.google.com/document/d/1S4VWtDXCTXw6toXBbbWrdmWuPas1NkKV33YCp9YCy-k/edit#bookmark=id.eqube51knwed

**Comment by jasonblais** [comment]
https://github.com/mattermost/docs/pull/1080
