### ISSUE TITLE
Doc how to add users to open team via API when the team is not open

### ISSUE THREAD

**Issue by it33** [mattermost/docs#999]
This is about generating and using `inviteId`, see: https://pre-release.mattermost.com/core/pl/1txauynczbbsznnodbeqyfb4ny

This should go into this PR: https://github.com/mattermost/docs/pull/728/files

**Comment by JeffSchering** [comment]
@it33 Is that the correct PR? #728  is for the Onboarding Guide.

**Comment by cwarnermm** [comment]
Closing.
